### ISSUE TITLE
Unable to add bower webjar for aurelia-framework 0.11

### ISSUE THREAD

**Issue by bpasson** [webjars/webjars#1000]
When trying to add a new bower webjar for the aurelia-framework version 0.11 the following error is displayed. Any fix available for this error?

Failed!
Could not convert npm version to maven for: core-js zloirock/core-js
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by jamesward** [comment]
Unfortunately this will need to be fixed upstream because this is not a valid version:
https://github.com/aurelia/framework/blob/master/bower.json#L28
