### ISSUE TITLE
ui-router-extras: New Bower WebJar

### ISSUE THREAD

**Issue by RBleyenberg** [webjars/webjars#1005]
Add a New Bower WebJar
trying to deploy ui-router-extras, and getting the following error

Failed! Version 0.0.13 for path 'webjars/maven/org.webjars.bower:ui-router-extras already exists If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by jamesward** [comment]
Something odd happened on BinTray.  It wasn't automatically included in JCenter so I've asked that it be included.  Then we can deploy it to Maven Central.

**Comment by jamesward** [comment]
This should be in Maven Central now.
