### ISSUE TITLE
Convert NPM Version Ranges With Gaps to Maven

### ISSUE THREAD

**Issue by RBleyenberg** [webjars/webjars#1006]
trying to deploy 9.0 of angular-material gives following error

Failed! Could not convert npm version to maven for: angular ^1.3.0 || >1.4.0-beta.0 If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by jamesward** [comment]
Unfortunately I can't think of a good way to convert the `||` range style to the Maven range definition.  So far not many libraries have used this syntax so it hasn't been much of a problem.

Any ideas about what to do about this?

**Comment by RBleyenberg** [comment]
nope, tho i guess just wait till angular 1.4 drops (anytime now) and i'll notify angular-material , so they can drop the syntax if they didn't already. 

thanks for your time.

**Comment by jamesward** [comment]
It looks like Maven does support multiple ranges:
https://maven.apache.org/pom.html#Dependencies

Like:

    (,1.0],[1.2,)
