### ISSUE TITLE
Bower WebJars: deploying react-router-bootstrap 0.13.4

### ISSUE THREAD

**Issue by mattgruter** [webjars/webjars#1007]
Just tried to deploy [react-router-bootstrap](https://github.com/react-bootstrap/react-router-bootstrap) and got an error that synchronization with MavenCentral failed.

The deployment seemed to succeed halfway though:
The package is visible on bintray ([link](https://bintray.com/webjars/maven/org.webjars.bower%3Areact-router-bootstrap/view)) however it is not linked to jCenter and thus not available through it or mavenCentral.

Any pointers in how to fix this?

**Comment by jamesward** [comment]
Odd.  For some reason the package didn't get automatically added to jCenter.  I've requested that it be added.  Once it is added I'll deploy it.

**Comment by jamesward** [comment]
This should be deployed now.

**Comment by mattgruter** [comment]
Great! Thank you for sorting it out.
