### ISSUE TITLE
Requirejs for webJar.bower

### ISSUE THREAD

**Issue by RBleyenberg** [webjars/webjars#1010]
Failed! License new BSD, and MIT is not acceptable on BinTray If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by jamesward** [comment]
Which library are you trying to deploy?

**Comment by RBleyenberg** [comment]
hmm, can't seem to refind the library, me own bad. If i'll find it again, i'll reopen this with proper comments :P  

thx tho for the reply, and also thx for those awesome youtube vid with you, really great info.

**Comment by jamesward** [comment]
Looks like maybe `requirejs 2.1.17` from the logs.  That sound right?

**Comment by jamesward** [comment]
I've submitted a PR to the upstream project to fix this: https://github.com/jrburke/requirejs-bower/pull/8

**Comment by jamesward** [comment]
Version `2.1.18` fixed this and has been published.
