### ISSUE TITLE
Bower webjar error - license information missing

### ISSUE THREAD

**Issue by ricardobarone** [webjars/webjars#1016]
The following error occurs when trying to deploy the latest version of `angular-datatables`:

        Invalid POM: /org/webjars/bower/angular-datatables/0.4.3/angular-datatables-0.4.3.pom: License information missing, Dropping existing partial staging repository.

This project has a MIT License, but it is not defined in `bower.json`.
However, version 0.4.2 also doesn't have a `license` key, but it is deployed.

**Comment by jamesward** [comment]
The upstream project needs to specify a license in the `bower.json` or add a LICENSE to the repo.

Unfortunately there was a bug in the Bower WebJar sync when `0.4.2` was deployed causing it to detect a license even though one wasn't specified.

**Comment by ricardobarone** [comment]
Thanks for the explanation.

Just to be clear, if the project chooses a file instead of a license in `bower.json`, does it need to be named `LICENSE` (uppercase)?

I understand that  [GitHub's docs](https://help.github.com/articles/open-source-licensing) recommends using `LICENSE` (or `LICENSE.md` / `LICENSE.txt`), but I've seen some projects using `License.txt`, like Datatable's extensions (ex.: ColVis, Scroller).

**Comment by jamesward** [comment]
I use my own GitHub License Service which currently supports any of those (case-sensitive):
https://github.com/jamesward/github-license-service/blob/master/app/utils/GithubUtil.scala#L12

**Comment by ricardobarone** [comment]
Thank you, James. I will try and ask `Datatables` to change the license filename to uppercase, or at least add the `license` key to `bower.json`.

**Comment by jamesward** [comment]
I'm not seeing a `license` file in the root of the project.  But a PR should be an easy way to get one there.
