### ISSUE TITLE
Cannot deploy NPM webjar for jsx-loader due to licensing issue

### ISSUE THREAD

**Issue by GitsMcGee** [webjars/webjars#1020]
This may not be solvable. I'm not a lawyer. When trying to create an NPM webjar for [jsx-loader](https://www.npmjs.com/package/jsx-loader), I get the following error: 

```
Failed! 
License Apache 2 is not acceptable on BinTray If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
```
This is a shame because this and a lot of other webjars that I want to create are apache 2 licensed. Why is Apache 2 bad?

**Comment by huntc** [comment]
I think that bintray is very specific about the license names - it may be looking for `Apache-2.0`.

**Comment by GitsMcGee** [comment]
@huntc Ahhh. Good eye. I assume it's scraping that license name from package.json? I can create a pull request in jsx-loader to change the spelling if there's nothing simple we can do here.

**Comment by jamesward** [comment]
For Bower the license should be the identifier in the [SPDX Index](https://spdx.org/licenses/) but I'm not sure if NPM has that same policy.  So you can send a PR but I will also fix this in our mappings.  One sec.

**Comment by GitsMcGee** [comment]
Great. Thanks @jamesward!
