### ISSUE TITLE
Failed to deploy NPM Webjar for loader-utils

### ISSUE THREAD

**Issue by GitsMcGee** [webjars/webjars#1024]
Hello. I'm trying to deploy a NPM Webjar for [loader-utils](https://www.npmjs.com/package/loader-utils) and it is failing with the following error:

```
Failed! 
Package for path 'webjars/maven' was invalid. Package license is mandatory
```

Looking at http://registry.npmjs.org/loader-utils/0.2.7 my guess is that things are being tripped up by the fact that the license is an object and not a string.

**Comment by jamesward** [comment]
It looks like the syntax is deprecated: https://docs.npmjs.com/files/package.json#license

I think that if the repo had a `LICENSE` file in the root then we would fall back to that.  Sending a PR for that is probably the easiest way to fix this.  What do you think?

**Comment by GitsMcGee** [comment]
I think that's perfectly reasonable. I'll make the PR. Thanks again!
