### ISSUE TITLE
UX - Retry Maven Central Sync

### ISSUE THREAD

**Issue by falconepl** [webjars/webjars#1025]
I've tried to publish `object-keys` (1.0.3) and `is-callable` (1.0.4) NPM packages at WebJars.org. I expect that deployment has failed, because both of these packages are now available at Bintray's repository, but unavailable at Sonatype's and Typesafe's repositories (Typesafe account at Bintray).

Thus, it looks like it has been published only partially, to some repositories handled by WebJars and from user's perspective it's impossible to fix this - as redeploying those packages ends up with a failure `Failed! Version X for path Y already exists`. I've tried to redeploy `object-keys` for `1.0.2` version, just out of curiosity, and it actually finished with success - it's available at Bintray's as well as Sonatype's repository.

Could you have a look at it and, if possible, fix missing packages for `object-keys 1.0.3` and `is-callable 1.0.4`? Also, it would be great if WebJars could properly handle partially successful deployments, either by allowing a user to redeploy given package version or by reverting such deployments.

**Comment by jamesward** [comment]
Thanks for reporting the problem.  I've re-synced these to Maven Central so they should show up there in the next few hours.

The OSS deployment error was:
```
Failed to close repository: orgwebjars-4013. Server response: *Unhandled: Staging repository is already transitioning: orgwebjars-4013 Dropping existing partial staging repository.
```

So definitely some strange stuff going on when you tried to deploy these.  It would be nice to provide a better retry mechanism on webjars.org so I'll leave this open.

**Comment by jamesward** [comment]
This error stemmed from doing multiple deploys at once. See #1028
