### ISSUE TITLE
NPM Webjars: Errant conversions

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1027]
[Chokidar](https://registry.npmjs.org/chokidar/) 1.0.1:
[xtend](https://registry.npmjs.org/xtend/) 4.0.0:
[estraverse](https://registry.npmjs.org/estraverse) 4.1.0:
```Failed! Package for path 'webjars/maven' was invalid. Package license is mandatory```

Has `licenses` defined, instead of `license`. This is a 'deprecated' use case. https://docs.npmjs.com/files/package.json#license

---

[Inflight](https://registry.npmjs.org/inflight/) 1.0.4:
```Failed! No repository found under this GitHub path```

The original repository has been moved to npm. Going to https://github.com/isaacs/inflight redirects to https://github.com/npm/inflight. Doing a `git clone git://github.com/isaacs/inflight` still works.

---

[Inherits](https://registry.npmjs.org/inherits/) 2.0.1:
```Failed! JsResultException(errors:List((/homepage,List(ValidationError(error.path.missing,WrappedArray())))))```

`__ \ "homepage"` is missing. Unsure if this field is optional or not. Package appears to be unmaintained.

**Comment by jamesward** [comment]
This should be deployed in about 15 minutes.
