### ISSUE TITLE
NPM Webjars: Uploading multiple webjars causes failure

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1028]
Tried to upload three different webjars at the same time, all three uploads failed.

```
Failed! {"status":"Validation Failed","messages":"[Missing SHA1: '/org/webjars/npm/has-ansi/1.0.3/has-ansi-1.0.3.pom.sha1', Missing MD5: '/org/webjars/npm/has-ansi/1.0.3/has-ansi-1.0.3.pom.md5', Missing: no main jar artifact found in folder '/org/webjars/npm/has-ansi/1.0.3', Missing Signature: '/org/webjars/npm/has-ansi/1.0.3/has-ansi-1.0.3.pom.asc' does not exist for 'has-ansi-1.0.3.pom'., Dropping existing partial staging repository.]"}
```
```
Failed! {"status":"Sync Failed","messages":"[Failed to close repository: orgwebjars-4066. Server response:\n *Unhandled: Staging repository is already transitioning: orgwebjars-4066, Dropping existing partial staging repository.]"}
```
```
Failed! {"status":"Validation Failed","messages":"[Failed to close repository: orgwebjars-4066., Dropping existing partial staging repository., Failed to drop repository: orgwebjars-4066. Server response:\n *Unhandled: Missing staging repository: orgwebjars-4066]"}
```

When attempting to re-deploy, the following messages are shown:
```
Failed! Version 1.0.3 for path 'webjars/maven/org.webjars.npm:has-ansi already exists 
```
```
Failed! Version 1.3.1 for path 'webjars/maven/org.webjars.npm:supports-color already exists 
```
```
Failed! Version 2.0.1 for path 'webjars/maven/org.webjars.npm:strip-ansi already exists 
```

Unsure if webjars have actually deployed. Will check and update this when maven updates.

**Comment by jamesward** [comment]
I think that BinTray doesn't like it when we try to do multiple Maven Central syncs at the same time.  I'll fine an issue with them.  In the meantime I'm manually syncing those packages to Maven Central.

**Comment by jamesward** [comment]
Bintray has acknowledged the issue and is investigating.

**Comment by nedtwigg** [comment]
@jamesward did Bintray ever get back to you with a solution or workaround?  I think I'm having the same problem.

**Comment by jamesward** [comment]
@nedtwigg What is the error you are seeing?

**Comment by nedtwigg** [comment]
I'm deploying a multiple-jar project to mavencentral through bintray.  Got them through eventually by pressing "Sync" many times over the course of days, but they were very similar to: `"Failed! {"status":"Sync Failed","messages":"[Failed to close repository: orgwebjars-4066. Server response:\n *Unhandled: Staging repository is already transitioning: orgwebjars-4066, Dropping existing partial staging repository.]"}"`.

Trying to figure out if this is going to be a problem every time we publish a new version.

**Comment by jamesward** [comment]
Usually I see this when Maven Central is having issues.  Where are you pressing "Sync"?

**Comment by nedtwigg** [comment]
My gradle script publishes to bintray, and syncs to maven from there.  In the past, this has always gone without a hitch.  I just started using this process for multi-jar projects for the first time, and it got wedged somehow.  The artifacts made it to bintray, but not to mavencentral.  Bintray's web UI has a "Maven Central" tab where you can enter your Sonatype credentials and press "Sync".

Don't want to take a lot of your time, but googling the error found this issue, and like this issue I was publishing multiple jars at once, so I thought maybe this was a known bintray issue with a workaround they gave you :)

**Comment by Lykathia** [comment]
> and like this issue I was publishing multiple jars at once

Just for completing the circle, is of note: I wasn't publishing multiple jars with the original issue per-say, I was doing three independent uploads simultaneously thru the webjars UI.

**Comment by jamesward** [comment]
@nedtwigg Ah. I thought this was happening via the WebJars stuff.  I don't think Bintray has fixed the simultaneous deploy issue yet.  Might help push them if you file a support issue.

**Comment by nedtwigg** [comment]
I have filed an issue with bintray, but they think it's me and/or sonatype.  There are also seemingly related issues raised in Sonatype's tracker ([OSSRH-27145](https://issues.sonatype.org/browse/OSSRH-27145) [OSSRH-6954](https://issues.sonatype.org/browse/OSSRH-6954)).  Regardless, thanks for the help, sorry for the noise :)  For others who find this via googling - hit the "sync" button a couple times per day, eventually it'll go through.  👎
