### ISSUE TITLE
WebJar Request: PolymerElements/paper-tabs and its dependencies

### ISSUE THREAD

**Issue by sergiuszkierat** [webjars/webjars#1032]
The [paper-tabs](https://github.com/PolymerElements/paper-tabs) isn't available as a bower registered package (is marked as private).
> $ bower search PolymerElements/paper-tabs
> No results.

and have some dependencies
> $ bower install git://github.com/PolymerElements/paper-tabs.git
> $ ls -l bower_components/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 iron-flex-layout/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 iron-icon/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 iron-iconset-svg/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 iron-meta/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 iron-resizable-behavior/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 iron-selector/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 paper-ripple/
> drwxrwxr-x 4 skierat skierat 4096 maj 25 10:52 paper-tabs/
> drwxrwxr-x 2 skierat skierat 4096 maj 25 10:52 polymer/
> drwxrwxr-x 2 skierat skierat 4096 maj 25 10:52 webcomponentsjs/

Is there any convenient option to deploy on-demand bower package with dependencies directly from [git](https://github.com/PolymerElements/paper-tabs) endpoint ?

**Comment by jamesward** [comment]
There isn't an option for this right now.  Even if there was I'm not sure what we would do with the way they are using dependencies: https://github.com/PolymerElements/paper-tabs/blob/master/bower.json#L17-L25

WebJars are really intended for published artifacts.  GitHub repos are not really published artifacts.

**Comment by sergiuszkierat** [comment]
@jamesward fair enough. I have to rethink whether to use Polymer and PolymerElements through WebJars, because it's not so easy.

**Comment by jamesward** [comment]
Yeah. It would be great if Polymer would release their artifacts to NPM and/or Bower.
