### ISSUE TITLE
[NPM] Legacy package w/ unusable license

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1033]
I'm trying to download the [yargs](https://registry.npmjs.org/yargs):1.3.3 package, however the license given in the package (MIT/X11) is non-standard. This has been fixed in the latest version of yargs.

How should webjars handle legacy versions that do not have their package json up to standard?

**Comment by jamesward** [comment]
Is there a dependency directly on `1.3.3` or is there a range?  Could a `1.3.4` with a fix for this help?

**Comment by Lykathia** [comment]
Was a range, yeah. I'll see about backporting a fix.

**Comment by jamesward** [comment]
I think that would be ideal.  I can't think of another way to handle this without adding explicit / package specific conversion rules and that is something I'd like to avoid.  The only other idea I had is to fallback to a LICENSE file in the repo under the tagged version.  But there wasn't even a tag in the repo for `1.3.3`.  Ugggg.

**Comment by Lykathia** [comment]
Need an explicit dependency on `org.webjars.npm#engine.io;1.5.1`. Upstream is fixed for 1.5.2 (unreleased) onwards.

Also have explicit dependencies on `org.webjars.npm#ms;0.7.1`, `org.webjars.npm#ms;0.7.0` and `org.webjars.npm#ms;0.6.2`.

Since these are all locked dependencies, not sure how to resolve.

**Comment by dougwilson** [comment]
I don't think the `ms` module even has any published version with a license at all; 0.7.1 is the latest version still.

**Comment by jamesward** [comment]
Option C) Fork the offending project(s). Rename. Fix deps. Publish to NPM. WebJar-ify.

Not sure what else we can do.

**Comment by Lykathia** [comment]
At least with these, the license is stated for the repos -- just not explicit in the metadata. Could manually create the jars, with the metadata altered to have the license addition.

In the context of forking, seems like it would be turtles all the way down.

Bintray does not support a 'none' license I presume?

**Comment by jamesward** [comment]
Yeah, we can't do an empty license on BinTray or Maven Central.

We could make the [github-license-service](https://github.com/jamesward/github-license-service) fallback to trying to parse a license out of the README.

**Comment by jamesward** [comment]
Oh, easier way...  If a license can't be found in the `package.json` then it falls back to the `LICENSE` in the git repo: https://github.com/webjars/webjars/blob/master/app/utils/NPM.scala#L60-L72

So all we really need is to have those projects add a `LICENSE`.  I'm closing this since I don't think there is anything specifically needed on our side.  But feel free to reopen or create a new issue if there is something else we can do to deal with this.
