### ISSUE TITLE
[NPM] Issues with non-github repository

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1043]
[weinre](https://registry.npmjs.org/weinre/): 2.0.0-pre-I0Z7U9OV

```Failed! No repository found under this GitHub path If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues```

Everything in the JSON looks valid/sound. Was going to take a further look into this, but got side tracked. Submitting issue so it doesn't get lost at least.

**Comment by jamesward** [comment]
I bet this is because my code has been pretty much assuming these are GitHub repos.  This one is not:
```
"repository": {
  "type": "git",
  "url": "https://git-wip-us.apache.org/repos/asf/incubator-cordova-weinre.git"
}
```

So I'm sure we need some tests and some better handling of this.  Adding this to my todo list unless someone else takes care of it first.  :)
