### ISSUE TITLE
Failed to deploy vis.js

### ISSUE THREAD

**Issue by stanleyxu2005** [webjars/webjars#1046]
I tried NPM and bower to deploy vis 4.0. Both do not work.

**Comment by jamesward** [comment]
Unfortunately that project doesn't have a way for us to determine the licenses programatically.  This will need to be fixed by the upstream project.  You could submit a pull request to them to add the licenses to their `bower.json` and/or `package.json` files.

**Comment by AlexanderRay** [comment]
+1
