### ISSUE TITLE
New webjar: BrowserSync

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1048]
https://github.com/Lykathia/browser-sync

Works locally at least!

![It seems to work](https://s3-eu-west-1.amazonaws.com/bowwowtimes/wp-content/uploads/2015/01/I-Have-No-Idea-What-Im-Doing-1.jpg)

**Comment by jamesward** [comment]
It doesn't look like we need both the `web` and `node` packages for this one because it doesn't appear that there are different distributions for each.

Also I think we can simplify this by just running `npm install` instead of downloading the zip.

**Comment by Lykathia** [comment]
Simplified some.

**Comment by jamesward** [comment]
I've forked it: https://github.com/webjars/browser-sync

But before I release it lets discuss the inclusion of `node_modules`.  Usually we drop those from WebJars and use defined dependencies instead.  So much fun, right?!?  There are obviously tradeoffs on both sides.  I'm happy to do whatever but wanted you to know our usual stance.

**Comment by Lykathia** [comment]
Well, the whole reason I made it as a classic webjar was due to the impossibility of getting the dependencies to work w/ node :(

**Comment by jamesward** [comment]
Cool.  Releasing it now.
