### ISSUE TITLE
Add OSCAR-js

### ISSUE THREAD

**Issue by tastle** [webjars/webjars#1050]
https://github.com/caris/oscar-webjar.git

We've made a 15.0.0-RC1 tag in our oscar-webjar repository and we'd like a webjar release to be built from it.

Just for my own clarification, once your organization forks this repository, we could probably delete the existing oscar-webjar repository from our organization and just do pull requests from the repository you've forked, correct?

Also, how does the process work for choosing a master / branch / tag in which to make the release build?  Is a request made to indicate this, or does the system assume something?  That's not really clear in these notes:  http://www.webjars.org/contributing

Thanks!

**Comment by jamesward** [comment]
Thanks for helping WebJars with this contribution.  Unfortunately it looks like the `upstream.url` is not publicly accessible.  Is the upstream library available publicly?

The release process for WebJars is:

1. Someone requests a new version either via an issue or a PR on the WebJar.
2. Someone from the WebJars team merges the PR or manually bumps the version and then releases the WebJar to Maven Central using the `maven-release-plugin` and `nexus-staging-maven-plugin` plugins.

**Comment by tastle** [comment]
Ugh, I'll fix up that tag.  I used an intranet URL instead of one publicly available online.  Just give me a few minutes.

**Comment by tastle** [comment]
@jamesward, I'm just checking in.  Is everything okay or are more changes needed?  (We're deploying webjar snapshots locally so I think it's good, but please let me know if it isn't.)

**Comment by jamesward** [comment]
I'm still seeing the private repo: https://github.com/caris/oscar-webjar/blob/master/pom.xml#L20

**Comment by tastle** [comment]
You're looking in the wrong place.  The tag has the public one.

https://github.com/caris/oscar-webjar/blob/15.0.0-RC1/pom.xml#L18

We have snapshots building internally, but tags will have external access.

**Comment by jamesward** [comment]
Ah cool.  I've updated the repo: https://github.com/webjars/oscar

One question before I publish this...  The current contents include a bunch of other libraries.  Usually we like to use dependencies for this instead of including them.  Would it break stuff if the WebJar just included the `scripts/oscar` contents and we defined dependencies for the other libs?

**Comment by tastle** [comment]
It would unfortunately.  We're aiming to split it up though.  We're moving to Grunt / Bower and going to update our dependencies to OpenLayers 3, the latest Proj4js, drop YUI and adopt RequireJS.  But we can't do it all at once.  The goal is to move to webjars (obvious benefits) and then in 16.0 and beyond split up the library.

If you don't mind going as-is for now, you'll see improvements as this library has been evolving for a while.

**Comment by jamesward** [comment]
Cool.  This will be released shortly as `15.0.0-RC1`.  Going forward you can send PRs to: https://github.com/webjars/oscar

**Comment by tastle** [comment]
Excellent, that's what we'll do.  We'll fork your fork and issue pull requests.

Thank you very much for your help.
