### ISSUE TITLE
Failed to deploy angular2-2.0.0-alpha.26 from NPM

### ISSUE THREAD

**Issue by catap** [webjars/webjars#1055]
Each time when I try to deploy a angular2 from NPM as webjar I had a error:
```
Failed! JsResultException(errors:List((/repository/url,List(ValidationError(error.path.missing,WrappedArray()), ValidationError(error.path.missing,WrappedArray()))))) If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues 
```

**Comment by jamesward** [comment]
I'm not sure why but the NPM metadata doesn't have a `repository.url`: https://registry.npmjs.org/angular2/2.0.0-alpha.26

Since we can't programmatically get that info, we can't create a WebJar for this.  Can you file an issue with the upstream project?
