### ISSUE TITLE
NPM webjars can return as already existing when they don't exist

### ISSUE THREAD

**Issue by terrymunro** [webjars/webjars#1066]
Attempting to Add new NPM WebJar for `arrow-style` responded with:

    Failed!
    Version 1.1.1 for path 'webjars/maven/org.webjars.npm:arrow-style already exists
    If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

But checking here:
https://dl.bintray.com/webjars/maven/org/webjars/npm/arrow-style/
I can only see version 1.1.0 but not 1.1.1

**Comment by jamesward** [comment]
For some reason the upload to BinTray failed.  I've deleted the version on BinTray and republished it.  Let me know if you have any issues.
