### ISSUE TITLE
Angular 1.4.0 not available as Bower web jar because deployment fails

### ISSUE THREAD

**Issue by Schweigi** [webjars/webjars#1069]
I would like to use the new Angular 1.4.0 version as a Bower web jar. The current Angular Bower web jar package has version 1.4.0-rc2 but not the final version 1.4.0. When I try to deploy the final version I get the following error:

```
Failed! Version 1.4.0 for path 'webjars/maven/org.webjars.bower:angulerjs already exists If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Created BinTray Package 
Converted project licenses 
Created Bower WebJar 
Fetched Bower zip 
Generated POM 
Converted dependencies to Maven 
Got Bower info 
Starting Deploy
```

So it looks like someone else already deployed V1.4.0 but the web jar is not visible nor accessible.

The same error does also happen for other Angular core packages like 'angular-animate', 'angular-aria', 'angular-message'.

**Comment by jamesward** [comment]
That package is actually there:

    "org.webjars.bower" % "angulerjs" % "1.4.0"

But notice the typo in the Bower package name?  This comes from the upstream project so there isn't any way we can fix it.

The tough part is that the current UI on webjars.org for adding a Bower WebJar shoves the `angular` and `angularjs` packages way down in the list making it impossible for them to find.  So I need to fix the UI.  I'll get that done asap.

**Comment by Schweigi** [comment]
Great. I got the package now.

The filter function has some issues too because for example filtering by `AngularJS` does not show the package.

**Comment by jamesward** [comment]
There is one other problem... The `angular` `1.4.0` package doesn't have a license specified.  So it won't be able to be deployed.  I've sent an upstream PR: https://github.com/angular/bower-angular/pull/42

But I'm also looking into grabbing the license from the `package.json` as a fallback.

**Comment by Schweigi** [comment]
Looks like all the Angular bower sub repositories (like https://github.com/angular/bower-angular-messages) have the same license issue.

**Comment by jamesward** [comment]
The new UI and new https://github.com/jamesward/github-license-service are both up and should make it easier and possible to deploy these kinds of packages.  Let me know if you have any issues.

**Comment by Schweigi** [comment]
For some reason the blue "+" deploy button doesn't work anymore (click doesn't open the popup).

**Comment by Schweigi** [comment]
Thx @jamesward. It works perfectly now.
