### ISSUE TITLE
Manual fix needed for angular-toggle-switch and angular-mocks

### ISSUE THREAD

**Issue by jordanjennings** [webjars/webjars#1072]
I uploaded several new versions of angular webjars, but along the way two of them failed due to timeouts and now when I retry it says "Failed". They are:

angular-mocks 1.4.0
angular-toggle-switch 1.3.0   (no previous version existed for this one)

Here's one of the error messages

```
Failed! Version 1.3.0 for path 'webjars/maven/org.webjars.bower:angular-toggle-switch already exists If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues 
```

Can you take a look at these two? Thank you!

**Comment by jamesward** [comment]
I've deployed these and they should be available shortly in Maven Central.

**Comment by jordanjennings** [comment]
Thanks for the quick fix!
