### ISSUE TITLE
Bower: please add support for license type: http://opensource.org/licenses/mit-license.php

### ISSUE THREAD

**Issue by h2000** [webjars/webjars#1074]
I tried to convert the bower package: autoNumeric 1.9.30

and got the error:
Failed! http://opensource.org/licenses/mit-license.php could not be converted to a knowable license If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Starting Deploy

**Comment by jamesward** [comment]
This needs to be fixed upstream because unfortunately we can't programmatically figure out the actual license from that URL.
