### ISSUE TITLE
Failure due to no license found for npm package with 2 licenses

### ISSUE THREAD

**Issue by emanueleperuffo** [webjars/webjars#1077]
I can't create a npm webjar for xmldom because the script can't parse the license, even though two licenses are present in package.json.

https://github.com/jindw/xmldom/blob/master/package.json
Extract of package.json:
{
  ...,
    "licenses": [{"type": "LGPL","url": "http://www.gnu.org/licenses/lgpl.html","MIT":"http://opensource.org/licenses/MIT"}]
}

This package has both LGPL and MIT licences, which are both listed in https://bintray.com/docs/api/#_footnote_1

Thanks,
Emanuele Peruffo

**Comment by jamesward** [comment]
Unfortunately `LGPL` isn't actually a valid license identifier because there are different versions of that license (`LGPL-2.1` & `LGPL-3.0`) and we have no way to distinguish which one the project is actually using.  This will have to be fixed upstream.

**Comment by mariussoutier** [comment]
If a project specifies two licenses, doesn't it mean you can choose the license yourself?

**Comment by jamesward** [comment]
In the Maven style, if multiple licenses are specified it is an `OR`; e.g. `MIT or GPL-3.0`.  In this case the consumer can choose the license that fits their needs.  However NPM has a way to specify an `OR` or and `AND`.  In the case of an `AND` it is usually used to license some assets like docs or fonts under a different license than the code.
