### ISSUE TITLE
WebJar for angular-placeholders

### ISSUE THREAD

**Issue by metasim** [webjars/webjars#1079]
My first contribution, so I expect I missed something. Other pending contributions have marked something about a tagged release, but I didn't understand what it meant. The upstream author doesn't have an official github-marked release, so I based it on the download links on the documentation page.

I did test it out locally as a snapshot release and works fine.

Repo: https://github.com/metasim/angular-placeholders-webjar

**Comment by jamesward** [comment]
Releases of WebJars need to correspond with a tagged release in the upstream project or a commit sha. If the upstream project doesn't have a tagged release then the ideal thing is that we get them to tag one.  If they won't do that, then we can do a release based on a git sha.  Or we can do a `SNAPSHOT` release.

Let me know which one you'd like to do.

**Comment by metasim** [comment]
I'll reach out to the author first. Stay tuned :)

**Comment by metasim** [comment]
After no response from the author, ended up forking and creating my own tagged release. So I'm ready for another try.

https://github.com/metasim/angular-placeholders-webjar

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/metasim-angular-placeholders

Note that I changed the `artifactId` to be `metasim-angular-placeholders` since this is a fork of the canonical distribution.

This will be released shortly.

**Comment by metasim** [comment]
Thanks so much! Good to know about the `artifactId` bit for future reference..
