### ISSUE TITLE
Supposedly missing license metadata for bower webjars

### ISSUE THREAD

**Issue by gjdev** [webjars/webjars#1080]
When trying to deploy webshim 1.15.7 as bower-webjar I get the following message:

> Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

Looking at the bower-metadata (see https://github.com/aFarkas/webshim/blob/gh-pages/bower.json) it does provide an entry:
> "license": "MIT"

According to the error message this should have been a recognized license. Why the error message?

**Comment by jamesward** [comment]
That isn't the same `bower.json` as in the `1.15.7` release:
https://bower-as-a-service.herokuapp.com/info/webshim/1.15.7

This will need to be fixed upstream.
