### ISSUE TITLE
Webjar for flexboxgrid

### ISSUE THREAD

**Issue by tbinna** [webjars/webjars#1082]
Hi,
I created this webjar for flexboxgrid (http://flexboxgrid.com/) and built it successfully on my machine.
Please let me know if there are any problems that hinder it from being merged.

Repo: https://github.com/tbinna/flexboxgrid

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/flexboxgrid

This will be released shortly.
