### ISSUE TITLE
angular-ui-tinymce:0.0.9 already exists but not deployed.

### ISSUE THREAD

**Issue by afenton90** [webjars/webjars#1083]
I tried to add angular-ui-tinymce 0.0.9 as a bower WebJar, however I lost connection whilst the WebJar was being added.
Now when I try to re-add the WebJar I get the following message:

Failed! Version 0.0.9 for path 'webjars/maven/org.webjars.bower:angular-ui-tinymce already exists If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Can this Bower WebJar be deployed successfully?

**Comment by jamesward** [comment]
I just manually deployed this one.  It should be in Maven Central shortly.

**Comment by afenton90** [comment]
Thanks @jamesward much appreciated. I will need #1084 resolving before I can use this package.
