### ISSUE TITLE
Adding tinymce-dist unable to convert license.

### ISSUE THREAD

**Issue by afenton90** [webjars/webjars#1084]
I am trying to add tinymce-dist as a Bower Webjar however I get the following error message when trying to do so:

Failed! http://www.tinymce.com/license could not be converted to a knowable license If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

The URL shows that the license is LGPL. Can this be fixed?

**Comment by jamesward** [comment]
It looks like the problem is that my https://github.com/jamesward/oss-license-detector service was timing out on the large license.  I'm deploying a change that should address this.  Can you give it a try in a few minutes?

**Comment by afenton90** [comment]
Yeah no problem. I will try again in 10 minutes.

**Comment by afenton90** [comment]
Just tried to add tinymce-dist as a Bower WebJar again and I get the same message.

**Comment by jamesward** [comment]
I discovered that Play's WS lib was not following redirects as I expected.  So I've fixed this.  In the process I was able to deploy this lib:
```
GroupID = org.webjars.bower
ArtifactID = tinymce-dist
Version = 4.1.10 
```
