### ISSUE TITLE
failed to deploy drag-helper 1.2.3

### ISSUE THREAD

**Issue by pwfcurry** [webjars/webjars#1088]
Attempting to deploy drag-helper v1.2.3 fails because it apparently already exists. It doesn't show up when searching on webjars.org, and doesn't resolve via maven. It looks like a previous deploy for this may have generated some invalid files?
```
Failed!
Version 1.2.3 for path 'webjars/maven/org.webjars.npm:drag-helper already exists
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
            
Created BinTray Package
Converted project licenses
Created NPM WebJar
Fetched NPM tgz
Generated POM
Converted dependencies to Maven
Got NPM info
Starting Deploy
```

**Comment by jamesward** [comment]
When deployment fails there isn't a way to retry.  So I've deployed this manually and it should be in Maven Central in the next few hours.  See #1025 for reference.
