### ISSUE TITLE
Package already exists but not displayed

### ISSUE THREAD

**Issue by AlexLourenco** [webjars/webjars#1089]
Hello there, while uploading a bunch of npm dependencies in parallel it seems bintray failed to push a couple of packages and now it refuses to attempt to re-upload them.

Packages are as follow:

Version 1.0.0 for path 'webjars/maven/org.webjars.npm:string-length already exists

Version 1.0.0 for path 'webjars/maven/org.webjars.npm:is-npm already exists

**Comment by jamesward** [comment]
Yeah, BinTray is aware of this issue and will hopefully fix it soon.  See #1028. In the meantime I'm manually publishing those now.
