### ISSUE TITLE
Webix webjar update

### ISSUE THREAD

**Issue by jlannoy** [webjars/webjars#1091]
Hello.

I update the repository for the "Webix" webjar to target last version (2.4.0)... Can you release it please?
(I don't know if you want anything else when it's related to a version update...)

Thanks in advance,

Jonathan Lannoy

**Comment by jlannoy** [comment]
Repository : https://github.com/jlannoy/webix

**Comment by jamesward** [comment]
Can you send a pull request to the WebJar?
