### ISSUE TITLE
Failed to create npmconf v2.1.1 on maven

### ISSUE THREAD

**Issue by mbelang** [webjars/webjars#1095]
I tried to deploy npmconf 2.1.1 on maven via webjars and it failed

Here is the error message :
Failed! Could not convert npm version to maven for: semver 2 || 3 || 4 If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got NPM info Starting Deploy

Thx

**Comment by jamesward** [comment]
This is like #1006.  I can't think of a way to convert gapped version ranges to Maven's versioning system.  So I'm not sure what to do with this right now.
