### ISSUE TITLE
Failed to collect dependencies at org.webjars.bower:bootswatch 3.3.5

### ISSUE THREAD

**Issue by samer-abdelkafi** [webjars/webjars#1104]
Failed to collect dependencies at org.webjars.bower:bootswatch:jar:3.3.5 -> org.webjars.bower:bootstrap:jar:[3.3.5,3.4): No versions available for org.webjars.bower:bootstrap:jar:[3.3.5,3.4) within specified range

**Comment by jamesward** [comment]
That is strange because `org.webjars.bower:bootstrap:jar:3.3.5` exists: https://repo1.maven.org/maven2/org/webjars/bower/bootstrap/3.3.5/

What build tool are you using?

**Comment by samer-abdelkafi** [comment]
I'm using maven 3.

Maven can resolve 3.3.4 version of bootswatch, but it fails for 3.3.5.

**Comment by jamesward** [comment]
It looks like Maven might not support the version range syntax where one side has `x.y.x` and the other has `x.y` but you can work around this with:
```
    <dependencies>
        <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>bootswatch</artifactId>
            <version>3.3.5</version>
            <exclusions>
                <exclusion>
                    <groupId>org.webjars.bower</groupId>
                    <artifactId>bootstrap</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>bootstrap</artifactId>
            <version>3.3.5</version>
        </dependency>
    </dependencies>
```

I need to fix the range syntax.

**Comment by jamesward** [comment]
After further investigation I figured out why this didn't work for `bootstrap` `3.3.5`.  The version is deployed but not listed in the artifact root pom:
https://repo1.maven.org/maven2/org/webjars/bower/bootstrap/maven-metadata.xml

I'm going to try and republish this artifact and see if it updates this time.

**Comment by jamesward** [comment]
Looks like it is there now.  So this should be fixed.
