### ISSUE TITLE
Maven bower Bootswatch 3.3.5 missing files

### ISSUE THREAD

**Issue by samer-abdelkafi** [webjars/webjars#1109]
The maven dependency org.webjars.bower:bootswatch:3.3.5 is missing fonts files.

https://github.com/thomaspark/bootswatch/tree/gh-pages/fonts

Bellow the list of packaged files:

META-INF/resources/webjars/bootswatch/3.3.5/LICENSE
META-INF/resources/webjars/bootswatch/3.3.5/README.md
META-INF/resources/webjars/bootswatch/3.3.5/bower.json
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/cerulean/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/cosmo/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/cyborg/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/darkly/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/darkly/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/darkly/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/darkly/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/darkly/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/darkly/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/darkly/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/flatly/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/flatly/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/flatly/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/flatly/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/flatly/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/flatly/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/flatly/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/journal/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/journal/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/journal/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/journal/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/journal/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/journal/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/journal/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/lumen/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/lumen/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/lumen/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/lumen/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/lumen/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/lumen/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/lumen/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/paper/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/paper/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/paper/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/paper/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/paper/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/paper/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/paper/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/readable/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/readable/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/readable/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/readable/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/readable/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/readable/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/readable/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/sandstone/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/simplex/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/simplex/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/simplex/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/simplex/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/simplex/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/simplex/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/simplex/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/slate/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/slate/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/slate/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/slate/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/slate/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/slate/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/slate/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/spacelab/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/superhero/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/superhero/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/superhero/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/superhero/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/superhero/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/superhero/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/superhero/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/united/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/united/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/united/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/united/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/united/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/united/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/united/variables.less
META-INF/resources/webjars/bootswatch/3.3.5/yeti/_bootswatch.scss
META-INF/resources/webjars/bootswatch/3.3.5/yeti/_variables.scss
META-INF/resources/webjars/bootswatch/3.3.5/yeti/bootstrap.css
META-INF/resources/webjars/bootswatch/3.3.5/yeti/bootstrap.min.css
META-INF/resources/webjars/bootswatch/3.3.5/yeti/bootswatch.less
META-INF/resources/webjars/bootswatch/3.3.5/yeti/thumbnail.png
META-INF/resources/webjars/bootswatch/3.3.5/yeti/variables.less

**Comment by jamesward** [comment]
The Bower WebJar just packages up whatever is in the Bower package.  So if there are missing files, then that is a problem with the upstream Bower package.
