### ISSUE TITLE
Add new version of mapbox.js; manual license inspection needed for Bower?

### ISSUE THREAD

**Issue by bbarker** [webjars/webjars#1114]
The [MapBox repo's](https://github.com/mapbox/mapbox.js) bower.json file has `"license": "See LICENSE.md"` in it, which is likely a problem ... after looking at the license, it has the somewhat strange request that the license be distributed with the "binary form" of the program. 

Not sure the best way to proceed. Classic webjar?

**Comment by jamesward** [comment]
Yeah, it doesn't look like our automated license detector will be able to figure that out.  So we will need to go with a Classic WebJar.  Can you go through the regular process to request that?
