### ISSUE TITLE
Failed to deploy bower webjar for jstat 1.3.0

### ISSUE THREAD

**Issue by mackler** [webjars/webjars#1121]
Running `bower info jstat` finds version 1.3.0, but trying to deploy I get an error:

    Failed! {"status":"Validation Failed","messages":"[There are no published artifacts to sync for this version.]"}
    If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
    Published BinTray Version
    Signed BinTray Assets
    Published BinTray Assets
    Created BinTray Version
    Created BinTray Package
    Converted project licenses
    Created Bower WebJar
    Fetched Bower zip
    Generated POM
    Converted dependencies to Maven
    Got Bower info
    Starting Deploy

**Comment by jamesward** [comment]
I've been having a strange timing issue with BinTray lately.  I've published this package manually so it should work now.

**Comment by mackler** [comment]
Worked; thanks!!
