### ISSUE TITLE
i18next Bower Webjar Failed : Published BinTray Not Allowed

### ISSUE THREAD

**Issue by M3lkior** [webjars/webjars#1124]
<code>Failed! <html>
 <head><title>405 Not Allowed</title></head>
 <body bgcolor="white">
 <center><h1>405 Not Allowed</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  
Published BinTray Version 
Signed BinTray 
Assets Published 
BinTray Assets Created
 BinTray Version Created
 BinTray Package 
Converted project licenses 
Created Bower WebJar
 Fetched Bower zip 
Generated POM 
Converted dependencies to Maven 
Got Bower info 
Starting Deploy</code>

**Comment by tscheinecker** [comment]
just ran into the same issue while trying to deploy system.js@0.18.4

**Comment by jamesward** [comment]
I think BinTray or Maven Central has been having some issues over the past few hours.  Can you try again?

**Comment by tscheinecker** [comment]
worked again for me!

**Comment by jamesward** [comment]
@M3lkior Can you let us know if it is working now?

**Comment by M3lkior** [comment]
Impossible ^^ Last release of i18next is published on Webjars :).

Thanks @jamesward
