### ISSUE TITLE
Bower Webjars not working with Play 2.3? 

### ISSUE THREAD

**Issue by cnmuc** [webjars/webjars#1125]
I followed your approach from http://www.jamesward.com/2015/03/23/scaling-the-webjars-project-with-on-demand-bower-packages and used "org.webjars.bower" % "angular-easyfb" % "1.3.1" in my Play application as there currently is no classic version of this lib available.
However, now I'm getting an error while building my project: 

Optimizing JavaScript with RequireJS
Error: Error: paths fallback not supported in optimizer. Please provide a build config path override for angular-easyfb

Is the bower-version compatible with Play 2.3? Or didn't I get it right?

**Comment by jamesward** [comment]
This is likely due to something with [sbt-rjs](https://github.com/sbt/sbt-rjs) not being configured correctly.  Check out the docs and file an issue over on that project if you think that there is a bug.
