### ISSUE TITLE
npm packages: SPDX expressions as license

### ISSUE THREAD

**Issue by cornerman** [webjars/webjars#1127]
According to the [npm-docs](https://docs.npmjs.com/files/package.json#license), multiple licenses should be written as SPDX expressions, but when I try to deploy, e.g., jshint (v2.8.0) with license ```(MIT AND JSON)```, bintray complains about an invalid license.

**Comment by jamesward** [comment]
Wow. They sure love making the parsing of this metadata fun.  I'm not sure we can express the differences between `AND` and `OR` in the `pom.xml`.  I can't tell from [the pom definition](https://maven.apache.org/pom.html#Licenses) whether multiple licenses are an `AND` or an `OR` so I'm not quite sure what to do about this.  Any ideas?

**Comment by cornerman** [comment]
Thanks for the response and all the work you are doing here. I feel your pain.

From what I have found, it seems that the licenses in the ```pom.xml``` are actually an ```OR```. The [maven reference](http://maven.apache.org/ref/3.3.3//maven-model/maven.html) says:

```"If multiple licenses are listed, it is assumed that the user can select any of them, not that they must accept all."```

So, support for a conjunction of licenses seems to be missing; not sure how to proceed for the ```AND``` operator.

**Comment by jamesward** [comment]
That makes sense.  I've seen an `AND` used when different parts of a distribution are licensed differently.   But a simple `AND` expression doesn't seem like a good way to express that case since it doesn't clarify which parts are licensed which way.  And I can't really think of a good reason why a whole distribution would be licensed under a conjoined license.  So maybe we should ask the upstream project for clarification around what they mean by their `(MIT AND JSON)` license choice.

**Comment by jamesward** [comment]
What makes this case especially odd is that jshint's [README specified license](https://github.com/jshint/jshint#license) and [actual LICENSE file](https://github.com/jshint/jshint/blob/master/LICENSE) are just MIT.  So this seems inconsistent with the `package.json` license expression.

**Comment by cornerman** [comment]
This is indeed inconsistent. There already seems to be a long lasting discussion about the licensing model: https://github.com/jshint/jshint/issues/1234

From what I understand, the whole situation seems to be due to license of the original codebase ```jslint``` from which it was forked and the original author refusing to license his code under a different license. They actually started rebasing the code on a snapshot that was licensed to the eclipse foundation under the MIT license (from the discussion I am not sure if this is finished). 
Funnily, the license was just [added](https://github.com/jshint/jshint/commit/e47168f5aa9576819830554f1b37dc0d49b76d31) to the ```package.json```.

Licenses...

**Comment by cornerman** [comment]
It is about the additional clause in the [JSON](http://www.json.org/license.html) license: ```The Software shall be used for Good, not Evil.```

**Comment by jamesward** [comment]
Wow. The plot thickens.  So in this case the `AND` does make some sense, assuming everyone shares a definition of `Good` and `Evil`.  :)

**Comment by cornerman** [comment]
:)

And let us thank bower for having an MIT licensed version.

**Comment by jamesward** [comment]
The fix for `OR` expressions will be deployed shortly.  I don't think we will be able to support the `AND` expressions so I'm going to leave this closed unless someone has an idea.
