### ISSUE TITLE
Bower WebJar creation failure for flux

### ISSUE THREAD

**Issue by asazernik** [webjars/webjars#1132]
Parsing the [license file](https://github.com/facebook/flux/blob/master/LICENSE) failed

```
Failed! https://github.com/facebook/flux/blob/master/LICENSE could not be converted to a knowable license
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Created Bower WebJar
Fetched Bower zip
Generated POM
Converted dependencies to Maven
Got Bower info
Starting Deploy
```

**Comment by asazernik** [comment]
Seems to be a pretty bog-standard BSD 3-clause.

**Comment by jamesward** [comment]
Yeah, and my license detector says so: https://github-license-service.herokuapp.com/facebook/flux

I think that I need to rework my logic for license detection in this app.  Stay tuned.

**Comment by asazernik** [comment]
:+1:

**Comment by jamesward** [comment]
This fix will be deployed in about 10 minutes.  Can you try again then and let me know how it goes?

**Comment by asazernik** [comment]
Yup - works!

(What an ugly special case to deal with.)

**Comment by jamesward** [comment]
Yeah.  Unfortunately the `package.json` and `bower.json` specs do not indicate that the `license` definition be actually resolvable by a machine. :(
