### ISSUE TITLE
Adding bower bootstrap-datepicker failed 1.4.0

### ISSUE THREAD

**Issue by zalizko** [webjars/webjars#1133]
Failed!
{"status":"Validation Failed","messages":"[There are no published artifacts to sync for this version.]"}
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
Created BinTray Package
Converted project licenses
Created Bower WebJar
Fetched Bower zip
Generated POM
Converted dependencies to Maven
Got Bower info
Starting Deploy

**Comment by jamesward** [comment]
Can you try again? There have been some intermitent issues with BinTray / Maven Central.

**Comment by zalizko** [comment]
I tried again, but I've got the same error

**Comment by jamesward** [comment]
Sorry about that.  I had to delete the version on BinTray and then redeploy it.  It is there now:
```
GroupID = org.webjars.bower
ArtifactID = bootstrap-datepicker
Version = 1.4.0
```

**Comment by zalizko** [comment]
thanks!
