### ISSUE TITLE
Failed to create ng-file-upload for npm 

### ISSUE THREAD

**Issue by stanleyxu2005** [webjars/webjars#1135]
I found ng-file-upload 5.0.9 in bower. I tried to deploy it in npm way, but failed. Could you please kindly find out the reason?

Here is the error message
```
Failed! {"status":"Validation Failed","messages":
"[Missing: no javadoc jar found in folder '/org/webjars/npm/ng-file-upload/5.0.9', Dropping existing partial staging repository.]"
} 

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
```

**Comment by jamesward** [comment]
I'm not sure why a javadoc jar is required all of a sudden for this one.  But I'm fixing this and the change should be deployed in 10 minutes.  Can you try again then?

**Comment by stanleyxu2005** [comment]
@jamesward Same error message

**Comment by jamesward** [comment]
I deleted this and tried again and it worked:
```
GroupID = org.webjars.npm
ArtifactID = ng-file-upload
Version = 5.0.9
```
