### ISSUE TITLE
Possible only deploy the dist directory?

### ISSUE THREAD

**Issue by stanleyxu2005** [webjars/webjars#1136]
I'm trying to switch classic webjars to npm webjars. I noticed that npms webjars are much larger than classic, because all directories are packed. Actually in most case we only need the dist files. All other files are not required. Is it possible to have dist-only (and full) versions?

**Comment by jamesward** [comment]
The NPM and Bower WebJars are just an automatic repackaging of the upstream distribution so there is no way for us to change the contents.

**Comment by stanleyxu2005** [comment]
Good to know. So I'd stick to `org.webjar` instead of `org.webjar.bower` or `org.webjar.npm`. Otherwise the size of required dependencies will be huge. I'm using angular, bootstrap and angular-strap. They are roughly 50MB... The real stuff for webapp is actually less than 1MB...

I do think there should be possible to remove everything but keep the dist directory only. E.g.
```
"org.webjar.npm.dist" %% "angularjs" %% "1.4.0" // means to download a minimal jar for production environment
"org.webjar.npm" %% "angularjs" %% "1.4.0" // means to download a full source package
```

**Comment by jamesward** [comment]
The problem is that we can't programmatically figure out where the `dist` stuff is since everyone uses different conventions and some libraries don't provide anything of the sort.  So for your uses it is probably better to stick with the Classic WebJars.
