### ISSUE TITLE
use license.txt as well as LICENSE.txt

### ISSUE THREAD

**Issue by ilazarte** [webjars/webjars#1138]
Deployment of a bower resource via: https://github.com/Reactive-Extensions/RxJS fails due to not locating the license.txt file even though the documentation suggests LICENSE.txt is valid.  Seems like it should be ok to use license.txt as another alternate name.

**Comment by hipnoizz** [comment]
Similar for https://github.com/inuyaksa/jquery.nicescroll - the license is in MIT.LICENSE file. The simplest and most flexible solution would be allowing to provide a filename when creating a webjar from a Bower-enabled project.

**Comment by jamesward** [comment]
I'm deploying a fix for `license.txt`: https://github.com/jamesward/github-license-service/commit/7924412c9362bb1fe39e70e4ac59cc35fb127d37

The better solution is to have projects specify the license metadata into their `package.json` or `bower.json` files so we don't have to go hunting around to find the license.

**Comment by ilazarte** [comment]
Works great, thanks.
