### ISSUE TITLE
license issue with nvd3 using bower deploy

### ISSUE THREAD

**Issue by manjoine** [webjars/webjars#1140]
I tried to deploy the nvd3 1.8.1 using bower and got this.

Failed! No valid licenses found. Detected licenses: Apache License, v2.0 The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo. 

If you look at the upstream for nvd3 it has the correct license in package.json and bower.json.

Can you let me know what the problem is so that i can create a ticket with the upstream provider? or do you want me to generate the classic webjar for it?

As a foot note, I found this issue when trying to get the latest angular-nvd3 running in bower.

I did see the npm for nvd3 but it wont work with the bower dependencies when I am using angular-nvd3 1.0.0-rc

"org.webjars.npm" % "nvd3" % "1.8.1",
"org.webjars.bower" % "angular-nvd3" % "1.0.0-rc",

[error] (*:update) sbt.ResolveException: unresolved dependency: org.webjars.bower#nvd3;[1.7.1,1.8): not found

**Comment by jamesward** [comment]
The problem is that `Apache License, v2.0` is not the correct [SPDX](https://spdx.org/licenses/) identifier.  But I've added a mapper for this that will be deployed shortly.  Try this again in 10 minutes and it should work.

**Comment by manjoine** [comment]
Works prefect now thanks! I will still let them know to use the correct identifier if you think its appropriate.

**Comment by jamesward** [comment]
Yeah, they should fix their metadata.

**Comment by manjoine** [comment]
They have it fixed for next release.

https://github.com/novus/nvd3/issues/1148
