### ISSUE TITLE
bower foundation license issue

### ISSUE THREAD

**Issue by damirv** [webjars/webjars#1143]
I can't deploy versions of foundation bower webjars. The license file is indeed missing in the downloaded `.tar.gz` (in my case [v4.3.2](https://github.com/zurb/bower-foundation/archive/4.3.2.tar.gz)), but there is a license file [here](https://github.com/zurb/foundation/blob/master/LICENSE). 

Do you have suggestions for a possible solution here?

Thanks.

**Comment by jamesward** [comment]
The problem is that the license metadata isn't programmatically discoverable because it isn't in the `bower.json` and the Bower project actually points to https://github.com/zurb/bower-foundation which doesn't contain a license.  This will have to be fixed upstream.
