### ISSUE TITLE
dhtmlxgantt

### ISSUE THREAD

**Issue by mahdimohammadi2** [webjars/webjars#1152]

**Comment by mahdimohammadi2** [comment]
Hi
I work on a erp system project and I need a lot of js library and some of them there is not in webjars repository.
can I create them?
one of them is dhtmlxgantt.

**Comment by mahdimohammadi2** [comment]
this is the repository
https://github.com/DHTMLX/gantt

**Comment by mahdimohammadi2** [comment]
and I don't know about tagged release.

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/gantt

This will be released shortly.

**Comment by mahdimohammadi2** [comment]
thank you james
