### ISSUE TITLE
HolderJS 2.8.1 cannot deploy due to license

### ISSUE THREAD

**Issue by alecharp** [webjars/webjars#1154]
I tried to deploy the latest version of holder.js project (2.8.1) but I get this:

```
Failed! No valid licenses found. No licenses were found. The acceptable 
licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 
License detection first uses the package metadata (e.g. package.json or 
bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or 
LICENSE.md file in the master branch of the GitHub repo. Since these 
methods failed to detect a valid license you will need to work with the 
upstream project to add discoverable license metadata to a release or to 
the GitHub repo.
```

This is a great validation to check for license. However, for holder.js project, there is the license in the package.json file: https://github.com/imsky/holder/blob/v2.8.1/package.json#L12

Do you think this is coming from webjars or BinTray? The message let me think it's coming from BinTray. Thanks for your help.

**Comment by jamesward** [comment]
Maybe you were trying to publish this as a Bower WebJar?  If so the metadata is in the `bower.json` and likely there isn't a valid license there.  I've published this as an NPM WebJar and it worked:
```
GroupID = org.webjars.npm
ArtifactID = holderjs
Version = 2.8.1
```

**Comment by alecharp** [comment]
Thanks!
