### ISSUE TITLE
Lato bower webjar license

### ISSUE THREAD

**Issue by danielnixon** [webjars/webjars#1155]
[Lato](https://github.com/mrkelly/lato)'s [package.json](https://github.com/mrkelly/lato/blob/master/package.json) and [bower.json](https://github.com/mrkelly/lato/blob/master/bower.json) point out that it is covered by OFL 1.1 for the fonts and MIT for the code. These both appear in the [Bintray footnote](https://bintray.com/docs/api/#_footnote_1) (although the footnote lists "Openfont-1.1", not "OFL-1.1") but WebJars won't deploy Lato.

**Comment by jamesward** [comment]
Unfortunately the license definitions in `bower.json` aren't valid according to the [spec](https://github.com/bower/bower.json-spec).  But I was able to publish the NPM package using the git repo (since the library wasn't officially published in NPM):
```
GroupID = org.webjars.npm
ArtifactID = github-com-mrkelly-lato
Version = 0.3.0
```

**Comment by danielnixon** [comment]
Thanks @jamesward.
