### ISSUE TITLE
Website broken on mobile

### ISSUE THREAD

**Issue by rathboma** [webjars/webjars#1160]
The header menu blocks a while bunch of the page and it seems to take ages to load some things.

Screenshot:https://goo.gl/photos/qES9Mui4og2e4SWW7

**Comment by jamesward** [comment]
Thanks for the bug report.  I haven't put any effort into making webjars.org mobile friendly because I think most WebJar users will be on larger profile machine when visiting the site.  So this will be low priority but I'd love for someone to send a PR to fix this.

**Comment by jamesward** [comment]
The UI overlap part of this was fixed by #1393.  The long loading part is the same as #1327.
