### ISSUE TITLE
Bower Webjars constantly fail due to missing license

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1161]
I am not sure if its just me, but automatically adding a bower webjar via http://www.webjars.org/bower seems to always fail with the 

>
Failed! No valid licenses found. Detected licenses: ./LICENSE The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Determined Artifact Name: angular-equalizer Starting Deploy

The thing is, these bower packages do have a license. As an example, I am trying to make a webjar of https://github.com/pocesar/angular-equalizer, and as you can see, there clearly is a `license` specified in the `bower.json`. Even the fallback isn't working (there is a `LICENSE` file in the root of the github)

Is there something that is fundamentally wrong with the repo, or is it something else? I have had these issues with other `bower` packages as well.

**Comment by gjdev** [comment]
Same here for bower packages for which this used to work, and where nothing (seems to) have changed regarding licensing in the package.json and github repo.

**Comment by jamesward** [comment]
There are so many different ways that the licenses are specified that we have to deal with them one by one.  I'll work on a fix for the way that angular-equalizer does things.  Other issues should be filed for other libraries that don't work.

**Comment by mdedetrich** [comment]
Cool thanks!
