### ISSUE TITLE
Bower package license issue (jquery-waypoints)

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1162]
>
Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Determined Artifact Name: jquery-waypoints Starting Deploy

jquery-waypoints 3.1.1, also 2.0.3

**Comment by jamesward** [comment]
This should be fixed by: https://github.com/jamesward/github-license-service/commit/9f980b1cabe493e9676628bea828b1bbaae25b31
