### ISSUE TITLE
Bower package license issue (jquery.fileDownload)

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1163]
>
Failed! No valid licenses found. No licenses were found. The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Determined Artifact Name: jquery.fileDownload Starting Deploy

https://github.com/johnculviner/jquery.fileDownload  with v1.4.2

**Comment by jamesward** [comment]
This worked fine for me:
```
GroupID = org.webjars.bower
ArtifactID = jquery-file-download
Version = 1.4.3
```

**Comment by mdedetrich** [comment]
Ah, I was using jquery.fileDownload instead of jquery-file-download
