### ISSUE TITLE
Webjar repo for bootstrap-treeview

### ISSUE THREAD

**Issue by bcopy** [webjars/webjars#1169]
Hello,

I've created a webjar for the excellent Bootstrap Treeview (v. 1.2.0).

The pom descriptor is ready (except not sure what's supposed to go in the requirejs section)

https://github.com/bcopy/bootstrap-treeview

Thanks,

Brice

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/bootstrap-treeview

This will be released shortly.
