### ISSUE TITLE
angular-ui-layout claims "No version was specified"

### ISSUE THREAD

**Issue by mackler** [webjars/webjars#1173]
And yet I selected the version from the pulldown menu on the ["Add a New Bower Webjar" dialog window](http://www.webjars.org/bower).

**Comment by jamesward** [comment]
Yeah, that is strange.  I'll investigate.

**Comment by jamesward** [comment]
I found the issue.  This following in the project's `bower.json` isn't valid:

    "raf": "https://gist.githubusercontent.com/paulirish/1579671/raw/3d42a3a76ed09890434a07be2212f376959e616f/rAF.js"

This will need to be fixed upstream because it isn't valid according to the Bower spec.

I'm also going to improve the error message.

**Comment by mackler** [comment]
Thank you for diagnosing that, James.
