### ISSUE TITLE
bootstrap-material-datetimepicker: Add a New Bower WebJar failed!

### ISSUE THREAD

**Issue by samer-abdelkafi** [webjars/webjars#1176]
Failed! Could not get license If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: bootstrap-material-datetimepicker Starting Deploy

License: https://github.com/T00rk/bootstrap-material-datetimepicker/blob/gh-pages/LICENSE.md

**Comment by jamesward** [comment]
The problem is that the license is on the `gh-pages` branch and we only look on the master branch right now.  I think I can add support for checking the `gh-pages` branch.
