### ISSUE TITLE
Handle spaces in version ranges

### ISSUE THREAD

**Issue by ryandbair** [webjars/webjars#1177]
Semver ignores a lot of whitespace, but the webjars.org "add a new webjar" utilities explode when they see unexpected spaces. 

One such example is js-yaml before version 3.3.0 (looking at 3.0.1 specifically) which has a dependency on argparse "~ 0.1.11". The space between the tilde and the version number causes an error.

**Comment by jamesward** [comment]
Thanks for the bug report.  I'll work on a regex fix.
