### ISSUE TITLE
Add bootstrap-languages webjar

### ISSUE THREAD

**Issue by php-coder** [webjars/webjars#1185]
I would like to have a webjar for https://github.com/usrz/bootstrap-languages project.

Anyway thank you for your work!

**Comment by jamesward** [comment]
This has been deployed as a Bower WebJar:
```
GroupID = org.webjars.bower
ArtifactID = bootstrap-languages
Version = 1.5.2
```

**Comment by php-coder** [comment]
Thanks a lot!

**Comment by php-coder** [comment]
I've tried to use it and I'm a bit frustrated about it, because there is no CSS files. How to supposed to use it? Right now it's unusable for me, unfortunately. :(

**Comment by jamesward** [comment]
@php-coder You'll have to bring that up with the upstream provider since the WebJar just packages whatever is in the Bower distribution.  Otherwise you could contribute a Classic WebJar that packages what you need.
