### ISSUE TITLE
Spring MVC instructions will misconfigure a Spring Boot application

### ISSUE THREAD

**Issue by spilth** [webjars/webjars#1187]
Spring Boot provides out of the box support for WebJars:

- [Spring Boot Reference Guide - 26.1.4 Static Content](http://docs.spring.io/spring-boot/docs/1.2.5.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-static-content)
- [Spring Boot WebMvcAutoConfiguration](https://github.com/spring-projects/spring-boot/blob/1466169dc087bbff62124251c4255abde5f8f642/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration.java#L243)

If you follow the Spring MVC instructions it ends up disabling the static resource mappings that Spring Boot sets up.

You only need to add a dependency and then reference the WebJars in your HTML.

I'll be making a Pull Request shortly to add documentation for Spring Boot.

**Comment by jamesward** [comment]
Thanks for pointing that out.  A PR would be awesome.
