### ISSUE TITLE
bootstrap-material-datetimepicker: Add a New Bower WebJar failed!

### ISSUE THREAD

**Issue by samer-abdelkafi** [webjars/webjars#1193]
Failed! Server returned HTTP response code: 500 for URL: https://bower-as-a-service.herokuapp.com/download/bootstrap-material-datetimepicker/2.0.0

I get a response from : https://bower-as-a-service.herokuapp.com/download/bootstrap-material-datetimepicker/2.0.0

**Comment by jamesward** [comment]
This is failing for the same reason as https://github.com/webjars/webjars/issues/1168

The output of `bower install bootstrap-material-datetimepicker#2.0.0` is:
```
Unable to find a suitable version for jquery, please choose one:
    1) jquery#1.11.0 which resolved to 1.11.0 and is required by bootstrap-material-datetimepicker#2.0.0
    2) jquery#>= 1.9.1 which resolved to 1.11.0 and is required by bootstrap#3.3.5
    3) jquery#~2.1.1 which resolved to 2.1.4 and is required by bootstrap-material-design#0.3.0

Prefix the choice with ! to persist it to bower.json

? Answer: 
```

I'm going to close this as a duplicate but you can watch that other issue for any updates.
