### ISSUE TITLE
Could not convert NPM / Bower version to Maven for: angular >=1.2.16 1.4.x  

### ISSUE THREAD

**Issue by philwestwell** [webjars/webjars#1194]
I'm trying to deploy a Bower webjar for angular-ui-grid 3.0.5 (the entry I'm referring to is https://github.com/angular-ui/bower-ui-grid and not  https://github.com/angular-ui/bower-ui-grid.git )

If I click the plus sign, then version 3.0.5 is available but when I add it, I get the following log error

Failed! Could not convert NPM / Bower version to Maven for: angular >=1.2.16 1.4.x If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

From the history, it looks like this used to work until the "1.3 dot x" was introduced to bower.json. Not knowing whether this was valid bower.json or not, I cloned https://github.com/angular-ui/bower-ui-grid and did a "bower install", but it worked producing the log below:

bower angular#>=1.2.16 1.4.x    cached git://github.com/angular/bower-angular.git#1.4.4
bower angular#>=1.2.16 1.4.x  validate 1.4.4 against git://github.com/angular/bower-angular.git#>=1.2.16 1.4.x
bower angular#>=1.2.16 1.4.x       new version for git://github.com/angular/bower-angular.git#>=1.2.16 1.4.x
bower angular#>=1.2.16 1.4.x   resolve git://github.com/angular/bower-angular.git#>=1.2.16 1.4.x
bower angular#>=1.2.16 1.4.x  download https://github.com/angular/bower-angular/archive/v1.4.5.tar.gz
bower angular#>=1.2.16 1.4.x   extract archive.tar.gz
bower angular#>=1.2.16 1.4.x  resolved git://github.com/angular/bower-angular.git#1.4.5
bower angular#>=1.2.16 1.4.x   install angular#1.4.5
 
Am I correct in thinking that if it works in Bower then it should work in webjars?

Thanks, 

Phil

(PS - in case you were wondering - after discussions with James last week about a classic webjar of ui-grid, it turns out that the software I'm using will only work with a Bower webjar, hence the renewed emphasis on Bower)

**Comment by jamesward** [comment]
The fix for the conversion bug should be deployed in about 10 minutes.  Feel free to reopen this if it still doesn't work.

**Comment by philwestwell** [comment]
Just tried it now and it seems to have worked. Thanks
