### ISSUE TITLE
Bower Webjars: Update with invalid license

### ISSUE THREAD

**Issue by KarelCemus** [webjars/webjars#1195]
Hi,

I'd like to add or update some libraries which do not provide valid license information. The license file is either missing or has wrong name such as `license.txt`. Right now webjars rejects these libraries even when the repository is already fetched for some version. 

1) what to do to include repository with wrong or missing license information?
2) is it possible to update bower webjars for [`tinymce-dist`](https://github.com/tinymce/tinymce-dist) to the latest version? There is old version but it rejects update requests.

Thanks

**Comment by jamesward** [comment]
1) We maintain some pretty crazy logic to programmatically determine the license.  In some cases that logic can be improved.  In other cases the upstream project needs to take steps to get their license metadata into a better state.  If the license detection logic is failing, please file an issue.
2) It looks like we should be able to figure out the license for that library.  What was the error?

**Comment by KarelCemus** [comment]
1) So when the license file is missing, it is necessary to update the upstream project? Even when it is more or less dead, i.e., almost impossible? Isn't there any workaround except forking the project?

2) There is error message

```
Failed!
License at http://www.tinymce.com/license was not plain text
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: tinymce-dist
Starting Deploy
```

**Comment by jamesward** [comment]
1) We use a lot of different methods to determine the license.  If all of them fail and it is not due to a bug, then the only options are to get the upstream to add a license or fork the project.  We won't maintain project specific metadata.

2) Thanks.  That is a bug.  I'll investigate.

**Comment by KarelCemus** [comment]
OK, thanks for information and accepting the bug.

**Comment by jamesward** [comment]
This fix should be deployed in about 10 minutes.

**Comment by KarelCemus** [comment]
Thanks for the quick bugfix!

**Comment by KarelCemus** [comment]
I'd like to reopen this issue. I tried to upgrade that tinymce-dist library and it failed with the following error:

```
Failed! 

<!DOCTYPE html> <html> <head> <meta name="viewport" content="width=device-width, initial-scale=1"> <style type="text/css"> html, body, iframe { margin: 0; padding: 0; height: 100%; } iframe { display: block; width: 100%; border: none; } </style> <title>Application Error</title> </head> <body> <iframe src="//s3.amazonaws.com/heroku_pages/error.html"> <p>Application Error</p> </iframe> </body> </html> 

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Determined Artifact Name: tinymce-dist
Starting Deploy
```

**Comment by jamesward** [comment]
A timeout is happening with the license detector service.  I'm investigating why this is happening now as it wasn't happening yesterday.

**Comment by jamesward** [comment]
I've fixed the timeout and was able to deploy this Bower WebJar:
```
GroupID = org.webjars.bower
ArtifactID = tinymce-dist
Version = 4.2.5
```

**Comment by KarelCemus** [comment]
Thanks!

**Comment by drumonii** [comment]
Found another case where bower webjars cannot parse a webpage containing a license in the bower.json.
```
Failed!
License at http://semantic-ui.mit-license.org/ was not plain text
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
            
Determined Artifact Name: semantic
Starting Deploy
```
Unlike tinymce, the license webpage for semantic does not redirect to a .txt file that can be easily parsed.

**Comment by jamesward** [comment]
I'm not sure if there is anything we can do about that since there would be no way to programmatically determine the license from that URL.  You can work with the upstream project maintainer to make the `bower.json` more "semantic" or you can try the NPM WebJar for this.

**Comment by drumonii** [comment]
Unfortunately the NPM webjar deploy fails as well:
```
Failed!
https://codeload.github.com/derekslife/wrench-js/legacy.tar.gz/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2: https://codeload.github.com/derekslife/wrench-js/legacy.tar.gz/156eaceed68ed31ffe2a3ecfbcb2be6ed1417fb2/info/refs?service=git-upload-pack not found
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
            
Got NPM info
Determined Artifact Name: semantic-ui
Starting Deploy
```
I'll raise an issue with the semantic ui repo and see what they can do about the Bower webjar. Thanks

**Comment by jamesward** [comment]
Ah, that failure is due to: https://github.com/Semantic-Org/Semantic-UI/blob/master/package.json#L85

We haven't added support for tgz dependencies yet, in part because it is hard to programmatically figure out if a dependency reference is a git repo or a tgz.  We do support git reference dependencies and I'm surprised that this project isn't using them.
