### ISSUE TITLE
Failed to deploy any npm package

### ISSUE THREAD

**Issue by stanleyxu2005** [webjars/webjars#1196]
I tried to deploy `angular-smart-table@2.1.3` and `dashing@0.2.1`, but failed with the same error message.

```
Failed! {
"status":"Sync Failed",
"messages":"[Failed to promote repository: orgwebjars-7097. Server response:\n could not parse response from server., Dropping existing partial staging repository.]"
}
```
Possibly caused by the recent nodejs major upgrade?

**Comment by jamesward** [comment]
Usually this happens when there are multiple BinTray deploys going on at once.  I've filed an issue with them.  Can you try the deploys again, but only do one at a time?  Sorry for the hassle.  I may have to work around this myself if they don't fix this soon.

**Comment by jamesward** [comment]
Looks like something is broken with either BinTray or Maven Central at the moment.

**Comment by stanleyxu2005** [comment]
Thanks for the reply. It still does not work. Before I report the problem, I didn't launch multiple deployment at a same time. 

I should have deploy these packages couple of days earlier, my commit that requires the packages will be blocked until the webjar issue gets fixed.

**Comment by jamesward** [comment]
There is still an issue with BinTray syncing to Maven Central.  I've reported the issue to BinTray so hopefully this is resolved soon.

**Comment by philwestwell** [comment]
In case this helps, is the a possibility it could be connected to the fix for the 1.4.x Bower issue you fixed yesterday (or the webjar I deployed straight after the fix)? webjars reported a success status, but the update never made it to Maven Central and when I tried a different version after a couple of hours I got the same error as @stanleyxu2005 reported.

**Comment by stanleyxu2005** [comment]
It works now.

**Comment by philwestwell** [comment]
I just got the problem now when I tried it. Is this a glitch or has the problem started again?

Failed! {"status":"Sync Failed","messages":"[Failed to promote repository: orgwebjars-7160. Server response:\n could not parse response from server., Dropping existing partial staging repository.]"} If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created BinTray Package Converted project licenses Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Determined Artifact Name: angular-ui-grid Starting Deploy

**Comment by stanleyxu2005** [comment]
Possible, as we dont have the concrete server response.

**Comment by jamesward** [comment]
@philwestwell Can you try again and report back?

**Comment by philwestwell** [comment]
I did angular-ui-grid v1.0.6 about an hour ago and just did v1.0.5 so I presume it's working again. I'll keep checking Maven Central and post back when it updates (or tomorrow if it doesn't update). Thanks

**Comment by philwestwell** [comment]
Update:: Maven Central still hasn't updated so I'm starting to think that something went wrong in the build of the webjars for angular-ui-grid 1.0.5 and 1.0.6. Does Maven Central issue any error logs for attempted uploads?

**Comment by jamesward** [comment]
@philwestwell I'm not seeing `angular-ui-grid` `1.0.5` or `1.0.6` available as valid upstream versions.  Can you double check those?

**Comment by philwestwell** [comment]
@jamesward thanks for the reply. I don't know how to spot valid/invalid upstream versions but here is the information from which I was proceeding. 
If you navigate to http://bower.io/search/?q=angular-ui-grid then click the link you end up on this page https://github.com/angular-ui/bower-ui-grid, which shows the bower.json tagged v3.0.5 (and package.son tagged v3.0.6, which is inconsistent, I suppose). 

If I do a bower install for angular-ui-grid, everything works. 

When I go to http://www.webjars.org/bower, filter by angular-ui-grid and click the plus sign, I'm offered versions 3.0.5 and 3.0.6 (although I don't know where it's looking to get these numbers).   

Is that the sort of upstream you meant?

**Comment by philwestwell** [comment]
Sorry, James I just re-read your comment and mine. I should have typed 3.0.5 and 3.0.6 in the earlier comments.

**Comment by philwestwell** [comment]
Sorry, @jamesward that was a mistype - I should have said 3.0.5 and 3.0.6. 

I've checked those versions and apart from an inconsistency between the bower.json/package.json version numbers of github (see https://github.com/angular-ui/bower-ui-grid) everything looks fine.

**Comment by jamesward** [comment]
I just redeployed `3.0.5` and `3.0.6` so they should be in Maven Central now.  The indexes will take a few hours to update.

**Comment by philwestwell** [comment]
Yes they are in Github now. Thanks.
