### ISSUE TITLE
The RequireJS config in the bootstrap WebJar may need to be updated. 

### ISSUE THREAD

**Issue by cplaetzinger** [webjars/webjars#1200]
I tried to use the following webjar

    <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>x-editable-bootstrap3</artifactId>
        <version>1.5.1</version>
    </dependency>

In my JavaScript code I try to load it using require.js but got the following error 

    Detected a legacy file name (bootstrap.js) as the thing to load.  Loading via file name is no longer     supported so the .js will be dropped in an effort to resolve the module name instead. webjarsjs:19 
    The webjars plugin loader (e.g. webjars!bootstrap) has been deprecated.  The RequireJS config in the bootstrap WebJar may need to be updated.  Please file an issue: http://github.com/webjars/webjars/issues/new

**Comment by jamesward** [comment]
A fix will be released shortly as `1.5.1-1`.  In the future please file issues for Classic WebJars on WebJar's repo, e.g. https://github.com/webjars/x-editable-bootstrap3

**Comment by cplaetzinger** [comment]
Thanks for your fast reply.

**Comment by cplaetzinger** [comment]
Just for the record: works perfectly :+1:
