### ISSUE TITLE
Cannot deploy new version of angular-translate, Bower package

### ISSUE THREAD

**Issue by twwwt** [webjars/webjars#1204]
Hello

Today I tried to deploy the latest version 2.7.2 of `angular-translate` and `angular-translate-loader-partial`. It failed in both cases with the following message in the dialog:

```
Failed!
Could not get license
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
Determined Artifact Name: angular-translate
Starting Deploy
```

Not sure whether the failure is actually caused by a problem in Webjar code or by some issue in the project. Just wanted to inform you about the problem. Since there are earlier versions for both modules deployed already, it must have worked sometime before.

**Comment by jamesward** [comment]
I'm not sure why this worked in the past, but the `angular-translate` [bower.json](https://github.com/angular-translate/bower-angular-translate/blob/master/bower.json#L8-L13) is not doing things according to [the spec](https://github.com/bower/bower.json-spec#license).

The `angular-translate-loader-partial` library is making the same mistake.

I'm not sure I want to add yet another workaround for non-compliant libs.  In which case you can either: - Work with the upstream project to fix this.
- Try the NPM WebJars for these
- Use the Classic WebJars

Let me know what you think.

**Comment by twwwt** [comment]
I agree that adding a workaround doesn't really help here. But I think the error message could give more insight in *why* the build failed. Rather than "Could not get license" it should say something like "License section not found or invalid in bower.json.".

I'll create an issue to fix the file in angular-translate. It seems that the bower.json was copied from a package.json because the license section uses the format defined for package.json files.

Btw, am I right that if there is both a package.json and a bower.json file then the latter is preferred over the former? I'm not an expert, but as far as my knowledge goes, I would prefer the former over the latter.

**Comment by twwwt** [comment]
Tracked on the opposite end by angular-translate/angular-translate#1212

**Comment by jamesward** [comment]
Sounds good.  I'll update the error message.

If you are deploying a Bower WebJar then the `bower.json` is used.  For NPM WebJars the `package.json` is used.

**Comment by knalli** [comment]
fyi: In addition to the referenced commit, our bower repositories have been patched also. But obviously: the change will be affective on the next (new) release.
