### ISSUE TITLE
The main website (www.webjars.org) cannot load assets and unusable

### ISSUE THREAD

**Issue by mickeyvip** [webjars/webjars#1206]
The main website `http://www.webjars.org` cannot load assets from `cdn.jsdelivr.net`.

Loading the following files:

* `http://cdn.jsdelivr.net/webjars/org.webjars/bootstrap/3.3.4/css/bootstrap.min.css`
* `http://cdn.jsdelivr.net/webjars/org.webjars/bootstrap/3.3.4/css/bootstrap-theme.min.css`
* `http://cdn.jsdelivr.net/webjars/org.webjars/select2/3.5.2/select2.css`
* `http://cdn.jsdelivr.net/webjars/org.webjars/select2/3.5.2/select2-bootstrap.css`
* `http://cdn.jsdelivr.net/webjars/org.webjars/highlightjs/8.0/styles/default.min.css`
* `http://cdn.jsdelivr.net/webjars/org.webjars/bootstrap/3.3.4/js/bootstrap.min.js`
* `http://cdn.jsdelivr.net/webjars/org.webjars/jquery/1.11.1/jquery.min.js`
* `http://cdn.jsdelivr.net/webjars/org.webjars/select2/3.5.2/select2.min.js`
* `http://cdn.jsdelivr.net/webjars/org.webjars/highlightjs/8.0/highlight.min.js`

gives and error `504 Gateway Time-out`.

**Comment by jamesward** [comment]
It looks like it is back up again.  I'm not sure what happened with the CDN but I'll investigate.

**Comment by mickeyvip** [comment]
Just rechecked.. same problem.

I am outside of US... maybe this is the problem.

**Comment by jamesward** [comment]
Hmm.  Maybe one of the CDN edge locations is having issues.

**Comment by mickeyvip** [comment]
Sorry for the false alarm

**Comment by jimaek** [comment]
We didnt see any issue at all, all locations operate normally.
To debug this please send the output from here http://www.jsdelivr.com/tools/debug-tool
and the exact error that you see.

**Comment by jamesward** [comment]
Thanks @jimaek.

**Comment by mickeyvip** [comment]
@jimaek, I just tried to load the http://www.webjars.org and it was ok. 

So it was probably some local issue.

I was able to navigate to the main site `jsdelivr` and get the `jquery.js` from there.

The problem was getting files from: `http://cdn.jsdelivr.net/webjars/org.webjars`.

In any case I just opened the debugger page and this is the output link: http://goo.gl/5hGiRx

Again, the http://www.webjars.org is now ok.

Thank you.

**Comment by tjdett** [comment]
I'm also seeing main site issues and having problems with the webjar CDN.

Everything in the debug tool seems fine:
http://goo.gl/LJkSu5

However with curl it's definitely broken:
```
$ curl 'https://cdn.jsdelivr.net/webjars/jquery/1.11.1/jquery.js' -v                                                                                                 
*   Trying 146.88.132.39...
* Connected to cdn.jsdelivr.net (146.88.132.39) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=cdn.jsdelivr.net,OU=Domain Control Validated
*       start date: Oct 30 20:00:38 2014 GMT
*       expire date: Oct 31 20:00:38 2015 GMT
*       common name: cdn.jsdelivr.net
*       issuer: CN=GlobalSign Domain Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE
> GET /webjars/jquery/1.11.1/jquery.js HTTP/1.1
> User-Agent: curl/7.40.0
> Host: cdn.jsdelivr.net
> Accept: */*
> 
< HTTP/1.1 504 Gateway Time-out
< Date: Thu, 17 Sep 2015 04:27:08 GMT
< Content-Type: text/html
< Content-Length: 183
< Connection: keep-alive
< Server: NetDNA-cache/2.2
< 
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.7.11</center>
</body>
</html>
* Connection #0 to host cdn.jsdelivr.net left intact
```

**Comment by jimaek** [comment]
Gateway timeout means that the origin server had issues not the CDN itself. In this case @jamesward controls the origin.
jsDelivr operates normally

**Comment by jamesward** [comment]
@jimaek I've recently seen some of those origin timeouts happen while the origin was operating normally.  Could possibly be that DNS issue cropping up again.

**Comment by jimaek** [comment]
I applied a fix for the DNS thing today http://tenzer.dk/nginx-with-dynamic-upstreams/
Monitor it and let me know if it fixed the issue.

**Comment by mickeyvip** [comment]
I am trying from home and it is ok.

**Comment by tjdett** [comment]
Seems to be working fine here too.
