### ISSUE TITLE
Deployment of material-design-icons fails

### ISSUE THREAD

**Issue by mackler** [webjars/webjars#1208]
Both bower and npm methods fail to deploy `material-design-icons`.  Bower fails with message:

> Server returned HTTP response code: 503 for URL: https://bower-as-a-service.herokuapp.com/download/material-design-icons/2.0.0

NPM fails with message:

> No valid licenses found. Detected licenses: CC-BY-4.0

I understand that license is not listed on the bintray page.  I doubt the project developers would change their license.  Is deployment a lost cause?  And why is the bower error different?

The repository [is here](https://github.com/google/material-design-icons).

**Comment by jamesward** [comment]
The Bower one is failing because of a timeout downloading the library from the https://bower-as-a-service.herokuapp.com/ service.  But even if it could download the package it would probably fail for deployment for the same reason.

BinTray only has a specific list of licenses they accept.  I'll ask them if they can add `CC-BY-4.0` to the list.

**Comment by itzg** [comment]
I believe I am running into a new variant of the same issue when adding a new Bower package pointed at https://github.com/google/material-design-icons with version 3.0.1. The deploy process seems to hang at the output below. They seem to have updated to Apache v2 license, so it doesn't seem to be that issue this time.

```
Fetched Bower zip 
Generated POM 
Converted dependencies to Maven 
Got Bower info 
Determined Artifact Name: github-com-google-material-design-icons 
Starting Deploy
```

**Comment by jamesward** [comment]
I was able to getting better cache handling into the bower-as-a-service app.  So I was able to deploy this:
```
GroupID = org.webjars.bower
ArtifactID = material-design-icons
Version = 3.0.1 
```

**Comment by itzg** [comment]
Thanks @jamesward 

Maybe it's just propagation delay, but I see the artifact at

https://bintray.com/webjars/maven/org.webjars.bower%3Amaterial-design-icons/3.0.1

which is what really matters, however, I don't see it when searching

http://www.webjars.org/bower

**Comment by itzg** [comment]
...upon further inspection, they seem to have something strange going on with their bower structure. The resulting jar has a `META-INF\resources\webjars\material-design-icons\3.0.1\action\` path but not an overarching CSS file.

**Comment by jamesward** [comment]
Yeah, it takes a few hours to show up on webjars.org so it should be there around now.

The WebJar contents should be the same as if you do a local `bower install` and look in the `bower_components/material-design-icons` dir.  Let me know if that isn't the case.

**Comment by itzg** [comment]
Sorry it took so long to follow up on this. I locally ran `bower install material-design-icons` and the content under `bower_components/material-design-icons` it appears to be the same structure as https://github.com/google/material-design-icons/tree/3.0.1 directories `action` through `toggle`.

So the webjars built jar is "truncated" with only one of those directories.

However, there's a strange dilemma with this particular project. They seem to have bundled all of the assets for every platform on the planet that they support. For us web app developers, I was able to confirm with local experiments that indeed all that is needed is https://github.com/google/material-design-icons/tree/3.0.1/iconfont and not even the SVG file under there.

So...would it make sense if I contribute a traditional, handcrafted webjars project for this one, include only `iconfont`, and perhaps qualify the project name as such?
