### ISSUE TITLE
WebJar Request: error-stack-parser

### ISSUE THREAD

**Issue by billccn** [webjars/webjars#1213]
Please pull:

https://github.com/billccn/stackframe-webjar

https://github.com/billccn/error-stack-parser-webjar

They have to be build in the above order.

This does not cover all the dependencies of stacktrace.js 1.0 but I only need them....

**Comment by jamesward** [comment]
Thanks!  Here are the forks:
https://github.com/webjars/stackframe
https://github.com/webjars/error-stack-parser

These will be released shortly.
