### ISSUE TITLE
Check "COPYING" when looking for license

### ISSUE THREAD

**Issue by mkotsbak** [webjars/webjars#1220]
I tried importing https://github.com/LazarSoft/jsqrcode but it fails with not finding the license. Although it has no LICENSE file, it has a file COPYING that should be checked.

I was trying to import NPM package "jsqrcode".

**Comment by jamesward** [comment]
I'd rather not add another file to check for the license.  Instead can you work with the project to copy the `COPYING` file to a `LICENSE` file?  Also, it looks like NPM points to: https://github.com/vicapow/jsqrcode

**Comment by mkotsbak** [comment]
Okay, I found a Bower package "qcode-decoder" to import from instead.
