### ISSUE TITLE
artifactId prefixed by github-com-* for bower webjar

### ISSUE THREAD

**Issue by sbley** [webjars/webjars#1222]
When I deploy a bower webjar the artifactId will be prefixed github-com-*. Why is that?
Example: https://github.com/PolymerElements/paper-styles/
This will be deployed as:
```xml
<dependency>
  <groupId>org.webjars.bower</groupId>
  <artifactId>github-com-polymerelements-paper-styles</artifactId>
  <version>1.0.3</version>
</dependency>
```
I expect it to be:
```xml
<dependency>
  <groupId>org.webjars.bower.polymerelements</groupId>
  <artifactId>paper-styles</artifactId>
  <version>1.0.3</version>
</dependency>
```

**Comment by jamesward** [comment]
It doesn't seem that there is a Bower package registered as `paper-styles`.  In which case we can't determine what the canonical repo for that package would be.  So we add our own namespacing based on the repo URL.

**Comment by jamesward** [comment]
For some background on this, see: https://github.com/webjars/webjars/issues/1044

**Comment by sbley** [comment]
You are right in that those `paper-`elements can't be found at http://bower.io/search.

In bower.json they are referenced like this:
`"paper-styles": "PolymerElements/paper-styles#^1.0.2"` 
which eventually fetches from https://github.com/PolymerElements/paper-styles/

**Comment by jamesward** [comment]
Bower supports using GitHub `org/repo` shortcuts as dependencies.  Bowe WebJars support that syntax too.  But if a library isn't registered in the Bower index then we can't use its name as the artifactId because there isn't a unique artifactId for the repo.
