### ISSUE TITLE
Licence for js-cookie

### ISSUE THREAD

**Issue by axos88** [webjars/webjars#1225]
Can't deploy js-cookie because of not being able to determine licence.

Poor naming of the file? https://github.com/js-cookie/js-cookie/blob/master/MIT-LICENSE.txt

**Comment by jamesward** [comment]
Yeah, here are the files we try: https://github.com/jamesward/github-license-service/blob/master/app/utils/GithubUtil.scala#L12

I'd rather not add another permutation.

It looks like the NPM metadata specifies a license: https://github.com/js-cookie/js-cookie/blob/master/package.json#L28

So you could either try the NPM WebJar or get them to fix their metadata.
