### ISSUE TITLE
Webjar for babel-runtime version 5.8.24 fails

### ISSUE THREAD

**Issue by xsistens** [webjars/webjars#1231]
I tried to upload babel-runtime to the npm-webjars repository, but it fails with the following error message:

*Failed! {"status":"Sync Failed","messages":"[Problem extracting files to sync. Please try again in a bit.]"} If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created BinTray Package Converted project licenses Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: babel-runtime Starting Deploy*

I tried the build 5 times over the last hour, but always the same failure.
Is there any way to fix this?

**Comment by jamesward** [comment]
It looks like Maven Central is having issues.  I'll keep monitoring it and let you know when it is working again.

**Comment by xsistens** [comment]
amazing, thanks for your effort!

**Comment by jamesward** [comment]
In the meantime you can get this from the BinTray repo:
```
<repositories>
  <repository>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
    <id>bintray-webjars-maven</id>
    <name>bintray</name>
    <url>http://dl.bintray.com/webjars/maven</url>
  </repository>
</repositories>
```

**Comment by jamesward** [comment]
Looks like this is working again.
