### ISSUE TITLE
angular-gridster has incorrect pom (artifactId) for javascript-detect-element-resize (failing on gradle refresh)

### ISSUE THREAD

**Issue by jbabuscio** [webjars/webjars#1235]
The pom file reads:
`<dependency>
<groupId>org.webjars.bower</groupId>
<artifactId>
github-com-sdecima-javascript-detect-element-resize
</artifactId>
<version>[0.5.1,0.6)</version>
</dependency>`

I think:
github-com-javascript-detect-element-resize
should be
javascript-detect-element-resize

**Comment by jamesward** [comment]
This is because the `angular-gridster` library depends on a git repo.  We can't determine an artifact name from a git repo so we make one up.  I've deployed the necessary git repo so this dependency should be there now.  Reopen this if you have issues still.
