### ISSUE TITLE
WebJar request: Official GMaps Clusterer

### ISSUE THREAD

**Issue by jirihelmich** [webjars/webjars#1236]
Located at: https://github.com/googlemaps/js-marker-clusterer

**Comment by jamesward** [comment]
Unfortunately there are no tagged releases for that library.  I can use a git commit sha instead.  WDYT?

**Comment by jirihelmich** [comment]
It seems as the only logical solution. It's ugly, but the internal version of the script is 1.0 since year 2010.

I would use the one that's already in WebJars (Marker Clusterer Plus), but with large amount of markers, it's very slow and this one is not.

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/js-marker-clusterer

This will be released shortly.

**Comment by jirihelmich** [comment]
Thanks a lot. I hope I will eventually get how maven works and would be
able to do PRs.

Wed, 28 Oct 2015 v 14:18 odesílatel James Ward
notifications@github.com> napsal:
