### ISSUE TITLE
Upgrade markdown-it to the latest version (5.0.0)

### ISSUE THREAD

**Issue by svozniuk** [webjars/webjars#1237]
The latest version for https://github.com/markdown-it/markdown-it on the webjars repo is 4.2.1. 
However there has been a number of releases since then and the latest is 5.0.0.
The releases are tagged here
https://github.com/markdown-it/markdown-it/releases

**Comment by jamesward** [comment]
I've just released `5.0.0` but in the future you can release these yourself since this library is a Bower WebJars: http://www.webjars.org/bower

**Comment by svozniuk** [comment]
Thanks. I will know for the future.
