### ISSUE TITLE
Add a New Bower WebJar fails for CC license

### ISSUE THREAD

**Issue by nafg** [webjars/webjars#1241]
I tried adding a webjar for https://github.com/adamwulf/Columnizer-jQuery-Plugin via the bower package jquery.columnizer, and I get:

> Failed! 
> All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. 
> If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  
>
> Determined Artifact Name: jquery.columnizer
> Starting Deploy

The license is creative commons, as you can see in `LICENSE` in the repo root:

https://github.com/adamwulf/Columnizer-jQuery-Plugin/blob/master/LICENSE

Thanks!

**Comment by jamesward** [comment]
Unfortunately BinTray doesn't support CC licenses at this time.  You can read more here: https://bintray.com/docs/usermanual/uploads/uploads_requestinganewlicense.html

That means we can't do a Bower WebJar for this.  But you could request a Classic WebJar for this library if one doesn't already exist.
