### ISSUE TITLE
"Add a New NPM WebJar" fails with HTTP 500

### ISSUE THREAD

**Issue by fkretzer** [webjars/webjars#1242]
Request answer is: "Comparison method violates its general contract!"
Reproduce:
- Search for "redux"
- click "+" next to the "vesions"-select
- type "redux" into search box
- check ajax request in developer tools
<img width="841" alt="bildschirmfoto 2015-11-02 um 18 08 15" src="https://cloud.githubusercontent.com/assets/5182212/10888537/1aab7c54-818d-11e5-9437-ca57156716fb.png">

**Comment by jamesward** [comment]
Thanks for filing this.  This fix should be deployed in about 15 minutes.
