### ISSUE TITLE
Git hash dependencies not working

### ISSUE THREAD

**Issue by mkotsbak** [webjars/webjars#1246]
I'm trying to import react-native, possibly to use in Scala.Js wrappers, but then I encounter this error:

```Failed! Could not convert NPM / Bower version to Maven for: react-tools git://github.com/facebook/react.git#b4e74e38e43ac53af8acd62c78c9213be0194245 If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got NPM info Determined Artifact Name: react-native Starting Deploy```

The dependency is declared as:

```
"react-tools": "git://github.com/facebook/react.git#b4e74e38e43ac53af8acd62c78c9213be0194245",
```

I'm not sure npm tool itself handles this. Maybe the git version is available in repository?

**Comment by jamesward** [comment]
This fix should be deployed in about 15 minutes.  Please reopen this issue if it still doesn't work.
