### ISSUE TITLE
Could not get HEAD for url: https://github.com/github:facebook/react

### ISSUE THREAD

**Issue by mkotsbak** [webjars/webjars#1247]
When trying to import "react-native" version >= 0.14.0, I get:

```Failed! Could not get HEAD for url: https://github.com/github:facebook/react If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Got NPM info Determined Artifact Name: react-native Starting Deploy```

Earlier versions works fine after issue #1246 was fixed.

**Comment by jamesward** [comment]
Thanks for finding these corner cases.  This fix should be deployed in 15 minutes.
