### ISSUE TITLE
webjar request for Alpaca JS

### ISSUE THREAD

**Issue by emandi** [webjars/webjars#1250]
Hello,

I would like to ask you to please upload the following WebJar for the Alpaca JS (forms for jQuery) in the list of the WebJars, webjars.org:

https://github.com/emandi/webjar-alpacajs

Thank you in advance. I remain at your disposal.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/alpaca

This will be released shortly.
