### ISSUE TITLE
WebJar request: video.js

### ISSUE THREAD

**Issue by mouhb** [webjars/webjars#1254]
Can you make a webjar of this repo please

https://github.com/xwiki-labs/video.js

**Comment by jamesward** [comment]
There is already a WebJar for that one: https://github.com/webjars/video-js

**Comment by mouhb** [comment]
Yes I know but the version is old, I want to create a webjar with the latest version.

**Comment by mouhb** [comment]
How can I integrate the last version of video.js ?

**Comment by jamesward** [comment]
You can either request a version bump on that WebJar or send a Pull Request to it.

**Comment by mouhb** [comment]
ok, I will make a PR on it. 
Thank you very much
