### ISSUE TITLE
npm package `@reactivex/rxjs` not found

### ISSUE THREAD

**Issue by laguiz** [webjars/webjars#1255]
Hi,

First big thanks to webjar.org it's amazing (especially the auto link to npm and bower repos)!

I encounter an issue trying to get `angular2:2.0.0-alpha.46`. At first I had to deploy 3 other dependencies that was required : 
1. reflect-metadata:0.1.2
2. @reactivex/rxjs:5.0.0-alpha.7
3. zone.js:0.5.8

For 1 and 3 it seems ok (sbt do not complain anymore).

For the second dependency the name looks strange to me. On Webjar.org the deployment of `@reactivex/rxjs` do not find anything. I tried `reactivex/rxjs` and it found something with the correct version. Here is the extract of the log deployment : 

```
GroupID = org.webjars.npm 
ArtifactID = github-com-reactivex-rxjs 
Version = 5.0.0-alpha.7  
```

As you can see the determined ArtifactID is **github-com-reactivex-rxjs** that is not the same as **@reactivex/rxjs** (the expect dependency we can see in sbt log).

Here is the deployed webjar : http://jcenter.bintray.com/org/webjars/npm/github-com-reactivex-rxjs/5.0.0-alpha.7/

For me it's the first time I see a dependency starting with `@` and that include a `/`. I'm not sure what does it mean.

Here is the original npm package I think angular need : https://www.npmjs.com/package/@reactivex/rxjs

I tried `npm install @reactivex/rxjs@5.0.0-alpha.7` and it seems to work properly.

As a workaround I did `exclude("org.webjars.npm", "@reactivex/rxjs")` and now it pass. I still have to see how to include the dependency manually and make it work with angular but it's an other story.

Do you have any idea of what could be the problem?

I'm available to help to debug this situation.

Thank you,
Maxence

**Comment by jamesward** [comment]
It looks like I need to add support for NPM Scoped Packages: https://docs.npmjs.com/getting-started/scoped-packages

**Comment by jamesward** [comment]
The fixes for these packages have been deployed but I had to change the artifactId in the dependency definition so the `angular2` artifact has been redeployed.  You might need to clear your Maven cache to pick that up.  Also in the future this should just work.  Let me know if you have any problems.

**Comment by laguiz** [comment]
Wow you committed and closed this issue. Really impressed by this fast reaction. Can't wait to try tomorrow. Keep awesome work with webjars!

**Comment by jamesward** [comment]
Thanks! I hope it all works as expected.

**Comment by laguiz** [comment]
Hi,

Download now works properly but I have an error that seems to be caused by ':' in the path.

I see this : 

```
[info] downloading https://repo1.maven.org/maven2/org/webjars/npm/reactivex:rxjs/5.0.0-alpha.7/reactivex:rxjs-5.0.0-alpha.7.jar ...
[info] 	[SUCCESSFUL ] org.webjars.npm#reactivex:rxjs;5.0.0-alpha.7!reactivex:rxjs.jar (751ms)
[info] Done updating.
[trace] Stack trace suppressed: run last compile:managedClasspath for the full output.
[error] (compile:managedClasspath) Path '/Users/laguiz/.ivy2/cache/org.webjars.npm/reactivex:rxjs/jars/reactivex:rxjs-5.0.0-alpha.7.jar' contains separator ':'
[error] Total time: 4 s, completed Nov 20, 2015 9:47:11 AM
```

Trace Info : 
```
java.lang.RuntimeException: Path '/Users/laguiz/.ivy2/cache/org.webjars.npm/reactivex:rxjs/jars/reactivex:rxjs-5.0.0-alpha.7.jar' contains separator ':'
	at scala.sys.package$.error(package.scala:27)
	at sbt.Path$$anonfun$makeString$2.apply(Path.scala:69)
	at sbt.Path$$anonfun$makeString$2.apply(Path.scala:69)
	at scala.Option.foreach(Option.scala:236)
	at sbt.Path$.makeString(Path.scala:69)
	at sbt.Path$.makeString(Path.scala:66)
	at sbt.Classpaths$.sbt$Classpaths$$exportClasspath(Defaults.scala:1001)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$exportClasspath$1$$anonfun$apply$45.apply(Defaults.scala:997)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$exportClasspath$1$$anonfun$apply$45.apply(Defaults.scala:997)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:managedClasspath) Path '/Users/laguiz/.ivy2/cache/org.webjars.npm/reactivex:rxjs/jars/reactivex:rxjs-5.0.0-alpha.7.jar' contains separator ':'
```

On my Mac I can do `cd /Users/laguiz/.ivy2/cache/org.webjars.npm/reactivex:rxjs/jars` and I see the jar `reactivex:rxjs-5.0.0-alpha.7.jar`.

I'm not sure if adding `:` in the path is a good idea in general. You probably let it respect the original npm package name. When we use npm directly here is how it's stored : `/Users/laguiz/temp/node_modules/@reactivex/rxjs`

I don't know what are the options here. Could we replace `:` with `--` for example of something?

Let me know if I can help.

**Comment by laguiz** [comment]
More info : 

I'm not sure if it's related but if I pass thought our Local Artifactory I see this in logs :
```
2015-11-20 09:46:22,034 [http-nio-8081-exec-5] [WARN ] (o.a.r.ArtifactoryResponseBase:105) - Sending HTTP error code 409: Old metadata notation is not supported anymore: maven-virtual:org/webjars/npm/reactivex:rxjs/5.0.0-alpha.7/reactivex:rxjs-5.0.0-alpha.7.pom
```

**Comment by jamesward** [comment]
Crap.  I guess I chose a terrible delimiter.

**Comment by jamesward** [comment]
Possible non-alphanumerics are: `.-_:`

Those others are used somewhat often in package names so there is a small chance of a collision.  We could do `--` as you suggest.  Or `...` or whatever.  What do you think?

**Comment by laguiz** [comment]
For me `--` looks ok. I like the fact that `-` is already used in artifactId in general so doubling it is the most natural for me.

However `__` is also interesting because it reduce seriously the risk of collision and focus on "we do something here that is not common" like what Scala do with scala versions (ex. `play_2.10`).

If I have to vote I would go for `__` for safety.

**Comment by jamesward** [comment]
This will be deployed in about 10 minutes.  Then can you redeploy the `angular2` and `rxjs` packages?  Let me know how it goes.

**Comment by laguiz** [comment]
Ok. Do you need to clean the repo before?

**Comment by jamesward** [comment]
Yeah, since we have to override the `angular2` release artifact you will need to delete it from your M2 cache.  After you release it from http://webjars.org/npm you will need to check that the `pom.xml` on BinTray has the right dependency definition: https://bintray.com/webjars/maven/org.webjars.npm%3Aangular2/view

It might take a little while to sync to Maven Central.

Let me know if you encounter any issues.

**Comment by laguiz** [comment]
Ok I understand that the deployment from webjars.org will override existing deployment. I try and let you know.

**Comment by jamesward** [comment]
I *think* it will override it.  But there is a chance that it won't.  In which case I will need to delete the release.  Let me know how it goes.

**Comment by laguiz** [comment]
I redeployed 2 times and so far `https://bintray.com/artifact/download/webjars/maven/org/webjars/npm/angular2/2.0.0-alpha.46/angular2-2.0.0-alpha.46.pom` still contains `reactivex:rxjs`.

**Comment by jamesward** [comment]
Arrrg.  Looks like it has to be deleted.  I've done that.  Try again.  Sorry for the hassle.

**Comment by laguiz** [comment]
No worry. I try.

**Comment by laguiz** [comment]
It works : 
```
[SUCCESSFUL ] org.webjars.npm#reactivex__rxjs;5.0.0-alpha.7!reactivex__rxjs.jar (190ms)
```

Maybe just a matter of time (cache) but I don't see it in the list here : http://www.webjars.org/npm

Later you may also want to clean old deployments like `"org.webjars.npm" % "reactivex:rxjs" % "5.0.0-alpha.7"` and `"org.webjars.npm" % "github-com-reactivex-rxjs" % "5.0.0-alpha.7"`.

Let me know if you need help for more testing.

Thank you very much for your efforts.

**Comment by jamesward** [comment]
Great!  Yeah, the webjars.org cache takes a few hours to update.

Thank you for working through that with me!

**Comment by laguiz** [comment]
In fact today it's visible. Thank you for this amazing project. Keep great work.

**Comment by wirdman** [comment]
Hi, just ran in the same issue and ended up copying the same dependencies 
please also take care of
"
Later you may also want to clean old deployments like "org.webjars.npm" % "reactivex:rxjs" % "5.0.0-alpha.7" and "org.webjars.npm" % "github-com-reactivex-rxjs" % "5.0.0-alpha.7".   
"
it's really misleading.

Thanks, for the great work

**Comment by laguiz** [comment]
@wirdman Hi, I'm not sure what do you mean by "misleading". Could my words sounds like I "requested" the thing to be done? I'm not native english so I probably miss something. I really meant "If you have time and just as a reminder (but do whatever you want) it could be interesting to ..." :) If you have any short way to say it feel free to share in a pm.

**Comment by jamesward** [comment]
Unfortunately it is pretty tough to remove stuff from Maven Central once it is out there.  So I'm not sure of a good way to handle the old deployments.  Any ideas on other approaches?

**Comment by laguiz** [comment]
In fact it seems it should not be done. I was not aware that you directly reflect maven central on webjar.org. An other approach would be to track them in webjar.org only and "hide" them in the list here : http://www.webjars.org/npm . Maybe not that elegant though. Nevertheless this is not really a big deal so the effort to spend on it is probably not necessary.
