### ISSUE TITLE
WebJar for React DnD and React DnD HTML5 Backend

### ISSUE THREAD

**Issue by tbinna** [webjars/webjars#1273]
https://github.com/tbinna/react-dnd
https://github.com/tbinna/react-dnd-html5-backend

WebJar for React DnD and React DnD HTML5 Backend.

The library backend is distributed as a separate dependency.

**Comment by jamesward** [comment]
Thanks! Here are the forks:
https://github.com/webjars/react-dnd
https://github.com/webjars/react-dnd-html5-backend

These will be released shortly.
