### ISSUE TITLE
Webjar combined-stream (License issue)

### ISSUE THREAD

**Issue by wapolinar** [webjars/webjars#1274]
I tried to add the combined-stream library version 0.0.7 to webjars (npm), because it is a requirement for another webjar and binjar complains about a missing license.

The github repository has a license file (MIT): https://github.com/felixge/node-combined-stream and it is also mentioned here: https://www.npmjs.com/package/combined-stream

All newer versions (1.x) work, but the license file was added in 2011 and not edited, so what is this project doing wrong?

**Comment by wapolinar** [comment]
Ok, it is, because they did not have a "license" field in the package.json. I suppose you are not performing a string matching on the "License" file, right? So, please feel free to comment and close this issue, then.

**Comment by jamesward** [comment]
Yeah, 0.0.7 doesn't have the license specified: https://github.com/felixge/node-combined-stream/blob/v0.0.7/package.json

But we should fall back to using: http://github-license-service.herokuapp.com/felixge/node-combined-stream

And that probably isn't looking for a file named `License` but we can fix that: https://github.com/jamesward/github-license-service/pull/1

Hang tight while that gets deployed...

**Comment by jamesward** [comment]
Looks like the license service is working now.  Want to try to deploy again?

**Comment by wapolinar** [comment]
Yes, it works now, thanks a lot!
