### ISSUE TITLE
webjars.org isn't doing search properly

### ISSUE THREAD

**Issue by kryton** [webjars/webjars#1275]
and it asked me to file an issue about it.

**Comment by jamesward** [comment]
It looks like it is back up.  Can you confirm?

**Comment by kryton** [comment]
backup now. but a second ago it was down.. it's intermittent.. possibly where you are getting the list of jars from is getting errors? (possibly you rebuild the list via cron?)

**Comment by jamesward** [comment]
I'll keep an eye on it.  Thanks for reporting this.
