### ISSUE TITLE
Using webjars to create private jar's/deployments?

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1277]
Is it possible to use the webjars infrastructure/code to make private deployments of code? The intent is if you want to share .js code privately within your organisation, an ideal way would be to create `.jar` out of your javascript, deploy it to your private repository, and then reuse it as a dependency in the same way you do with webjars.

Obviously you can share it right now by just using standard java `resources` folder, but it would be good if we could deploy it the `webjar` way, so that frameworks like play can auto load the resources.

**Comment by jbalsas** [comment]
I'd also be interested in this. I was actually coming to ask the same question.

In our case, we are heavily moving our frontend project dependencies to webjars. Some of these projects are our own, and in some cases it would be nice to be able to create a local snapshot to verify everything works before releasing a version to the public.

Could we package and distribute `WebjarUtils` somehow so it could be used from outside the web project?

Thanks a lot!

**Comment by jamesward** [comment]
This is actually really easy to do since WebJars are nothing special.  Anyone can create a JAR with resources in the `META-INF/resources` directory and deploy that on their internal Nexus / Artifactory server.

Does that help?

**Comment by jbalsas** [comment]
Hey @jamesward, sure we could create the JAR ourselves, but that introduces a possible error step where my test build process is different (mistakes, updates, ...) from the release one using webjars... I'd like to make sure that there won't be any difference between the artifact I'm generating and the one that will get released.

**Comment by jamesward** [comment]
So you just want to release WebJars to an internal Nexus or something?  I think that might work but where it gets tricky is that Maven release plugin tags the git repo and you won't have access to do that (at least the push part).  You could try a release locally: `mvn release:prepare release:perform`

**Comment by mdedetrich** [comment]
@jamesward Although on the surface it may seem simple to just add resources into your resources folder, it does appear to be a bit more complex when I look at the structure of the webjar `.jar`.

1. The resources folder is not just `.resources`. its `.resources.xxx`. For example with `angular-ui` it is
`META-INF/resources.webjars.angular-ui.0.4.0`.
2. There are also how dependencies are managed (whether they are internal or not)

> So you just want to release WebJars to an internal Nexus or something?
Yes that is the intention

Maybe if you just uploaded a sample project or a guide (in either maven, or if you are in Scala SBT) which shows how this can be done with the same naming scheme that webjars uses, thats all that would be needed.

If you are wondering, our use case is that we have assets that are used in multiple websites (Scala play projects) and for obvious reasons, we wan't to share them (and we can't upload this stuff publicly). 

Another use case is also altering settings for stuff like zurb foundation. If you have a look at http://foundation.zurb.com/sites/docs/v/5.5.3/sass-files.html#filelist, you can customize the variables of foundation using sass, however that obviously requires sass installed to work. The intention is to create a build system which runs the sass to create a custom build of foundation, which is what would then get packaged by maven internally.

**Comment by jamesward** [comment]
The layout for WebJars is: `META-INF/resources/webjars/ARTIFACT_ID/VERSION`
There is some info on creating WebJars at: http://www.webjars.org/contributing

Classic WebJars are manually deployed to Maven Central using `nexus-staging-maven-plugin`.  I'm sure it would be easy to create your own WebJars or fork existing ones and use that plugin to deploy to your own Nexus server.

Bower & NPM WebJars are deployed to Maven Central through BinTray.  The code that packages up the WebJar and deploys it to BinTray is in this repo.  You could definitely take this code and do whatever you want with it.

**Comment by mdedetrich** [comment]
Was just about to reply!

Its all good, I am just basing my projects of the class webjar `.pom`'s in this github organisation and its actually fairly simple

Thanks for the help!

**Comment by mdedetrich** [comment]
@jbalsas I just created https://github.com/mdedetrich/foundation-webjar-custom-settings-template. Its actually quite easy, classic webjars are just standard maven builds, the only difference is the path of the outputted directory (and other options such as `require.js).

Its easiest if you just start off with an existing `pom.xml` and just work from there

**Comment by jbalsas** [comment]
Hi @mdedetrich, thanks a lot for the advice! I need to get back to this, but I've been swamped with other stuff.

In our case, we're using it mostly for npm/bower webjars, so I'll probably try to dig around the bintray code in this repo to see what we can do. I'll update this issue whenever I have something going on.

Thanks!

**Comment by heruan** [comment]
I'm curious, is there any method to easily create a Webjar (with deps and files in the right place) from an existing NPM/Bower project?

I guess this is what is already done automatically for public NPM/Bower projects, but how can I apply this on a local project?

**Comment by jamesward** [comment]
@heruan It is definitely possible with this codebase but not straightforward.  We probably could start refactoring that logic out into a library.  Would that help?

**Comment by jamesward** [comment]
Would you need the BinTray support? Or you just want the WebJar jar file?

**Comment by heruan** [comment]
I'd just need the Maven project to be deployed on a Nexus repository, i.e. a `pom.xml` with the needed dependencies and the structure above in place where needed (e.g. `META-INF/resources`?) so that I'd just `mvn deploy` to get the Webjar available on a local Nexus repository.

**Comment by jbalsas** [comment]
Hey @heruan, if it's of any help, we developed https://github.com/liferay/liferay-gulp-tasks/blob/master/index.js a while back, although we are no longer using it. Might be a good starting point for what you need 🤷‍♂️

**Comment by heruan** [comment]
Thank you @jbalsas for the reference, that's an interesting script. Actually I'm looking forward a more integrated approach with the WebJars API, especially for Polymer Web Components and the new `GithubBower` API.

@jamesward do you think it would be possible to run the API locally (e.g. localhost) and customize the deployment process to upload packages from NPM/Bower to Maven Central and private packages to a local Nexus?

**Comment by jamesward** [comment]
@heruan Yeah, we definitely could make it possible to run this elsewhere and customize the endpoints.

**Comment by heruan** [comment]
That would be definitely awesome! Do you mind if I open an issue for that?

**Comment by jamesward** [comment]
@heruan Go for it!
