### ISSUE TITLE
"Add a New NPM WebJar" fails with HTTP 500

### ISSUE THREAD

**Issue by Vulcannis** [webjars/webjars#1278]
Same as #1242, though this time with the typescript package.

Looking at VersionOrdering.scala and the typescript versions, I guess that the "-dev.date" suffix is what's doing it. Handling dev like beta and rc would probably deal with it, but a more general fix would be to handle the NumberFormatExceptions by falling back to string comparisons rather than returning a constant 1, which should cause the contract violations almost every time given a sufficient # of versions.

I'd submit a fix myself but I don't know Scala well enough.

**Comment by jamesward** [comment]
This should be deployed in about 10 minutes.  Let me know if it fixes the problem.

**Comment by Vulcannis** [comment]
Still getting the error.

BTW, I was referring to the "case e: NumberFormatException => 1" line in my comment. Perhaps it should be "case e: NumberFormatException => aV.compareTo(bV)"?

**Comment by jamesward** [comment]
Sorry, I had some other test failures crop up.  I'm almost done fixing them and then the deploy should work.  Current status: https://travis-ci.org/webjars/webjars

**Comment by Vulcannis** [comment]
Works great now, thanks! :thumbsup:
