### ISSUE TITLE
Webjar Request: react-motion 0.3.1

### ISSUE THREAD

**Issue by jclyons** [webjars/webjars#1286]
Can you bump the version on webjars/react-motion to 0.3.1 and publish a new webjar? There's a tagged release on chenglou/react-motion.

**Comment by jamesward** [comment]
I'm releasing this now.  In the future please file version bump requests on the actual WebJar, e.g. https://github.com/webjars/react-motion

**Comment by jclyons** [comment]
willdo, sorry about that,  thanks!
