### ISSUE TITLE
knockout-validation dependencies

### ISSUE THREAD

**Issue by unterstein** [webjars/webjars#1291]
Hi there,

i wanted to use "org.webjars.bower" % "knockout-validation" % "2.0.3" in my project and i can`t find the github project of this deployment, therefore i am opening a ticket here.

I found the maven dependency to: 

```
        <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>knockout</artifactId>
            <version>[2.3.0,)</version>
        </dependency>
```

But this artifact is not deployed at the webjars.org site or maven central or somewhere else. Can this dependency be removed in the next release or be corrected to the correct groupId/artifactId "org.webjars.bower" % "knockoutjs"?

For now i solved this issue by excluding this dependency through:

```
"org.webjars.bower" % "knockout-validation" % "2.0.3" exclude("org.webjars.bower", "knockout")
```

Cheers
Johannes

**Comment by jamesward** [comment]
Right now [transitive dependency deployment is not automatic](https://github.com/webjars/webjars/issues/1186).  I've deployed the `knockout` `2.3.0` Bower WebJar using: http://www.webjars.org/bower

In the future you can do the same.  Please reopen this if it doesn't resolve your issue.
