### ISSUE TITLE
Deploying alloy-ui fails

### ISSUE THREAD

**Issue by jonmak08** [webjars/webjars#1294]
I tried adding a new alloy-ui version bower webjar and it fails with the message:

```
Failed!
Server returned HTTP response code: 503 for URL: https://bower-as-a-service.herokuapp.com/download/alloy-ui/3.0.3-deprecated.7
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Generated POM
Converted dependencies to Maven
Got Bower info
Determined Artifact Name: alloy-ui
Starting Deploy
Deploy!
```

We have deployed other versions of alloy-ui successfully, but now it is consistently giving a 503 error.

Our releases that we are trying to deploy can be found at https://github.com/liferay/alloy-ui/releases.

**Comment by jamesward** [comment]
This is due to: https://github.com/jamesward/bower-as-a-service/issues/1
