### ISSUE TITLE
Failed on adding new Bower WebJar

### ISSUE THREAD

**Issue by bpervan** [webjars/webjars#1301]
C/P error from Deploy Log:

Failed! /tmp/git7195206435766104732/git:/github.com/sporritt/jsPlumb.git/MIT/GPL2 (No such file or directory) If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: jsplumb Starting Deploy

I feel like this is failure in error. If you take a look at github.com/sporritt/jsPlumb, there is no such folder structure as /MIT/GPL2.

Cheers,
Branimir

**Comment by jamesward** [comment]
The metadata for the license is in the incorrect form.  You will need to work with the upstream project to fix this.
