### ISSUE TITLE
Deplyment of yadcf fails

### ISSUE THREAD

**Issue by hectorgarzon** [webjars/webjars#1305]
Hi,
I'm trying to deploy this bower component "yadcf": https://github.com/vedmack/yadcf/tree/0.8.8   but the deployment process is failing with this message:

*"Failed! All attempts to determine a license have been exhausted. The bower.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo. This problem will likely need to be resolved by working with the library maintainers directly. If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Determined Artifact Name: yadcf"*

The license is published in this file: https://github.com/vedmack/yadcf/blob/0.8.8/LICENSE-MIT.txt

Thanks

**Comment by jamesward** [comment]
There isn't a good programatic way to detect the license for that project.  The `bower.json` file should specify the license.  This will have to be fixed upstream.
