### ISSUE TITLE
WebJar Request: jshamcrest

### ISSUE THREAD

**Issue by shiver-me-timbers** [webjars/webjars#1314]
https://github.com/shiver-me-timbers/jshamcrest

**Comment by jamesward** [comment]
Why does this one not download the artifact(s) as part of the build?

**Comment by shiver-me-timbers** [comment]
I added a comment about this in the pom.xml :)

```xml
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- The built JS script for this library is contained within this project instead of being downloaded during -->
    <!-- the build process. This is because the release ZIP only contains the prebuilt source and the hosted built -->
    <!-- JS is not versioned (http://danielmartins.ninja/jshamcrest/jshamcrest.js). -->
    <requirejs>
        {
          "paths": {
            "jshamcrest": "jshamcrest"
          }
        }
    </requirejs>
</properties>
```

**Comment by jamesward** [comment]
One option would be to not have a minified version and use: https://github.com/danielfm/jshamcrest/tree/master/build

Another option would be to run the build as part of the WebJar build process.  We've done that for a few other libs and it works well.  For maintainability I'd rather go with one of those options than to put the assets in the WebJar.

**Comment by jamesward** [comment]
Here is an example of running an npm build via Maven:
https://github.com/webjars/browser-sync/blob/master/pom.xml#L89-L91

**Comment by shiver-me-timbers** [comment]
Ok, doing the build in the build looks like the best option. I'll implement that soon :)

**Comment by shiver-me-timbers** [comment]
Done. The build now downloads the release tar and builds it before moving the built JS file into place for packaging.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jshamcrest

This will be released shortly.
