### ISSUE TITLE
WebJar Request: jsmockito-jshamcrest-integration

### ISSUE THREAD

**Issue by shiver-me-timbers** [webjars/webjars#1316]
https://github.com/shiver-me-timbers/jsmockito-jshamcrest-integration

Depends on: 
**WebJar Request: jshamcrest** (#1314)
**WebJar Request: jsmockito** (#1315)

**Comment by jamesward** [comment]
Thanks!  Here is the fork: https://github.com/webjars/jsmockito-jshamcrest-integration

This will be released shortly.
