### ISSUE TITLE
Deploying froala-wysiwyg-editor Bower

### ISSUE THREAD

**Issue by stefanneculai** [webjars/webjars#1324]
I was trying to deploy the `froala-wysiwyg-editor` bower package and I get the following error. I believe it should not fail because it matches the [Bower specs for license field](https://github.com/bower/spec/blob/master/json.md#license).

> Failed! License at https://www.froala.com/wysiwyg-editor/pricing was not plain text

**Comment by jamesward** [comment]
Unfortunately that license isn't a valid open source license.  And having an open source license is a requirement for BinTray deployment.  Sorry.
