### ISSUE TITLE
Frontpage too heavy to load

### ISSUE THREAD

**Issue by johndevs** [webjars/webjars#1327]
When accessing the frontpage firefox dies. The problem is the table that has too many rows to render in a decent time. Would suggest to either lazy load or paginate the table.

**Comment by jamesward** [comment]
I guess that most users go to webjars.org to find a WebJar.  So we could just do a search box.  I had originally put everything on one page for SEO and crtl-f searching.  But with the number of WebJars now over 4000, the tradeoffs probably aren't worth it.

It would be cool to at least show some popular WebJars by default but then I'd need to pull in download stats from Maven Central which might be tough.

In the meantime you can search on Maven Central: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.webjars%22

**Comment by tokuhirom** [comment]
I suggest to use pagination and js based incremental search.

**Comment by jamesward** [comment]
I've been working on this: https://github.com/webjars/webjars/tree/landing-page-popular

You can see the current status: https://webjars-test.herokuapp.com/

Would love some feedback.

**Comment by zy4** [comment]
I think the way to go would be server-side pagination with something like this:
https://datatables.net/examples/data_sources/server_side.html

I did this a while ago and it is really fast. Your experimental branch seems to have performance issues on startup at least.

**Comment by jamesward** [comment]
I think the startup issue you saw was just due to Heroku unidling a Dyno and starting the Play app.  We don't use idleable Dynos in production so this shouldn't be an issue.

**Comment by luq-0** [comment]
I think anything would do better than the current setup. I haven't visited the website in a while, but I have made that mistake today, making my browser as well as the rest of the desktop environment completely stuck loading, had to kill them from another tty. No one actually needs thousands of webjars on the frontpage, a searchbox will do fine.

**Comment by jamesward** [comment]
I think the only missing feature from the new homepage is a search...  Once I get that added I think it will be ok to roll this out.

**Comment by 58a36f** [comment]
Had to install chrome to get into page ,firefox simply dies ..so looking forward for new page

**Comment by a1russell** [comment]
Any update on this? https://webjars-test.herokuapp.com/ at least loads, but the search box needs to search everything rather than just the list shown, and the subsections (NPM, Bower, Classic) should get the same treatment.

**Comment by jamesward** [comment]
The latest Chrome totally chokes on these pages now too.  So I really gotta fix this.

**Comment by jamesward** [comment]
https://webjars-test.herokuapp.com/ has been updated with my latest UI changes.  Can some folks do some testing?

**Comment by a1russell** [comment]
So much better!

**Comment by jamesward** [comment]
Any usability issues that need to be addressed?

**Comment by gpgekko** [comment]
Observations and ideas:

- One thing that would be nice if it would remember the query when using the back button.
- I also noticed after using the back button that the versions select element will be empty for some packages.
- Another (more important) thing is that the build tool hint is for the first selected source when you have multiple sources selected; i.e., package is available through all npm, bower and classic but the hint will be based on npm, no choice (although I guess you could say that the choice is through the source selector above the query field), but also no indication if they are available via the other systems.
- Also, related to that, if you unselect a source you will first have to change the query before the results change.
- Also not sure if the 'all webjars' link should disappear when searching.
- I personally would like the search field to have `autofocus`.

But above all, my browser and I thank you for the work you've put into this!

**Comment by buckett** [comment]
@jamesward Really nice and fast. thanks.

@gpgekko I've found `autofocus` can end up making keyboard shortcuts not work (eg alt-left for back in history) although I don't know if this is just a bad implementation. I quite like the keyboard shortcut of `/` that some sites have for focusing search but this is overkill for this site most likely.

- You need to enter more than 2 characters to search. So looking for `dc` doesn't work and there's no indication of it not trying.

**Comment by jamesward** [comment]
Thanks for the feedback!

I like the idea of adding back button support but I think I can push that out a bit.

@gpgekko What do you mean by "Another (more important) thing is that the build tool hint" ...  I need more details on that one.

Changing sources now re-searches.  Also you can hit "enter" to force a search with 1 or 2 characters.

I think this fixes the most critical issues enough to release this.  So I'm going to create a PR.  Speak up if anyone finds a show-stopper.

**Comment by jamesward** [comment]
This will be deployed shortly.  For the back button issues and any other, can you all file new issues?  Thanks!
