### ISSUE TITLE
Angular Material Data Table as a classic webjar

### ISSUE THREAD

**Issue by datenbrille** [webjars/webjars#1328]
Hi,

I created a classic webjar out of the bower webjar and introduced the requirejs configuration. It would be really nice if you could include it into this organisation.

The link to the repository https://github.com/datenbrille/md-data-table

Thanks

**Comment by jamesward** [comment]
Thanks.  Here is the fork: https://github.com/webjars/md-data-table

This will be released shortly.  But out of curiosity, what didn't work about the Bower WebJar?

**Comment by datenbrille** [comment]
We use org.webjar.angularjs and org.webjar.angular-material as dependencies. The Bower WebJar had dependencies to Bower versions of angular and material. Did we something wrong? Did I oversee a configuration option. I just started to use WebJar's at all.

**Comment by jamesward** [comment]
I see.  That is fine because the transitive dependencies stay within the type of WebJar.
