### ISSUE TITLE
WebJars Request: victory

### ISSUE THREAD

**Issue by mariussoutier** [webjars/webjars#1331]
Tried it via NPM, but it's an endless dependency hell...

https://github.com/FormidableLabs/victory

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/victory

This will be released shortly.

**Comment by mariussoutier** [comment]
Thank you!!

**Comment by mariussoutier** [comment]
Can you also update to 0.4.0? Currently only 0.1.1 is available as a WebJar.

**Comment by jamesward** [comment]
Releasing `0.4.0` now.

**Comment by mariussoutier** [comment]
Thanks!
