### ISSUE TITLE
Angular File Upload as a classic webjar

### ISSUE THREAD

**Issue by datenbrille** [webjars/webjars#1336]
Hi,

I created a classic webjar out of the bower webjar and introduced the requirejs configuration. It would be really nice if you could include it into the webjar organisation.

The link to the repository https://github.com/datenbrille/ng-file-upload

I would like to have it as classic webjar because I do not want to mix classic and bower webjars.

Thanks

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/ng-file-upload

This will be released shortly.
