### ISSUE TITLE
51Degrees Lite Binary Database 

### ISSUE THREAD

**Issue by domdorn** [webjars/webjars#1341]
51Degrees Lite Binary database for server side browser detection.
https://github.com/greyflower/51degrees-lite-binary

The binaries are pulled from 
https://github.com/51Degrees/Device-Detection/tree/master/data
where they are uploaded in binary on a monthly basis. 

The files are packaged like
META-INF/resources/webjars/51degrees-lite-binary/51Degrees-Lite.dat
**explicitly without a version number**, as a developer only wants to update 
the version string in the build.sbt file to use a updated version of the dataset. 
If the version would be included, source files would have to be changed 
every time the data is updated to adjust to the new path.

**Comment by jamesward** [comment]
Are you looking to have that WebJar added to this org and released to Maven Central?

**Comment by domdorn** [comment]
yes, please include it in this org and release it to maven central.

the plan is to make it easy for everyone who uses the server side browser detection to get current versions of the data file. webjars is the perfect fit for this (imho).

**Comment by jamesward** [comment]
I've forked that WebJar but it is not actually downloading anything so the WebJar is empty.  Here is the repo: https://github.com/webjars/51degrees-lite-binary

Can you send a pull request with an update that actually downloads and populates the WebJar?
