### ISSUE TITLE
CC-BY-4.0 License Support

### ISSUE THREAD

**Issue by mckoon** [webjars/webjars#1347]
Trying to create an npm webjar for "material-design-icons", I experience the following error:

> Failed! No valid licenses found. Detected licenses: CC-BY-4.0 The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

https://github.com/google/material-design-icons/ contains a LICENSE file, with the CC-BY-4.0 license, which does allow for use in commercial software.

From https://design.google.com/icons/

> Feel free to use, remix, and re-share the icons in your products. The icons are available under the CC-BY license. We'd love attribution in your app's "about" screen, but it's not required. The only thing we ask is that you not re-sell the icons.

I would like to create this webjar, it can be npm, bower, or classic, but this license check is blocking me.

Thanks.

**Comment by mckoon** [comment]
FYI - I just found this old ticket for CC-BY-3.0:

https://github.com/webjars/webjars/issues/977

**Comment by mckoon** [comment]
Also relevant, is a request for a previous release of the Google material design icons that was closed:
https://github.com/webjars/webjars/issues/960

Based on the existence of these closed tickets, it looks like issues with BinTray's supported licenses are not an easy fix.

**Comment by jamesward** [comment]
I've requested that BinTray add the `CC-BY-4.0` license.

**Comment by mckoon** [comment]
In the meantime, until BinTray adds `CC-BY-4.0` license support, I have created a classic webjar for `material-design-icons` and created a ticket for it to be added: #1360

**Comment by gpgekko** [comment]
Almost one year later, can someone poke BinTray about their progress on this...?

**Comment by jamesward** [comment]
Poked...

**Comment by dhakehurst** [comment]
is it worth poking again?
;-)

**Comment by jamesward** [comment]
Now that we are off Bintray, this is resolved.
