### ISSUE TITLE
Webjar Fork Request for hello.js 1.12

### ISSUE THREAD

**Issue by rpiaggio** [webjars/webjars#1359]
I would like to contribute an update for the webjar project for hello.js (last contribution was 1.5, current version is 1.12).
Please fork this repository:
https://github.com/rpiaggio/hello.js.webjar

Thank you!

**Comment by jamesward** [comment]
Can you send a Pull Request to the WebJar's repo? https://github.com/webjars/hello.js

**Comment by rpiaggio** [comment]
Sure, wasn't sure how to proceed in case of an update.

**Comment by rpiaggio** [comment]
@jamesward Do I still get notified when the new webjar is ready? Thank you!

**Comment by jamesward** [comment]
Yeah, I'll correspond with you on your PR.
