### ISSUE TITLE
Webjar request: croppie

### ISSUE THREAD

**Issue by nremond** [webjars/webjars#1361]
Hi,

I was wondering what I can do to make the last version of croppie available as a webjar?
The version available is 1.0.5 and the last one is 2.0.2, cf : https://www.npmjs.com/package/croppie

Thank you.

**Comment by jamesward** [comment]
You can deploy the new NPM WebJar yourself: http://webjars.org/npm

**Comment by nremond** [comment]
Got it ! 
Sorry for the annoyance James.
