### ISSUE TITLE
NPM Addition Failed - Package not found

### ISSUE THREAD

**Issue by Lykathia** [webjars/webjars#1378]
Haven't seen this error before. Previous addition I tried had worked.

```
Failed!
Package 'org.webjars.npm:satellizer' was not found
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Created BinTray Package
Converted project licenses
Created NPM WebJar
Fetched NPM tgz
Generated POM
Converted dependencies to Maven
Got NPM info
Determined Artifact Name: satellizer
Starting Deploy
```

**Comment by jamesward** [comment]
Looks like there is something strange happening on the BinTray side.  I'll investigate.  In the meantime it looks like the Bower WebJar for that library is good.

**Comment by jamesward** [comment]
I manually created the package on BinTray then tried again and it worked.  So I think there was something funky on BinTray.  I'll watch the logs to see if this happens with other packages.  But closing this for now.
