### ISSUE TITLE
Angular Material Date Time Picker as a classic webjar

### ISSUE THREAD

**Issue by datenbrille** [webjars/webjars#1381]
Hi,

I created a classic webjar out of the bower webjar and introduced the requirejs configuration. It would be really nice if you could include it into this organisation.

The link to the repository https://github.com/datenbrille/sc-date-time

Thanks

**Comment by jamesward** [comment]
Thanks!  Here is the fork: https://github.com/webjars/sc-date-time
This will be released shortly.

Out of curiosity, what was wrong with the requirejs config from the Bower WebJar?  Maybe we can fix the logic that generates that config.

**Comment by datenbrille** [comment]
Hi James,

this is a reasonable question. I tried the bower webjar but there are some problems:

* The requirejs config does not specifiy angular as a dependency only the pom does
* The font awesome load less instead of css files
* Is there a solution to mix classic webjar and bower webjar? Because if I mix them I got to angular versions in my library and in in the requirejs

I would love to use only one type of webjar. But at the moment I prefer the classic webjars.

Did I miss a point? Can I somehow help to improve the process?

**Comment by jamesward** [comment]
Yeah, it sounds like the RequireJS config for this probably can't be generated.  For some reason I thought I had some RequireJS config in the Bower & NPM WebJars, but looks like not: https://github.com/webjars/webjars/blob/master/app/templates/pom.scala.xml#L14
