### ISSUE TITLE
Use webjars to manage typescript type declarations

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1382]
I'm using Play together with Typescript to develop Angular2 applications.
To make that work well I'm developing an [sbt-typescript](https://github.com/joost-de-vries/sbt-typescript) plugin. And typescript applications sometimes require extra type declaration files. This is the case when a JS library doesn't provide them themselves.
The [typings](https://github.com/typings/typings) TypeScript Definition Manager downloads these dependencies. 

I'd like to use sbt to manage these dependencies. And to make that work it seems webjars would be the designated way to download them.

So that's my proposal: let's use webjars to manage typescript type declarations.

Some design thoughts:
There's an endorsed github repo that contains most type declarations. https://github.com/DefinitelyTyped/DefinitelyTyped 
Specific definitions are referenced by subdirectory+commit hash. We could create functionality to create a specfic jar from this. Similar to how it is possible to create an npm webjar on demand.
This is a registry that references that https://github.com/typings/registry/tree/master/npm

**Comment by jamesward** [comment]
You can deploy a Git repo via the NPM WebJar deployer.  You just specify a Git URL, like: `https://github.com/DefinitelyTyped/DefinitelyTyped.git#master`
Loading the list of commits will take a while the first time but then they'll be cached.
I was able to deploy the latest commit:
```
GroupID = org.webjars.npm
ArtifactID = github-com-DefinitelyTyped-DefinitelyTyped
Version = 0.0.1
```

I think that the version `0.0.1` came from the `package.json` and we might need to fix something there.  But let me know in general if this will solve the problem you are having.

**Comment by joost-de-vries** [comment]
Huh, I didn't consider just downloading the whole github repo. Also I didn't know I could add it myself.
Of course then all declarations need to be of the same commit. But maybe that's not such a problem in practice.
I'll try that approach. Thank you so much!

I'll close this issue in the meantime.
