### ISSUE TITLE
Can't add npm 'codelyzer'

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1383]
I can't seem to add this npm to npm webjars: [codelyzer](https://www.npmjs.com/package/codelyzer)
I'm not sure what makes this npm different from others. F.i. the license seems ok. 
It's just not available in the webjars.org/npm search interface.

Is this fixable? Or should I request it as a classic webjar?

**Comment by jamesward** [comment]
I was able to add this without any problems:
```
GroupID = org.webjars.npm
ArtifactID = codelyzer
Version = 0.0.18
```

Feel free to reopen this if your issues wasn't resolved.

**Comment by joost-de-vries** [comment]
Strange.
Thanks so much.
