### ISSUE TITLE
WebJars doesn't get all tags possible

### ISSUE THREAD

**Issue by slavede** [webjars/webjars#1384]
http://www.webjars.org/_bower/versions?name=https://github.com/slavede/bootstrap-ui-datetime-picker does not return all of the possible tags. I open github project, and there is 1.2.7 which is missing here (1.2.7 is the latest tag, does it take some time for webjar to get it locally?)

**Comment by slavede** [comment]
My suggestion was right, it takes some time to refresh.

**Comment by jamesward** [comment]
Yeah, there is a 1 hour cache on the versions: https://github.com/webjars/webjars/blob/master/app/controllers/Application.scala#L102-L104
