### ISSUE TITLE
Cannot search for NPM WebJars

### ISSUE THREAD

**Issue by JesseTG** [webjars/webjars#1390]
> Looks like there was an error fetching the WebJars. If this problem persists please file an issue.

And thus here I am.  This does not happen with the Bower or the Classic sections.

EDIT: And like that, it works literally less than ten seconds after posting this issue.

**Comment by jamesward** [comment]
I've noticed that the http://search.maven.org service isn't particularly reliable.  I'd rather not increase the cache timeout because that'd mean higher latency with new packages showing up.  I wonder if before invalidating the cache I could make sure that I can reach the backing service...
