### ISSUE TITLE
Why is source repository metadata required?

### ISSUE THREAD

**Issue by pfgray** [webjars/webjars#1392]
Hi, 

To give some context, I recently tried to declare `npm@3.8.7` as an sbt dependency in my project.

I have a project with a single file `build.sbt`:

    libraryDependencies ++= Seq(
      "org.webjars.npm" % "npm" % "3.8.7"
    )

This will fail since all of `npm@3.8.7`'s dependencies are not resolvable.

One of them is:

    [error] unresolved dependency: org.webjars.npm#wcwidth;[1.0.0,2): not found

I've tried to go to http://www.webjars.org/npm and deploy this repository, but I get the following error:

    Failed! 
    The source repository for wcwidth 1.0.0 could not be determined
      but is required to published to Maven Central.
    This will need to be fixed in the project's package metadata.
    If you feel you have reached this failure in error,
      please file an issue: https://github.com/webjars/webjars/issues  

    Determined Artifact Name: wcwidth
    Starting Deploy

I'm guessing this is because there is no `"repository"` field in **wcwidth**'s `package.json` file  
My question is **why is this a necessary requirement for pushing npm modules to maven central**?

Thanks in advance

**Comment by pfgray** [comment]
It seems that this is a requirement of Maven Central's (not webjars as I previously thought)

http://central.sonatype.org/pages/requirements.html

Npm is lax in this regard.

This is an unfortunate, but understandable problem. I'll see if I can go bug wcwidth to add a repository to their package descriptor while wondering if there is a better solution to this problem.

**Comment by jamesward** [comment]
Yeah, unfortunately the only viable solution is to work with the upstream libraries on this.
