### ISSUE TITLE
Development Setup Documentation

### ISSUE THREAD

**Issue by pfgray** [webjars/webjars#1394]
Hi, it'd be nice to have some documentation on how to start development on this repo. You've done a great job of making the server runnable with:

    sbt
    >run

However, there are other setup steps I believe I'm missing (i.e. some environment variables in conf/application.conf).

I'd be willing to submit a PR with this information, but I'm not sure if I'd be able to include all of the necessary information.

I've got the app running with the `run` command on http://localhost:9000/, however the app never loads the "All Deployed WebJars" section.

Also, when I go to: http://localhost:9000/npm I get:

    Execution exception
    [NoSuchElementException: None.get] 
    In webjars/app/utils/Pusher.scala:15

which shows:

    val appid = config.getString("pusher.appid").get

I'm guessing it's because I don't have some api authentication configuration setup, but how would I go about doing this?

Thanks!

**Comment by jamesward** [comment]
I'e added some additional info for local dev.  Let me know if that helps.  Thanks for your help!
