### ISSUE TITLE
Can't add highcharts

### ISSUE THREAD

**Issue by slavede** [webjars/webjars#1396]
I can't add bower jar for highcharts...

both

https://github.com/highcharts/highcharts
https://github.com/highcharts/highcharts-dist

1) Don't display all tags
2) If I select one of the suggested ones I get:

```
Failed! Ref 0.7.0 can not be resolved If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues 
Determined Artifact Name: github-com-highcharts-highcharts-dist
Starting Deploy
```

**Comment by jamesward** [comment]
I screwed up the cache with this change: https://github.com/webjars/webjars/commit/13e009d1351ff6d5b17cce65d2a8a09bf3539940#diff-2bc81ddbaac9248c65583b4697ee54faR107

This has been fixed and will be deployed in about 10 minutes.
