### ISSUE TITLE
webjars not reading updated package.json file

### ISSUE THREAD

**Issue by nickrobison** [webjars/webjars#1400]
In attempting to deploy some new npm webjars (supercluster, rbush, kdbush) I've run into an issue in that the package.json files don't have the required source repository field. I've worked with the package maintainers to add the missing pieces, but the webjars site is still complaining that the information is missing.

I'm not sure if this is a bug, or me just missing a step. Do the package authors need to push an update to the npm repo?

**Comment by jamesward** [comment]
Yeah, the metadata is read from the released upstream artifact.  So there needs to be a new version released that has the updated metadata.
