### ISSUE TITLE
datatables.net-plugins

### ISSUE THREAD

**Issue by mirabilos** [webjars/webjars#1410]
Hi,

currently it doesn’t seem possible to build this as bower webjar, so I created one manually, mostly by copy’n’pasting from existing ones serving as examples.

https://github.com/mirabilos/datatables.net-plugins

Please take this over, improve and publish it. Thanks!

**Comment by jamesward** [comment]
I think that is the same as: https://github.com/webjars/datatables-plugins

If you need new versions feel free to create an issue or PR on that repo.

**Comment by mirabilos** [comment]
Huh… would you look at that… indeed.

I wonder why I didn’t find that in the search earlier then. Weird.
