### ISSUE TITLE
Request: Firebase - accept Google terms

### ISSUE THREAD

**Issue by FrankFischer** [webjars/webjars#1418]
Adding a new Bower WebJar for Firebase v3.1.0 

   https://github.com/firebase/firebase-bower

fails with:

"License at https://developers.google.com/terms was not plain text
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues"

(the 6 available Firebase WebJar versions are outdated)

How to proceed?

Might it be possible to accept https://developers.google.com/terms - even 
it is not plain Text?

Frank

**Comment by jamesward** [comment]
Unfortunately that license is not a recognized OSS license so Bintray won't allow us to deploy the artifact.
