### ISSUE TITLE
Unable to create angular-scenario NPM webjars for version 1.5.7

### ISSUE THREAD

**Issue by growak** [webjars/webjars#1420]
Failed! Forbidden! If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Published BinTray Version Signed BinTray Assets Published BinTray Assets Created BinTray Version Created BinTray Package Converted project licenses Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: angular-scenario Starting Deploy
Deploy!

**Comment by jamesward** [comment]
Ditto #1421
