### ISSUE TITLE
Unable to create angular-message-format NPM webjars for version 1.5.7

### ISSUE THREAD

**Issue by growak** [webjars/webjars#1421]
Failed! Forbidden! If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created BinTray Package Converted project licenses Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: angular-message-format Starting Deploy

**Comment by jamesward** [comment]
I'm not sure what went wrong but I've deleted the package on Bintray and it worked this time.
