### ISSUE TITLE
font-awesome NPM jar deployement failed for 4.6.3

### ISSUE THREAD

**Issue by growak** [webjars/webjars#1422]
Failed! No valid licenses found. Detected licenses: (OFL-1.1 AND MIT) The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: font-awesome Starting Deploy
Deploy!

**Comment by jamesward** [comment]
See #1167
