### ISSUE TITLE
angular-google-maps 2.3.3 NPM webjar dependencies not availables on webjars

### ISSUE THREAD

**Issue by growak** [webjars/webjars#1424]
unresolved dependency: org.webjars.npm#google-maps-utility-library-v3-infobox;1.1.14: not found
unresolved dependency: org.webjars.npm#github-com-nmccready-google-maps-utility-library-v3-markerwithlabel;1.1.10: not found
unresolved dependency: org.webjars.npm#google-maps-utility-library-v3-keydragzoom;2.0.9: not found

**Comment by jamesward** [comment]
Have you tried to add those using http://webjars.org/npm ?

**Comment by jamesward** [comment]
Oh, and some of those are non-NPM repo dependencies.  So you need to add them via the Git URL.  In the form, enter the Git URL, like: `https://github.com//nmccready/google-maps-utility-library-v3-markerwithlabel.git`

**Comment by growak** [comment]
Thank you James

**Comment by growak** [comment]
I upgrade the angular-google-maps version to 2.3.3 and it seems that the dependencies were not fetched transitively.

What do you mean by adding https://github.com//nmccready/google-maps-utility-library-v3-markerwithlabel.git ? I can do it in the webjars site ?

Thx

**Comment by jamesward** [comment]
Yeah, you can deploy NPM packages either from the NPM repo or from their git repo using: http://webjars.org/npm

**Comment by growak** [comment]
I tried to deploy https://github.com/nmccready/google-maps-utility-library-v3-infobox 1.1.14 and it failed.

Failed! No valid licenses found. Detected licenses: Apache License 2.0 The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: github-com-nmccready-google-maps-utility-library-v3-infobox Starting Deploy
Deploy!

-------

I tried to deploy https://github.com/nmccready/google-maps-utility-library-v3-keydragzoom 2.0.9 and it failed.

Failed! No valid licenses found. Detected licenses: Apache License 2.0 The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: github-com-nmccready-google-maps-utility-library-v3-keydragzoom Starting Deploy

-------

I tried to deploy https://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel 1.1.10 and it failed.

Failed! No valid licenses found. Detected licenses: Apache License 2.0 The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.  If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: github-com-nmccready-google-maps-utility-library-v3-markerwithlabel Starting Deploy
Deploy!

**Comment by jamesward** [comment]
It looks like the fix for this (#1423) didn't deploy because Travis tests failed due to a BinTray issue.  I've kicked the CI build to see if it will work this time.

**Comment by jamesward** [comment]
The fix has been deployed.  Can you try again to deploy these?

**Comment by growak** [comment]
It works !
Thx James

--------
https://github.com/nmccready/google-maps-utility-library-v3-infobox

Deployed! It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar now. GroupID = org.webjars.npm ArtifactID = github-com-nmccready-google-maps-utility-library-v3-infobox Version = 1.1.14  Synced With Maven Central Published BinTray Version Signed BinTray Assets Published BinTray Assets Created BinTray Version Created BinTray Package Converted project licenses Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: github-com-nmccready-google-maps-utility-library-v3-infobox Starting Deploy
Deploy!
--------
 https://github.com/nmccready/google-maps-utility-library-v3-keydragzoom

Deployed! It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar now. GroupID = org.webjars.npm ArtifactID = github-com-nmccready-google-maps-utility-library-v3-keydragzoom Version = 2.0.9  Synced With Maven Central Published BinTray Version Signed BinTray Assets Published BinTray Assets Created BinTray Version Created BinTray Package Converted project licenses Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: github-com-nmccready-google-maps-utility-library-v3-keydragzoom Starting Deploy
Deploy!
----------
https://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel

Deployed! It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar now. GroupID = org.webjars.npm ArtifactID = github-com-nmccready-google-maps-utility-library-v3-markerwithlabel Version = 1.1.10  Synced With Maven Central Published BinTray Version Signed BinTray Assets Published BinTray Assets Created BinTray Version Created BinTray Package Converted project licenses Created NPM WebJar Fetched NPM tgz Generated POM Converted dependencies to Maven Got NPM info Determined Artifact Name: github-com-nmccready-google-maps-utility-library-v3-markerwithlabel Starting Deploy
Deploy!

**Comment by jamesward** [comment]
Great!
