### ISSUE TITLE
Webjar for MooWheel JS library

### ISSUE THREAD

**Issue by emandi** [webjars/webjars#1430]
Hello,

I would like to request a classic webjar for the MooWheel JS library (http://labs.unwieldy.net/moowheel/).

The GitHub repo I created for it is: https://github.com/emandi/webjar-moowheel

I remain at your disposal if anything else is needed.

Thank you in advance,
Eleni

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/moowheel

This will be released shortly.

**Comment by emandi** [comment]
Thank you for the release!

I would like to ask you if the rest of the files in the zip (https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/moowheel/moowheel_v02.zip) can also be included in the webjar. Currently I can see only the moowheel.js.

Thanks a lot,
Eleni

**Comment by jamesward** [comment]
Can you file an issue on: https://github.com/webjars/moowheel
