### ISSUE TITLE
Problem deploying NPM package `angular-pageslide-directive`

### ISSUE THREAD

**Issue by mickeyvip** [webjars/webjars#1431]
https://github.com/dpiccone/ng-pageslide

I tried to deploy this package to Bower and NPM WebJars.

Bower (`angular-pageslide-directive`, MIT) did succeed, but NPM (`angular-pageslide-directive`, MIT) fails while complaining about `bower.json`(!)

![image](https://cloud.githubusercontent.com/assets/220427/16763733/ef254084-4832-11e6-8ff8-2ac2e1baa5f7.png)

What is the problem with this package?

Thank you.

**Comment by jamesward** [comment]
The error message was wrong.  I've fixed that.  But the package won't deploy because there was a typo in the `package.json` for the specified version: https://github.com/dpiccone/ng-pageslide/blob/v1.4.3/package.json#L18

**Comment by mickeyvip** [comment]
Thank you so much!

**Comment by mickeyvip** [comment]
I am still seeing `bower.json` in the error message

**Comment by jamesward** [comment]
It now says `The bower.json or package.json did not contain a spec-compliant license definition and the license could not be determined by trolling through the GitHub repo.`

Not as precise as it could be, but better.
