### ISSUE TITLE
Search on webjars.org is extremly slow...

### ISSUE THREAD

**Issue by PhantomYdn** [webjars/webjars#1436]
I recommend to take a look what FontAwesome did: http://fontawesome.io/icons/
They integrated with https://www.algolia.com/ for almost instant search.
Imho, use-cases are pretty much the same - so it shouldn't be a big problem to migrate.

**Comment by PhantomYdn** [comment]
Or if pricing will be high for your volume: I can propose to utilize [Orienteer](http://orienteer.org) on our hardware for free.

**Comment by jamesward** [comment]
Related to: #1327
