### ISSUE TITLE
webjars.org should publish github packages always in lowercase

### ISSUE THREAD

**Issue by manolo** [webjars/webjars#1438]
Right now it is duplicating packages like the case of:
- github-com-polymerelements-iron-icons
- github-com-PolymerElements-iron-icons

Apart from duplicity, this produces certain undesired errors like you have to use camelised artifactId in maven when the lowercased does not exist. Dependencies are a mess, for instance if your project depends on `paper-elements` bundle project which have dozens of transitive dependencies mixing upper and lower cases for the same element. Other times you get io errors in eclipse when trying to access .xml files in the local repo because they are installed twice in upper and lower cases.

I think the best option would be to lowercase everything because:

`Github.Com/PolymerElements/Iron-Icons` resolves to `github.com/polymerelements/iron-icons`

**Comment by manolo** [comment]
As additional info, in  bower.json names are case insensitive you can see this example:

```
bower info iron-input 
...
  dependencies: {
    'iron-a11y-announcer': 'PolymerElements/iron-a11y-announcer#^1.0.0',
    'iron-validatable-behavior': 'PolymerElements/iron-validatable-behavior#^1.0.0',
    polymer: 'Polymer/polymer#^1.0.0'
  },
...

bower info iron-icon
...
  dependencies: {
    'iron-flex-layout': 'polymerelements/iron-flex-layout#^1.0.0',
    'iron-meta': 'polymerelements/iron-meta#^1.0.0',
    polymer: 'Polymer/polymer#^1.1.0'
  },
...

That produces dependencies in pom.xml generated in webjars being almost unusable because of mix dependencies upper/lower case

So everything in pom.xml should also go to uppercase.

**Comment by jamesward** [comment]
I think this stems from GitHub paths being case insensitive.  So I agree that we need to match that behavior and the right way to do it is by lowercasing artifact names when they are based on GitHub repos.
