### ISSUE TITLE
Provide a way for deploying multiple packages

### ISSUE THREAD

**Issue by manolo** [webjars/webjars#1446]
If you want to make available a large set of components, for instance `paper-elements` you need to request one by one a total of 60 elements.
Providing an API, or just a text area with a list of dependencies could mitigate the effort. 
Another option could be a flag for uploading all dependent webjars.

**Comment by jamesward** [comment]
You can use:
```
curl -X POST 'http://www.webjars.org/_npm/deploy?name=NAME&version=VERSION&channelId=0'
```
