### ISSUE TITLE
The plus button dialog does not work for full-qualified bower packages

### ISSUE THREAD

**Issue by manolo** [webjars/webjars#1453]
Go to http://www.webjars.org/bower and select a package that includes the github repo in its name (for instance `github-com-vaadin-vaadin-combo-box`), the dialog opens, but it does not find any version. To make it work, you need to manually remove the `github-com` part and replace the first dash by a slash

**Comment by jamesward** [comment]
The git deployment has been a bit of a secret feature but I need to make it more clear how to use it.  You need to enter a Git URL in the input box or a Bower-style GitHub reference.  So to deploy `github-com-vaadin-vaadin-combo-box` you need to enter either `https://github.com/vaadin/vaadin-combo-box.git` or `vaadin/vaadin-combo-box`.

Let me know if that works and I'll update the UI.

**Comment by jamesward** [comment]
Related to: #1419

**Comment by jamesward** [comment]
Kinda fixed by https://github.com/webjars/webjars/commit/37b7877f675cfaba4df0ed03998339adb8b26ed4
