### ISSUE TITLE
creating a webjar

### ISSUE THREAD

**Issue by xenoterracide** [webjars/webjars#1454]
I'm looking for documentation on how to bundle my own webjar from a private repository, or perhaps just after an npm dist, and bundle and ship to a private repo (I know how to ship to a private repo). I'm not sure if there's a tool I can use?

**Comment by jamesward** [comment]
You should be able to follow the same packaging format as a normal WebJar and then change the repository that Maven deploys to.  Does that help?

**Comment by xenoterracide** [comment]
is that format documented? I'm just not that familiar yet, and didn't see anything obvious on the site.

also unsure if there's a decent clean way to build the dist then the jar, or whether there's like a maven/other plugin I can use to generate the jar from a dist.

Just trying to figure a process out for bundling a frontend that needs transpiling/preprocessing into a spring boot app. Thinking that packing it as a webjar is an option, then the frontend becomes just another maven dep.

**Comment by jamesward** [comment]
Yeah, here are the docs for creating WebJars: http://www.webjars.org/contributing

I think your approach sounds great!

**Comment by bcopy** [comment]
@xenoterracide  : Would that plugin help ? it does a decent job interfacing with npm and other node build tools :  https://github.com/eirslett/frontend-maven-plugin

**Comment by xenoterracide** [comment]
hmm? oh maybe, ultimately decided to just unpack my npm tarball and point spring boot at the directory to serve statics in my docker container
