### ISSUE TITLE
Add a New NPM WebJar fails with d3-timer 1.0.1

### ISSUE THREAD

**Issue by arlowhite** [webjars/webjars#1455]
d3-timer 1.0.1 fails with:

> Failed! {"status":"Sync Failed","messages":"[Failed to close repository: orgwebjars-18559. Server response:\n <nexus-error>\n <errors>\n <error>\n <id>*<\u002fid>\n <msg>Unhandled: Repository: orgwebjars-18559 has invalid state: closed<\u002fmsg>\n <\u002ferror>\n <\u002ferrors>\n<\u002fnexus-error>, Dropping existing partial staging repository.]"}

Also, I'm installing this because it's a dependency of d3 4.2.0, but why doesn't webjars.org automatically install all dependencies?

**Comment by arlowhite** [comment]
The 2nd try worked.

Some kind of temporary server issue?
Close this issue?

**Comment by jamesward** [comment]
Yeah, that means that Maven Central had a temporary hiccup.
