### ISSUE TITLE
WebJar request: uswds-0.11.0

### ISSUE THREAD

**Issue by vjkapur** [webjars/webjars#1458]
"Open source UI components and visual style guide for U.S. government websites" (https://standards.usa.gov). Would be nice to auto-generate a WebJar from the npm package, but their licensing attribution is thorough and might not lend itself to available metadata constraints even if I requested it.

I've created a project to compile a jar for v0.11.0 (latest release) here: https://github.com/intrical/uswds-mvn

Hope that's well-formed.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/uswds

This will be released shortly.
