### ISSUE TITLE
Bower deployment not working - deploying empty files to the JSDELIVR CDN

### ISSUE THREAD

**Issue by bcopy** [webjars/webjars#1462]
Hello,

We have tried to trigger a new Bower webjar deploy for Polymer app-route  (Bower PolymerElements/app-route  version 0.9.2)  - while the resulting JAR is correct, the files never get deployed to the JSDELIVR CDN, examples :

* http://cdn.jsdelivr.net/webjars/org.webjars.bower/github-com-PolymerElements-app-route/0.9.2/app-route.html
* http://cdn.jsdelivr.net/webjars/org.webjars.bower/github-com-PolymerElements-app-route/0.9.2/app-route-converter.html

**Comment by jamesward** [comment]
It is looking like they are there now.  But those files include relative paths that do not work.
