### ISSUE TITLE
Cannot deploy jqzoom Bower WebJar

### ISSUE THREAD

**Issue by YoanaIvanova** [webjars/webjars#1470]
Greetings.

I'm trying to add jqzoom 2.3.0 as a [bower webjar](http://www.webjars.org/bower) and I get the following error:

![jqzoom webjar 2](https://cloud.githubusercontent.com/assets/15999515/18166856/301e7f2e-7056-11e6-81f0-d474413e5ec7.png)

I'm not sure which repo is being referred to here.

This should be the original jqzoom repo: https://github.com/kangax/jqzoom.git - I tried adding it instead of just typing "jqzoom", but apparently they don't have a bower.json file and I get an error.

This repo, however, has a bower.json file and there should be no problems deploying it: https://github.com/kangax/jqzoom.git (I spoke to the owner here: https://github.com/gregra81/jqzoom/issues/1). However, when I try to add his repo as a Bower WebJar, the "Version" dropdown is empty and when I click "Deploy!", the process hangs at "Starting Deploy":

![jqzoom webjar](https://cloud.githubusercontent.com/assets/15999515/18166986/e440235e-7056-11e6-832b-0f039fea99ce.png)

I'd be happy if you guys could shed some light on this.

**Comment by jamesward** [comment]
Yeah, the `jqzoom` Bower package's [repo](https://github.com/kangax/jqzoom) doesn't have a `bower.json` - how is that even possible?

There aren't any tagged releases in: https://github.com/gregra81/jqzoom
However, if you want to deploy a commit, put `https://github.com/gregra81/jqzoom#master` in the first text input.
