### ISSUE TITLE
Cannot deploy npm webjar: entities 1.0.0

### ISSUE THREAD

**Issue by szeiger** [webjars/webjars#1471]
While deploying entities 1.0.0:

> Failed! No valid licenses found. Detected licenses: BSD-like The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

The [license file](https://github.com/fb55/entities/blob/master/LICENSE) looks like a standard 2-clause BSD license to me.

**Comment by jamesward** [comment]
If the license specified in the `package.json` then it is used and since `1.0.0` specifies an invalid `BSD-like` license, it won't work:
https://github.com/fb55/entities/blob/v1.0.0/package.json#L33

Can you use a newer version that has fixed this?

**Comment by szeiger** [comment]
I'll try. It's a transitive dependency of `mathjax-npm`, which pulls in what seems to be half of the npm ecosystem, including `entities` < 1.1.0. This whole house of cards will probably collapse anyway when I try to run it on Nashorn.

**Comment by jamesward** [comment]
I just pushed a change that should fix this.  It will take about 15 minutes to deploy then you should be able to deploy the `1.0.0` package.  Let me know how it goes.
