### ISSUE TITLE
RxJs installs in wrong directory

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1476]
Hi,

There's a problem with some releases of RxJs npm where it doesn't get installed into 
```
...node-modules/main/webjars/rxjs/<lib contents>
```
But into
```
...node-modules/main/webjars/Ben Lesh/<lib contents>
```
This is the case for RxJs `5.0.0-beta.11` f.i. "Ben Lesh" happens to be the name of the author of RxJs.

The strange thing is that the webjar dir name is correct in `web-modules/main/webjars/lib`.

**Comment by jamesward** [comment]
What is extracting the WebJar to that dir?

**Comment by joost-de-vries** [comment]
Wow. Your fast. :-)
This is in a Play framework application. 
I haven't installed `"org.webjars" %% "webjars-play" % "2.5.0"`. 
(I'm not clear tbh on what webjars-play adds. webjars seem to work fine by default in a Play application)

**Comment by jamesward** [comment]
Yeah, you only need `webjars-play` if you want to use a special route or RequireJS support with WebJars.

The WebJar extractor is going through `sbt-web` and comes from webjars-locator-core: https://github.com/webjars/webjars-locator-core

Would you mind filing an issue over there?
