### ISSUE TITLE
Getting the webjarsjs file via maven unpack-dependencies

### ISSUE THREAD

**Issue by ThYpHo0n** [webjars/webjars#1477]
Hi,

I want to implement frontend testing into our Angular 1 project by using Karma. We use requirejs with Webjars which works smoothly in the browser and on runtime because we get the generated /webjarsjs file which we can just load. Now I wanted to use the maven unpack-dependencies and use the extracted webjars from target/dependency/META-INF/resources/webjars/... which is not a problem but how can I generate "on the fly" the appropriate /webjarsjs file for this kind of loading? Any ideas?

**Comment by jamesward** [comment]
The RequireJS config is generated by https://github.com/webjars/webjars-locator so it seems totally feasible that you could use that util to generate the config via a different lifecycle.

Does that help?

**Comment by ThYpHo0n** [comment]
Yes, perfect. I will have a look into it.
