### ISSUE TITLE
name of webjar 

### ISSUE THREAD

**Issue by glipka** [webjars/webjars#1489]
Hi 
I try to create npm webjars from : 
https://github.com/bjyoungblood/es6-error 
https://github.com/dashed/shallowequal 

but the generated webjar name is github-com-dashed-shallowequal  and github.com-bjyoungblood-es6-error  

Any idea ? 
Best regards

**Comment by glipka** [comment]
same thing for : https://github.com/then/is-promise

**Comment by jamesward** [comment]
Instead of putting the GitHub URL in, put the registered name of the package.  Let me know if that works.

**Comment by glipka** [comment]
it's work 
Best Regards
