### ISSUE TITLE
leaflet.gridlayer.googlemutant with "BeerWare" license

### ISSUE THREAD

**Issue by hakan42** [webjars/webjars#1490]
Hi,

I would like to contribute (with the new automated tools) Leaflet.GridLayer.GoogleMutant which is a nice extension to leaflet.

The license is rejected by the webjars scripts, telling me that this is not one of the accepted (by whom? bintray) open source licenses. The original author argues that this license is much like the WTFPL, and should be acceptable.

Is there a way to include his license into the list of accepted ones? Or have some marker in his LICENSE files that makes the scripts accept it as a valid one?

Link to the ticket in the upstream repo:

https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant/issues/7

**Comment by jamesward** [comment]
Are you trying to deploy this via the Bower or NPM form on webjars.org?  If so then the license needs to be an Open Source one that BinTray recognizes.  If you do this as a Classic WebJar then it doesn't matter.

**Comment by cyrus07424** [comment]
@jamesward Can you deploy `leaflet.gridlayer.googlemutant` as Classic WebJar?
I wanna use this library as webjar.

**Comment by jamesward** [comment]
The new WebJar is here: https://github.com/webjars/Leaflet.GridLayer.GoogleMutant

This will be released shortly.
