### ISSUE TITLE
Link to demo on webjars.org is broken

### ISSUE THREAD

**Issue by rygel** [webjars/webjars#1492]
If you go to http://www.webjars.org/documentation#pippo and click on the link to example you will be forwarded to https://github.com/decebals/pippo/tree/master/pippo-demo/pippo-demo-ajax which is the old pippo-demo location. This should to be updated to https://github.com/decebals/pippo-demo/tree/master/pippo-demo-ajax.
Also a link to http://www.pippo.ro/doc/templates.html would be great to give more information about the webjars handling in other template languages.

**Comment by decebals** [comment]
I think that it's the wrong repository. Please create the same issue on [Pippo](https://github.com/decebals/pippo).

**Comment by decebals** [comment]
@danjee Ping

**Comment by danjee** [comment]
Thanks for input, I will update ASAP

**Comment by jamesward** [comment]
Fixed by #1494

This has been deployed.
