### ISSUE TITLE
jquery-duration-picker does not work

### ISSUE THREAD

**Issue by fabriziofortino** [webjars/webjars#1498]
Getting the following error when I add the dependency to jquery-duration-picker

```
Could not transfer artifact org.webjars.bower:semantic:pom:semantic-ui#~2.1.4 from/to central (https://repo1.maven.org/maven2/): Illegal character in fragment at index 97: https://repo1.maven.org/maven2/org/webjars/bower/semantic/semantic-ui#~2.1.4/semantic-semantic-ui#~2.1.4.pom
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```

**Comment by jamesward** [comment]
Thanks for reporting.  For now you will need to exclude that transitive dependency in your build definition.  The way the upstream project [specifies its dependency](https://github.com/QueraTeam/jquery-duration-picker/blob/master/bower.json#L26) on `semantic-ui` isn't compliant with [the spec](https://github.com/bower/spec/blob/master/json.md).  So this should never have been able to be deployed.  I'll fix this for future deploys.  But there is nothing we can do about this bad pom.
