### ISSUE TITLE
Timeout: owl.carousel:2.2.0 Bower-webjar deployment fails

### ISSUE THREAD

**Issue by groie** [webjars/webjars#1505]
I am trying to package and deploy 2.2.0 of owl.carousel. Unfortunately it does not work and I get the following error:

> Failed! 
> Request timeout to not-connected after 120000 ms 
> If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  
> 
> Created BinTray Package 
> Created Bower WebJar 
> Fetched Bower zip 
> Generated POM 
> Converted dependencies to Maven
> Resolved Licenses 
> Got Bower info 
> Determined Artifact Name: owl.carousel 
> Starting Deploy
> Deploy!

What I do see is that the library is available at [Bintray](https://bintray.com/webjars/maven/org.webjars.bower%3Aowl.carousel/2.2.0#) but not at [Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.webjars.bower%22%20AND%20a%3A%22owl.carousel%22). Unfortunately at my Corporate Setting I am not able to use Bintray, just mvn-central.

**Comment by jamesward** [comment]
It looks like there was a temporary issue syncing to Maven Central.  I've resynced this WebJar so it should be available in Maven Central within the next few hours.

**Comment by groie** [comment]
Thanks @jamesward!
