### ISSUE TITLE
Update classic WebJar for Mirador

### ISSUE THREAD

**Issue by morpheus-87** [webjars/webjars#1506]
Today a new version 2.1.2 was released, see https://github.com/ProjectMirador/mirador/releases/tag/v2.1.2. Could you please update the WebJar for Mirador, @jamesward?

**Comment by jamesward** [comment]
This will be released shortly.  In the future please file version bump requests for existing WebJars on their respective repo.  i.e https://github.com/webjars/mirador

**Comment by morpheus-87** [comment]
Thank you very much for the release, @jamesward! In the future, I will file an issue in the corresponding repository, for sure.
