### ISSUE TITLE
some @types npms are not copied into node_modules

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1509]
I'm writing a react application with typescript. And I see the strange thing that a lot of relevant typescript definitions such as `@types/react` are not to be found in `target/web/node_modules` where I'd expect them. They _can_ be found in `target/web/web_modules` with a name like `types__react`.
Some type definitions do end up in `node_modules`. For instance `@types/redux`. I don't see a difference though in their `package.json`.
I'm using the following dependencies:
```
  "org.webjars" % "webjars-locator" % "0.32",
  "org.webjars" % "webjars-locator-core" % "0.32",
```
and 
```
addSbtPlugin("com.typesafe.sbt" % "sbt-js-engine" % "1.1.4")
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.0")
```

[This github repo](https://github.com/joost-de-vries/play-reactjs-typescript) shows off the problem.

**Comment by jamesward** [comment]
Hmm..  So maybe a problem with the extractor in `webjars-locator-core`?  I'm not sure where that logic actually resides...  sbt-web or somewhere else.  @huntc

**Comment by joost-de-vries** [comment]
Such a quick response. Have a good sunday James. :-)

**Comment by joost-de-vries** [comment]
Isn't it [WebjarsExtractor](https://github.com/webjars/webjars-locator-core/blob/master/src/main/java/org/webjars/WebJarExtractor.java) that does this?

**Comment by jamesward** [comment]
Yeah, that sounds right.  Think you can create a breaking test for this in the `webjars-locator-core` project?

**Comment by joost-de-vries** [comment]
Yeah. I'll have a look.

**Comment by joost-de-vries** [comment]
My findings so far:

The @types webjars that do _not_ work have in common: their contents do not contain the files directly. But the files are within a subdirectory. Like so  
`META-INF/resources/webjars/types__react-redux/4.4.32/react-redux/package.json`
And they are shown on webjars.org/npm under the `@types/react-redux` kind of name.

The @types webjars that _do_ work have in common: their contents contain the files directly. Like so
`META-INF/resources/webjars/types__redux/3.3.26/package.json`  
And they are shown on webjars.org/npm under the `types__redux` kind of name.  

So it seems that this is something that happens when importing the npm through the UI from npm to wewbjars. Any idea what this can be?

**Comment by jamesward** [comment]
Thanks for sleuthing that out!  I think you are right that this is a packaging bug.  Investigating now.

**Comment by jamesward** [comment]
So for some reason different NPM packages are packaged differently:
```
~/Desktop $ tar -ztvf react-redux-4.4.32.tgz 
-rw-r--r--  0 1000   1000      620 Sep 19 11:28 react-redux/README.md
-rw-r--r--  0 1000   1000     4105 Sep 19 11:28 react-redux/index.d.ts
-rw-r--r--  0 1000   1000      624 Sep 19 11:28 react-redux/package.json
-rw-r--r--  0 1000   1000      815 Sep 19 11:28 react-redux/types-metadata.json
~/Desktop $ tar -ztvf redux-3.3.26.tgz 
-rw-rw-rw-  0 0      0         470 Jul 14 07:52 package/package.json
-rw-rw-rw-  0 0      0         601 Jul 14 07:52 package/README.md
-rw-rw-rw-  0 0      0        1496 Jul 14 07:52 package/index.d.ts
-rw-rw-rw-  0 0      0         736 Jul 14 07:52 package/types-metadata.json
```

Geeze. :(

**Comment by jamesward** [comment]
This should be deployed in about 30 minutes.  Then you will need to redeploy a new version of the `react-redux` lib to see if it works.  Let me know how it goes!

**Comment by joost-de-vries** [comment]
You've fixed it! Super cool.
Tx man.

**Comment by joost-de-vries** [comment]
Ehm. 
I've hit a snag with `@types/react-router`. For some reason it contains its type files in a `lib` subdirectory. And that leads in the node_modules directory to an unpackaged dir `@types/react-router.lib`. 
The error message when runnint `sbt assets` is as follows  
```
[error] (web-assets:webJarsNodeModules) java.io.FileNotFoundException: /Users/joost1/source/play-react-typescript/target/web/node-modules/main/webjars/@types/react-router/lib (Is a directory)
[error] (web-assets:webJars) java.io.FileNotFoundException: /Users/joost1/source/play-react-typescript/target/web/web-modules/main/webjars/lib/types__react-router/lib (Is a directory)
```

**Comment by jamesward** [comment]
Whoops.  I was not adding the directories to the zip correctly.

**Comment by jamesward** [comment]
The fix for this will be deployed in about 30 minutes.

**Comment by jamesward** [comment]
I feel like we can't overwrite artifacts on Maven Central.  But we should try it once this is deployed and see if it works.

**Comment by joost-de-vries** [comment]
I've tried deleting my local ivy2 cache and re-adding `@types/react-router` to `webjars.org/npm`.
But after an `sbt clean` I still get
```
[error] (web-assets:webJarsNodeModules) java.io.FileNotFoundException: /Users/joost1/source/play-react-typescript/target/web/node-modules/main/webjars/@types/react-router/lib (Is a directory)
[error] (web-assets:webJars) java.io.FileNotFoundException: /Users/joost1/source/play-react-typescript/target/web/web-modules/main/webjars/lib/types__react-router/lib (Is a directory)
```
Am I doing something wrong?

**Comment by jamesward** [comment]
It looks like the new deploy didn't overwrite the old one.  I've deleted the artifact from BinTray and am trying a deploy again.

**Comment by joost-de-vries** [comment]
Yesterday evening I tried again: the problem with `@types/react-router` is resolved. Tx!

Unfortunately the other `@types` dependencies don't appear in `node_modules`. I'll try again tonight...
Maybe we should delete all the react related `@types` npm webjars to make sure we don't hit stale cached jars. Wat do you think?

**Comment by jamesward** [comment]
Do you think this is due to those projects not being packages correctly before the changes related to this issue?

**Comment by joost-de-vries** [comment]
I've looked into it. 

It seems files are not updated if from the UI you 'import' a version again that already exists.
For instance I added `@types/redux` again for version `3.6.31` . But when I [look at the files](http://www.webjars.org/listfiles/org.webjars.npm/types__redux/3.6.31) I still see the unwanted subdirectory.

Any ideas how to fix that?

**Comment by jamesward** [comment]
Let me know what packages are broken and I'll delete them from BinTray.  Hopefully that will work.
