### ISSUE TITLE
Transitive dependency ranges should include prerelease

### ISSUE THREAD

**Issue by doug-wade** [webjars/webjars#1512]
In https://github.com/doug-wade/jsinopia/issues/1, the existing express version 5.0.0-alpha.2 should fulfill the version range `>=5.0.0`, but it does not.

**Comment by jamesward** [comment]
We don't control the version resolution.  That is handled by your build tool.  However I think that technically an alpha match the requirement of a release version.  Yet you can probably override the resolution in your build tool.

**Comment by doug-wade** [comment]
@jamesward in this case, its a transitive dependency, so I don't control version resoltuion.  I'm trying to install the web jar `sinopia`, and _it_ has a dependency on [`express >= 5.0.0`](https://github.com/rlidwka/sinopia/blob/master/package.yaml#L21).  *That* dependency is fulfilled by a local `npm install`, but adding a dependency on the `sinopia` web jar _fails_ because it declares an unfulfilled dep.

**Comment by jamesward** [comment]
I think I'd consider that a bug in `sinopia` since that is a dependency that can not currently be fulfilled by any released version of `express`.  So you will need to tell your dependency resolver (i.e. build tool) to ignore that transitive dependency and then override it with an existing version.
