### ISSUE TITLE
NPM version ranges not properly handled

### ISSUE THREAD

**Issue by gpgekko** [webjars/webjars#1514]
It seems that for NPM, one can use a revision range where only the major version part is mentioned. Basically, `1` is equal to `1.x.x`. However, this is not really translated well to Maven.

> [info] Resolving org.webjars.npm#semver;[2,3),[3,4),[4,5),[5,6) ...
> [warn]  module not found: org.webjars.npm#semver;[2,3),[3,4),[4,5),[5,6)
> [warn] ==== typesafe-ivy-releases: tried
> [warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.webjars.npm/semver/[2,3),[3,4),[4,5),[5,6)/ivys/ivy.xml
> [warn] ==== sbt-plugin-releases: tried
> [warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars.npm/semver/[2,3),[3,4),[4,5),[5,6)/ivys/ivy.xml
> [warn] ==== local: tried
> [warn]   C:\Users\[user]\.ivy2\local\org.webjars.npm\semver\[2,3),[3,4),[4,5),[5,6)\ivys\ivy.xml
> [warn] ==== public: tried
> [warn]   https://repo1.maven.org/maven2/org/webjars/npm/semver/[2,3),[3,4),[4,5),[5,6)/semver-[2,3),[3,4),[4,5),[5,6).pom
> [warn] ==== activator-local: tried
> [warn]   C:\Play\activator\repository\org.webjars.npm\semver\[2,3),[3,4),[4,5),[5,6)\ivys\ivy.xml
> [warn] ==== Maven2 Local: tried
> [warn]   file:/C:/Users/[user]/.m2/repository/org/webjars/npm/semver/[2,3),[3,4),[4,5),[5,6)/semver-[2,3),[3,4),[4,5),[5,6).pom
> [warn] ==== typesafe-releases: tried
> [warn]   https://repo.typesafe.com/typesafe/releases/org/webjars/npm/semver/[2,3),[3,4),[4,5),[5,6)/semver-[2,3),[3,4),[4,5),[5,6).pom
> [warn] ==== typesafe-ivy-releasez: tried
> [warn]   https://repo.typesafe.com/typesafe/ivy-releases/org.webjars.npm/semver/[2,3),[3,4),[4,5),[5,6)/ivys/ivy.xml
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: org.webjars.npm#semver;[2,3),[3,4),[4,5),[5,6): not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]
> [warn]  Note: Unresolved dependencies path:
> [warn]          org.webjars.npm:semver:[2,3),[3,4),[4,5),[5,6)
> [warn]            +- org.webjars.npm:normalize-package-data:[2.3.2,3)
> [warn]            +- org.webjars.npm:read-pkg:[1.0.0,2)
> [warn]            +- org.webjars.npm:read-pkg-up:[1.0.1,2)
> [warn]            +- org.webjars.npm:yargs:[4.7.1,5)
> [warn]            +- org.webjars.npm:postcss-cli:2.6.0

**Comment by jamesward** [comment]
The `org.webjars.npm:normalize-package-data:2.3.5` dependency on NPM is:
```
"semver": "2 || 3 || 4 || 5",
```
From: https://cdn.jsdelivr.net/webjars/org.webjars.npm/normalize-package-data/2.3.5/package.json

That was translated to:
```
[2,3),[3,4),[4,5),[5,6)
```

From: https://repo1.maven.org/maven2/org/webjars/npm/normalize-package-data/2.3.5/normalize-package-data-2.3.5.pom

So that looks correct.  But sbt wasn't able to resolve this.  A while back I filed a bug for this: https://github.com/sbt/sbt/issues/2647

In the meantime you'll need to force sbt to use a specific version.

**Comment by gpgekko** [comment]
Ah, alright. I should have taken a little bit more time to look at it, makes sense that the resolving step is at the SBT side. Forcing it has proven to be tricky, so far every time I get it right in the plugin I'm writing, I still get the above stacktrace when trying to use it in a project. For now the only way I have it all working is by adding a `dependencyOverrides += "org.webjars.npm" % "semver" % "5.3.0"` in the project. :(

Thanks for your time, I'll subscribe to the SBT bug and stick to the workaround for now.
