### ISSUE TITLE
Webjar for google analytics snippet

### ISSUE THREAD

**Issue by johann-abraham** [webjars/webjars#1517]
This webjar is for the google analytics snippet that sets up the analytics.js global ga function.  The snippet can be seen here:
https://developers.google.com/analytics/devguides/collection/analyticsjs/

The webjar can be found here:
https://github.com/johann-abraham/webjars-google-analytics-snippet

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/google-analytics-snippet

This will be released shortly.
