### ISSUE TITLE
Failed!  No repository found under this GitHub path

### ISSUE THREAD

**Issue by Saadati** [webjars/webjars#1521]
Failures for NPM assets that exists when repository removed but dependency for it exist ...

**Comment by jamesward** [comment]
Can you provide an example that is failing?

**Comment by Saadati** [comment]
Thanks James.
We deployed org.webjars.npm:react-date-picker:5.3.28 when depend on deleted git projects but NPM projects are exist.

Deleted git projects are:
org.webjars.npm:react-flex:jar:2.2.7 
org.webjars.npm:react-inline-block:jar:2.0.0 
org.webjars.npm:react-notify-resize:jar:1.0.3 
org.webjars.npm:react-field:jar:2.0.2

**Comment by jamesward** [comment]
This fix should be deployed in about 20 minutes.  Then you can try again and see if I've actually fixed it.
