### ISSUE TITLE
WebJar Request: videojs

### ISSUE THREAD

**Issue by g-gabber** [webjars/webjars#1524]
I created a webjar for videojs.
Here is my repo https://github.com/g-gabber/videojs

**Comment by jamesward** [comment]
I think this might already exist: https://github.com/webjars/video-js

Is that the same library?

**Comment by g-gabber** [comment]
No, there is a small difference.
Im my version it download the release version with out sources and example.`
https://github.com/videojs/video.js/releases/download/v${upstream.version}/video-js-${upstream.version}.zip`
vs
`https://github.com/videojs/video.js/archive/v${version.unsnapshot}/video-js-${version.unsnapshot}.zip`

My version has only 46 files vs ~ 200 files.

**Comment by jamesward** [comment]
Can you send a Pull Request to the existing WebJar with these changes?
