### ISSUE TITLE
Issue deploying files to webjars

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1526]
Failed!

{"status":"Sync Failed","messages":"[Problem extracting files to sync. Please try again in a bit.]"}
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by mdedetrich** [comment]
Working now

**Comment by jamesward** [comment]
This was a transient issue with BinTray or Maven Central.

**Comment by Dominator008** [comment]
I have a couple of packages that were reported as "Deployed!" on WebJars, but hasn't shown up on Maven Central for ~12 hours yet.

**Comment by jamesward** [comment]
Let me know what packages didn't sync and I'll try to do it manually.

**Comment by mdedetrich** [comment]
@jamesward I think I have the same problem as well, will let you know in a couple of hours

**Comment by jamesward** [comment]
I think this was related to: https://twitter.com/sonatype_ops/status/811269152673562626

**Comment by PhantomYdn** [comment]
I have the same. Package is deployed
```
Deployed!
It will take a few hours for the Maven Central index to update but you should be able to start using the Bower WebJar now. 
GroupID = org.webjars.bower
ArtifactID = pivottable
Version = 2.4.0
Synced With Maven Central
Created BinTray Package
Created Bower WebJar
Fetched Bower zip
Generated POM
Converted dependencies to Maven Resolved Licenses
Got Bower info Determined 
Artifact Name: pivottable 
Starting Deploy
```
But **nothing on central for several hours**

**Comment by jamesward** [comment]
@PhantomYdn I've redeployed that.  Let me know if it doesn't show up soon.

**Comment by PhantomYdn** [comment]
I tried several times in last hours.
And btw, if I'm not mistaken: previously new version appeared on webjars right after deploying. But currently it's not showing up. Is it taking info from maven central?

It seems to be issue with Maven Central...

**Comment by Dominator008** [comment]
Mines are codemirror-5.22.0 and codemirror-minified-5.22.0, thanks!

**Comment by jamesward** [comment]
Yeah, webjars.org refreshes from Maven Central every hour and there is a delay on Maven Central's index as well.  Maven Central has been having some deploy issues over the past few days.

@Dominator008 I've resynced those.  They should show up in the next few hours.

**Comment by Dominator008** [comment]
@jamesward Thanks a lot!

**Comment by mdedetrich** [comment]
My packages ended up resolving without any further deployment, it just appeared to take ages

**Comment by andreaferretti** [comment]
Still getting

{"status":"Sync Failed","messages":"[Problem extracting files to sync. Please try again in a bit.]"}

**Comment by jamesward** [comment]
@andreaferretti What is the package you are trying to deploy?

**Comment by andreaferretti** [comment]
It is now working after a few hours. In any case, it was `paths-js`

**Comment by jamesward** [comment]
Ah.  Thanks.  Seems like Maven Central is still a bit flappy.

**Comment by PhantomYdn** [comment]
Pivottable is still not available. During last day I did redeploying of the same version several times.

Am I right that publishing done directly or through Synapsis?

**Comment by jamesward** [comment]
@PhantomYdn WebJars are uploaded to BinTray and then synced from there to Maven Central.  I've resynced both the NPM & Bower WebJars for pivottable.  So hopefully they show up soon.

**Comment by jamesward** [comment]
It seems like these issues have dissipated.

**Comment by PhantomYdn** [comment]
Thank you! And thank you again for the great way to have frontend libs packed for backend:)
