### ISSUE TITLE
Foundation 6.3.0

### ISSUE THREAD

**Issue by zy4** [webjars/webjars#1527]
Hi, can you please check this:

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.webjars.npm#what-input;[4.0.3,5): not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.webjars.npm:what-input:[4.0.3,5)
[warn] 		  +- org.webjars.npm:foundation-sites:6.3.0

Thanks!

**Comment by jamesward** [comment]
Transitive dependencies aren't auto-deployed.  I just started a deploy for `org.webjars.npm:what-input:4.0.3` via http://www.webjars.org/npm

That should be there in a few hours.  In the future you should be able to deploy these missing transitives on your own.
