### ISSUE TITLE
md-data-table

### ISSUE THREAD

**Issue by RBleyenberg** [webjars/webjars#1535]
md-data-table (name) within webjars/npm exsist twice 

"org.webjars.npm" % "md-data-table" % "1.4.2"  (search md-data-table)
"org.webjars.npm" % "github-com-iamisti-mdDataTable" % "1.8.0"    (search mdDataTable)

because of this i think i'm unable to import it within stb

to be clear i can import "org.webjars.npm" % "md-data-table" % "1.4.2"  but i'm in need for "org.webjars.npm" % "github-com-iamisti-mdDataTable" % "1.8.0" and the later doesn't work in sbt

here a snippet of the dep.

```
    jsDependencies ++= Seq(
      "org.webjars.npm" % "angular" % angularVersion / s"${angularVersion}/angular.js", 
      "org.webjars.npm" % "angular-animate" % angularVersion / "angular-animate.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-aria" % angularVersion / "angular-aria.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-messages" % angularVersion / "angular-messages.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-material" % "1.0.7" / "angular-material.js" dependsOn "angular-animate.js",
      "org.webjars.npm" % "angular-sanitize" % angularVersion / "angular-sanitize.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-ui-router" % "0.2.15" / "release/angular-ui-router.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "github-com-iamisti-mdDataTable" % "1.8.0" / "dist/md-data-table.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "github-com-iamisti-mdDataTable" % "1.8.0" / "dist/md-data-table-templates.js" dependsOn  "dist/md-data-table.js",
      RuntimeDOM % "test"
    )).
  enablePlugins(ScalaJSPlugin, ScalaJSPlay).
  dependsOn(sharedJs)
```

**Comment by jamesward** [comment]
What is the error you are receiving?

**Comment by RBleyenberg** [comment]
webjar/npm >  search > md-data-table

"org.webjars.npm" % "md-data-table" % "2.2.0"

`Error:Error while importing SBT project:<br/>...<br/><pre>	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] sbt.compiler.EvalException: Type error in expression
[error] Use 'last' for the full log.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384M; support was removed in 8.0</pre><br/>See complete log in <a href="C:\Users\remco\.IntelliJIdea2016.2\system\log\sbt.last.log">C:\Users\remco\.IntelliJIdea2016.2\system\log\sbt.last.log</a>`

**Comment by jamesward** [comment]
I can't tell from that error what the problem might be.  What is the full contents of your `build.sbt` file?

**Comment by RBleyenberg** [comment]
pretty large project ^^ but goto scalajs section

it all works... exept when putting md-data-table in jsdeps.

`import com.typesafe.sbt.SbtScalariform._
import sbt.Project.projectToRef

import scalariform.formatter.preferences._


lazy val clients = Seq(scalajs)

lazy val commonSettings = Seq(
  scalaVersion := "2.11.8",
  organization := "nl.dare",
  version := "0.1"
)

lazy val angularVersion = "1.4.9"

lazy val play = (project in file("play")).
  settings(commonSettings: _*).
  settings(
    resolvers += "Atlassian Releases" at "https://maven.atlassian.com/public/",
    scalaJSProjects := clients,
    pipelineStages := Seq(scalaJSProd, gzip),
    dependencyOverrides += "org.webjars" % "jquery" % "2.1.4", // force all to depend on jquery 2.1.4, if there is a jquery dependency
    libraryDependencies ++= Seq(
      "com.typesafe.netty" % "netty-http-pipelining" % "1.1.4",
      "org.reactivemongo" %% "play2-reactivemongo" % "0.11.7.play24",
      "com.mohiva" %% "play-silhouette" % "3.0.0",
      "net.codingwell" %% "scala-guice" % "4.0.0",
      "org.webjars" %% "webjars-play" % "2.4.0-2",
      "com.vmunier" %% "play-scalajs-scripts" % "0.2.2",
      "org.webjars" % "jquery" % "2.1.4",
      "com.github.benhutchison" %% "prickle" % "1.1.9",
      "net.ceedubs" %% "ficus" % "1.1.2",
      "biz.enef" %% "slogging" % "0.3",
      "org.scalactic" %%% "scalactic" % "3.0.1",
      "org.scalatest" %% "scalatest" % "3.0.1" % "test",
      cache,
      filters
    )
  ).
  enablePlugins(PlayScala).
  aggregate(clients.map(projectToRef): _*).
  dependsOn(sharedJvm, hooke, leibniz)

lazy val scalajs = (project in file("scalajs")).
  settings(commonSettings: _*).
  settings(
    persistLauncher := true,
    persistLauncher in Test := false,
    skip in packageJSDependencies := false,
    //    sourceMapsDirectories += sharedJs.base / "..",
    unmanagedSourceDirectories in Compile := Seq((scalaSource in Compile).value),
    resolvers += "Atlassian Releases" at "https://maven.atlassian.com/public/",
    resolvers += Resolver.sonatypeRepo("snapshots"),
    relativeSourceMaps := true,
    libraryDependencies ++= Seq(
      "be.doeraene" %%% "scalajs-jquery" % "0.8.1",
      "com.typesafe.netty" % "netty-http-pipelining" % "1.1.4",
      "com.greencatsoft" %%% "scalajs-angular" % "0.5",
      "com.github.benhutchison" %%% "prickle" % "1.1.10",
      "biz.enef" %%% "slogging" % "0.3",
      cache,
      filters
    ),
    jsDependencies ++= Seq(
      "org.webjars.npm" % "angular" % angularVersion  / s"${angularVersion}/angular.js", // no 1.4.1 available
      "org.webjars.npm" % "angular-animate" % angularVersion / "angular-animate.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-aria" % angularVersion / "angular-aria.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-messages" % angularVersion / "angular-messages.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-material" % "1.0.7" / "angular-material.js" dependsOn "angular-animate.js",
      "org.webjars.npm" % "angular-sanitize" % angularVersion / "angular-sanitize.js" dependsOn  s"${angularVersion}/angular.js",
      "org.webjars.npm" % "angular-ui-router" % "0.2.15" / "release/angular-ui-router.js" dependsOn  s"${angularVersion}/angular.js",
      RuntimeDOM % "test"
    )).
  enablePlugins(ScalaJSPlugin, ScalaJSPlay).
  dependsOn(sharedJs)

lazy val leibniz = (project in file("leibniz")).
  settings(commonSettings: _*).
  settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.0.1" % "test"
    )).
  dependsOn(sharedJvm)

lazy val hooke = (project in file("hooke")).
  settings(commonSettings: _*).
  settings(
    libraryDependencies ++= Seq(
      "org.scalatest" %% "scalatest" % "3.0.1" % "test"
    )).
  dependsOn(sharedJvm, leibniz)

lazy val shared = (crossProject.crossType(CrossType.Pure) in file("shared")).
  settings(commonSettings: _*).
  settings(
    resolvers += "Atlassian Releases" at "https://maven.atlassian.com/public/",
    libraryDependencies ++= Seq(
      "biz.enef" %%% "slogging" % "0.3",
      "org.scalactic" %%% "scalactic" % "3.0.1",
      "org.scalatest" %%% "scalatest" % "3.0.1" % "test",
      cache,
      filters
    )
  ).
  enablePlugins(ScalaJSPlugin).
  jsConfigure(_ enablePlugins ScalaJSPlay)
//  jsSettings(sourceMapsBase := baseDirectory.value / "..")

lazy val sharedJvm = shared.jvm
lazy val sharedJs = shared.js

scalacOptions ++= Seq(
  "-deprecation", // Emit warning and location for usages of deprecated APIs.
  "-feature", // Emit warning and location for usages of features that should be imported explicitly.
  "-unchecked", // Enable additional warnings where generated code depends on assumptions.
  //  "-Xfatal-warnings", // Fail the compilation if there are any warnings.
  "-Xlint", // Enable recommended additional warnings.
  "-Ywarn-adapted-args", // Warn if an argument list is modified to match the receiver.
  "-Ywarn-dead-code", // Warn when dead code is identified.
  "-Ywarn-inaccessible", // Warn about inaccessible types in method signatures.
  "-Ywarn-nullary-override", // Warn when non-nullary overrides nullary, e.g. def foo() over def foo
  "-Ywarn-numeric-widen" // Warn when numerics are widened.
)

//********************************************************
// Scalariform settings
//********************************************************

defaultScalariformSettings

ScalariformKeys.preferences := ScalariformKeys.preferences.value
  .setPreference(FormatXml, false)
  .setPreference(DoubleIndentClassDeclaration, false)
  .setPreference(PreserveDanglingCloseParenthesis, true)



commands += Command.command("runPlay")((state: State) => {
  var newState = Command.process("project play", state)
  Command.process("run", newState)
})

commands += Command.command("docker")((state: State) => {
  Command.process("""eval "docker/dare-mongo/start-docker.bat" !                                          """, state)
})

commands += Command.command("mongo")((state: State) => {
  var newState = state
  newState = Command.process("""eval "docker build -t dare/mongo:0.1-beta docker/dare-mongo/ " !          """, newState)
  newState = Command.process("""eval "docker stop  mongo " !                                              """, newState)
  newState = Command.process("""eval "docker rm -v  mongo " !                                             """, newState)
  newState = Command.process("""eval "docker run -p 27017:27017 -d --name mongo dare/mongo:0.1-beta " !   """, newState)
  newState
})



// loads the Play project at sbt startup
onLoad in Global := (Command.process("project play", _: State)) compose (onLoad in Global).value
`

**Comment by jamesward** [comment]
I don't know much about the `jsDependencies` stuff but maybe it is because you have the same dependency in there twice:
```
"org.webjars.npm" % "github-com-iamisti-mdDataTable" % "1.8.0" / "dist/md-data-table.js" dependsOn  s"${angularVersion}/angular.js",
"org.webjars.npm" % "github-com-iamisti-mdDataTable" % "1.8.0" / "dist/md-data-table-templates.js" dependsOn  "dist/md-data-table.js",
```      
Can you get a stack trace out of sbt?

**Comment by RBleyenberg** [comment]
will stack trace it abit later on (not on the desk atm)

On webjars you have two different names ak.
"github-com-iamisti-mdDataTable"
"md-data-table"

both link to the same github repo... so i was thinking that that's the problem.

![image](https://cloud.githubusercontent.com/assets/6377954/21623681/ea941634-d203-11e6-8f15-4f05db365ea6.png)

![image](https://cloud.githubusercontent.com/assets/6377954/21623710/184a8810-d204-11e6-9c1a-950051a2a1bf.png)

**Comment by jamesward** [comment]
That should be fine.  They are different artifacts.  One was created by pointing to the GitHub repo, the other was created by pointing to the NPM artifact.

**Comment by RBleyenberg** [comment]
`started a discussion at https://gitter.im/scala-js/scala-js?at=586c9dcb9e6f00e74af49f13 

starting from D Stibbe @dstibbe think the link will take you there tho

**Comment by RBleyenberg** [comment]
`Have opened a issue at scalajs

https://github.com/scala-js/scala-js/issues/2710

Think we can close it here.... thx again for your help

**Comment by jamesward** [comment]
Sounds good.  Feel free to reopen this if that doesn't help solve it.
