### ISSUE TITLE
Error when importing npm @types/react

### ISSUE THREAD

**Issue by joost-de-vries** [webjars/webjars#1544]
I get an exception when trying to import the npm module `@types/react`.
Strangely I get the error as well when I try to import a version that was imported previously.
The message is
```
Failed!
JsResultException(errors:List((,List(ValidationError(List(Predicate does not hold for https://www.github.com/DefinitelyTyped/DefinitelyTyped),WrappedArray())))))
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
          
Determined Artifact Name: types__react
Starting Deploy
```
Any idea what causes this?

**Comment by jamesward** [comment]
I made a recent change to the JSON parsing which is probably the issue.  I'll investigate.

**Comment by jamesward** [comment]
I believe I've fixed this and the change should be deployed in about 15 minutes.

**Comment by joost-de-vries** [comment]
Wow you're fast. :-)
Yes, you fixed it. Tx!
