### ISSUE TITLE
WebJar Request: angular-ui-notification

### ISSUE THREAD

**Issue by bidek** [webjars/webjars#1545]
POM file:
https://github.com/bidek/angularuinotification-webjar/blob/master/pom.xml
Release:
https://github.com/bidek/angularuinotification-webjar/releases/download/0.3.5/angular-ui-notification-0.3.5.jar

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/angular-ui-notification

This will be released shortly.
