### ISSUE TITLE
WebJar Request: Tether

### ISSUE THREAD

**Issue by nremond** [webjars/webjars#1547]
Bootstrap 4 has a dependency on Tether and the webjar Bower or NPM package contains too many files. 

So, I created the following https://github.com/nremond/tether

Can it be include in the official webjars packages ?

Thank you

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/tether

This will be released shortly.

**Comment by nremond** [comment]
Thank you very much
