### ISSUE TITLE
google-code-prettify 1.0.5

### ISSUE THREAD

**Issue by emeraldjava** [webjars/webjars#1551]
Hi,

I attempted to deploy a 1.0.5 version of google-code-prettify to the npm repo. The source code is at

https://github.com/spencewood/google-code-prettify

but i get this error

`Failed!
JsResultException(errors:List((/repository/url,List(ValidationError(List(error.path.missing),WrappedArray()), ValidationError(List(error.path.missing),WrappedArray())))))
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: google-code-prettify
Starting Deploy`

**Comment by jamesward** [comment]
Unfortunately there is a bunch of missing metadata in their `package.json` so that will need to be resolved upstream.  Maybe you'll have better luck with the Bower one?

**Comment by emeraldjava** [comment]
I've placed this pull request https://github.com/spencewood/google-code-prettify/pull/14 which added the missing license details to the package.json file.
