### ISSUE TITLE
Cannot create NPM WebJar for electron-to-chromium.

### ISSUE THREAD

**Issue by danielnixon** [webjars/webjars#1552]
> Failed!
> Package for path 'webjars/maven' was invalid
> If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
>           
> Created NPM WebJar
> Fetched NPM tgz
> Generated POM
> Converted dependencies to Maven
> Resolved Licenses
> Got NPM info
> Determined Artifact Name: electron-to-chromium
> Starting Deploy

**Comment by jamesward** [comment]
For some reason BinTray was confused.  I've unconfused it and deployed `1.2.2` of this.  Let me know if you have any issues.
