### ISSUE TITLE
Capitalization of Polymer GitHub artifacts is inconsistent and breaks dependencies

### ISSUE THREAD

**Issue by punkstarman** [webjars/webjars#1556]
In a Maven project, I'm trying to use the paper-elements artifact from org.webjars.bower. Therefore in the pom.xml file there is the following dependency:

```xml
<dependency>
    <groupId>org.webjars.bower</groupId>
    <artifactId>paper-elements</artifactId>
    <version>1.0.7</version>
</dependency>
```

Any maven build trigger the following error:
```
[ERROR] Failed to execute goal on project cu-manager-ui: Could not resolve dependencies for project fr.treeptik:cu-manager-ui:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at org.webjars.bower:paper-elements:jar:1.0.7 -> org.webjars.bower:github-com-PolymerElements-paper-radio-button:jar:1.3.1 -> org.webjars.bower:github-com-polymerelements-iron-flex-layout:jar:[1.3.0,1.4): No versions available for org.webjars.bower:github-com-polymerelements-iron-flex-layout:jar:[1.3.0,1.4) within specified range
```

It looks like the paper radio button element depends on an iron flex layout element with a version between 1.3.0 (included) and 1.4 (excluded). It should find one since there is a version 1.3.1 on the Maven central repository. However, the artifactId of that version has a slightly different capitalization: `github-com-PolymerElements-iron-flex-layout` instead of all lower case.

Maven coordinates are case sensitive, at least on Linux, so this breaks the dependency chain.

Artifact `github-com-PolymerElements-paper-radio-button` should probably depend on `github-com-PolymerElements-iron-flex-layout`, which is in line with the iron-elements artifact.

**Comment by jamesward** [comment]
Case sensitivity is preserved on deploy so I just deployed `github-com-PolymerElements-paper-radio-button` version `1.3.1` and it should be in Maven Central soon.
