### ISSUE TITLE
Creating validationengine 2.6.4 failing

### ISSUE THREAD

**Issue by cjjava** [webjars/webjars#1557]
Failed!
/tmp/git914349601383459917/https:/github.com/posabsolute/jQuery-Validation-Engine/bower.json (No such file or directory)
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: github-com-posabsolute-jQuery-Validation-Engine
Starting Deploy

**Comment by jamesward** [comment]
The `bower.json` seems to only exist on master, but not on a tag.
