### ISSUE TITLE
Add webjar for expandjs-all

### ISSUE THREAD

**Issue by bcopy** [webjars/webjars#1559]
Hi @jamesward, 

Same treatment as Polymer All for the Expand JS webcomponents library.
Hopefully, this time, it should go without a hitch ( :crossed_fingers: )

https://github.com/bcopy/webjars-expandjs-all

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/expandjs-all

This will be released shortly.
