### ISSUE TITLE
Create webjar for ckeditor-wordcount

### ISSUE THREAD

**Issue by buckett** [webjars/webjars#1563]
There is a wordcount plugin for ckeditor: https://github.com/w8tcha/CKEditor-WordCount-Plugin/

which @jonespm original packaged up for Sakai, I've split it off here:

https://github.com/buckett/ckeditor-wordcount

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/ckeditor-wordcount

This will be released shortly.
