### ISSUE TITLE
Create ckeditor autosave plugin webjar

### ISSUE THREAD

**Issue by buckett** [webjars/webjars#1564]
Could you add 

https://github.com/buckett/ckeditor-autosave

to the webjars please, it's a packaging of

https://github.com/w8tcha/CKEditor-AutoSave-Plugin

and the NPM configuration in the upstream repository isn't complete enough.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/ckeditor-autosave

This will be released shortly.
