### ISSUE TITLE
License error with BSD-2-Clause when deploying

### ISSUE THREAD

**Issue by btmcnellis** [webjars/webjars#1569]
When trying to deploy the esprima package (3.1.0+), I get the following error:

```
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/jquery/esprima
The acceptable open source software licenses are at: https://bintray.com/docs/api/#_footnote_1
The provided licenses were: BSD-2-Clause
This problem will likely need to be resolved by working with the library maintainers directly.
```

However, `BSD-2-Clause` seems like it's a valid license type, and it's clearly specified in the project's `package.json`: https://github.com/jquery/esprima/blob/master/package.json#L36

**Comment by jamesward** [comment]
We were missing a synonym for `BSD-2-Clause` so I've added it and this change will be deployed in about 15 minutes.

**Comment by jamesward** [comment]
I've deployed `esprima` `3.1.3`.
