### ISSUE TITLE
Several NPM webjars disappeared

### ISSUE THREAD

**Issue by jclyons** [webjars/webjars#1573]
This morning, SBT can't resolve the following webjars:

[warn] 	:: org.webjars.npm#punycode;[1.4.1,2): not found
[warn] 	:: org.webjars.npm#har-validator;[4.2.1,4.3): not found
[warn] 	:: org.webjars.npm#tunnel-agent;[0.6.0,0.7): not found
[warn] 	:: org.webjars.npm#caseless;[0.12.0,0.13): not found

This is currently breaking our CI builds and we would appreciate it if this be resolved as soon as possible.

**Comment by jamesward** [comment]
It doesn't seem like those were ever deployed.  Can you try to deploy them: http://www.webjars.org/npm

**Comment by jclyons** [comment]
Ok, thanks! I published them.  Sorry for the impatience.

Looks like they are all transitive dependencies of jsdom - but we didn't change our version of jsdom. Could it be someone republished the same version of jsdom (7.0.2) with different point versions on the 'request' subdependency (looks like 2.55.0)?

**Comment by jamesward** [comment]
My guess is that some new version of a transitive dependency (that fit the range scope) changed it's transitive dependencies.  This is why ranges are bad.  But since NPM uses them, so do we.  :(
