### ISSUE TITLE
paginationjs nonexistent dependency

### ISSUE THREAD

**Issue by mdgeek** [webjars/webjars#1574]
The paginationjs webjar has a strange dependency that does not exist in Maven Central.  It looks to be a dependency on jquery, but is not formatted correctly:

        <dependency>
            <groupId>org.webjars.bower</groupId>
            <artifactId>github-com-components-jquery</artifactId>
            <version>[1.8.3,1.9)</version>
        </dependency>

**Comment by jamesward** [comment]
Unfortunately the `paginationjs` has a transitive dependency on something which can't be deployed because it doesn't have a `bower.json`.  So you will have to tell you package manager to exclude that transitive dependency.
