### ISSUE TITLE
Add classic webjar for jquery-corner

### ISSUE THREAD

**Issue by skotfred** [webjars/webjars#1575]
Version 2.13 is trunk at https://github.com/malsup/corner

**Comment by jamesward** [comment]
I don't see any tagged releases for that library.  We can still to a Classic WebJar but will have to use a commit hash.  That ok?

**Comment by skotfred** [comment]
Anything to get a usable webjar works for me, just trying to get some of these older libraries taken care of while they are still being used. Thanks

+1 (815) 556-9080

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/corner

This will be released shortly.
