### ISSUE TITLE
update webjar for jquery-text-counter to 0.6.0 version

### ISSUE THREAD

**Issue by g-gabber** [webjars/webjars#1576]
https://github.com/ractoon/jQuery-Text-Counter

Thanks in Advance

**Comment by jamesward** [comment]
This looks like a request for a new Classic WebJar because I can't find an existing Classic WebJar with that name.  Or are you using an NPM or Bower WebJar for this?

**Comment by g-gabber** [comment]
Npm would be nice.

**Comment by jamesward** [comment]
You can deploy NPM and Bower WebJars yourself: http://webjars.org/npm  http://webjars.org/bower

Let me know if you have any issues.
