### ISSUE TITLE
SBT/Maven version issue

### ISSUE THREAD

**Issue by VeryBueno** [webjars/webjars#1577]
Hello,
On [webjars.org/npm](http://www.webjars.org/npm), I added the [devextreme-angular](https://www.npmjs.com/package/devextreme-angular) npm package and it reported that deployment was successful. I also deployed its dependency, [@types/jquery](https://www.npmjs.com/package/@types/jquery) to webjars. However, when I spin up sbt, I get a `sbt.ResolveException: unresolved dependency: org.webjars.npm#types__jquery;[2.0.0,3),[3.0.0,4): not found` error.

I created a simple [sbt project that reproduces this issue](https://github.com/VeryBueno/webjar-version-issue). Its only dependency is the `devextreme-angular` package I deployed on the webjars site.

Could this be a problem with the npm package itself? The [metadata from npm](https://registry.npmjs.com/devextreme-angular/16.2.5) lists `"@types/jquery":"^2.0.0 || ^3.0.0"` as a dependency, which appears to be [valid syntax](https://docs.npmjs.com/misc/semver) and the [ webjar pom](https://bintray.com/webjars/maven/org.webjars.npm%3Adevextreme-angular#files/org/webjars/npm/devextreme-angular/16.2.5) translated it to maven-style `<version>[2.0.0,3),[3.0.0,4)</version>` which also seems to be valid syntax (please correct me if I'm wrong)

Do you have any tips? Thanks!

**Comment by jamesward** [comment]
Thanks for the detailed bug report!

This is due to a bug in sbt: https://github.com/sbt/sbt/issues/2647

You'll need to override the dependency tree to fix this, like: https://github.com/webjars/webjars/issues/1514#issuecomment-263515143

Sorry for the hassle.
