### ISSUE TITLE
Upgrade leaflet-markercluster to the latest release (1.0.4)

### ISSUE THREAD

**Issue by venky-git** [webjars/webjars#1578]
The latest version of leaflet-markercluster on webjars is 0.4.0. Number of changes has been added and the latest release is 1.0.4.  The releases are tagged here:
https://github.com/Leaflet/Leaflet.markercluster

**Comment by jamesward** [comment]
This will be released shortly.  In the future please file version bump requests on the actual WebJar, i.e. https://github.com/webjars/leaflet-markercluster
