### ISSUE TITLE
WebJar request: Google Maps canvas layer

### ISSUE THREAD

**Issue by linnando** [webjars/webjars#1583]
Please add a webjar for Google Maps canvas layer, developed by @brendankenny.

I have prepared a repo with maven build for a classic webjar: https://github.com/linnando/google-maps-canvas-layer

The upstream repository is located here: https://github.com/brendankenny/CanvasLayer

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/google-maps-canvas-layer

This will be released shortly.
