### ISSUE TITLE
webjar request: mindmup editable table

### ISSUE THREAD

**Issue by hdeadman** [webjars/webjars#1590]
Here is webjar project: https://github.com/hdeadman/editable-table

I am looking into converting another open source project to use webjars instead of CDN links. This editable table javascript file was being pulled from cdn.rawgit.com and I couldn't find a webjar for it so I made this one. Since the upstream github project didn't ever tag their repo, I used the sha for the version and pull it from cdn.rawgit.com. If that's not an acceptable version, that is fine, it probably makes sense to just copy the javascript into the other project. 

![image](https://cloud.githubusercontent.com/assets/1556777/26007522/d933e192-370e-11e7-9cd3-ce3ed5088643.png)

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/editable-table

This will be released shortly.
