### ISSUE TITLE
JSZIP can't deploy with dual license

### ISSUE THREAD

**Issue by erickjx** [webjars/webjars#1593]
Hi, 
jszip has dual license "MIT or GPLv3", but i can't deploy with New Bower WebJar, it fail with this message:

All attempts to determine an acceptable license have been exhausted.

The project file "bower.json" : 

{
  "name": "jszip",
  "homepage": "http://stuartk.com/jszip",
  "authors": [
    "Stuart Knightley <stuart@stuartk.com>"
  ],
  "description": "Create, read and edit .zip files with Javascript http://stuartk.com/jszip",
  "main": "dist/jszip.js",
  "keywords": [
    "zip",
    "deflate",
    "inflate"
  ],
  "license": "MIT or GPLv3",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}

**Comment by jamesward** [comment]
The syntax for the SPDX License Expression is invalid.  It should be: `(MIT OR GPLv3)`

Spec: https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60
