### ISSUE TITLE
NPM Publish fails with weird error message

### ISSUE THREAD

**Issue by BardurArantsson** [webjars/webjars#1604]
So I tried to publish version `0.0.4` of `amdefine` (written exactly like that in the form), and got this (form validation?) error:

```
Failed!
JsResultException(errors:List((/repository/url,List(ValidationError(List(error.path.missing),WrappedArray())))))
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: amdefine
Starting Deploy
```

**Comment by jamesward** [comment]
The problem is that the `package.json` doesn't specify the repo url: https://github.com/jrburke/amdefine/blob/0.0.4/package.json

This is required for Maven Central deployment.  But since it does specify a `homepage` maybe I can fallback to that.

**Comment by jamesward** [comment]
Ah shoot.  The value for `homepage` isn't valid.  So that isn't going to work.

**Comment by jamesward** [comment]
This comes up often.  So maybe I can add an additional deploy parameter that allows a manual repo to be specified.

**Comment by BardurArantsson** [comment]
Anything to allow for publishing such semi-broken artifacts would be great :).

(The artifact is in a long dependency chain which I have basically no control over because it's in a long dependency chain where I cannot upgrade the "head" dependency without huge amounts of work. I'm just wondering why it's stopped working -- I'm 99% sure the artifact has been resolvable up until a few days/weeks ago.)

**Comment by jamesward** [comment]
I've added the support for overriding the repo and successfully deployed `amdefine` `0.0.4` with the updated repo.  Right now this is only available to admins to prevent abuse.

**Comment by BardurArantsson** [comment]
Thanks!
