### ISSUE TITLE
Is it possible to require() webjar dependencies in a pure Java 8 Nashorn engine environment?

### ISSUE THREAD

**Issue by deinspanjer** [webjars/webjars#1605]
I'm looking for a way to be able to use npm modules inside a non-webapp Java application that executes Javascript using the Nashorn engine.

For simple modules such as underscore, lodash, or moment, I'd like to be able to just add them as a Maven dependency and then use them inside a compiled script via a simple require() call like `var moment = require('moment')`.  Is this possible?  I've read through all the different framework documentation on the webjars site, but it is all centered around making the webjars available to a web client which is making calls to a Java web application container.

Is this scenario also achievable?

**Comment by jamesward** [comment]
Yeah, that should be fine because the files are all available on the classpath so as long as Nashorn can load them from there, you should be good.

**Comment by deinspanjer** [comment]
Is there any chance you could share some simple example of how to do this in your documentation?

I tried several different forms of require, but the only way I was able to get a module to load was if it was a single file and just explicitly evaling it.

**Comment by jamesward** [comment]
I'm not familiar with how Nashorn does with module loading.  So unfortunately I can't help with this one.  Sorry.

**Comment by deinspanjer** [comment]
Thank you very much for your reply. :)
