### ISSUE TITLE
Update request: webcomponentsjs

### ISSUE THREAD

**Issue by dazraf** [webjars/webjars#1606]
Hi,

webjars version: 0.7.24
current version: 1.0.1

https://github.com/webcomponents/webcomponentsjs/blob/v1.0.1/package.json

thanks and regards,
Fuzz.

**Comment by jamesward** [comment]
This will be released shortly.  In the future please file version bumps on the actual WebJar repo, e.g. https://github.com/webjars/webcomponentsjs

**Comment by dazraf** [comment]
Thank you very much James. Sorry I missed the instructions before.

Do you think webjars can be automatically updated with new versions from upstream? Is this something that's been considered before?

**Comment by jamesward** [comment]
We considered it but have so far stuck with being demand-driven because we don't want to put GBs of unneeded artifacts on BinTray & Maven Central.  Also since users can deploy their own NPM & Bower WebJars the auto-updating hasn't been really necessary.
