### ISSUE TITLE
Unhelpful timeout error message creating NPM WebJar.

### ISSUE THREAD

**Issue by Jeff-Walker** [webjars/webjars#1608]
When trying to create a webjar jar from "https://github.com/winmarkltd/BootstrapFormHelpers.git", I get the message below. It's hard to tell what might be the problem, whether it's a local problem, or remote; GitHub, maven, BinTry, NPM, etc.

Maybe related: https://github.com/webjars/webjars/issues/1505

Great project, btw. Extremely useful.

```
Failed!
Request timeout to not-connected after 120000 ms
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Created BinTray Package
Created NPM WebJar
Fetched NPM tgz
Generated POM
Converted dependencies to Maven
Resolved Licenses
Got NPM info
Determined Artifact Name: github-com-winmarkltd-BootstrapFormHelpers
Starting Deploy
```

**Comment by jamesward** [comment]
I'm not sure what was causing the timeout.  But I've confirmed that the artifact was deployed.  So you should be good.

**Comment by Jeff-Walker** [comment]
Odd. I see it now. Thanks.
