### ISSUE TITLE
NPM publisher is creating extra 'package' folder

### ISSUE THREAD

**Issue by VeryBueno** [webjars/webjars#1610]
I used the "Add a WebJar" button to publish `@ng-bootstrap/ng-bootstrap` version 1.0.0-alpha.24.
It published the jar successfully, however it has an extra 'package' folder. My TypeScript compilation is failing to find ng-bootstrap and I believe the extra folder is causing it.

A version that was already published, [1.0.0-alpha.26](https://bintray.com/webjars/maven/org.webjars.npm%3Ang-bootstrap__ng-bootstrap/1.0.0-alpha.26#files/org/webjars/npm/ng-bootstrap__ng-bootstrap/1.0.0-alpha.26) has this structure:

```
META-INF/
├── maven
│   └── org.webjars.npm
│       └── ng-bootstrap__ng-bootstrap
│           ├── pom.properties
│           └── pom.xml
└── resources
    └── webjars
        └── ng-bootstrap__ng-bootstrap
            └── 1.0.0-alpha.26
                ├── [rest of files]

```

However, [the one I just published](https://bintray.com/webjars/maven/org.webjars.npm%3Ang-bootstrap__ng-bootstrap/1.0.0-alpha.24#files/org/webjars/npm/ng-bootstrap__ng-bootstrap/1.0.0-alpha.24) has this structure:

```
META-INF/
├── maven
│   └── org.webjars.npm
│       └── ng-bootstrap__ng-bootstrap
│           ├── pom.properties
│           └── pom.xml
└── resources
    └── webjars
        └── ng-bootstrap__ng-bootstrap
            └── 1.0.0-alpha.24
                └── package    <----------------------- where did this come from??
                    ├── [rest of files]
```

Thanks

**Comment by jamesward** [comment]
Ah crap.  A recent refactor broke this.

**Comment by jamesward** [comment]
The fix will be deployed shortly.  But I'm still not sure if it actually works to overwrite artifacts once deployed.  We can try it though.  I'll delete the version on BinTray.  Then I can do another deploy.

**Comment by VeryBueno** [comment]
Thanks for your quick response! 
Earlier today I tried re-deploying the same version but it failed uploading because the artifact already existed. So could you please delete [tether 1.3.9](https://bintray.com/webjars/maven/org.webjars.npm%3Atether/1.3.9#files/org/webjars/npm/tether/1.3.9) and [ng-bootstrap__ng-bootstrap 1.0.0-alpha.24](https://bintray.com/webjars/maven/org.webjars.npm%3Ang-bootstrap__ng-bootstrap/1.0.0-alpha.24)? Thank you!

**Comment by jamesward** [comment]
Those have been redeployed to BinTray.  If it works to overwrite these on Maven Central, it'll take a few hours.  Let me know how it goes!  Sorry for the hassle!

**Comment by VeryBueno** [comment]
All is right in the universe once more. The packages work now. Thanks!
