### ISSUE TITLE
Error creating Webjar for node-occ

### ISSUE THREAD

**Issue by NarendraPatwardhan** [webjars/webjars#1611]
For a project using scala-js I require 3 webjars : Threejs, Verb-Nurbs and Node-occ. Out of the the 3, Threejs was already available so I decided to request deploying other two.
At the first pass, I requested deploying node-occ, which after signing BinTray Version timed out after 120000 ms and resulted in a failure. So I tried the same with Verb-nurbs which succeeded. After that when I tried to deploy node-occ again I receieved following error:
"Failed!
Unable to upload files: An artifact with the path 'org/webjars/npm/node-occ/0.2.0/node-occ-0.2.0.pom' already exists"

**Comment by jamesward** [comment]
A recent refactor made redeploying existing artifacts not work.  So I need to fix that.  In the meantime I've attempted to redeploy the one that failed.

**Comment by NarendraPatwardhan** [comment]
Thank you for such a quick and effective reply.
Greatly appreciate the work you are doing!
