### ISSUE TITLE
How to make the webjar searchable in webjar.org?

### ISSUE THREAD

**Issue by hyphenman2010** [webjars/webjars#1613]
Hi,

Not sure if this is the right place to answer this question. I am completely new to webjar.
I have deployed a bower webjar:

Deployed!
It will take a few hours for the Maven Central index to update but you should be able to start using the Bower WebJar now.
GroupID = org.webjars.bower
ArtifactID = ngInput
Version = 0.0.10
...
...
Starting Deploy

hours later, I am able to see the jar file in maven central, ans works with sbt-webjar/PLAY
However, it is not listed in webjar.org, any idea?

github: https://github.com/hyphenman2010/ngInput

**Comment by hyphenman2010** [comment]
Hi James,

Thx for the reply but it has been 2 days after the deploy to maven, any idea why not listed in webjars.org?

**Comment by jamesward** [comment]
Ah.  You've discovered a bug!  Recently we added the support for popularity to the WebJars index.  I think that newly deployed artifacts are no longer showing up because we don't have any statistics for them.

**Comment by jamesward** [comment]
This fix has been deployed.
