### ISSUE TITLE
React DnD Failing

### ISSUE THREAD

**Issue by 0xfaded** [webjars/webjars#1616]
Hi, the below are package uploads are failing.

```
"org.webjars.npm" % "react-dnd" % "2.4.0"
"org.webjars.npm" % "react-dnd-html5-backend" % "2.4.0"
```
 Thank you for your work maintaining webjars

```
Failed!
JsResultException(errors:List((,List(ValidationError(List(Predicate does not hold for https://www.npmjs.com/package/react-dnd),WrappedArray()))), (/repository/url,List(ValidationError(List(error.path.missing),WrappedArray())))))
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
```

**Comment by jamesward** [comment]
This is related to #1604.  But I think I need to do something different with the default that is being provided here `https://www.npmjs.com/package/react-dnd` and provide a better error message.

**Comment by jamesward** [comment]
With #1604 fixed I've deployed those NPM WebJars.  Let me know if you have any issues.
