### ISSUE TITLE
Optional npm Dependencies

### ISSUE THREAD

**Issue by mckoon** [webjars/webjars#1618]
### Proposal
npm optional dependencies translate to optional dependencies in the webjar's pom.xml file.

### Workaround
Exclude all transitive dependencies for webjars, and manage them all manually.

### References:
npm optional dependencies: https://docs.npmjs.com/files/package.json#optionaldependencies

maven optional dependencies: https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

### Example of issue
The linkifyjs library has a [package.json](https://github.com/SoapBox/linkifyjs/blob/v2.1.4/package.json) with an optional dependency on the latest version of react:

```
"optionalDependencies": {
    "jquery": ">=1.9.0",
    "react": ">=0.14.0",
    "react-dom": ">=0.14.0"
  }
```

The generated pom file in the org.webjars.npm:linkifyjs webjar contains this:

```
    <dependencies>

        <dependency>
            <groupId>org.webjars.npm</groupId>
            <artifactId>jquery</artifactId>
            <version>[1.9.0,)</version>
        </dependency>

        <dependency>
            <groupId>org.webjars.npm</groupId>
            <artifactId>react</artifactId>
            <version>[0.14.0,)</version>
        </dependency>

        <dependency>
            <groupId>org.webjars.npm</groupId>
            <artifactId>react-dom</artifactId>
            <version>[0.14.0,)</version>
        </dependency>

    </dependencies>
```

Now there is a webjar for react 16.0.0-alpha.12. It depends on a webjar for fbjs 0.9.0-alpha.2, which depends on a webjar for org.webjars.npm:fbjs-css-vars with a range [1.0.0,2), which does not exist.

This causes a maven build to fail, unless explicit exclusions are added:

```
[ERROR] No versions are present in the repository for the artifact with a range [1.0.0,2)
[ERROR] org.webjars.npm:fbjs-css-vars:jar:null
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR] <REDACTED>
[ERROR] Path to dependency:
[ERROR] 1) <REDACTED>
[ERROR] 2) <REDACTED>
[ERROR] 3) <REDACTED>
[ERROR] 4) <REDACTED>
[ERROR] 5) org.webjars.npm:linkifyjs:jar:2.1.4
[ERROR] 6) org.webjars.npm:react:jar:16.0.0-alpha.12
[ERROR] 7) org.webjars.npm:fbjs:jar:0.9.0-alpha.2
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/OverConstrainedVersionException
```

All this for an *optional* dependency; a dependency I don't even intend to use.

There are workarounds, and a lot of the issues in this case come from too liberal version range dependencies. However, I think that perhaps generated webjars should retain npm optional dependencies as maven optional dependencies in webjars going forward.

Thoughts?

**Comment by jamesward** [comment]
Arggg...  So the NPM repo mucks with the `package.json` and makes `optionalDependencies` also `dependencies`: https://registry.npmjs.org/linkifyjs/2.1.4

So this becomes more painful.  I think we'll have to remove the duplication in our metadata parsing.  I think we have to use the registry provided `package.json` because it contains some other stuff we need.

**Comment by jamesward** [comment]
I've redeployed `linkifyjs` version `2.1.4` with this fix and it worked: https://bintray.com/webjars/maven/download_file?file_path=org%2Fwebjars%2Fnpm%2Flinkifyjs%2F2.1.4%2Flinkifyjs-2.1.4.pom

This will take a few hours to sync to Maven Central.

**Comment by mckoon** [comment]
Thanks for the quick response. I think honoring optional dependencies is a good change.

FYI - maven central still uses the old one (at least it does now --17 hours after your comment): http://repo1.maven.org/maven2/org/webjars/npm/linkifyjs/2.1.4/linkifyjs-2.1.4.pom

**Comment by jamesward** [comment]
Strange... It seems that sometimes a redeploy overwrites Maven Central and sometimes not.  Which is a bad practice anyhow.  So maybe I need another solution.  Right now artifacts are overwritten on redeploy.  It'd be better to bump version numbers.  In this case the artifact would be `2.1.4-1` but there are probably cases where that doesn't work with automatic transitive stuff.  WDYT?

**Comment by jamesward** [comment]
This would be a general change for all redeploys so I need to think about this for more than just this use case.  But I think I need to make this change since releases are supposed to be immutable (for build reproducibility).

Note: I should probably add UI in the deployment form that lets a user know if something has already been deployed.

**Comment by jamesward** [comment]
I've deployed the patch version that fixes this:
```
GroupID = org.webjars.npm
ArtifactID = linkifyjs
Version = 2.1.4-1
```
