### ISSUE TITLE
Missing jquery-csv

### ISSUE THREAD

**Issue by reggert** [webjars/webjars#1621]
The jquery-csv library, despite being available via NPM and Bower, is not available as a WebJAR.

**Comment by jamesward** [comment]
WebJars are published on-demand, not automatically.  You can publish NPM & Bower WebJars on your own though: http://webjars.org

**Comment by reggert** [comment]
Ah. I did not realize that.

However, trying to publish the NPM package results in the following:
```
Failed!
Package for path 'webjars/maven' was invalid
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Created NPM WebJar
Fetched NPM zip
Generated POM
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Got NPM info
Determined Artifact Name: jquery-csv
Deploying org.webjars.npm jquery-csv 0.8.3
Starting Deploy
```

**Comment by reggert** [comment]
Publishing the Bower package worked.

**Comment by jamesward** [comment]
That looks like a transient issue with BinTray.
