### ISSUE TITLE
Deploy indexof npm module as special case, even though missing repo url

### ISSUE THREAD

**Issue by 0xfaded** [webjars/webjars#1622]
Hello again,

`indexof` is a ridiculously popular browser shim that, because it lacks a repo url, prevents many other modules from being used. It is MIT, downloaded 1/4 million times a day, and has never had a version bump (still at 0.0.1).

issues #1244 #1318 and #1366 all pertain to this package.

I'm wondering if it would be possible to special case this package and manually deploy it as an npm module since it has so many dependencies.

https://www.npmjs.com/package/indexof

Thank you

```
Deploy Log

Failed!
The metadata was missing a required field: /repository/url
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: indexof
Deploying org.webjars.npm indexof 0.0.1
Starting Deploy
```

**Comment by jamesward** [comment]
Thanks for bringing this up!  I recently added a way to override the repo url to work around these issues.  So I'm deploying `indexof` `0.0.1` now.

**Comment by 0xfaded** [comment]
Thank you
