### ISSUE TITLE
Cannot deploy due to read timeout on bintray.com after 120000 ms

### ISSUE THREAD

**Issue by LuigiPeace** [webjars/webjars#1628]
Hi,

I've been deploying three npm webjars with success on WebJars.org.
Now I need to continue deploying more libraries (polymer-bundler require some dependencies not currently available).
Deployment end-up with this following error:

> Failed!
> Read timeout to bintray.com/108.168.194.93:443 after 120000 ms
> If you feel you have reached this failure in error, please file an issue: 
> https://github.com/webjars/webjars/issues

Everything else is fine in the logs when deploying... I'm wondering why I get this error.
Is there a limit of deployment by IP address and/or time delay between deployments?

Thanks in advance, WebJars is an awesome tool!

**Comment by jamesward** [comment]
Yeah, I've been seeing these timeouts lately. I'm not sure what the cause is.  If you keep trying it will eventually work.  Sucks.  I'll file a support issue with BinTray.

**Comment by LuigiPeace** [comment]
Ok nice, let's brut force... Thank you for the support issue.

**Comment by jamesward** [comment]
Can you try again?  I think BinTray has resolved their issue.

**Comment by epot** [comment]
I can still see occurrences of this issue today :(.

**Comment by LuigiPeace** [comment]
I tried again and it is the same as for epot, occurrences of this issue too.

**Comment by jamesward** [comment]
This morning it seems like Maven Central is having issues.

**Comment by LuigiPeace** [comment]
Did some deployments today, everything seems fine.

**Comment by namKolo** [comment]
Hi
It seems like the issue happens again :( I tried a lot ~15 times to deploy a new version 
![image](https://user-images.githubusercontent.com/16164170/28708530-ca6e3624-73a6-11e7-90fb-4020943f851c.png)
Are there anyone here meet that issue ?

**Comment by jamesward** [comment]
Looks like we broke BinTray again.  I filed a support request.

**Comment by jamesward** [comment]
@namKolo This should be fixed.

**Comment by LuigiPeace** [comment]
Thank you for the support request. I was able to add some dependencies without facing this issue.

**Comment by karuniko** [comment]
This issue is back on track again.
Failed with the same error today :-1: 
Failed!
Read timeout to bintray.com/75.126.118.184:443 after 120000 ms
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

**Comment by jamesward** [comment]
I noticed that Maven Central deployment was flapping today.  This is becoming common enough that I might need to add some auto-retry.

**Comment by swatifursule** [comment]
I tried twice today morning for deploying angular-mocks and angular-touch bower webjars. 
What needs to be done?

![screen shot 2017-11-29 at 10 24 45 am](https://user-images.githubusercontent.com/20913905/33349778-bd481c30-d4ef-11e7-8a68-ac48fa968437.png)

**Comment by jamesward** [comment]
@swatifursule It looks like Maven Central deployment wasn't working at that time but is now.  I've deployed those two Bower WebJars.
