### ISSUE TITLE
Unable to resolve dependency with version 0

### ISSUE THREAD

**Issue by btmcnellis** [webjars/webjars#1632]
While trying to resolve JSCS 3.0.7, I've been getting the following error:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.webjars.npm#jsonlint;[1.6.2,1.7): not found
[warn] 	:: org.webjars.npm#deep-equal;0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.webjars.npm:jsonlint:[1.6.2,1.7)
[warn] 		  +- org.webjars.npm:jscs:3.0.4 (/Users/bmcnellis/application/project/plugins.sbt#L27-28)
[warn] 		  +- default:application-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 		org.webjars.npm:deep-equal:0
[warn] 		  +- org.webjars.npm:utile:[0.2,0.3)
[warn] 		  +- org.webjars.npm:prompt:[0.2.14,0.3)
[warn] 		  +- org.webjars.npm:jscs:3.0.4 (/Users/bmcnellis/application/project/plugins.sbt#L27-28)
[warn] 		  +- default:application-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
```

The `jsonlint` error is easy to fix by publishing locally, since that just needs a proper license in its `package.json`. 

But the `deep-equal` error seems like a bug to me. The `deep-equal` dependency is brought in by a (pointless) package called `utile`, which for some reason has a wildcard for the version in its `package.json`: https://github.com/flatiron/utile/blob/v0.2.1/package.json#L15

There's already a version `0.0.0` of `deep-equal` that's been published, but for some reason sbt is trying to resolve version `0` and so it's failing.

**Comment by jamesward** [comment]
Interesting... Two things:
1. I need to make it possible to manually deploy `jsonlint` with the right license.
2. I think the `*` NPM version range should have been converted to something like `(,)` or whatever the Maven equivalent of *any version* is.

So thanks for reporting this.  I'll work on some fixes.

**Comment by jamesward** [comment]
Ah, so for 2 the `*` did get converted correctly: https://repo1.maven.org/maven2/org/webjars/npm/utile/0.2.1/utile-0.2.1.pom

But maybe for some reason `[0,)` doesn't resolve to `0.0.0` in sbt?  I remember issues with sbt's range handling and there being an open issue for this.

**Comment by jamesward** [comment]
I can't find the sbt issue.  So I think you should file one and override the transitive version of `org.webjars.npm#deep-equal` to work around this for now.

**Comment by jamesward** [comment]
Using the new manual license override I've deployed `jsonlint` `1.6.2`.
