### ISSUE TITLE
Redoc webjar unresolved dependencies

### ISSUE THREAD

**Issue by likern** [webjars/webjars#1633]
I have deployed `redoc` webjar version `1.16.1` and it deployed successfully.
But the problem is that it has as dependency `lunr` version `1.0.0` - http://repo1.maven.org/maven2/org/webjars/npm/redoc/1.16.1/redoc-1.16.1.pom.
While I tried to deploy that version of webjar - it looks like it has different `artifactId` - `github-com-olivernn-lunr-js`, instead of `lunr`.
And now I get
```sbt
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.webjars.npm#lunr;1.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.webjars.npm:lunr:1.0.0
[warn] 		  +- org.webjars.npm:redoc:1.16.1 (/home/vamalov/Projects/printing/build.sbt#L22-42)
[warn] 		  +- printing:printing_2.12:dev-local
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: org.webjars.npm#lunr;1.0.0: not found
[error] Total time: 3 s, completed Jul 26, 2017 4:59:50 PM
```

**Comment by jamesward** [comment]
I just deployed `lunr` `1.0.0` - if you specify a Git URL then it uses that for the artifact name.  If you specify an NPM artifact name, then it uses the name.  This is to deal with NPM deps that specify a Git repo instead of an NPM artifact.
