### ISSUE TITLE
Failed deploy for https://github.com/Turfjs/turf

### ISSUE THREAD

**Issue by sshikov** [webjars/webjars#1639]
Both npm and bower webjars failed when only github url and version specified.

Not sure this is an issue because I'm able to deploy it using npm package name instead of github url.

**Comment by jamesward** [comment]
What is the error?

**Comment by gruneldjoe** [comment]
Here is the error I received when attempting to deploy as https://github.com/ptv-logistics/Leaflet.NonTiledLayer as NPM type:

> Failed!
> /tmp/git3185819699942472601/https:/github.com/ptv-logistics/Leaflet.NonTiledLayer/package.json (No such file or directory)
> If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
> 
> Determined Artifact Name: github-com-ptv-logistics-Leaflet-NonTiledLayer
> Deploying org.webjars.npm https://github.com/ptv-logistics/Leaflet.NonTiledLayer v0.7.3
> Starting Deploy

**Comment by jamesward** [comment]
It looks like the `package.json` isn't on that tag: https://github.com/ptv-logistics/Leaflet.NonTiledLayer/tree/v0.7.3

So this deployment won't work with the NPM WebJar deployer.  We can do a Classic Webjar instead.
