### ISSUE TITLE
New WebJar request AdminBSBMaterialDesign

### ISSUE THREAD

**Issue by diegobmd** [webjars/webjars#1640]
I would like to contrib with a new webjar for project [AdminBSBMaterialDesign](https://github.com/gurayyarar/AdminBSBMaterialDesign)

https://github.com/diegobmd/AdminBSBMaterialDesign

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/AdminBSBMaterialDesign

This will be released shortly.
