### ISSUE TITLE
can't deploy web jar for babel-types 6.24.1

### ISSUE THREAD

**Issue by mike-kukla** [webjars/webjars#1643]
I'm trying to deploy a new webjar (npm)   for babel-types 6.24.1
But the attempt errors out.  Here's the deploy log: 

https://github.com/babel/babel/tree/master/packages
Failed!
The metadata was missing a required field: /version
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: github-com-babel-babel
Deploying org.webjars.npm https://github.com/babel/babel v6.24.1
Starting Deploys

**Comment by mike-kukla** [comment]
Sorry,  I lear

**Comment by mike-kukla** [comment]
Never mind! I just used the package name rather than the git-hub URL and the deploy worked like a charm. Thanks for this truly A-1 service!

**Comment by jamesward** [comment]
Great!
