### ISSUE TITLE
sbt unable to resolve npm webjar with version gaps

### ISSUE THREAD

**Issue by btmcnellis** [webjars/webjars#1644]
I'm trying to add a package that includes the `semver` package as one of its transitive dependencies. `semver` is pulled in by `normalize-package-data` in the following line:

https://github.com/npm/normalize-package-data/blob/6ba494919aa5f8aa7bb2881a136eefbd04b9d141/package.json#L18

This version is translated to `[2,3),[3,4),[4,5),[5,6)`, which seems reasonable. However, Ivy, unlike Maven, doesn't seem to support multiple version ranges, and it tries to download the package from the URL https://dl.bintray.com/webjars/maven/org/webjars/npm/semver/[2,3),[3,4),[4,5),[5,6)/semver-[2,3),[3,4),[4,5),[5,6).pom which clearly won't work.

Any help would be greatly appreciated.

**Comment by btmcnellis** [comment]
On further investigation, this seems to be due to sbt's issues with version ranges: https://github.com/sbt/sbt/issues/2647

**Comment by jamesward** [comment]
Glad you found the sbt issue!  In the meantime I think you can workaround this by overriding the dependency info in your `build.sbt` - let me know if you need help with that.
