### ISSUE TITLE
Naming NPM webjars

### ISSUE THREAD

**Issue by morpheus-87** [webjars/webjars#1646]
Is it possible to define the artifactid for a NPM webjar?

**Comment by jamesward** [comment]
This is related to #1629.  At this point, no.  What is your use case?

**Comment by morpheus-87** [comment]
It's nearly the same use case. I have a npm package named `@dbmdz/mirador-canvaslink` and the corresponding artifactid of the webjar is `dbmdz__mirador-canvaslink`. Is there any reason, why the slash is converted to a double underscore? In my opinion, that looks totally weird. I would prefer a hyphen.

**Comment by jamesward** [comment]
We needed some convention that attempts to avoid possible collisions.  There could be an NPM package named `dbmdz-mirador-canvaslink` which would then conflict with the `@dbmdz/mirador-canvaslink` package.  The double underscore has the same potential but seems less likely.  I'm going to close this as a duplicate and think more about what options we might have.

**Comment by morpheus-87** [comment]
Would it be possible to skip the orgname in the name of the directory?

**Comment by jamesward** [comment]
There actually needs to be a 1:1 mapping between the artifact id and the dir name.

**Comment by morpheus-87** [comment]
What is the reason for that?

**Comment by jamesward** [comment]
webjars-locator has some methods that locate assets given an artifact id.  So if we change the convention then that stuff would break.
