### ISSUE TITLE
systemjs-plugin-css

### ISSUE THREAD

**Issue by mdgeek** [webjars/webjars#1649]
Since version 0.1.32, the systemjs-plugin-css webjar contents does not make sense.  The directory structure has completely changed and, for example, the main file, css.js is no longer present.

**Comment by jamesward** [comment]
It looks like you are referring to the NPM WebJar.  These WebJars are generated from the NPM modules.  We don't have any control over what goes into them.  If you want something custom then create a Classic WebJar: http://www.webjars.org/contributing

**Comment by mdgeek** [comment]
This kind of response is frustrating.  I am really trying to be an advocate of webjars, but it is difficult when stability is such a problem.  I don't see any change in that project that should cause such severe breakage in the resulting webjar.  However, if this is the response that I can expect when reporting such anomalies, I will refrain from reporting them in the future.

**Comment by jamesward** [comment]
I understand your frustration but ultimately NPM WebJars are at the will of the NPM publishers.  To have more control over the packaging, Classic WebJars are the way to go.  I'd be happy to help you create a Classic WebJar.  To get the process started, got to http://webjars.org and click the *Add a WebJar* button.
