### ISSUE TITLE
Failed to deploy because of transitive dependency

### ISSUE THREAD

**Issue by nymanjens** [webjars/webjars#1652]
Exact error message that I get when trying to add the newest version (2.4.0) to `dnd-core`:

```
Failed!
The metadata was missing a required field: /repository/url
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Determined Artifact Name: dnd-core
Deploying org.webjars.npm dnd-core 2.4.0
Starting Deploy
```

The reason I tried this is because I'm relying on `react-tag-input` 3.0.0 ([package.json](https://cdn.jsdelivr.net/webjars/org.webjars.npm/react-tag-input/3.0.0/package.json)) which relies on `react-dnd` ^2.0.2 ([package.json of 2.0.2](https://cdn.jsdelivr.net/webjars/org.webjars.npm/react-dnd/2.0.2/package.json)) which relies on `dnd-core` ^1.2.2 [(package.json of 1.2.2)](https://cdn.jsdelivr.net/webjars/org.webjars.npm/dnd-core/2.0.2/package.json).

However, when using this library, sbt complains that `dnd-core` 2.4.0 could not be found ([see error](https://pastebin.com/raw/73xHvcPw)). IMO this is weird in 2 ways:
* An older version is allowed
* It doesn't look like a genuine dependency because [this working example](http://prakhar1989.github.io/react-tags/example/) only relies on `ReactTags.min.js` (`react-tag-input`) and `ReactDnD.min.js` (`react-dnd`).

**Comment by jamesward** [comment]
I've manually deployed `dnd-core` `2.4.0` using the source url of: `https://github.com/react-dnd/react-dnd`

I think that should resolve this but let me know if you still have issues.

**Comment by nymanjens** [comment]
I retried it and it works! Thanks!
