### ISSUE TITLE
Webjar update request: vuetify

### ISSUE THREAD

**Issue by bmhm** [webjars/webjars#1655]
Source: 
https://github.com/vuetifyjs/vuetify

What exists:
* 'org.webjars.npm:github-com-vuetifyjs-vuetify:0.12.7'
* NPM
* v0.12.7

What I'd like to request:
* 'org.webjars.bower:vuetifyjs-vuetify:0.15.7'
* bower
* v0.15.7

Haven't found any vuetify-Package on bower, however.

**Comment by jamesward** [comment]
It doesn't look like that package exists in Bower.  In that case we can't publish a Bower WebJar for this.
