### ISSUE TITLE
Invalid Bower webjar version if bower.json doesn't declare a version

### ISSUE THREAD

**Issue by Legioth** [webjars/webjars#1656]
Looking at the Bower WebJars available for `github-com-polymer-polymer`, it seems like the packages for versions 2.x have an additional `v` in the beginning of the Maven version number. This makes Maven consider the 1.x versions to be newer than the 2.x versions, and completely excludes the 2.x versions from version ranges.

I suspect that the cause for this difference is that the Polymer project no longer includes the version number in their `bower.json`. If the version number is not declared there, the WebJars packaging logic seems to fall back to using the tag name instead. The version number field is deprecated in the bower specification: https://github.com/bower/spec/blob/master/json.md#version.

I see two ways of solving this:
1. Strip a leading `v` from the Git tag if the rest of the string follows a conventional version number pattern
2. Use the version number from `package.json` as fallback when available

**Comment by jamesward** [comment]
I think that when specifying a Git-based dependency, the version must be a tag in the git repo.  But when specifying a Bower artifact dependency the version must be a version deployed on Bower.  Not totally sure about that though.  Can you provide an example where this is the case and we can investigate how Bower is handling the resolution.

**Comment by Legioth** [comment]
The other day, I pushed the `v2.0.0-alpha1` tag to `https://github.com/vaadin/vaadin-core`. The same content was immediately available in several different ways:
* `bower install https://github.com/vaadin/vaadin-core.git#2.0.0-alpha1` 
* `bower install vaadin/vaadin-core#2.0.0-alpha1`
* `bower install vaadin-core#2.0.0-alpha1` (works because we have registered the repository as `vaadin-core` in the Bower registry, but no registration was done specifically for this version)
* `bower install vaadin-core-elements#2.0.0-alpha1` (previously also registered with this name)

In all cases, using `#v2.0.0-alpha1` and `#2.0.0-alpha1` has the same effect. Bower automatically looks for a tag with a `v` prefix added even if entering `#2.0.0-alpha1`. When installing, Bower reports the version without the `v` prefix even if using the `#v2.0.0-alpha1` form. This can also be seen by inspecting the difference between the original `bower.json` in `bower_components/vaadin-core/bower.json` and Bower's own metadata file in `bower_components/vaadin-core/.bower.json`. The latter still contains a version number even though the former doesn't have one.

**Comment by jamesward** [comment]
So it sounds like I'm wrong and it is the version in the `bower.json` that should never be used.  But the git tag is always consistent with the `v`-less version in a dependency definition.  In this case could also always use the `v`-less versions in the poms.

**Comment by bartolom** [comment]
We also stumbled upon this https://github.com/Polymer/polymer/issues/4794 and a commenter there pointed out that `version` was deprecated in bower https://github.com/bower/spec/blob/master/json.md#version 

Therefore this seem to be valid from a JavaScript / Bower point of view and they closed the ticket. But affects Java build tool like Gradle

**Comment by Legioth** [comment]
I just realized that you only get the invalid version number for when generating a WebJar based on the longer GitHub URL but not when creating one based on the shorted Bower registry name. As an example, compare the versions available for https://bintray.com/webjars/maven/org.webjars.bower%3Avaadin-grid and https://bintray.com/webjars/maven/org.webjars.bower%3Agithub-com-vaadin-vaadin-grid. 

Potentially related is also the fact that 4.0.0-alpha5 for `vaadin-grid` contains 46 files whereas `github-com-vaadin-vaadin-grid` contains 122 files. I would guess that the `ignore` section of `bower.json` wasn't taken into account when generating the latter?

**Comment by SomeoneToIgnore** [comment]
Hey, I've created the PR fixing the issue, feedback is welcome :)

**Comment by jamesward** [comment]
Fixed via #1702
