### ISSUE TITLE
graceful-readlink 1.0.0 npm webjar deploy failed

### ISSUE THREAD

**Issue by danoliv** [webjars/webjars#1658]
Failed!
{"status":"Validation Failed","messages":"[Invalid POM: /org/webjars/npm/graceful-readlink/1.0.0/graceful-readlink-1.0.0.pom: SCM URL missing, Dropping existing partial staging repository.]"}
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Published BinTray Version
Signed BinTray Assets
Published BinTray Assets
Created BinTray Version
Created BinTray Package
Created NPM WebJar
Fetched NPM zip
Generated POM
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Got NPM info
Determined Artifact Name: graceful-readlink
Deploying org.webjars.npm graceful-readlink 1.0.0
Starting Deploy

**Comment by jamesward** [comment]
This is because the required metadata is not available on that version of the package.  But it was added for `1.0.1`: https://github.com/zhiyelee/graceful-readlink/commit/f6655275bebef706fb63fd01b5f062a7052419a5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Can you try to deploy that version instead?
