### ISSUE TITLE
graceful-readlink 1.0.1 npm deploy failed

### ISSUE THREAD

**Issue by danoliv** [webjars/webjars#1659]
Failed!
{"status":"Sync Failed","messages":"[Failed to close repository: orgwebjars-33518. Server response:\n <nexus-error>\n  <errors>\n    <error>\n      <id>*<\u002fid>\n      <msg>Unhandled: Repository: orgwebjars-33518 has invalid state: closed<\u002fmsg>\n    <\u002ferror>\n  <\u002ferrors>\n<\u002fnexus-error>, Dropping existing partial staging repository.]"}
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
          
Published BinTray Version
Signed BinTray Assets
Published BinTray Assets
Created BinTray Version
Created BinTray Package
Created NPM WebJar
Fetched NPM zip
Generated POM
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Got NPM info
Determined Artifact Name: graceful-readlink
Deploying org.webjars.npm graceful-readlink 1.0.1
Starting Deploy

**Comment by jamesward** [comment]
This was a transient issue with Maven Central.  I've manually deployed this and it seems to have worked correctly.
