### ISSUE TITLE
Create a new version of crlcu-multiselect is not showing the correct versions

### ISSUE THREAD

**Issue by ncelerier** [webjars/webjars#1663]
Hello, 

I would like to create a new version for crlcu-multiselect, but it looks like the versions are not correct. 

How to reproduce: 
- Type select in the search box ;
- There are multiple "multiselect", try to add a new version for crlcu-multiselect.
- You can only see version from 0.9.1. to 0.9.12, whereas crlcu-multiselect has version such as 2.3.11 or 2.4.0 (currently the latest that I would like to use as webjars). 

Can you help me on this one ? It is looking like a bug. I think it is using another git repository (https://github.com/lou/multi-select/releases) than the crlcu-multiselect repository because crclu-multiselect doesn't have release such as 0.9.x. (see the first releases of the project: https://github.com/crlcu/multiselect/releases?after=v2.1.3).

Thank you for your help !

**Comment by jamesward** [comment]
The `"org.webjars.bower" % "github-com-crlcu-multiselect"` WebJar is deployed via Bower WebJars and the git repo.  You can add the version you need on http://webjars.org by clicking the *Add a WebJar* button and then selecting Bower and entering the git repo `https://github.com/crlcu/multiselect.git` then select the version you need and deploy it.
