### ISSUE TITLE
Ignore section from bower.json is ignored for WebJars created based on a GitHub URL

### ISSUE THREAD

**Issue by Legioth** [webjars/webjars#1664]
As noted in https://github.com/webjars/webjars/issues/1656#issuecomment-339114944, there seems to be a difference in WebJar contents depending on whether it has been generated based on the short Bower registry name or the longer GitHub URL.

`github-com-vaadin-vaadin-grid` contains files such as `.npmignore` and `test/filtering.html` even though the corresponding `bower.json` has ignores for `**/.*` and `**/test`. Those files are not present in the `vaadin-grid` WebJar.

The expected result is the one in `vaadin-grid`, since this set of files matches what you would get by doing either `bower install vaadin-grid#4.0.0-alpha5` or `bower install vaadin/vaadin-grid#4.0.0-alpha5`.

**Comment by jamesward** [comment]
Anyone know how Bower resolves `4.0.0-alpha5` to `v4.0.0-alpha5` when using a GitHub repo instead of a Bower artifact?  Do they just try what was specified and then fallback to prepending a `v` ?

**Comment by Legioth** [comment]
I don't think Bower makes any difference between a GitHub repo or a Bower name since the Bower name is simply an alias to a GitHub URL.

In either case, my observation is that Bower finds the intended version regardless of whether the GitHub repository has `v` prefixes in version number tags. I would guess that it's hardcoded to look for both variants (but hopefully only for definitions that parse according to semver rules to avoid looking for a tag named `vfoo` if doing `bower install package#foo`).

**Comment by jamesward** [comment]
Fixed here: https://github.com/webjars/webjars/compare/wip-bower-new#diff-8e2d27bf629e02be090dda3d0e2a02e4R78
And here: https://github.com/webjars/webjars/compare/wip-bower-new#diff-8e2d27bf629e02be090dda3d0e2a02e4R92

But not fixed yet for `NPM` and `Bower`

**Comment by jamesward** [comment]
Fixed via #1702
