### ISSUE TITLE
Bower webjar deployed with wrong license

### ISSUE THREAD

**Issue by Artur-** [webjars/webjars#1666]
https://github.com/Artur-/highcharts-dist-test/tree/v6.0.2 contains a `bower.json` with `  "license": "license.txt"`, referring to the `license.txt` in the project: https://github.com/Artur-/highcharts-dist-test/blob/v6.0.2/license.txt. 

If you deploy this through webjars.org, you end up with http://repo1.maven.org/maven2/org/webjars/bower/github-com-Artur--highcharts-dist-test/6.0.2/github-com-Artur--highcharts-dist-test-6.0.2.pom, saying that the license is 
```
<license>
<name>WTFPL</name>
<url>https://spdx.org/licenses/WTFPL#licenseText</url>
<distribution>repo</distribution>
</license>
```

That's not right

**Comment by Artur-** [comment]
Expected would be that the license section contains "custom" or some other name with the URL referring to the file set in `bower.json`

**Comment by jamesward** [comment]
Thanks for reporting this.  It is due to a false positive in https://github.com/jamesward/oss-license-detector  I'll investigate.

**Comment by jamesward** [comment]
This now works as expected: https://github-license-service.herokuapp.com/Artur-/highcharts-dist-test

But the problem is that you won't be able to deploy it via WebJars because BinTray requires open source licenses.  So you'll have to use the Classic WebJars for this.
