### ISSUE TITLE
WebJars service should lowercase urls accepted for deployment

### ISSUE THREAD

**Issue by SomeoneToIgnore** [webjars/webjars#1668]
When using GitHub urls to deploy new WebJars, case matters currently:

* https://github.com/PolymerElements/iron-elements produces artifact with id `github-com-PolymerElements-iron-elements`
* https://github.com/polymerelements/iron-elements produces artifact with id `github-com-polymerelements-iron-elements`

Note: both urls are valid and GitHub resolves both to the same repository.

<img width="1676" alt="screen shot 2017-11-01 at 11 26 59" src="https://user-images.githubusercontent.com/2690773/32266226-9a4f5c7e-bef7-11e7-9ddc-5e65364defcc.png">

This brings the following issues:
* **fragmentation** 
Judging from the list of already published versions, users tend to publish both uppercase and lowercase artifactIds but the contents is the same for same package versions

* **case-insensitive file system errors** 
I don't know how users are supposed to work with both cases together in such systems.
It's possible to happen if user specifies one package with uppercase artifactId in the root pom.xml and get lowercase version as a transitive dependency from the other package

* **case-sensitive file system errors** 
If both cases come to the same project, Maven considers them to be totally different packages which hides potential version conflicts

* **redundancy** 
I've noticed that the majority of the `bower` WebJars with uppercase artifactId are outdated: their lowercase analogues always have a newer version or at least the same.
I might be wrong about this one but it looks like the users tend to use lowercase artifactIds more often.

* **correctness**
Although not explicitly restricting the opposite, Maven guide [states](https://maven.apache.org/guides/mini/guide-naming-conventions.html) that artifactIds should be
> with lowercase letters and no strange symbols

The proposition is to use the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) and accept all forms but produce lower case artifactIds only.

**Comment by SomeoneToIgnore** [comment]
The fix looks easy https://github.com/webjars/webjars/pull/1669 but I am afraid I'm missing something here.

**Comment by jamesward** [comment]
I had worked on doing this a while back but then ran into the case where we'd still need to be able to publish mixed case WebJars due to existing deps.

I forget... does Bower doesn't allow different artifacts with the same name if their case differs (like NPM does)?  Like can there be a `jquery` and a `jQuery` artifact in Bower?

**Comment by SomeoneToIgnore** [comment]
> the case where we'd still need to be able to publish mixed case WebJars due to existing deps.

Can you elaborate on this? Afaik, when publishing any bower WebJar, I have had to publish its dependencies too, if they were not published yet.

> does Bower doesn't allow different artifacts with the same name if their case differs

Technically, it should not allow any uppercase package names due to its specification:
https://github.com/bower/spec/blob/master/json.md

> The name of the package as stored in the registry.
...
> * Lowercase, a-z, can contain digits, 0-9, can contain dash or dot but not start/end with them.

**Comment by jamesward** [comment]
Fixed via #1702
