### ISSUE TITLE
Update Datum to 0.10.0

### ISSUE THREAD

**Issue by MartinRixham** [webjars/webjars#1671]
Would you mind updating the Datum webjar to the new version? The build files are here:
https://unpkg.com/Datum@0.10.0/target/Datum.js
and here:
https://unpkg.com/Datum@0.10.0/target/Datum.min.js

thanks in advance

**Comment by jamesward** [comment]
This will be released shortly.  In the future please file Classic WebJar bump requests on the actual WebJar repo, i.e. https://github.com/webjars/Datum

**Comment by MartinRixham** [comment]
sure will do

thanks a lot
