### ISSUE TITLE
 Problem with the CC-BY license 

### ISSUE THREAD

**Issue by morpheus-87** [webjars/webjars#1672]
Why is the CC-BY license not supported? Is there any reason?

**Comment by jamesward** [comment]
That is a BinTray decision.  I've filed issues with them to add support for this but so far haven't been able to get them to budge.  In the meantime we'll have to use Classic WebJars for these.

**Comment by morpheus-87** [comment]
Ok, I see - thanks for your effort! Could you maybe generate a Classic WebJar for this repo: https://github.com/subugoe/tify?

**Comment by jamesward** [comment]
Can you fill out the request form on https://www.webjars.org ?
