### ISSUE TITLE
Empty deploy of bower jsdiff package

### ISSUE THREAD

**Issue by attaboy** [webjars/webjars#1680]
I used the webjars.org page to deploy the [jsdiff bower package v3.4.0](https://github.com/components/jsdiff). I got an error the first time, tried again, and it looked like it worked, but the deployed package has no files in it. The github repository for the package looks normal to me.

I've tried re-deploying after that, but it still seems to be a webjar with nothing in the resources directory: http://repo1.maven.org/maven2/org/webjars/bower/jsdiff/3.4.0/

**Comment by jamesward** [comment]
I think this was due to #1679. The fix was deployed 4 hours ago.  Did you happen to do this before then?

**Comment by attaboy** [comment]
I can't be certain about my first attempt, but I've definitely tried to re-deploy less than 4 hours ago. My last attempt, which claimed to succeed was around 2:50 PM EST. (The timestamp on maven says 15:57, but I don't know what time zone that is.)

**Comment by jamesward** [comment]
I'm pretty sure that once something is on Maven Central it can't be overwritten.  :( It looks like the latest on BinTray is fixed: https://bintray.com/webjars/maven/org.webjars.bower%3Ajsdiff

So that is good but we need to figure out how to deal with the broken package.  Can you use a different package or do you need these coordinates due to a transitive dep?

**Comment by attaboy** [comment]
Hmm. To me, the version on bintray looks the same: the jar doesn't contain the source files.

I've already investigated using the NPM version of the same package, and I suspect it will work fine (and that webjar was deployed properly). So I can probably ignore this and move on, but it doesn't seem great to leave a broken deployed webjar out there for others to stumble on. 😞

**Comment by jamesward** [comment]
Oh, so this wasn't due to the bug in packaging.  We just repackage whatever is in the Bower repo.  And in the case the source files aren't in the Bower artifact:
https://bower-as-a-service.herokuapp.com/download/jsdiff/3.4.0

**Comment by attaboy** [comment]
Sorry, I made a mistake. I should've been clearer: what I meant by "source files" was just _any_ JS files at all. But you were right — the BinTray version is fine. The Maven version has no JS files in it though. The directory where those 5 files should be is empty (and/or maybe the JAR itself is just corrupt).

**Comment by attaboy** [comment]
(Also, alas, the NPM version won't work like I thought. 😞)

**Comment by jamesward** [comment]
Ah, so we did hit the bug on the deploy to Maven Central.  Let me know if you want a Classic WebJar instead.
