### ISSUE TITLE
Could not determine a source URL

### ISSUE THREAD

**Issue by sherzinger** [webjars/webjars#1681]
I'm trying to add a npm project (fractalis v0.1.6) to webjars but always get this error message:

```
Failed!
Could not determine a source URL
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Deploying org.webjars.npm fractalis 0.1.6
Starting Deploy
```

I assume there is an issue in this file?
https://git-r3lab.uni.lu/Fractalis/fractal.js/blob/master/package.json

**Comment by jamesward** [comment]
A fix for this should be deployed in about 10 minutes.
