### ISSUE TITLE
Two recent Web JARs of AngularJS are broken.

### ISSUE THREAD

**Issue by twwwt** [webjars/webjars#1682]
Not sure whether this is the right place to post this: the Web JARS

"org.webjars.bower" % "angular" % "1.6.7"
"org.webjars.bower" % "angular-animate" % "1.6.7"

are broken. The folder `META-INF/resources` is completely missing. Is there a possibility to retract published artifacts? How to resolve this issue?

**Comment by GlaserIngo** [comment]
Having the same issue

**Comment by jamesward** [comment]
This was due to a temporary deployment bug.  :(  It has been fixed but now we'll need to see if there is some way to replace those packages on Maven Central - which usually doesn't do that.  I'll investigate.  But if there are newer versions we can deploy, that'd be an easy workaround.

**Comment by twwwt** [comment]
@jamesward Negative. There is no newer version (1.6.7 is the latest as of today). From what I read [here](https://stackoverflow.com/q/9789611), it seems that a new version needs to be published. Would a version like `1.6.7_1` be a way to go? I'm just wondering whether it could be done in the usual way on [www.webjars.org](www.webjars.org) web site.

**Comment by jamesward** [comment]
We don't have a way right now to publish these patch versions, in part because changing the version number can mess up dependencies.  I think we *could* come up with a way to do the manual patch.  But before I work on that, will it fix things for you if I can publish a `1.6.7-1` of these two artifacts?

**Comment by twwwt** [comment]
@jamesward Publishing a version 1.6.7-1 of these two artifacts is OK for me.

**Comment by jamesward** [comment]
I've added the ability to manually override the version and released:

```
GroupID = org.webjars.bower
ArtifactID = angular
Version = 1.6.7-1
```

```
GroupID = org.webjars.bower
ArtifactID = angular-animate
Version = 1.6.7-1
```

Let me know how it goes!

**Comment by twwwt** [comment]
Works for me. Thanks!
