### ISSUE TITLE
Error adding NPM @types/

### ISSUE THREAD

**Issue by cchampignon** [webjars/webjars#1684]
Getting the following error when trying to add any @types module, including existing webjars such as @types/react https://www.npmjs.com/package/@types/react

`Failed!
The package name in the Json body should starts with a letter or a digit. The package name can contain only letters digits and the following special characters: '-' '_' ':' '.' '+' 
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues`

The fact that many other @types [exist](http://www.webjars.org/listfiles/org.webjars.npm/types__react/15.6.1) suggests I'm either doing something wrong on the add form or there has been a regression. Thoughts?

**Comment by jamesward** [comment]
Whoops.  I screwed this up.  The fix will be deployed in about 10 minutes.
