### ISSUE TITLE
graceful-readlink 1.0.0 npm webjar fails to deploy

### ISSUE THREAD

**Issue by mhzajac** [webjars/webjars#1685]
When I attempt to deploy the 1.0.0 version of graceful-readlink through the webjars.org website, it fails with the following output:

```
Failed!
URI is not absolute
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Deploying org.webjars.npm graceful-readlink 1.0.0
Starting Deploy
```

**Comment by jamesward** [comment]
Can you try `1.0.1` instead?  The required repo url was not set initially on this repo, but was then fixed:
https://github.com/zhiyelee/graceful-readlink/commit/f6655275bebef706fb63fd01b5f062a7052419a5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Let me know if that isn't an option.
