### ISSUE TITLE
angular-animate 1.6.7 is empty

### ISSUE THREAD

**Issue by KarelCemus** [webjars/webjars#1688]
It seems that the bower archive of angular-animate 1.6.7 is empty.

[here is maven repo](https://mvnrepository.com/artifact/org.webjars.bower/angular-animate/1.6.7)

**Comment by KarelCemus** [comment]
Now I noticed it is related to #1682, but there is not `1.6.7-1` for `angular-animate` package, only for angular itself.

**Comment by jamesward** [comment]
I'm releasing `1.6.7-1` now which should fix this.
