### ISSUE TITLE
CeCILL-B free software licence is not accepted

### ISSUE THREAD

**Issue by isoum2** [webjars/webjars#1689]
I tried to add a WebJar from the NPM package "ol3-ext". The CeCILL-B free software licence is not accepted (http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html).

This is the deployement log:
Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/Viglino/ol3-ext.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: CECILL-B
This problem will likely need to be resolved by working with the library maintainers directly.
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Deploying org.webjars.npm ol3-ext 1.0.1
Starting Deploy

**Comment by jamesward** [comment]
Unfortunately since that isn't an acceptable OSS license for BinTray we will need to do a Classic WebJar for this.  If that works for you, can you do the new Classic WebJar request via https://www.webjars.org/
