### ISSUE TITLE
Trailing slash in sourceUrl results in error

### ISSUE THREAD

**Issue by gpgekko** [webjars/webjars#1691]
The `electron-to-chromium` npm package has a trailing slash in its `sourceUrl`. This didn't use to be a problem (I've deployed the previous version without problems a while ago, and it had the same URL), but if I try to deploy the latest version (1.3.28) it refuses with an error, and in the message I can see it appends `.git` to the URL without stripping that trailing slash.

https://github.com/webjars/webjars/commit/b8af656c254553f0c3f2b9ba9fbb1d4cb5bf9d91#commitcomment-26276639

**Comment by jamesward** [comment]
This fix should be deployed in about 15 minutes.  Then you can try again.

**Comment by gpgekko** [comment]
Works like a charm, thanks!
