### ISSUE TITLE
Vis 4.21.0.jar file is not available 

### ISSUE THREAD

**Issue by RupaliPandekar** [webjars/webjars#1693]
Hello,
I am using vis 4.20.0  but there ' OnDropObjectOnIem ' option is not available.The same option is available in vis 4.21.0, but jar file of vis 4.21.0 is not present in webjars folder.Can any one please provide the jar file of vis 4.21.0.
Thanks in Advance!!!

**Comment by jamesward** [comment]
Which type of WebJar do you need a new version of this for? NPM, Bower, Classic.

**Comment by jamesward** [comment]
Resolved by: https://github.com/webjars/visjs/issues/11
