### ISSUE TITLE
rc-slider

### ISSUE THREAD

**Issue by mdedetrich** [webjars/webjars#1697]
So I have been trying to deploy rc-slider for a day now, usually it fails but at some times it succeeded (however I have never been able to actually retrieve the dependency). The last try outputs this

```
Failed!
<html>

<head><title>405 Not Allowed</title></head>

<body bgcolor="white">

<center><h1>405 Not Allowed</h1></center>

<hr><center>nginx</center>

</body>

</html>


If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
          
Created BinTray Version
Created BinTray Package
Created NPM WebJar
Fetched NPM zip
Generated POM
Got the source URL: https://github.com/react-component/slider
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Deploying org.webjars.npm rc-slider 7.0.0
Starting Deploy
```

I noticed this when trying to deploy other dependencies to webjars, it only works around 10% of the time. This is the only dependency however that I wasn't able to actually get working

EDIT: Here is an example of a successful deploy (even though I can't retrieve it)

```
Deployed!
It will take a few hours for the Maven Central index to update but you should be able to start using the NPM WebJar now.
GroupID = org.webjars.npm
ArtifactID = rc-slider
Version = 7.0.0
        
Synced With Maven Central
Published BinTray Version
Signed BinTray Assets
Published BinTray Assets
Created BinTray Version
Created BinTray Package
Created NPM WebJar
Fetched NPM zip
Generated POM
Got the source URL: https://github.com/react-component/slider
Converted optional dependencies to Maven
Converted dependencies to Maven
Resolved Licenses
Deploying org.webjars.npm rc-slider 7.0.0
Starting Deploy
```

**Comment by jamesward** [comment]
Yesterday Heroku was having some issues which might have been the underlying cause of this.  Let me know if you are still having issues.

**Comment by mdedetrich** [comment]
@jamesward Found the problem

```
[warn] problem while listing resources in https://maven.zalando.net/content/repositories/releases/org/webjars/npm/rc-slider/ with zalando-nexus-releases:
[warn]   java.lang.NullPointerException charsetName
[warn] problem while listing resources in https://maven.zalando.net/content/repositories/snapshots/org/webjars/npm/rc-slider/ with zalando-nexus-snapshots:
[warn]   java.lang.NullPointerException charsetName
[warn] 	module not found: org.webjars.npm#rc-slider;[7.0.0,7.1)
```

I think the jar was uploaded incorrectly

**Comment by jamesward** [comment]
Ah weird.  Looks like Maven Central had an issue deploying that since it is not listed at: https://repo1.maven.org/maven2/org/webjars/npm/rc-slider/maven-metadata.xml

But does exist: https://repo1.maven.org/maven2/org/webjars/npm/rc-slider/7.0.0/

**Comment by jamesward** [comment]
I'm trying to resync it to see if that works.

**Comment by jamesward** [comment]
Maven Central isn't allowing me to resync that.  Will `7.0.8` work instead?  I'm trying to deploy that now.

**Comment by mdedetrich** [comment]
Unfortunately its still not working since its not being picked up as a transitive dependency. I am not directly depending on rc-slider, the dependency is coming from antd 2.9.3, and since the ivy resolution does pick up the broken version of rc-slider v7.0.0 before anything else, it will always fail.

How hard is it to get maven to delete a current dependency, I know that its immutable but basically there is a completely broken package that has been deployed?

**Comment by jamesward** [comment]
Here is the issue I've filed with Sonatype about this: https://issues.sonatype.org/browse/OSSRH-37027

**Comment by jamesward** [comment]
This seems to have been fixed.  It might take a few hours to sync to Maven Central.  Let me know how it goes.

**Comment by mdedetrich** [comment]
Fixed from my end, all resolved, thanks for the help!
