### ISSUE TITLE
deploy failed often with "+" button and works fine with "add a webjar"

### ISSUE THREAD

**Issue by ZheSun88** [webjars/webjars#1699]
I have deployed a few webjars via using https://www.webjars.org/.  Thanks for the work. 

I got one interesting observation on the different performances with the "+" button and "add a webjar".. 
normally, when i am using the "+" button to deploy a webjar, it will fail for most of the case... but with "add a webjar" button, it works quite well...

I am using google chrome `Version 63.0.3239.132`  on windows 10. 

Not sure this is a issue or not even.

**Comment by jamesward** [comment]
Did you get an error when trying to deploy with the `+` button?  I think there were sync issues between BinTray & Maven Central over the past 12 hours.

**Comment by ZheSun88** [comment]
Yeah, I think it is just an temporary issue. So I just closed this ticket. Thanks.
