### ISSUE TITLE
BowerGitHub UI

### ISSUE THREAD

**Issue by jamesward** [webjars/webjars#1703]
- [x] Deploy UI
- [x] Search UI

**Comment by Artur-** [comment]
Any plans for this? While the new Bower webjars are awesome, the lack of a UI makes them pretty hard to use

**Comment by OlliTietavainenVaadin** [comment]
This is relevant to my interests.

**Comment by jamesward** [comment]
Yeah, I need to work on this.   Just haven't had time but will soon.

**Comment by jamesward** [comment]
The UI changes can be tested at: https://webjars-test.herokuapp.com/

**Comment by Artur-** [comment]
As people generally do not read documentation it could be useful to indicate that `Bower Original` is deprecated in the "Add a New WebJar" popup e.g. by wrapping it as `<del>Bower Original</del>`

**Comment by jamesward** [comment]
Thanks!  I've updated the test app.  LMKWYT

**Comment by jamesward** [comment]
This has been deployed to prod.  Please file new issues if needed.
