### ISSUE TITLE
WebJars request: jspdf and plugins

### ISSUE THREAD

**Issue by medonja** [webjars/webjars#1704]
Hi,

would it be possible to update jspdf as a classical WebJar since the current version does not setup the requirejs path properly and also does not include any of the standard plugins (https://github.com/MrRio/jsPDF/tree/master/plugins)? It would be quite handy to have those scripts as a classical WebJar.

Did you maybe consider providing an automated way of submitting new webjars? I guess its not a small job for you to manually generate webjars? I really appreciate what you are doing, keep up the good work! :)

Thanks, 
Marko

**Comment by jamesward** [comment]
Can you file an issue on the Classic WebJar's repo? i.e. https://github.com/webjars/jspdf

We definitely would like to add more automation.  The Bower & NPM self-service method has worked well but there is more we can do to make this easier.
