### ISSUE TITLE
WebJarAssetLocator returns incorrect id and version for new Bower WebJars

### ISSUE THREAD

**Issue by eriklumme** [webjars/webjars#1705]
Please correct me if I'm talking out of my arse.

I added a Bower WebJar yesterday from [release v1.0.0](https://github.com/eriklumme/timer-bar/releases/tag/v1.0.0) of [my web component](https://github.com/eriklumme/timer-bar/).

After adding it as a Maven dependency, the `webjars-locator-core` `WebJarAssetLocator.getWebJar(String path)` -function comes up with the following *id* and *version* given the path:

```
path: META-INF/resources/webjars/github-com-eriklumme-timer-bar/v1.0.0/LICENSE
id: github-com-eriklumme-timer-bar
version: v1.0.0
```

This works fine. Today I added a new WebJar from a [new release v1.1.1](https://github.com/eriklumme/timer-bar/releases/tag/v1.1.1). When adding it as a Maven dependency, I noticed that `v1.1.1` does not work, instead I must use `1.1.1`. In addition, the `getWebJar` method returns incorrect *id* and *version*:

```
path: META-INF/resources/webjars/org.webjars.bower/timer-bar/v1.1.1/LICENSE
id: org.webjars.bower
version: timer-bar
```

Is the locator broken for new Bower WebJars?

The jars can be found in Maven central [here](https://repo1.maven.org/maven2/org/webjars/bower/github-com-eriklumme-timer-bar/).

**Comment by eriklumme** [comment]
Should perhaps mention my project is using version 0.34 of `webjars-locator-core` instead of the latest 0.35, but judging from the latest update this shouldn't be an issue.

**Comment by jamesward** [comment]
Thanks for reporting this.  It is possible that I broke / changes something with #1702.  I'll investigate.

**Comment by jamesward** [comment]
This should be fixed by https://github.com/webjars/webjars/commit/31cbbd379ff8f555da45445d84347d609824dff2

The fix will be deployed in about 10 minutes.  Then we should probably deploy a new `1.1.1-1` release of your lib but I'll have to do that manually.

**Comment by eriklumme** [comment]
Alright, thank you very much for the quick help :)

**Comment by jamesward** [comment]
NP.  Sorry for the hassle.  Check out this artifact and see if it is right:
https://bintray.com/webjars/maven/org.webjars.bower%3Agithub-com-eriklumme-timer-bar/1.1.1-1#files/org%2Fwebjars%2Fbower%2Fgithub-com-eriklumme-timer-bar%2F1.1.1-1

**Comment by eriklumme** [comment]
Works great! Thank you!

**Comment by jamesward** [comment]
Cool.  I'll see if I can get it synced to Maven Central (was having an issue with that part).
