### ISSUE TITLE
postcss-normalize-charset

### ISSUE THREAD

**Issue by dhakehurst** [webjars/webjars#1709]
Trying to deploy version 1.1.1 and/or 1.1.0

Failed!
Could not get the current URL for https://github.com/ben-eb/postcss-charset because status was Not Found

URL seems to be wrong, I can find
https://github.com/ben-eb/postcss-normalize-charset, but that seems to have releases for 'v1.1.1' not '1.1.1'

**Comment by jamesward** [comment]
Yeah, the URL registered with NPM is wrong.  I've manually deployed this with the right URL.
```
GroupID = org.webjars.npm
ArtifactID = postcss-normalize-charset
Version = 1.1.1
```

**Comment by dhakehurst** [comment]
thanks
