### ISSUE TITLE
xmldom

### ISSUE THREAD

**Issue by dhakehurst** [webjars/webjars#1710]
Trying to deploy,

package.json in repo says,
  "license": "(LGPL-2.0 or MIT)"

Failed!
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/jindw/xmldom.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: LGPL
This problem will likely need to be resolved by working with the library maintainers directly.

**Comment by jamesward** [comment]
The issue is that BinTray for some reason doesn't have `LGPL-2.0` in their list of supported OSS licenses.  I've filed a request to have them add it.

**Comment by dhakehurst** [comment]
thanks

**Comment by jamesward** [comment]
This has been released:
```
GroupID = org.webjars.npm
ArtifactID = github-com-jindw-xmldom
Version = 0.1.28
```
