### ISSUE TITLE
To create webjars without a compatible license, it would be handy to be able to get the webjar out anyway

### ISSUE THREAD

**Issue by Artur-** [webjars/webjars#1712]
When you have a Bower dependency without a suitable free license, it would be very handy if there was a way to get the generated webjar even though it can't be deployed to Bintray. This would allow creating webjars the same way regardless of the license, and then dealing manually with getting them deployed somewhere.  E.g. a `/create` REST API which would run through only the packaging steps and return the generated pom+jar would be nice.

**Comment by jamesward** [comment]
This has been deployed.  Example:
`curl -X POST -OJ 'https://www.webjars.org/create?webJarType=BowerGitHub&nameOrUrlish=polymer&version=2.0.2'`

Right now it returns the WebJar jar file.  The pom file can be found inside of it.

**Comment by Artur-** [comment]
Thanks! Tested using
```
curl -X POST -OJ  'https://www.webjars.org/create?webJarType=BowerGitHub&nameOrUrlish=https://github.com/vaadin/vaadin-board&version=v2.0.0-alpha1'
```

but the response only contained
```
        <h1>Oops, an error occurred</h1>

        <p id="detail">
            This exception has been logged with id <strong>7701cgclf</strong>.
        </p>
```

**Comment by jamesward** [comment]
Looks like I need to output an error when one occurs.  I wonder if curl will handle that ok...

**Comment by jamesward** [comment]
I have the error handling ready and in this case the error was:
```
All attempts to determine an acceptable license have been exhausted.  The bower.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/vaadin/vaadin-board.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: https://raw.githubusercontent.com/vaadin/vaadin-board/master/LICENSE.txt
This problem will likely need to be resolved by working with the library maintainers directly.
```

So it seems like I need to add an optional license override.  Right?

**Comment by Artur-** [comment]
Yeah the whole point with the endpoint would be that the license should not matter. The generated pom probably needs to be modified by hand if the original license reference is not retained

**Comment by jamesward** [comment]
Once this is deployed in about 15 minutes you should be able to override the license, like:
```
curl -OJ -d '{"license": { "MIT": "http://foo.com" } }' 'https://www.webjars.org/create?webJarType=bower&nameOrUrlish=bootstrap&version=3.3.1'
```

**Comment by Artur-** [comment]
```
curl -OJ -d '{"license": { "MIT": "http://foo.com" } }' 'https://www.webjars.org/create?webJarType=bowergithub&nameOrUrlish=vaadin/vaadin-board&version=v2.0.0-alpha3'
```

still results in
```
All attempts to determine an acceptable license have been exhausted.  The bower.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/vaadin/vaadin-board.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: https://raw.githubusercontent.com/vaadin/vaadin-board/master/LICENSE.txt
This problem will likely need to be resolved by working with the library maintainers directly.
```

**Comment by jamesward** [comment]
Oh, looks like you have to set the content type as well:
```
curl -OJ -H "Content-Type: application/json" -d '{"license": { "MIT": "http://foo.com" } }' 'https://www.webjars.org/create?webJarType=bowergithub&nameOrUrlish=vaadin/vaadin-board&version=v2.0.0-alpha3'
```

**Comment by Artur-** [comment]
Thanks, now it works! This is awesome. 

Is it possible to override more than the license in the JSON data? To be able to publish the webjar, I have to change the group id as I can't publish in the `org.webjars` namespace.

**Comment by jamesward** [comment]
Yeah, we can setup overrides for anything we want.

**Comment by Artur-** [comment]
`curl -OJ -H "Content-Type: application/json" -d '{"groupId": "com.vaadin.webjar", "license": { "MIT": "http://foo.com" } }' 'https://www.webjars.org/create?webJarType=bowergithub&nameOrUrlish=vaadin/vaadin-board&version=v2.0.0-alpha3'`

would be very handy as you always need to change to `groupId`
