### ISSUE TITLE
Failed to deploy https://github.com/MyScript/myscript-math-web

### ISSUE THREAD

**Issue by Artur-** [webjars/webjars#1716]
`curl -X POST https://www.webjars.org/deploy?webJarType=BowerGitHub&nameOrUrlish=https://github.com/MyScript/myscript-math-web&version=v4.1.0`

```
Picked up JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
[info] application - Deploying org.webjars.bowergithub.myscript myscript-math-web 4.1.0
[info] application - Resolved Licenses
[info] application - Failed!JsResultException(errors:List((,List(JsonValidationError(List(null is not an object),WrappedArray())))))If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues          
[error] application - JsResultException(errors:List((,List(JsonValidationError(List(null is not an object),WrappedArray())))))
```

**Comment by binhbbui411** [comment]
https://github.com/MyScript/myscript-math-web/pull/2 

This could fix it. I ran into some wrong version declaring in `bower.json`

**Comment by jamesward** [comment]
Yeah, @binhbbui411 is right.  The specified Bower dependency syntax: `"KaTeX": "katex#^0.8.3"` isn't valid.  We *could* support it but I'm not sure if we should.
