### ISSUE TITLE
TinyMCE: Unable to Create/Deploy npm webjar 

### ISSUE THREAD

**Issue by Daekard** [webjars/webjars#1719]
I've been trying to deploy an  npm version of the tinyMCE webjar (we'd like to use npm over bower), but have encountered the following problems. 

On attempting to create a npm webjar using the webjar name, the following error is displayed:
`The metadata was missing a required field: /repository/url`

In contrast the bower webjar deploys perfectly. 

Attempting to create an npm webjar from the `tinymce-dist` git repo also causes issues, as the resulting webjar does not contain any of the source files in the repo's root directory.

**Comment by jamesward** [comment]
The `The metadata was missing a required field: /repository/url` error means the `package.json` doesn't have required metadata.  We can manually deploy it but this should be fixed upstream.  What is the NPM artifact name and the repo for it?

**Comment by Daekard** [comment]
The name of the artefact is `tinymce`, the git repo is https://github.com/tinymce/tinymce-dist, and the npm registry entry is https://registry.npmjs.org/tinymce

You're correct that the `package.json` file doesn't have the repo URL in the metadata.

**Comment by jamesward** [comment]
I've manually deployed this:
```
GroupID = org.webjars.npm
ArtifactID = tinymce
Version = 4.7.6
```

**Comment by Daekard** [comment]
Much appreciated. Thank you.
