### ISSUE TITLE
org.webjars.bower.dojox Incorrect Licence

### ISSUE THREAD

**Issue by harleyhooper1** [webjars/webjars#1720]
Licence specified in the POM at: http://central.maven.org/maven2/org/webjars/bower/dojox/
is incorrectly identified as OSL 3.0

Actual licence is either BSD OR AFL 2.1
https://github.com/dojo/dojox/blob/master/LICENSE

**Comment by jamesward** [comment]
Thanks for reporting.  This stemmed from that package not using the standard `license` property.  I've added handling for this but also need to fix the incorrect fallback GitHub license resolution:
https://github-license-service.herokuapp.com/dojo/dojox

I've released an updated package with the correct license:
```
GroupID = org.webjars.bower
ArtifactID = dojox
Version = 1.13.0-1
```
