### ISSUE TITLE
Deploy UI Broken in Firefox

### ISSUE THREAD

**Issue by jamesagnew** [webjars/webjars#1721]
Steps to reproduce:

1. Select a webjar from http://webjars.org (in this case I'm trying `org.webjars.bower:chartjs` but others seem to produce the same result
2. Click the blue plus button
3. Select the latest version
4. Click deploy
5. The resulting screen just hangs indefinitely at "Starting Deploy"

![selection_052](https://user-images.githubusercontent.com/3465117/36201645-9c73f9f2-114e-11e8-9261-bb1f7b457a3c.png)

**Comment by jamesward** [comment]
I think maybe this is a browser issue with some recent changes I've made.  Are you getting any JavaScript errors?

**Comment by jamesagnew** [comment]
Hi @jamesward , thanks for the quick response.

The following shows up in the Firefox error console when I first open the "Add a new WebJar" dialog:
```
XML Parsing Error: no root element found
Location: https://www.webjars.org/exists?webJarType=bower&name=chart.js
Line Number 1, Column 1: exists:1:1
```

No further errors show up after I've hit the deploy button though. This is on Firefox 58, tested on OSX and Linux.

I do note that the webjar version (`org.webjars.bower:chartjs:2.7.1`) I was trying to deploy yesterday did in fact show up in the Maven repos this morning, so I guess that means this is a glitch in the deployig UI and not with the deploying process itself?

**Comment by jamesward** [comment]
So Firefox doesn't support the streaming fetch responses.  :( But you are right that the deploy should still happen.

**Comment by jamesagnew** [comment]
Hmm, ok so weirdly I could have sworn that the 2.7.1 version was deployed when I checked yesterday, but today it's not showing up on webjars.org or in [Maven Central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.webjars.bower%22%20AND%20a%3A%22chartjs%22). Now I'm not so sure the deploy worked either.

**Comment by jamesward** [comment]
The indexes take a while to refresh.  But it is in Maven Central: https://repo1.maven.org/maven2/org/webjars/bower/chart.js/2.7.1/

**Comment by andreaferretti** [comment]
I have the same issue - both with Firefox 58.0.2 and Chrome 64.0.3282.186 on Mac Sierra. I am not sure whether anything went on, but I cannot see the new version (paths-js 0.4.6) in the webjars interface.

**Comment by jamesward** [comment]
@andreaferretti That is weird that it didn't work in Chrome.  Did you get any JavaScript errors?

**Comment by andreaferretti** [comment]
I tried again to deploy (bower mode) paths-js version 0.4.6, using just `andreaferretti/paths-js` instead of `https://github.com/andreaferretti/paths-js`. Now Chrome gives me a feedback but it ends with an error 405 Not Allowed

**Comment by jamesward** [comment]
@andreaferretti Looks like there is an issue with our BinTray stuff right now.  I've filed an issue with them.

**Comment by jamesward** [comment]
@andreaferretti This has been resolved and deployed:
```
GroupID = org.webjars.bower
ArtifactID = github-com-andreaferretti-paths-js
Version = 0.4.6
```

**Comment by andreaferretti** [comment]
Great, thank you!

**Comment by jamesward** [comment]
Investigating this...  Server-Sent Events and Comet can't use the POST method.  :(
