### ISSUE TITLE
Cannot deploy npm:trim:0.0.1 

### ISSUE THREAD

**Issue by maroziza** [webjars/webjars#1722]
When i try to deploy packages there is an error.
```
Starting Deploy
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
The metadata was missing a required field: `/repository/url`
```
btw. why we need all that dependencies in maven?  
trim is needed as a dependency to videojs.
Just excluded it as a workaround.

**Comment by jamesward** [comment]
NPM dependencies are converted to Maven dependencies.

I've manually deployed the `trim` library.
