### ISSUE TITLE
semantic-ui-react

### ISSUE THREAD

**Issue by roti** [webjars/webjars#1723]
How can I find the source of "org.webjars.npm" % "semantic-ui-react" ? It doesn't seem to neither under the webjars project, nor the semantic-ui-react project.

**Comment by jamesward** [comment]
This is deployed from the NPM package:
https://www.npmjs.com/package/semantic-ui-react

Which says it's source is at:
https://github.com/Semantic-Org/Semantic-UI-React

The contained pom.xml file should include a link to the correct source location.  Let me know if that is not the case.
