### ISSUE TITLE
Problem deploying new 1.0.1 npm version of Stimulus

### ISSUE THREAD

**Issue by teggr** [webjars/webjars#1724]
Hi there,

I've tried deploying the 1.0.1 npm version of the stimulus library which seems to be failing with a 405 error at somepoint after the **Created BinTray Version** log message. I'm not sure what is returning that 405 or how to rectify or workaround. Any thoughts?

Thasnk in advance :)

------------------

Starting Deploy
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Got package info for org.webjars.npm stimulus 1.0.1
Determining dependency graph
Deploying these dependencies: @stimulus/core#1.0.1 @stimulus/webpack-helpers#1.0.0 @stimulus/mutation-observers#1.0.0 @stimulus/multimap#0.9.0
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Got package info for org.webjars.npm stimulus__core 1.0.1
WebJar org.webjars.npm stimulus__core 1.0.1 has already been deployed
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Got package info for org.webjars.npm stimulus__webpack-helpers 1.0.0
WebJar org.webjars.npm stimulus__webpack-helpers 1.0.0 has already been deployed
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Got package info for org.webjars.npm stimulus__mutation-observers 1.0.0
WebJar org.webjars.npm stimulus__mutation-observers 1.0.0 has already been deployed
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
Got package info for org.webjars.npm stimulus__multimap 0.9.0
WebJar org.webjars.npm stimulus__multimap 0.9.0 has already been deployed
Resolved Licenses: MIT -> https://spdx.org/licenses/MIT#licenseText
Converted dependencies to Maven
Converted optional dependencies to Maven
Got the source URL: https://github.com/stimulusjs/stimulus
Generated POM
Fetched NPM zip
Created NPM WebJar
Created BinTray Package
Created BinTray Version

405 Not Allowed

nginx

**Comment by jamesward** [comment]
Looks like this was a transient failure with BinTray.  I've redeployed it and it worked.

**Comment by teggr** [comment]
Thanks @jamesward. Appreciate your help :)
