### ISSUE TITLE
Option to re-run the dependency resolution process of adding an npm webjar

### ISSUE THREAD

**Issue by McNetic** [webjars/webjars#1726]
When adding an npm webjar, all dependencies are resolved and also added (so far, so good).
Unfortunately, it can (and will) happen that the deployment of some of the dependencies fails during the deployment process. With several hundreds of them in for some packages, it's a tedious and time consuming task of finding the missing dependencies and re-deploying them manually.

As long as the parent package is not propagated to maven central, it still possible to restart the deployment process, so the dependencies get tried another time. It would, hovewer, by nice to be able to re-check and deploy the dependencies of a given package afterwards.

**Comment by jamesward** [comment]
I think you should be able to just redeploy the root dependency and have it try everything again.  Did that not work?

**Comment by McNetic** [comment]
Yes, sorry, thats totally possible. I thought already existing versions would be removed from the list.
