### ISSUE TITLE
Webjar Request: bootstrap-scss

### ISSUE THREAD

**Issue by JohnFord** [webjars/webjars#1727]
https://github.com/JohnFord/bootstrap-scss

Bootstrap used to have a separate sass distribution, bootstrap-sass and there was a corresponding bootstrap-sass webjar. Now, as of bootstrap 4, the sass files are distributed as part of the regular bootstrap release but they are not included in the bootstrap webjar. 

This webjar allows developers to import the bootstrap sass files into their project as a webjar.

**Comment by jamesward** [comment]
Do you think we should just add those scss files back to the regular bootstrap WebJar?

**Comment by JohnFord** [comment]
I was actually thinking of setting up a separate repo with a pull request for that option, as well. I think that would probably be easiest for users but wasn't sure if it had been left out for a reason.

**Comment by jamesward** [comment]
Cool.  I've released a `4.0.0-1` that includes the `scss` dir.

**Comment by jmarkham** [comment]
Doesn't appear that the scss directory made it into 4.0.0-1 release

**Comment by jamesward** [comment]
Whoops.  This is being released at `4.0.0-2`.

**Comment by jmarkham** [comment]
Thanks...was creating issues creating checkboxes with custom-checkbox.  Appreciate it.
