### ISSUE TITLE
Pom is missing for already deployed org.webjars.npm.for-own 0.1.5

### ISSUE THREAD

**Issue by McNetic** [webjars/webjars#1729]
For org.webjars.npm.for-own version 1.5, the pom is missing in maven central (see http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.webjars.npm%22%20AND%20a%3A%22for-own%22)

Re-creating the package appears to work, but does not change the status quo (I alread did this some days ago).

**Comment by jamesward** [comment]
I've deployed `0.1.5-1` and it should have the pom.

**Comment by McNetic** [comment]
Uhm. I didn't notice you released a new version. Is it not possible to replace the errournous release? As is, this new release is not helpful for me, as other webjars have dependencies on this one and can't be used because of this (its the same btw for the other problematic releases I reported).

**Comment by jamesward** [comment]
Typically Sonatype doesn't remove artifacts (to not break builds).  We can ask them to do it if necessary.  Does the parent dependency use a version range that would include the patch release?
