### ISSUE TITLE
Pom is missing for already deployed org.webjars.npm.cyclist 0.2.2

### ISSUE THREAD

**Issue by McNetic** [webjars/webjars#1730]
For org.webjars.npm.cyclist version 0.2.2, the pom is missing in maven central (see http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.webjars.npm%22%20AND%20a%3A%22cyclist%22)

Re-creating the package appears to work, but does not change the status quo (I alread did this some days ago).

**Comment by jamesward** [comment]
I'm not sure what went wrong on that deploy.  But I've deployed `0.2.2-1` which should have the pom.
