### ISSUE TITLE
JAR was deployed to BinTray but not to Maven Central

### ISSUE THREAD

**Issue by gilberto-torrezan** [webjars/webjars#1734]
I have this webjar https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-checkbox/2.0.0-beta1 that has been deployed to BinTray, but for some reason it never got synchronized to Maven Central.

Is there anything I can do to force the synchronization? I can't redeploy it because it's already there.

**Comment by jamesward** [comment]
I've manually deployed that from BinTray.  Let me know if there are any issues.
