### ISSUE TITLE
Don't crash on invalid repository url

### ISSUE THREAD

**Issue by nafg** [webjars/webjars#1735]
I tried to add an npm webjar for react-component-managers 3.1.0. It fails with "Could not convert provided source uri '' to a URL."

<details>
<summary>Click for full output</summary>
<pre>
Starting Deploy
Got package info for org.webjars.npm react-component-managers 3.1.0
Determining dependency graph
Deploying these dependencies: core-js#2.5.3 loose-envify#1.3.1 fbjs#0.9.0-alpha.2 spy-on-component#1.0.2 asap#2.0.6 setimmediate#1.0.5 isomorphic-fetch#2.2.1 node-fetch#2.0.0-alpha.9 prop-types#15.6.1 ua-parser-js#0.7.17 js-tokens#3.0.2 object-assign#4.1.1 fbjs-css-vars#1.0.1 promise#7.3.1 whatwg-fetch#2.0.3
Got package info for org.webjars.npm core-js 2.5.3
WebJar org.webjars.npm core-js 2.5.3 has already been deployed
 Got package info for org.webjars.npm loose-envify 1.3.1
WebJar org.webjars.npm loose-envify 1.3.1 has already been deployed
 Got package info for org.webjars.npm fbjs 0.9.0-alpha.2
WebJar org.webjars.npm fbjs 0.9.0-alpha.2 has already been deployed
 Got package info for org.webjars.npm spy-on-component 1.0.2
WebJar org.webjars.npm spy-on-component 1.0.2 has already been deployed
Got package info for org.webjars.npm asap 2.0.6
WebJar org.webjars.npm asap 2.0.6 has already been deployed
Got package info for org.webjars.npm setimmediate 1.0.5
WebJar org.webjars.npm setimmediate 1.0.5 has already been deployed
Got package info for org.webjars.npm isomorphic-fetch 2.2.1
WebJar org.webjars.npm isomorphic-fetch 2.2.1 has already been deployed
 Got package info for org.webjars.npm node-fetch 2.0.0-alpha.9
WebJar org.webjars.npm node-fetch 2.0.0-alpha.9 has already been deployed
Got package info for org.webjars.npm prop-types 15.6.1
WebJar org.webjars.npm prop-types 15.6.1 has already been deployed
Got package info for org.webjars.npm ua-parser-js 0.7.17
WebJar org.webjars.npm ua-parser-js 0.7.17 has already been deployed
Got package info for org.webjars.npm js-tokens 3.0.2
WebJar org.webjars.npm js-tokens 3.0.2 has already been deployed
 Got package info for org.webjars.npm object-assign 4.1.1
WebJar org.webjars.npm object-assign 4.1.1 has already been deployed
Got package info for org.webjars.npm fbjs-css-vars 1.0.1
WebJar org.webjars.npm fbjs-css-vars 1.0.1 has already been deployed
Got package info for org.webjars.npm promise 7.3.1
WebJar org.webjars.npm promise 7.3.1 has already been deployed
Got package info for org.webjars.npm whatwg-fetch 2.0.3
WebJar org.webjars.npm whatwg-fetch 2.0.3 has already been deployed
Resolved Licenses: MIT -> https://spdx.org/licenses/MIT#licenseText
Converted dependencies to Maven
Converted optional dependencies to Maven
Could not convert provided source uri '' to a URL
</pre>
</details>

<br>

I think it's because https://github.com/jquense/react-component-managers/blob/v3.1.0/package.json#L36 says `"repository": ""`.

I submitted a fix and it was merged (https://github.com/jquense/react-component-managers/pull/3), but of course that doesn't help for existing versions.

**Comment by jamesward** [comment]
Since the source repo is required I manually deployed this:
```
GroupID = org.webjars.npm
ArtifactID = react-component-managers
Version = 3.1.0
```

And thanks to your fix, this should be good in the future.

**Comment by nafg** [comment]
Thanks. What do you mean that it's required? Do you mean by maven central?

**Comment by jamesward** [comment]
It is required by BinTray (which we use to deploy to Maven Central).
