### ISSUE TITLE
webjars in Bintray but not yet in maven

### ISSUE THREAD

**Issue by ZheSun88** [webjars/webjars#1738]
We have this https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-progress-bar/1.0.0-beta2/ in the bintray which had been deployed yesterday. But still it is not in maven yet.

also I just found, https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/polymerelements/paper-card/2.0.0/ this one is having the same problem.. 

Recently, the percentage of asynchronous webjars is getting higher.

**Comment by jamesward** [comment]
I've redeployed those so they should be in Maven Central soon.  Sometimes there are issues deploying to Maven Central.  But you should be able to redeploy them from https://webjars.org

**Comment by ZheSun88** [comment]
i have also tried to redeploy from webjars.org, but it said "XX-XXX has already been deployed". now there is another one with https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-grid/5.0.0-beta7/
![image](https://user-images.githubusercontent.com/31067185/37890742-600465be-30da-11e8-8f5a-ea36f53b8ba1.png)

**Comment by jamesward** [comment]
I'm not sure what went wrong with that one as it was partially deployed.  I'm redeploying it now.

**Comment by ZheSun88** [comment]
Thank you! How are you able to redeploy it? What should we do the next time this happens (instead of reporting to you)?

**Comment by ZheSun88** [comment]
Okay, thanks again for that.. :-)
