### ISSUE TITLE
New WebJar contribution: dna.js

### ISSUE THREAD

**Issue by poikilotherm** [webjars/webjars#1747]
Dear admired people running webjars,

I would be very thankful if you could consider reviewing and integrating my [dna.js](https://github.com/dnajs/dna.js) webjar config, to be found at https://github.com/poikilotherm/webjar-dna.js.

Any comments and hints are much appreciated, as this is my first time creating a WebJar. :-)
Thank you!

Cheers
Oliver

EDIT: I forgot to mention: I already tried to create this from NPM as a `org.webjar.npm` package. That didn't work out so well, as the actual JS code wasn't integrated, just the mocha tests.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/dna.js

This will be released shortly.

**Comment by poikilotherm** [comment]
Thanks for merging and cleaning up my mess... Next time I'll know better :-)
