### ISSUE TITLE
librairie not found for tempusdominus-bootstrap webjar

### ISSUE THREAD

**Issue by marccollin** [webjars/webjars#1749]
for this component

https://github.com/tempusdominus/bootstrap-4

I have this line in my build.gradle
[compile 'org.webjars.npm:tempusdominus-bootstrap-4:5.0.0-alpha17'](url)

I get this message

```
Could not resolve all files for configuration ':compileClasspath'.
> Could not find org.webjars.npm:jquery:[1.9.1,2),[2.0.0,3),[3.0.0,4).
  Required by:
      project : > org.webjars.npm:tempusdominus-bootstrap-4:5.0.0-alpha17
```

I added this line

`compile 'org.webjars.bower:jquery:3.0.0'`

but get same issue

**Comment by jamesward** [comment]
Can you try:
```
compile 'org.webjars.npm:3.3.1'
```

**Comment by marccollin** [comment]
seem good
