### ISSUE TITLE
Elasticsearch client

### ISSUE THREAD

**Issue by ptahchiev** [webjars/webjars#1750]
Hi,
here's the repository for mobz elasticsearch client (https://github.com/mobz/elasticsearch-head/):

https://github.com/ptahchiev/elasticsearch-client-webjar

**Comment by jamesward** [comment]
Thanks.  How is this different from: https://github.com/webjars/elasticsearch-js

**Comment by ptahchiev** [comment]
Hi @jamesward  elasticsearch-js is a javascript library to create an elasticsearch search server instance. While the one I am referring to is a client library with GUI to connect to an elasticsearch server instance.

**Comment by jamesward** [comment]
Cool.  Thanks for the details.  Here is the fork: https://github.com/webjars/elasticsearch-head

This will be released shortly.
