### ISSUE TITLE
cldr-localenames-modern license issue

### ISSUE THREAD

**Issue by skissane** [webjars/webjars#1753]
Trying to add a new webjar, cldr-localenames-modern, Bower Original, version 33.0.0

Gets the error "License fetch error:".

The license is a custom Unicode Consortium license, but it is permissive (very similar to MIT/BSD/etc).

Note this worked for older versions of cldr-localenames-modern, you have a webjar for 31.0.1, which had the same LICENSE

Also note this license has an SPDX code: https://spdx.org/licenses/Unicode-DFS-2015.html
But unfortunately neither the bower.json nor packages.json declares the license using correct SPDX format.

I have emailed the CLDR maintainers (who I believe are @JCEmmons and @srl295) to ask them if they could kindly fix the license metadata.

But, that is not enough to fix the issue. BinTray will also have to approve the Unicode-DFS-2015 as an open source license. https://bintray.com/api/v1/licenses/oss_licenses does not return that license as a valid open source license. How does one ask BinTray to support a new license?

**Comment by skissane** [comment]
After email discussion with CLDR maintainers, filed a ticket with the CLDR issue tracker - https://unicode.org/cldr/trac/ticket/11059

**Comment by srl295** [comment]
I missed the mention at first, but this makes sense.
It's a little ironic, the JSON output of a Java project getting repackaged as a jar…

**Comment by jamesward** [comment]
The license has been added.
