### ISSUE TITLE
All attempts to determine an acceptable license have been exhausted

### ISSUE THREAD

**Issue by binhbbui411** [webjars/webjars#1755]
During deploying [px-actionable-design](https://github.com/predixdesignsystem/px-actionable-design), I ran to this error even though it's still successfully deployed.

> All attempts to determine an acceptable license have been exhausted.  The bower.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/inuitcss/tools.functions.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: Apache
This problem will likely need to be resolved by working with the library maintainers directly.
WebJar org.webjars.bowergithub.predixdesignsystem px-actionable-design 2.0.0 has already been deployed

**Comment by jamesward** [comment]
This error is due to a bad license definition in the `inuit-functions` repo's `bower.json`.  I need to manually deploy this but there is a bug preventing the override that I need to fix.

**Comment by jamesward** [comment]
I've deployed `inuit-functions` `0.2.0` with the `Apache-2.0` license override.
