### ISSUE TITLE
Maven Central and JCenter have different JARs for org.webjars.bower:jquery:3.2.1

### ISSUE THREAD

**Issue by skissane** [webjars/webjars#1760]
For artifact `org.webjars.bower:jquery:3.2.1`

Maven Central has this JAR:
http://central.maven.org/maven2/org/webjars/bower/jquery/3.2.1/jquery-3.2.1.jar

JCenter has this JAR:
https://jcenter.bintray.com/org/webjars/bower/jquery/3.2.1/jquery-3.2.1.jar

The two JARs are different sizes:
1. The JCenter JAR is 460,268 bytes
2. The Maven Central JAR is 461,058 bytes

They have different number of files:
1. The JCenter JAR contains 153 files
2. The Maven Central JAR has 152 files

The file `META-INF/resources/webjars/jquery/3.2.1/dist/jquery.min.js`
exists in the Maven Central JAR, but is absent in the JCenter JAR

The same file appears to be in the JCenter file under the name
`META-INF/resources/webjars/jquery/3.2.1/jquery.min.js` instead
But that path is absent in the Maven Central version.

I have built an internal project which depends on `org.webjars.bower:jquery:3.2.1`. This inconsistency breaks the project. We have the Maven Central version of the JAR in our internal Artifactory, and that is what our CI pipeline uses. But some of our developers end up pulling the JAR from JCenter directly, which gives them the JCenter version of the JAR.

I could probably work around this through some terribly hacky code, like looking for both paths in the JAR resources, and working out which version of the JAR we have based on that.

But this is wrong. Asking for a given Maven coordinates should always return the same artifact, whether I am using JCenter or Maven Central.

**Comment by jamesward** [comment]
Thanks for reporting this.  I'm not sure how that happened.  Since Maven Central deploys are immutable I've deployed `3.2.1-1` which should stay consistent across both repos.  Please reopen this if you have any issues with that one.
