### ISSUE TITLE
webjars missing from maven

### ISSUE THREAD

**Issue by ZheSun88** [webjars/webjars#1761]
We have the following webjars which are in the bintray but not in the maven

https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-date-picker/3.0.0/

https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-dialog/2.0.0/

https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-list-box/1.0.1/

**Comment by jamesward** [comment]
These should all be deployed.
