### ISSUE TITLE
New WebJar is not a valid ZIP file

### ISSUE THREAD

**Issue by oluwasayo** [webjars/webjars#1764]
Newly published webjars on both Maven Central and Bintray are not valid ZIP files.

https://repo1.maven.org/maven2/org/webjars/bowergithub/polymerelements/paper-dialog-behavior/2.2.2/paper-dialog-behavior-2.2.2.jar

Attempting to extract the above with `unzip` results in

> unzip:  cannot find zipfile directory in one of paper-dialog-behavior-2.2.2.jar or
>         paper-dialog-behavior-2.2.2.jar.zip, and cannot find paper-dialog-behavior-2.2.2.jar.ZIP, period.

Versions 2.2.0 and 2.2.1 work as expected.

**Comment by jamesward** [comment]
Thanks for reporting.  I'm not sure what happened with those files but I've published `2.2.2-1` and it seems to be better.
