### ISSUE TITLE
Jar archive corrupt

### ISSUE THREAD

**Issue by Skalda73** [webjars/webjars#1767]
Hi, 
  I have a problem with this webjar:
https://mvnrepository.com/artifact/org.webjars.npm/browserify-aes
version 1.2.0, the archive jar file is corrupt.
I verified it downloadind by browser:
http://central.maven.org/maven2/org/webjars/npm/browserify-aes/1.2.0/browserify-aes-1.2.0.jar
How to ricreate the archive?

Below log error in Eclipse, I use Ant+Ivy:
[javac] error: error reading /Users/Documents/workspace/adminLTESkeleton/lib/browserify-aes-1.2.0.jar; error in opening zip file
[javac] 1 error

many thx
Matteo

**Comment by jamesward** [comment]
This is being deployed as `1.2.0-1`.
