### ISSUE TITLE
Add a New WebJar - Timeout

### ISSUE THREAD

**Issue by sherzinger** [webjars/webjars#1769]
This just times out after 10 minutes.
Any ideas?

![screen shot 2018-05-23 at 14 32 24](https://user-images.githubusercontent.com/11333940/40424579-4687cb14-5e96-11e8-9c9a-acba9f4857be.png)

**Comment by jamesward** [comment]
The dep graph for that package is massive - 1500 packages.  We need to do some optimizations (#1725).  But it does look like this package should be using `devDependencies` for a lot of the stuff.
