### ISSUE TITLE
Add nodemailer from npm

### ISSUE THREAD

**Issue by borkdude** [webjars/webjars#1771]
Fails with message `null`

![screenshot 2018-05-28 12 16 49](https://user-images.githubusercontent.com/284934/40610076-2f98197a-6271-11e8-8d2c-73a7a30b368f.png)

**Comment by borkdude** [comment]
Still failing.

**Comment by jamesward** [comment]
Still hasn't been deployed.  Waiting on CI...

**Comment by jamesward** [comment]
Ok, should be deployed now.

**Comment by borkdude** [comment]
Cool, it seems to have worked. How long does it typically take to sync to Maven Central?

**Comment by jamesward** [comment]
Cool!  Usually under an hour to get to repo1 and a few hours to get to the search index (which webjars.org uses).

**Comment by borkdude** [comment]
Thanks!
