### ISSUE TITLE
Deploy failing with null

### ISSUE THREAD

**Issue by robtaireeo** [webjars/webjars#1772]
Starting Deploy
Got package info for org.webjars.npm quasar-extras 2.0.2
Determining dependency graph
No dependencies.
Resolved Licenses: MIT -> https://spdx.org/licenses/MIT#licenseText
Converted dependencies to Maven
Converted optional dependencies to Maven
Got the source URL: https://github.com/quasarframework/quasar-extras
Generated POM
null

**Comment by jamesward** [comment]
Duplicate of #1771
