### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by nak-g-its** [webjars/webjars#1774]
Hi, I try to deploy following library,
but deploy was failed.

library: normalize-wheel:1.0.1

error message:
The metadata was missing a required field: /repository/url

**Comment by jamesward** [comment]
That is a required field for us to deploy.  I can manually override it if you can locate the source associated with this package.

**Comment by nak-g-its** [comment]
Thank you for your reply,
the repository is followig,

https://github.com/basilfx/normalize-wheel

**Comment by jamesward** [comment]
This has been deployed:
```
GroupID = org.webjars.npm
ArtifactID = normalize-wheel
Version = 1.0.1
```
