### ISSUE TITLE
Sha1 mismatch

### ISSUE THREAD

**Issue by gpgekko** [webjars/webjars#1777]
I'm getting a checksum mismatch for the `org.webjars.npm#object.omit` 2.0.1 webjar. The `.sha1` file on Maven Central says `1951e6db3e56a215ae3871cd12532956841a95fc`, but the computed value is `702786c725a17860575a57abdaaf2ff3a1296de5`.
I wonder if it might have something to do with its dependency on `org.webjars.npm#for-own` 0.1.5, which had a [failed deploy](https://github.com/webjars/webjars/issues/1729), though I don't immediately see how that might interfere.

**Comment by jamesward** [comment]
I'll probably have to do a new release to fix this.  If I do a `2.0.1-1` will that work for you?

**Comment by gpgekko** [comment]
Yeah, I can work with that.

**Comment by jamesward** [comment]
Version `2.0.1-1` will be deployed shortly.
