### ISSUE TITLE
autocomplete.js webjar

### ISSUE THREAD

**Issue by rbarazzutti** [webjars/webjars#1779]
added algolia's autocomplete.js, here is my repo: https://github.com/rbarazzutti/webjars-autocomplete.js

**Comment by jamesward** [comment]
That repo is missing the `pom.xml`

**Comment by rbarazzutti** [comment]
Hi James!

Forgot to push the master branch ;-)

Are the tags taken into account as well?

Thanks, Raphaël

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/autocomplete.js

This will be released shortly.

On tags... Maven will handle that automatically on release.

**Comment by rbarazzutti** [comment]
Thanks!
