### ISSUE TITLE
Weird webjars in maven

### ISSUE THREAD

**Issue by ZheSun88** [webjars/webjars#1780]
@jamesward problem is with this version `1.3.7` of `iron-flex-layout` webjar, https://search.maven.org/#artifactdetails%7Corg.webjars.bowergithub.polymerelements%7Ciron-flex-layout%7C1.3.7%7CN%2FA

and compare with a correct one, like this https://search.maven.org/#artifactdetails%7Corg.webjars.bowergithub.polymerelements%7Ciron-flex-layout%7C2.0.3%7Cjar
![image](https://user-images.githubusercontent.com/31067185/41700364-ab65c832-7530-11e8-9d6e-a2fc565bd777.png)

 the POM content is not showing in the page, I don't know if this is something wrong or not, but it indeed cause some kind of the build failure with cannot resolve the dependency of `iron-flex-layout 1.3.7`
![image](https://user-images.githubusercontent.com/31067185/41719355-7de458be-7568-11e8-98b6-1e48cc8b161b.png)

**Comment by jamesward** [comment]
Strange.  I can deploy `1.3.7` again with a version of `1.3.7-1` - will that solve your issue?

**Comment by ZheSun88** [comment]
that is fine, we have set an fixed version for this webjar...
when we are deploying our stuff and it suddenly starts to check all the available versions and this one is somehow failed on that..

**Comment by jamesward** [comment]
Sounds like there is a version range transitive dep on this so releasing `1.3.7-1` won't fix that unless you need `1.3.7` which it sounds like you don't.

**Comment by ZheSun88** [comment]
yes, it is not necessary to deploy the 1.3.7-1. the ticket just reminds me the weird maven. 
This issue can be closed now.
