### ISSUE TITLE
Failed to collect dependencies at org.webjars.npm:ng-admin:jar:1.0.12 -> org.webjars.npm:admin-config:jar:[0.12.4,0.13)

### ISSUE THREAD

**Issue by OlgaMaciaszek** [webjars/webjars#1784]
While building the project containing ng-admin 1.0.12 jar, the folowing error has appeared:

```
Failed to collect dependencies at org.webjars.npm:ng-admin:jar:1.0.12 -> org.webjars.npm:admin-config:jar:[0.12.4,0.13): No versions available for org.webjars.npm:admin-config:jar:[0.12.4,0.13) within specified range.
```

**Comment by OlgaMaciaszek** [comment]
@jamesward Unfortunately, it looks like there is yet another missing jar.

**Comment by jamesward** [comment]
I tried to deploy that one but couldn't because it doesn't have a license.  I've filed an issue: https://github.com/marmelab/admin-config/issues/79

**Comment by jamesward** [comment]
Well, that repo has now been archived.  So the only good option is to setup an exclusion in your build.  But I'm not sure how to do that with WRO4J.
