### ISSUE TITLE
Please update graphiql to latest v0.11.11 release

### ISSUE THREAD

**Issue by marceloverdijk** [webjars/webjars#1788]
Currently webjars provides `v0.11.3` and `v0.11.5`. I would like to use the latest `v0.11.11` release.

**Comment by jamesward** [comment]
There are a few flavors or WebJars (NPM, Bower, Classic).  Which do you need?  If NPM or Bower, you can deploy it yourself via https://webjars.org and if you need a Classic, please file the request on the WebJar's repo: https://github.com/webjars/graphiql

**Comment by marceloverdijk** [comment]
Thx @jamesward I created this issue https://github.com/webjars/graphiql/issues/4 for upgrading the classic version.
