### ISSUE TITLE
org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found

### ISSUE THREAD

**Issue by japgolly** [webjars/webjars#1789]
A new issue has begun appearing since a few days ago:

Builds that used to work fine before now fail with an error:

```
org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
```

Example: The only webjars used here are `org.webjars.npm:react:16.3.2` and  `org.webjars.npm:react-dom:16.3.2`.

https://travis-ci.org/japgolly/scalajs-react/jobs/403008499#L914

I'm also seeing it in other builds with the same deps but version 16.2.0 where they worked before.

I can also see that on 11th Jul the webjars were released for 3.0.0 and 4.0.0, even though 3.0.2 was there before. http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.webjars.npm%22%20AND%20a%3A%22js-tokens%22

**Comment by japgolly** [comment]
It seems loose-envify 1.4.0 introduced this with this change: https://github.com/zertosh/loose-envify/commit/c1bdbe99e01078f21150cd89c96a80a9cb4746de

**Comment by japgolly** [comment]
See also: https://stackoverflow.com/questions/51317975/how-to-work-around-broken-transitive-jsdependencies

**Comment by japgolly** [comment]
Turns out this is an SBT issue: https://github.com/sbt/sbt/issues/2647

Workaround in StackOverflow link above

**Comment by jamesward** [comment]
Thanks for figuring this out and putting all the relevant info here!

**Comment by joan38** [comment]
This mean everywhere we use scalajs-react we need to add this `ThisBuild / dependencyOverrides += "org.webjars.npm" % "js-tokens" % "3.0.2"`?
This is uge!
