### ISSUE TITLE
vue-template-es2015-compiler 

### ISSUE THREAD

**Issue by dhakehurst** [webjars/webjars#1790]
> Starting Deploy
>  
> The metadata was missing a required field: /repository/url

I'm not sure why this will not deploy.
the package.json has got the repository url in it!

>   "repository": {
>     "type": "git",
>     "url": "https://github.com/vuejs/vue-template-es2015-compiler"
>   },

**Comment by jamesward** [comment]
That was added after the `1.6.0` release: https://github.com/vuejs/vue-template-es2015-compiler/commit/2e64198a547d0ec077cc8a092b95a7dd04b3cba6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

But I've manually deployed this:
```
GroupID = org.webjars.npm
ArtifactID = vue-template-es2015-compiler
Version = 1.6.0
```

**Comment by dhakehurst** [comment]
Thanks
