### ISSUE TITLE
Error after adding ng-admin 1.0.12 and wro4j 1.8.0 to dependencies: Failure to find org.webjars.npm:github-com-jpetitcolas-ui-codemirror:jar:di 

### ISSUE THREAD

**Issue by OlgaMaciaszek** [webjars/webjars#1791]
Maven build fails with:
Plugin ro.isdc.wro4j:wro4j-maven-plugin:1.8.0 or one of its dependencies could not be resolved: Failure to find org.webjars.npm:github-com-jpetitcolas-ui-codemirror:jar:di

**Comment by jamesward** [comment]
Looks like a transitive hasn't been deployed.  I can't find `ng-admin` `1.2.0` available for deployment.  Is that the right version?

**Comment by OlgaMaciaszek** [comment]
@jamesward sorry my bad - it was 1.0.12.
