### ISSUE TITLE
Old version of jstokens

### ISSUE THREAD

**Issue by tobyweston** [webjars/webjars#1792]
How does stuff end up in webjars?

We had a break caused indirectly (and via transitive dependencies) where webjars contains only older versions ofjstokens. The project owner knew nothing about webjars (see https://github.com/lydell/js-tokens/issues/9).

How do we get newer version uploaded?

**Comment by jamesward** [comment]
The easiest way to get a new version is to go to https://www.webjars.org then search for the WebJar and hit the `+` button.
