### ISSUE TITLE
org.webjars.bowergithub.* packages create a different META_INF structure

### ISSUE THREAD

**Issue by kanwei** [webjars/webjars#1794]
When moving to org.webjars.bowergithub.* packages from org.webjars.bower* packages, the META-INF paths no longer have the version, eg:

"META-INF/resources/webjars/jquery/3.3.1/src/var/support.js"
to
"META-INF/resources/webjars/jquery/src/var/support.js"

This breaks a lot of existing tools, like ring-webjars, which expects the version to be in the path. Is this an intended change?

**Comment by jamesward** [comment]
Yeah, we debated it but in the end went versionless to better support Polymer: https://github.com/webjars/webjars/issues/1670
