### ISSUE TITLE
webjar in bintray but not in maven

### ISSUE THREAD

**Issue by ZheSun88** [webjars/webjars#1797]
Hi James, We have this webjar https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-element-mixin/1.1.2/

It has been there for a day now, but still cannot find in maven.

**Comment by jamesward** [comment]
I'm seeing it at: https://repo1.maven.org/maven2/org/webjars/bowergithub/vaadin/vaadin-element-mixin/1.1.2/

If something is wrong with it, let me know.

**Comment by jamesward** [comment]
Looks like it was just put there.  So maybe someone redeployed it from webjars.org ?

**Comment by ZheSun88** [comment]
yeah, looks like it is fine now, so maybe someone did that. Thanks.
