### ISSUE TITLE
Unable to deploy npm package with sources that are part of a bigger github repo

### ISSUE THREAD

**Issue by roti** [webjars/webjars#1801]
Hi,

I am unable to deploy a [npm package](https://www.npmjs.com/package/@babel/runtime), and I believe it's due to the fact that it does not have its own github repo, but it's part of a bigger repository.
```
Starting Deploy

Got package info for org.webjars.npm babel__runtime 7.0.0-beta.55
Determining dependency graph
Deploying these dependencies: core-js#3.0.0-beta.3 regenerator-runtime#0.12.1
Got package info for org.webjars.npm core-js 3.0.0-beta.3
WebJar org.webjars.npm core-js 3.0.0-beta.3 has already been deployed

Got package info for org.webjars.npm regenerator-runtime 0.12.1
Resolving licenses & dependencies for org.webjars.npm regenerator-runtime 0.12.1
Resolved Licenses: MIT
Converted dependencies to Maven
Converted optional dependencies to Maven
Could not get a Source URL from https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime.git
Resolving licenses & dependencies for org.webjars.npm babel__runtime 7.0.0-beta.55
Resolved Licenses: MIT
Converted dependencies to Maven
Converted optional dependencies to Maven
Could not get a Source URL from https://github.com/babel/babel/tree/master/packages/babel-runtime.git
```

**Comment by jamesward** [comment]
Technically the spec says the `package.json` for these is wrong:
> The URL should be a publicly available (perhaps read-only) url that can be handed directly to a VCS program without any modification. It should not be a url to an html project page that you put in your browser. It's for computers.

But my life is devoted to working around differences between specs & reality, so the "fix" will be deployed in about 15 minutes.
