### ISSUE TITLE
Iron Ajax 2.1.3 pom.xml missing from central

### ISSUE THREAD

**Issue by Artur-** [webjars/webjars#1806]
http://dl.bintray.com/webjars/maven/org/webjars/bowergithub/polymerelements/iron-ajax/2.1.3/iron-ajax-2.1.3.pom is missing from http://central.maven.org/maven2/org/webjars/bowergithub/polymerelements/iron-ajax/2.1.3/

**Comment by jamesward** [comment]
I'm trying a resync.

**Comment by jamesward** [comment]
Let's see if it shows up in the next hour.

**Comment by jamesward** [comment]
That didn't work.  :(  I'll file an issue with Central to have them remove that bad deploy.

**Comment by jamesward** [comment]
This has been redeployed.  Let me know if you don't see a corrected version up there shortly.
