### ISSUE TITLE
Add Tabler to webjar

### ISSUE THREAD

**Issue by phaus** [webjars/webjars#1810]
I just crated a webjar of tabler  https://tabler.github.io.

https://github.com/tabler/tabler-webjar

Could you please add the webjar :-).

**Comment by jamesward** [comment]
Thanks! Here is the fork:
https://github.com/webjars/tabler

This will be released shortly.

**Comment by phaus** [comment]
Still nothing there. At lease the listing at https://www.webjars.org does not contains any tabler JAR.

**Comment by jamesward** [comment]
Maybe just taking a while for the index to update.  It's on Central: https://repo1.maven.org/maven2/org/webjars/tabler/

**Comment by phaus** [comment]
Ah cool :-). Thx again.
