### ISSUE TITLE
Request for npm:tiny-invariant

### ISSUE THREAD

**Issue by spencerhakim** [webjars/webjars#1824]
`npm:react-router` requires this, but it's currently failing to deploy with

```
Starting Deploy
The metadata was missing a required field: /repository/url
```

Unfortunately, the repo data wasn't added until after the most recent version (1.0.3) was published. Could someone manually deploy this for me? Thanks in advance.

**Comment by jamesward** [comment]
I can deploy this manually.  Do you know the repo url?

**Comment by spencerhakim** [comment]
Whoops, sorry, here you go: https://github.com/alexreardon/tiny-invariant

**Comment by jamesward** [comment]
Oh, what version do you need?  I tried `1.0.3` but it was already deployed.

**Comment by spencerhakim** [comment]
Really? It doesn't show up on the Webjars site and can't be resolved when I try to compile. But yeah, I'm looking for `1.0.3`, though technically anything that satisfies `[1.0.2,2)` will do.

sbt error messages, both for when I try to let it automatically resolve and when I explicitly include `1.0.3`
```
unresolved dependency: org.webjars.npm#tiny-invariant;[1.0.2,2): not found
unresolved dependency: org.webjars.npm#tiny-invariant;1.0.3: not found
```

**Comment by jamesward** [comment]
Whoops!  I tried to deploy `react-router` (hadn't had coffee yet).  Deploying `org.webjars.npm#tiny-invariant;1.0.3` now.

**Comment by spencerhakim** [comment]
Thanks!
