### ISSUE TITLE
Deploy fails for react-styleguidist v9.0.4

### ISSUE THREAD

**Issue by roti** [webjars/webjars#1843]
Trying to deploy NPM package react-styleguidist v9.0.4 fails with following error message: "Read 9816 bytes which is more than 8192 without seeing a line terminator"

NPM Package is here: https://www.npmjs.com/package/react-styleguidist

**Comment by jamesward** [comment]
This fix will be deployed in about 20 minutes.

**Comment by roti** [comment]
Thank you.
