### ISSUE TITLE
can you support snapshots repository

### ISSUE THREAD

**Issue by peacetrue** [webjars/webjars#1851]
publish to Maven Central need hours, can you support snapshots repository, eg  https://oss.sonatype.org/content/repositories/snapshots/,  
This will enable a faster and better experience

**Comment by jamesward** [comment]
Typically the snapshots are used for pre-released / mutable artifacts and due to the indeterminate mutation most folks don't use them.  If you are using the NPM or Bower WebJars then you should be able to use the Bintray repo instead.  Let me know if that is an option.

**Comment by peacetrue** [comment]
> Typically the snapshots are used for pre-released / mutable artifacts and due to the indeterminate mutation most folks don't use them. If you are using the NPM or Bower WebJars then you should be able to use the Bintray repo instead. Let me know if that is an option.

I am use NPM WebJars, is the Bintray repo means 'https://www.npmjs.com/', this is an option.
I prefer to reference via maven instead of npm.
Is there a way to reuse the packaging logic of webjars and push it to the local repository?

**Comment by jamesward** [comment]
You can add a new repository to your build tool pointed at:
https://dl.bintray.com/webjars/maven

That should enable immediate usage of the NPM WebJars before they sync to Maven Central.

**Comment by peacetrue** [comment]
@jamesward I did what you said, no problem. Thanks
