### ISSUE TITLE
WebJar Request:tablesorter

### ISSUE THREAD

**Issue by Samigh** [webjars/webjars#1861]
hi @jamesward  please can you fork this project :
https://github.com/Samigh/tablesorter

Thanks
Samir

**Comment by jamesward** [comment]
I think there is already a WebJar for this: https://github.com/webjars/tablesorter

**Comment by Samigh** [comment]
Hi @jamesward 

I need 2.0.5 as version 

thanks
Samir

**Comment by jamesward** [comment]
Can you file that request on the WebJar? https://github.com/webjars/tablesorter/issues

**Comment by jamesward** [comment]
This is a different underlying artifact so I've forked the repo:
https://github.com/webjars/christianbach-tablesorter

Problem now is that there aren't any tagged releases.  I can use a git commit instead of a tag.  Just want the latest?

**Comment by Samigh** [comment]
ok you can do that

**Comment by jamesward** [comment]
The upstream project is what I'm referring to.  I'll just use the latest commit.

**Comment by jamesward** [comment]
Version `07e0918` (a short git commit sha) will be released shortly.
