### ISSUE TITLE
java.lang.ClassLoader can't get resource of monaco-editor 0.17.1

### ISSUE THREAD

**Issue by phucnh** [webjars/webjars#1866]
Hi, I have added [`org.webjars.npm/monaco-editor 0.17.1` version](https://repo.maven.apache.org/maven2/org/webjars/npm/monaco-editor/0.17.1/monaco-editor-0.17.1.jar) by click on plus button (`+`) at https://www.webjars.org/ website as follows:
![image](https://user-images.githubusercontent.com/1061090/62957486-dd79d400-be2f-11e9-96ee-72bfb7a74dae.png)

But the [webjars-locator-core](https://github.com/webjars/webjars-locator-core) didn't extract the content of monaco-editor. 

**Note**: I have tried with `org.webjars.npm/monaco-editor 0.15.6` version and it worked as expected.

Seems that the `java.lang.ClassLoader` could not get the resources from `monaco-editor-0.17.1.jar` with `META-INF/resources/webjars` search path.

Like following:
```scala
package com.example
import java.io.File
import java.net.URL
import java.net.URLClassLoader
import scala.collection.JavaConverters._
import java.lang.ClassLoader

object WebjarExtractorTest extends App {

  val paths = List(
    new URL("file:/Users/a13942/.ivy2/cache/org.webjars.npm/monaco-editor/jars/monaco-editor-0.17.1.jar"),
    new URL("file:/Users/a13942/.ivy2/cache/org.webjars.npm/monaco-editor/jars/monaco-editor-0.15.6.jar")
  )
  val classLoaders = paths.map(path => new URLClassLoader(Array(path), null))

  val resource = "META-INF/resources/webjars"
  println("Resources: ")
  classLoaders.foreach(cl => println(cl.getResource(resource)))
}
```

Then the result is:
```console
[info] Running com.example.WebjarExtractorTest 
Resources: 
null
jar:file:/Users/a13942/.ivy2/cache/org.webjars.npm/monaco-editor/jars/monaco-editor-0.15.6.jar!/META-INF/resources/webjars
```

The resource of monaco-editor 0.17.1 was `null`

**Comment by jamesward** [comment]
This is due to #1863 which I'm working on fixing.  But I'm also working on fixing webjars-locator-core with a fix for the WebJars which don't have the directory entries.  Sorry for the hassle.

**Comment by phucnh** [comment]
Thank for information 👍
