### ISSUE TITLE
License identifier is not compataible with BinTray

### ISSUE THREAD

**Issue by v6ak** [webjars/webjars#1869]
1. Go to https://www.webjars.org/
2. Add a WebJar, choose NPM @zalando/oauth2-client-js in version 0.0.18.
3. Press “Deploy!”

Expected results: The WebJar is deployed.

Actual results: The deploy fails with license error. It seems that it does not handle well license names, so it tries to use  “Apache 2.0” instead of “ Apache-2.0”. The wrong license name is then rejected by Bintray.

```
Resolving licenses & dependencies for org.webjars.npm zalando__oauth2-client-js 0.0.18
All attempts to determine an acceptable license have been exhausted.  The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/zalando-stups/oauth2-client-js.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: Apache 2.0
This problem will likely need to be resolved by working with the library maintainers directly.
```

While this looks similar to #1003, this seems to be a bit different. IIUC, WebJars tries to autodetect the license from Github. It succeeds, but it uses a non-compliant identifier.

**Comment by jamesward** [comment]
Thanks for reporting.  That wasn't a variant we'd seen.  The fix should be deployed in 15 minutes.

**Comment by v6ak** [comment]
Thank you! It seems to work well now.
