### ISSUE TITLE
npm: mmenu-js license error

### ISSUE THREAD

**Issue by nafg** [webjars/webjars#1873]
```
Starting Deploy
Got package info for org.webjars.npm mmenu-js 8.2.3
Determining dependency graph
No dependencies.
Resolving licenses & dependencies for org.webjars.npm mmenu-js 8.2.3
 
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/FrDH/mmenu-js.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: CC-BY-NC-4.0
This problem will likely need to be resolved by working with the library maintainers directly.
```

**Comment by jamesward** [comment]
Unfortunately BinTray doesn't support that license so we will have to use a Classic WebJar, but I think there is already one for this: https://github.com/webjars/jQuery.mmenu

**Comment by nafg** [comment]
What version is it on?

**Comment by jamesward** [comment]
`5.3.2` but can be bumped if needed, just file an issue: https://github.com/webjars/jQuery.mmenu/issues

**Comment by nafg** [comment]
Thanks. I opened https://github.com/webjars/jQuery.mmenu/issues/4. I need
mhead also which goes along with it, how does that work?

Also can you explain why classic webjars avoid the bintray license issue?

**Comment by jamesward** [comment]
Classic WebJars get deployed straight to Maven Central so they don't have the license restrictions.
