### ISSUE TITLE
Syncing to Maven Central doesn't seem to work

### ISSUE THREAD

**Issue by Haprog** [webjars/webjars#1879]
I've been trying to add a WebJar of `vaadin-grid` 5.4.11 for a few days now. Yesterday I tried adding it from webjars.org for many many times every 1 or 2 hours during the day. Everything else seems to be fine but the WebJar never gets added to Maven Central.

The log always ends like this:
```
...
Resolving licenses & dependencies for org.webjars.bowergithub.vaadin vaadin-grid 5.4.11
Resolved Licenses: Apache-2.0
Converted dependencies to Maven
Converted optional dependencies to Maven
Got the source URL: https://github.com/vaadin/vaadin-grid
Generated POM
Fetched BowerGitHub zip
Created BowerGitHub WebJar
Created BinTray Package
Created BinTray Version
Published BinTray Assets
Signed BinTray Assets
Published BinTray Version
Syncing to Maven Central (this could take a while)











Request timeout to bintray.com/108.168.194.93:443 after 300000 ms
```

It went fine to Bintray I think even on the first try. You can see it here: https://dl.bintray.com/webjars/maven/org/webjars/bowergithub/vaadin/vaadin-grid/5.4.11/

But it never goes to Maven Central. Not available e.g. via:
- http://repo.maven.apache.org/maven2/org/webjars/bowergithub/vaadin/vaadin-grid/5.4.11/
- https://repo1.maven.org/maven2/org/webjars/bowergithub/vaadin/vaadin-grid/5.4.11/

First we had the issue with vaadin-grid version 5.4.10, but since it didn't seem to work we released 5.4.11 to see it it would work. In the end after many tries 5.4.10 did get one single file (`.pom.sha1`) synced to Maven Central, that's when we released 5.4.11 the next morning, but after releasing 5.4.11 the older version (5.4.10) somehow got magically fixed (even though it had had only the one file for a whole night, the timestamp of that also got updated) and seems to be good now in Maven Central, but now we have the problem that latest version is 5.4.11 which is also needed in Maven Central. Now it has been well over 24 hours since we first tried adding the WebJar of vaadin-grid 5.4.11.

To me this seems like a problem with https://www.webjars.org/ especially that it always seems to stop with the same error "Request timeout to bintray.com/108.168.194.93:443 after 300000 ms".

**Comment by Haprog** [comment]
After trying to deploy this for several days, this morning it finally worked (no error message) and vaadin-grid v5.4.11 appeared in Maven Central.

Feel free to close this issue if you think it is solved (but maybe it makes sense to keep open if this is a reoccurring issue and it just randomly happened to work now).

**Comment by jamesward** [comment]
Maven Central had a bunch of service issues last week.  I think we could have better error handling or do some kind of background sync retry thing.  But I'll close this issue since it does seem resolved now.
