### ISSUE TITLE
angularjs version of 1.7.9 is not available in Maven 

### ISSUE THREAD

**Issue by Shalini1703** [webjars/webjars#1881]
The angularjs version of 1.7.9 is not available in Maven Repository.May i know, when it will be available because we faced one vulnerability in 1.7.0 which expects 1.7.9 to resolve this vulnerability.

**Comment by jamesward** [comment]
This will be released shortly.  In the future, please file version bump requests on the actual webjar, i.e. https://github.com/webjars/angularjs
