### ISSUE TITLE
WebJar request: node-snackbar

### ISSUE THREAD

**Issue by xabgesagtx** [webjars/webjars#1882]
Hey,
I want to use the library node-snackbar (aka SnackBar) from https://www.polonel.com/snackbar/.

Could you please add my repo for this new webjar?

https://github.com/xabgesagtx/node-snackbar

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/node-snackbar

This will be released shortly.

**Comment by xabgesagtx** [comment]
Thanks!
