### ISSUE TITLE
WebJar request: simple-lightbox

### ISSUE THREAD

**Issue by xabgesagtx** [webjars/webjars#1883]
Hey,
I want to use the library simple-lightbox (aka simpleLightbox) from https://dbrekalo.github.io/simpleLightbox/

Could you please add my repo for this new webjar?

https://github.com/xabgesagtx/simple-lightbox

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/simple-lightbox

This will be released shortly.
