### ISSUE TITLE
New version for webjars-bootbox

### ISSUE THREAD

**Issue by anmeeks-vt-edu** [webjars/webjars#1884]
https://github.com/anmeeks-vt-edu/webjars-bootbox

**Comment by jamesward** [comment]
Are you looking for a new version of https://github.com/webjars/bootbox ?  If so, what version?

**Comment by anmeeks-vt-edu** [comment]
Hi James,  yes!  The current version of bootbox, 5.4.0, applies some useful css classes on the dialog buttons.  I wanted to continue using a webjar rather than break it out to node.  I installed it in my local maven but would prefer to still pull the artifact from central.

**Comment by jamesward** [comment]
This will be released shortly.  In the future please request version bumps on the actual WebJar repo, i.e. https://github.com/webjars/bootbox
