### ISSUE TITLE
Add npm foundation-emails webjar

### ISSUE THREAD

**Issue by bseib** [webjars/webjars#1892]
Hi! Please add `foundation-emails` CSS framework to the list of webjars available.

https://www.npmjs.com/package/foundation-emails
https://github.com/foundation/foundation-emails

BTW -- what does it take to make a webjar available? Something that the open source community can help you with and create PRs? Or it is literally adding an NPM address to a list?

**Comment by jamesward** [comment]
For NPM WebJars you can deploy them via https://www.webjars.org - just click the "Add a WebJar" button.  I've just done that for `foundation-emails` and here are the Maven coordinates:
```
GroupID = org.webjars.npm
ArtifactID = foundation-emails
Version = 2.2.1
```
