### ISSUE TITLE
Release of vaadin-context-menu v4.4.0 is broken

### ISSUE THREAD

**Issue by PiercarloSlavazza** [webjars/webjars#1893]
The new release v4.4.0 of vaadin-context-menu declares a dependency from vaadin-list-box version [1.3.0,2) - but there no version of vaadin-list-box matching pattern [1.3.0,2): indeed, on Maven Central, the latest version of vaadin-list-box is 1.3.0-alpha3 - so the maven builds fail.

Who is in charge of release v4.4.0 of  vaadin-context-menu which can fix this issue?

**Comment by PiercarloSlavazza** [comment]
I also report the error message I get from the failing maven build:

> [INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ilex-vaadin10: Could not resolve dependencies for project eu.elibra.ilex:ilex-vaadin10:jar:r20200420.4-SNAPSHOT: Failed to collect dependencies at                                                 com.vaadin:vaadin-spring-boot-starter:jar:14.1.3 -> com.vaadin:vaadin-core:jar:14.1.3 -> com.vaadin:vaadin-menu-bar-flow:jar:1.0.2 -> org.webjars.bowergithub.vaadin:vaadin-menu-bar:jar:1.0.                                                3 -> org.webjars.bowergithub.vaadin:vaadin-context-menu:jar:4.4.0 -> org.webjars.bowergithub.vaadin:vaadin-list-box:jar:[1.3.0,2): No versions available for org.webjars.bowergithub.vaadin:v                                                aadin-list-box:jar:[1.3.0,2) within specified range -> [Help 1]

**Comment by jamesward** [comment]
Looks like vaadin-list-box 1.3.0 was just deployed: https://repo1.maven.org/maven2/org/webjars/bowergithub/vaadin/vaadin-list-box/1.3.0/

I'm trying the vaadin-context-menu 4.4.0 deploy again.

**Comment by jamesward** [comment]
Looks like this has already been deployed. So you should be good now.
