### ISSUE TITLE
Add support for NPM deployment of packages with ISC license

### ISSUE THREAD

**Issue by bcopy** [webjars/webjars#1896]
Test case : 
* Go to webjars.org and attempt to add a new npm package "vue-golden-layout"
* The deployment will complain that no license is defined for this package, but the package.json does specify a license (ICS license) 
* The package is however correctly deployed

**Comment by jamesward** [comment]
Which version are you trying to deploy? The `2.0.10` version has already been deployed.

**Comment by bcopy** [comment]
Yes the deploy worked, there's just a warning that made thought it had
failed, complaining about the lack of a license.

No biggie, but I thought it's easy to fix.

**Comment by jamesward** [comment]
Ah, I was able to reproduce:
```
Got package info for org.webjars.npm intersection-observer 0.5.1
Resolving licenses & dependencies for org.webjars.npm intersection-observer 0.5.1
All attempts to determine an acceptable license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/w3c/IntersectionObserver.git
The acceptable open source software licenses are at bottom of: https://bintray.com/docs/api/
The provided licenses were: W3C-20150513
```

I'll work on a fix for that.
