### ISSUE TITLE
Can't make Webjar from NPM package because Github repo is private.

### ISSUE THREAD

**Issue by igreulich** [webjars/webjars#1898]
I have a (seemingly) unique issue.

I have an [npm package](https://www.npmjs.com/package/@talloinc/celula), that I need to turn into a WebJar for an app at work. I don't seem to be able to do that because the GitHub link associated with the npm package is a private repo, and therefore 404's for the WebJar creation process.

![Screen Shot 2020-09-04 at 9 43 27 AM](https://user-images.githubusercontent.com/144287/92246172-63c9e380-ee93-11ea-8ccd-5a33efb58b2f.png)

This _seems_ odd to me, since on [the homepage](https://www.webjars.org/) it says, for NPM packages, "Contents mirror NPM package". And I have read in other issues that imply the Webjar just grabs the artifacts in question from the npm repo. (But the error suggests otherwise.)

So I guess I am asking if this is a bug? From everything I can find, it seems like I should be able to do this...

Thank you.

**Comment by jamesward** [comment]
Ah interesting. We read the `package.json` and validate the URLs. I tried to manually deploy this but that didn't work either because we still validate the URLs.  I'm going to fix that so we can get this deployed.

**Comment by igreulich** [comment]
I realize this is an...odd situation with some open bits and some closed bits. But all the same.

Thanks!

**Comment by jamesward** [comment]
I got past the validation we do, but then BinTray wouldn't let us add the package since it tried to validate the existence of the source repo.  So I think our only option is a Classic WebJar (where there is no validation).  Does that work for you?

**Comment by igreulich** [comment]
Let's hold off for the moment. I am working on getting all the i's crossed, and the t's dotted to just open source the repo as well. (Not just the package.)

**Comment by Fisherswamp** [comment]
I think I am having a similar issue, as my GitHub repo is private and I am getting the error:
`The POM for org.webjars.npm:chalk:jar:2.2.2 is missing, no dependency information available`
Am I on the right track and if so, what can I do other than making the repo public?
