### ISSUE TITLE
Getting Failure to find org.webjars.npm:chalk:pom:2.2.2 when running mvn install

### ISSUE THREAD

**Issue by Fisherswamp** [webjars/webjars#1899]
As the title says, I am getting the below errors when trying to install

`Failure to find org.webjars.npm:chalk:pom:2.2.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`
`Failure to find org.webjars.npm:iconv-lite:pom:0.4.21 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`

All my other dependencies work, and I am not sure what the issue is.  I saw in #[1898](https://github.com/webjars/webjars/issues/1898) that they are getting an error due to the repo being private, which mine is too, but I don't think this issue is necessarily related since I am not trying to make a webjar.

**Comment by Fisherswamp** [comment]
Looks like it has something to do with:
https://repo.maven.apache.org/maven2/org/webjars/npm/chalk/2.2.2/chalk-2.2.2.pom
^this resource not existing

**Comment by Fisherswamp** [comment]
I found a workaround by having different dependencies. If anyone is coming here from the same place I was, I am working on Javalin + OpenAPI and I found this pom with working dependancies:

https://github.com/tipsy/javalin-openapi-example/blob/master/pom.xml

**Comment by jamesward** [comment]
I'm not sure what happened on the deploy, but I've requested they delete that artifact so I can re-upload it:
https://issues.sonatype.org/browse/MVNCENTRAL-6151

**Comment by Fisherswamp** [comment]
Ran  it again, and as you said the pom files are there now! However, it looks like lunr:2.3.3 is missing a pom file still:

https://repo.maven.apache.org/maven2/org/webjars/npm/lunr/2.3.3/

**Comment by jamesward** [comment]
Whoops.  I've requested that one also be deleted so I can redeploy: https://issues.sonatype.org/browse/MVNCENTRAL-6152

**Comment by jamesward** [comment]
I've redeployed those and they should be in Maven Central shortly.  Let me know if it works this time.  Thanks for your patience!

**Comment by Fisherswamp** [comment]
Looks to be working now, thanks so much!
