### ISSUE TITLE
mapbox-gl cannot be deployed due to license

### ISSUE THREAD

**Issue by axelfontaine** [webjars/webjars#1902]
It contains the text `SEE LICENSE IN LICENSE.txt` which webjars fails to understand and is therefore unable to deploy the package. 

See https://github.com/mapbox/mapbox-gl-js/blob/main/package.json#L7

**Comment by axelfontaine** [comment]
This is still failing on webjars.org

Is deployment of the new code delayed or is there a way to check when it goes out so I can make sure I don't unnecessarily report this?

**Comment by jamesward** [comment]
Yeah, sorry about that.  I fixed one part but am still working on the other part.

**Comment by jamesward** [comment]
Validated that this is now fixed.
