### ISSUE TITLE
Add support for CC-BY-3.0 license

### ISSUE THREAD

**Issue by platypii** [webjars/webjars#1903]
The fairly popular package `spdx-exceptions` which is a downstream dependency of `npm` and other other packages is not currently deployable with webjars.

It is licensed as CC-BY-3.0 and is the only package downstream of `npm` that is not already in the approved licenses for webjars.

I would propose to add the CC-BY-3.0 license to the list of webjar approved licenses. 

As an example of similar projects allowing this license as open source compatible: https://github.com/bbc/apache2-license-checker/blob/master/scripts/whitelist.js

I will open a fork and PR for this issue shortly for consideration by the maintainers. Thanks!

**Comment by jamesward** [comment]
Now that we are off Bintray, this is resolved.
