### ISSUE TITLE
Please update github-com-novnc-noVNC from 0.6.2 to 1.2.0

### ISSUE THREAD

**Issue by aoindustries** [webjars/webjars#1908]
The webjars for noVNC are for version 0.6.2 released in 2017.

Please update to the 1.2.0 release:
https://github.com/novnc/noVNC/releases/tag/v1.2.0

**Comment by jamesward** [comment]
This is an NPM WebJar so you should be able to deploy the new version yourself. Just go to https://webjars.org and find the WebJar, then click the + button.  Feel free to reopen if you have any issues.
