### ISSUE TITLE
Deployment Error 

### ISSUE THREAD

**Issue by ani2fun** [webjars/webjars#1909]
Hi , 

I am trying to deploy following library but deploy failed with error 

library: robust-predicates
https://www.npmjs.com/package/robust-predicates
https://github.com/mourner/robust-predicates

```
Starting Deploy
The metadata was missing a required field: /repository/url
```

I tried to deploy it using Github Repo Url but the artifiactId is different from what I expected

```
    <artifactId>github-com-mourner-robust-predicates</artifactId>
    <version>2.0.4</version>
```
 
but I want to deploy with artifactId : robust-predicates

```
    <artifactId>robust-predicates</artifactId>
    <version>2.0.4</version>
```

but it this one gives me error, missing a required field: /repository/url.

**Comment by jamesward** [comment]
I've manually deployed this. If you'd like to deploy it on your own you'll need to get that project to add a `repository.url` field to their `package.json` file.

**Comment by ani2fun** [comment]
Thanks James :)
