### ISSUE TITLE
WebJARs for material-components-web v9/v10

### ISSUE THREAD

**Issue by mmoayyed** [webjars/webjars#1911]
Please publish the webjars for:

- material-components-web 9.0.0
- material-components-web 10.0.0

...and all modules they depends on.

You can find the releases available here:
https://github.com/material-components/material-components-web/releases

At the moment, only version 8.0.0 is published on Central. However, version 8.0.0 depends on a list of modules all of which require version 8.0.0 or above and yet, very few of them are published on Central. It looks like they might be available on Bintray instead, but of course, that will not be practical for too long [long](https://github.com/webjars/webjars/issues/1910).

Example build error when using 8.0.0 from Central:

```
> Could not find any version that matches org.webjars.npm:material__floating-label:[8.0.0,9).
Versions that do not match:
- 7.0.0
- 6.0.0
- 4.0.0
- 4.0.0-canary.1
- 3.2.0
- + 18 more
Searched in the following locations:
- file:/home/runner/.m2/repository/org/webjars/npm/material__floating-label/
- https://repo.maven.apache.org/maven2/org/webjars/npm/material__floating-label/maven-metadata.xml
- https://oss.sonatype.org/content/repositories/snapshots/org/webjars/npm/material__floating-label/maven-metadata.xml
- https://oss.sonatype.org/content/repositories/releases/org/webjars/npm/material__floating-label/maven-metadata.xml
Required by:
org.webjars.npm:material-components-web:8.0.0
```

**Comment by jamesward** [comment]
These are NPM WebJars and you can deploy them at https://webjars.org

I'm deploying `material-components-web:9.0.0` now. Will then do `10.0.0`.

**Comment by mmoayyed** [comment]
Thanks much! If I understand correctly, you are saying that the dependency list not published automatically as material-web-comoonents is published? And that one has to do that manually?

**Comment by jamesward** [comment]
When publishing an NPM package via https://webjars.org it will deploy the dependencies. It seems like in your case that didn't happen correctly for some reason.  It might be that a package couldn't be correctly deployed.  I'm publishing `10.0.0` now and then you can try things.  Re-open this issue if it doesn't work correctly.

**Comment by mmoayyed** [comment]
Thank you James. I appreciate the info and help.
