### ISSUE TITLE
WebJar Request: govuk-frontend

### ISSUE THREAD

**Issue by MatthewAtHull** [webjars/webjars#1914]
Hi,

The WebJar generated from NPM for `govuk-frontend` is not very useful because it just contains SASS and unminified JS.

I followed [the contributing guide](https://www.webjars.org/contributing) to create <https://github.com/MatthewAtHull/govuk-frontend>, which is based on the compiled SASS and minified JS, for inclusion in the WebJars organisation.

Thanks,
Matthew

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/govuk-frontend
This will be released shortly.
