### ISSUE TITLE
New WebJar: DataTables Responsive

### ISSUE THREAD

**Issue by dheid** [webjars/webjars#1915]
Hi @jamesward,

for a project I need only a specific DataTable extension and not the rest. So I added a new classic WebJar for DataTables Reponsive:

https://github.com/dheid/datatables-responsive

Could we please include it to the collection of official WebJars?

Thank you very much!

Daniel

**Comment by jamesward** [comment]
Hi there! Looks like we already have this one: https://github.com/webjars/datatables-responsive

**Comment by dheid** [comment]
Ah, I'm so blind. Thank you!
