### ISSUE TITLE
Another new WebJar: DataTables DateTime

### ISSUE THREAD

**Issue by dheid** [webjars/webjars#1916]
Hey @jamesward,

and here is a second DataTables Extension I need a WebJar for: DataTables DateTime.

I did pretty much the same as with DataTables Responsive. Here's the repo:

https://github.com/dheid/datatables-datetime

I hope you can add it as an official WebJar. Thanks again!

Best wishes

Daniel

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/datatables-datetime

This will be released shortly.

**Comment by dheid** [comment]
Great! Many thanks!!!
