### ISSUE TITLE
WebJar for jQuery Tristate

### ISSUE THREAD

**Issue by dheid** [webjars/webjars#1917]
Hi @jamesward,

here is another WebJar for a jQuery Tristate component:

https://github.com/dheid/jquery-tristate

I checked, whether it already exists and didn't find anything.

Would you please add it and create a release? Thank you!!!

Best regards

Daniel

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jquery-tristate
This will be released shortly.
