### ISSUE TITLE
hmrc-frontend WebJar cannot deploy due to "All attempts to determine a license have been exhausted"

### ISSUE THREAD

**Issue by JoPintoPaul** [webjars/webjars#1920]
Currently unable to deploy `hmrc-frontend` version `1.27.0` as `npm` WebJar, due to the following error:
```
Resolving licenses & dependencies for org.webjars.npm hmrc-frontend 1.27.0
All attempts to determine a license have been exhausted. The package.json file did not contain a spec-compliant license definition and the license could not be determined by trolling through the source repo: https://github.com/hmrc/hmrc-frontend.git
This problem will likely need to be resolved by working with the library maintainers directly.
```

I notice there have changes to the license validation, is there documentation of the required license format anywhere?

**Comment by jamesward** [comment]
Whoops. I must have messed something up because that should be working. I'll take a look asap.

**Comment by jamesward** [comment]
Turns out this is a bit tricky because what they publish to NPM doesn't have any license info in it.  Their published `package.json` doesn't have the info and there isn't event a `LICENSE` file in the artifact.  Think you can file an issue with them to fix that?

In the meantime, I've manually deployed this.

**Comment by JoPintoPaul** [comment]
Thanks for manually deploying, really appreciate that. I'll look into the package.json and see what's happening with LICENSE file in the artefact.

**Comment by jamesward** [comment]
Cool. Note that what is in GitHub under the tag is not the same as what is on NPM.
