### ISSUE TITLE
WebJar Request: flexmonster

### ISSUE THREAD

**Issue by mhalaida** [webjars/webjars#1923]
Hi James,

I've followed [the contribution guide](https://www.webjars.org/contributing) and created a Maven build for the flexmonster library. It's not very convenient for us to create a dedicated repo with the build – is it ok if I simply provide you with the contents of the `pom.xml` file?

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>9</version>
    </parent>

    <packaging>jar</packaging>
    <groupId>org.webjars</groupId>
    <artifactId>flexmonster</artifactId>
    <version>2.8.30</version>
    <name>flexmonster</name>
    <description>WebJar for flexmonster</description>
    <url>http://webjars.org</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <upstream.url>
            https://flexmonster.s3.amazonaws.com/dist/flexmonster-pivot-javascript/${version}/FlexmonsterPivotTable-v${version}.zip
        </upstream.url>
        <destDir>${project.build.outputDirectory}/META-INF/resources/webjars/${project.artifactId}/${project.version}
        </destDir>
        <requirejs>
            {
            "paths": {
            "flexmonster": "flexmonster"
            }
            }
        </requirejs>
    </properties>

    <developers>
        <developer>
            <id>flexmonsterteam</id>
            <name>Flexmonster Team</name>
            <email>help@flexmonster.com</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Flexmonster Terms and Conditions</name>
            <url>https://www.flexmonster.com/terms/Flexmonster-Terms-and-Conditions.pdf</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>http://github.com/webjars/flexmonster</url>
        <connection>scm:git:https://github.com/webjars/flexmonster.git</connection>
        <developerConnection>scm:git:https://github.com/webjars/flexmonster.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <build>
        <plugins>
            <plugin>
                <groupId>com.jamesward</groupId>
                <artifactId>unsnapshot-maven-plugin</artifactId>
                <version>0.2</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>unsnapshot</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <get src="${upstream.url}" dest="${project.build.directory}/${project.artifactId}.zip" />
                                <unzip src="${project.build.directory}/${project.artifactId}.zip" dest="${project.build.directory}/${project.artifactId}" />
                                <move todir="${destDir}">
                                    <fileset dir="${project.build.directory}/${project.artifactId}" />
                                </move>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.3</version>
            </plugin>

            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.8</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>sonatype-nexus-staging</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
    </build>

    </project>

Please let me know if otherwise.

Thanks,
Mykhailo

**Comment by jamesward** [comment]
Yup! Should the artifact for this be `FlexmonsterPivotTable` ?

**Comment by mhalaida** [comment]
@jamesward, just `flexmonster` would be fine, thank you.

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/flexmonster

This will be released shortly.
