### ISSUE TITLE
Unable to deploy material-components-web v11

### ISSUE THREAD

**Issue by mmoayyed** [webjars/webjars#1924]
In trying to deploy material-components-web `v11.0.0`, the deploy process fails with the following error:

![image](https://user-images.githubusercontent.com/1205228/114998295-10525600-9eb6-11eb-9db8-3afa6d2eb4fd.png)

I am not sure if this issue belongs here or in the `material-components-web` repo, or if it's an issue at all and might go away in a bit, (since the release is about 10 hours hold). If there is something I can do to help and remove this issue, please let me know.

Thanks!

**Comment by jamesward** [comment]
This is the right place for it. :) The [package.json](https://github.com/material-components/material-components-web/blob/v11.0.0/package.json) doesn't have the required fields.  I'm deploying it now using just the NPM name and it seems like it is working.  (There is different metadata used depending on if you use an NPM package name or a git repo.)

**Comment by mmoayyed** [comment]
Thank you!

**Comment by mmoayyed** [comment]
For future passerbys, same issue with v12 and this approach as recommended by James works well:

![image](https://user-images.githubusercontent.com/1205228/127295664-1131128d-0544-4605-ad60-62f8dc92e4f6.png)
