### ISSUE TITLE
Could not convert provided source uri error when updating NPM package

### ISSUE THREAD

**Issue by LaughingLogic** [webjars/webjars#1925]
When trying to update the NPM libphonenumber-js webjar I get presented with this error:

> Got package info for org.webjars.npm libphonenumber-js 1.9.17
> Determining dependency graph
> No dependencies.
> Resolving licenses & dependencies for org.webjars.npm libphonenumber-js 1.9.17
> Resolved Licenses: MIT
> Converted dependencies to Maven
> Converted optional dependencies to Maven
> Could not convert provided source uri 'git+https://gitlab.com/catamphetamine/libphonenumber-js.git' to a URL
> 

When looking at the `package.json` it does indeed have this:

> "repository":` {
>     "type": "git",
>     "url": "git+https://gitlab.com/catamphetamine/libphonenumber-js.git"
>   },

Should this type of URL be supported?

**Comment by jamesward** [comment]
This fix will be deployed in about 10 minutes.
