### ISSUE TITLE
Please Release Version: 7.x and 6.x

### ISSUE THREAD

**Issue by pocorall** [webjars/webjars#1926]
This project is not updated for a long time, and npm 5.x is not runnable with node 14.x. Please release more recent versions.
Specifically, 7.11.2 and 6.14.13 would be nice, as they are the most recent version right now.

**Comment by mkurz** [comment]
@jamesward I tried to add the latest npm webjar (the npm one, not the classic one) via the UI ("Add a New WebJar" button), which as of today would be 10.8.2, however after clicking "Deploy" I get following error:

```
Starting Deploy
Got package info for org.webjars.npm npm 10.8.2

Determining dependency graph

For strip-ansi-cjs could not convert npm:strip-ansi@^6.0.1 to range
````

Can you check? Thanks!

**Comment by jamesward** [comment]
Oh! Well that `npm:strip-ansi@^6.0.1` syntax is new to me :) I've added support for it and once it is deployed, I'll try this deploy.

**Comment by jamesward** [comment]
It appears that `org.webjars.npm npm 10.8.2` deployed successfully.  Let me know if you have any issues with it.

**Comment by mkurz** [comment]
@jamesward Thanks! Not using it currently, maybe in the upcoming weeks.

IMHO we can close this issue, it's >3 years old and we have latest npm now deployed. (Not sure the classic webjar should be upgraded, but the npm one can be used anyway)
