### ISSUE TITLE
Fail to add `minipass-collect`

### ISSUE THREAD

**Issue by pocorall** [webjars/webjars#1927]
Originally, I tried to include `"org.webjars.npm" % "npm" % "7.16.0"` in an sbt project, but it fails to load a transitive dependency `minipass-collect`.

In `webjars.org`, I pressed `Add a WebJar` button, select `NPM` type, and tried to deploy `minipass-collect` version 1.0.2. It failed with the message

```
Starting Deploy
The metadata was missing a required field: /repository/url
```

**Comment by jamesward** [comment]
Unfortunately that artifact doesn't have source repo info in its `package.json` but I've manually deployed it.
