### ISSUE TITLE
Fail to add some webjars

### ISSUE THREAD

**Issue by pocorall** [webjars/webjars#1928]
Thanks @jamesward for your quick response for #1927. Actually, it was part of the problem. Here I describe the whole:

When I try to include "org.webjars.npm" % "npm" % "7.16.0" in an sbt project, it fails to load these transitive dependencies:
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.webjars.npm#minipass-pipeline;[1.2.4,2): not found
[warn]  :: org.webjars.npm#http-cache-semantics;[4.1.0,5): not found
[warn]  :: org.webjars.npm#minipass-json-stream;[1.0.1,2): not found
[warn]  :: org.webjars.npm#npmcli__node-gyp;[1.0.1,2): not found
[warn]  :: org.webjars.npm#walk-up-path;[1.0.0,2): not found
[warn]  :: org.webjars.npm#promise-all-reject-late;[1.0.0,2): not found
[warn]  :: org.webjars.npm#npmcli__node-gyp;[1.0.2,2): not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::              FAILED DOWNLOADS            ::
[warn]  :: ^ see resolution messages for details  ^ ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.webjars.npm#depd;1.1.2!depd.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

```

For `minipass-pipeline`, `promise-all-reject-late`, `@npmcli/node-gyp` failed to add a WebJar on webjars.org with this message:
```
Starting Deploy
The metadata was missing a required field: /repository/url
```
For `walk-up-path`, `minipass-json-stream` failed to add a WebJar on webjars.org with this message:
```
Starting Deploy
Response was 404 for Could not get the current URL for https://github.com/XXXX because status was Not Found
```

For `http-cache-semantics` 4.1.0, the project is already published *without* the pom file:
https://repo1.maven.org/maven2/org/webjars/npm/http-cache-semantics/4.1.0/http-cache-semantics-4.1.0.pom

For `depd` 1.1.2, its sha1 gone wrong:
```
[info] downloading https://repo1.maven.org/maven2/org/webjars/npm/depd/1.1.2/depd-1.1.2.jar ...
[warn]  [FAILED     ] org.webjars.npm#depd;1.1.2!depd.jar: invalid sha1: expected=5a519f688a4d46262337b0c8c4d7478a72b48a95 computed=a13dc4dea07dd1c47cd8aa5aa325e445857171f5 (850ms)
[warn]  [FAILED     ] org.webjars.npm#depd;1.1.2!depd.jar:  (0ms)
```

**Comment by jamesward** [comment]
Thanks for the details. I'll get these fixed and report my progress.

**Comment by jamesward** [comment]
`minipass-pipeline`, `promise-all-reject-late`, and `@npmcli/node-gyp` have been released so they'll be in Maven Central shortly.

**Comment by jamesward** [comment]
The original source repo for `walk-up-path` is gone so I made a new one: https://github.com/webjars/_npm-walk-up-path
Same for `minipass-json-stream` so the new one is: https://github.com/webjars/_npm-minipass-json-stream

I've released both of those.

**Comment by jamesward** [comment]
I've requested that the broken `http-cache-semantics` and `depd` artifacts be removed so I can redeploy them:
https://issues.sonatype.org/browse/MVNCENTRAL-6783

**Comment by pocorall** [comment]
Thanks for your amazing help! By the way, is there some way to modify webjar system to solve these problems? When some source code url is missing, if webjar uploader can specify it, I could solve this problem by myself.

**Comment by jamesward** [comment]
I have an admin tool to override the source URL but have kept this just for admins to preserve integrity of the metadata.

**Comment by pocorall** [comment]
I understand. Thank you for your care.

**Comment by jamesward** [comment]
`depd` and `http-cache-semantics` have been redeployed. Some hopefully once this gets to maven central we are good. Please re-open this if not. Thanks!
