### ISSUE TITLE
WebJar Request: JSmol

### ISSUE THREAD

**Issue by leadpony** [webjars/webjars#1930]
Hello @jamesward 

Jmol is an open-source Java viewer for chemical structures in 3D.
http://jmol.sourceforge.net/
And JSmol is the HTML5 modality of Jmol, able to be embedded into web pages. 

Could you please fork my repo for this new webjar?
https://github.com/leadpony/jsmol

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jsmol

This will be released shortly.
