### ISSUE TITLE
Update plotly.js webjars

### ISSUE THREAD

**Issue by Okeanos** [webjars/webjars#1931]
The plotly.js jars [available right now](https://search.maven.org/search?q=a:plotly.js%20OR%20a:plotly.js-dist) are widely out of date. Is it possible to get them updated?

Depending on the kind, currently published on Maven Central are `1.54.1` to `1.57.1`. However, [latest available](https://github.com/plotly/plotly.js/releases) versions are `1.58.5` and `2.3.1` respectively.

Is that something I could contribute? If so, how?

**Comment by jamesward** [comment]
The best option is to deploy the NPM WebJars yourself from https://www.webjars.org

Let me know if you have any issues.
