### ISSUE TITLE
webjars pull request

### ISSUE THREAD

**Issue by rsDevelopment** [webjars/webjars#1932]
https://github.com/rsDevelopment/accounting.js

**Comment by rsDevelopment** [comment]
Please, approve pull request.

**Comment by jamesward** [comment]
Is this library published to NPM or Bower? If so, you should be able to publish it as a WebJar via https://www.webjars.org

**Comment by rsDevelopment** [comment]
James,

I attempted to do it via the WebJar site. Unfortunately, it can’t detect the license and the upload fails. After doing some research, I found a way to generate a jar with the pom.xml that includes the license definition. This pull request is a fork, from the original project, with the Pom.xml as the only difference as a way to address the license error. 

thank u.

**Comment by jamesward** [comment]
Instead of doing it that way, can you add a `0.4.2` tag in your fork? Then we should be able to deploy this via https://www.webjars.org since the license field was added to the `package.json` after the `0.4.1` release.
