### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by jeromebridge** [webjars/webjars#1937]
I get an error trying to deploy the artifact `outline-icons` version: `1.26.1`

```
Starting Deploy
The metadata was missing a required field: /repository/url
```

**Comment by jamesward** [comment]
This happens when metadata is missing from `package.json` and would need to be added by the upstream project.  As a workaround you should be able to deploy using the Git URL (instead of the NPM package name).  Reopen this issue if you have any problems with that approach.
