### ISSUE TITLE
Webjar for ag-grid enterprise

### ISSUE THREAD

**Issue by earcam** [webjars/webjars#1952]
Hi,

The ag-grid project has moved/been refactored a few times (the old webjar for the enterprise version points to a defunct GitHub project).

Both the community and enterprise versions are maintained in the same repo https://github.com/ag-grid/ag-grid

Webjars has an up-to-date community version `org.webjars.npm:ag-grid-community:26.0.0`, would it be possible to create an artifact for the enterprise version?

Thank you

**Comment by jamesward** [comment]
Is that available via NPM? If so you can deploy it yourself via https://webjars.org

**Comment by earcam** [comment]
Thank you!
