### ISSUE TITLE
Unable to publish govuk-frontend 4.0.0, connection to Nexus repository OSS times out

### ISSUE THREAD

**Issue by JoPintoPaul** [webjars/webjars#1953]
Been trying to deploy the `4.0.0` release of `govuk-frontend` library via Webjars, but unfortunately the job keeps timing out as follows:

```
Starting Deploy
Got package info for org.webjars.npm govuk-frontend 4.0.0
Determining dependency graph
No dependencies.
Resolving licenses & dependencies for org.webjars.npm govuk-frontend 4.0.0
Resolved Licenses: MIT
Converted dependencies to Maven
Converted optional dependencies to Maven
Got the source URL: https://github.com/alphagov/govuk-frontend
Generated POM
Fetched NPM zip
Created NPM WebJar




Request timeout to oss.sonatype.org/54.175.43.38:443 after 120000 ms
```

**Comment by jamesward** [comment]
It appears that Sonatype has been having some service issues: https://status.maven.org/

I need to see if we can move to their new infrastructure.

**Comment by JoPintoPaul** [comment]
Thanks @jamesward, didn't realise there was a Maven issue, managed to get it deployed now. Thanks for investigating.
