### ISSUE TITLE
How to deal with repos without dist folders

### ISSUE THREAD

**Issue by david-wg2** [webjars/webjars#1958]
I'm not sure how exactly to phrase this, but I want to user highlight.js as a WebJar. I successfully deployed version 11.4.0, but when I browse the files on https://www.webjars.org, there are only source files from https://github.com/highlightjs/highlight.js. What I'm really after are the files from https://highlightjs.org/download: 

```
<link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/styles/default.min.css">
<script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.4.0/build/highlight.min.js"></script>
```

Is there any way to achieve this?

I see that in this particular case, they have https://github.com/highlightjs/cdn-release, but if I try to deploy that I get 

```
/tmp/git8442484226463463246/https:/github.com/highlightjs/cdn-release/package.json (No such file or directory)
```

**Comment by jamesward** [comment]
The NPM WebJar appears to not have any of the compiled artifacts:
https://www.webjars.org/listfiles/highlightjs/10.1.2

(This is just the contents of the NPM package)

But the Classic WebJar does:
https://www.webjars.org/listfiles/highlightjs/10.1.2

So maybe you can use the classic one?

**Comment by david-wg2** [comment]
Thanks @jamesward! I could use the classic one, but that one requires a manual deploy from you guys. I'm looking for a self-service solution to more easily deploy WebJars for projects that don't have a dist folder. Having these folders is becoming less common, but most libraries still offer a CDN versjon with prebuilt files. Maybe it could be possible to:

* Click add WebJar
* Choose "CDN" as type (this would have to be added)
* Enter something like `cdn.jsdelivr.net/gh/highlightjs/cdn-release` in the "Package name or GitHub Repo URL" field

Does this sound like something you could offer?

**Comment by jamesward** [comment]
From what I've seen, many NPM packages include the dist artifacts so this is only occasionally an issue.  For highlightjs I discovered that we can just NPM WebJar `@highlightjs/cdn-assets` to get the dist artifacts.  I've deployed the following from webjars.org:
```
GroupID = org.webjars.npm
ArtifactID = highlightjs__cdn-assets
Version = 11.4.0
```

Let me know if that resolves the issue for you.

**Comment by david-wg2** [comment]
@jamesward That does indeed work for me. How did you add it? Was the `/tmp/git8442484226463463246/https:/github.com/highlightjs/cdn-release/package.json (No such file or directory)` message an unrelated error?

**Comment by jamesward** [comment]
I just put the name `@highlightjs/cdn-assets` into the deploy form.  What did you put into the form?  And gawd if I would have actually read your original message I would have discovered the `@highlightjs/cdn-assets` package yesterday.  Sorry!

**Comment by david-wg2** [comment]
> And gawd if I would have actually read your original message I would have discovered the @highlightjs/cdn-assets package yesterday. Sorry!

No worries :)

I also just put that into the form. I tried both the repo URL and `@highlightjs/cdn-assets`, but it only spit that error message back out. I am not able to resolve `highlightjs__cdn-assets` now though: 

```
Resolution error: Error downloading org.webjars.npm:highlightjs__cdn-assets:11.4.0
  not found: https://repo1.maven.org/maven2/org/webjars/npm/highlightjs__cdn-assets/11.4.0/highlightjs__cdn-assets-11.4.0.pom
```

**Comment by david-wg2** [comment]
Thanks @jamesward, I was able to resolve the dependency now! I will keep an eye on https://www.webjars.org/ and see if the artifact shows up there, and I'll close the issue when it does. I will ping you if it doesn't.

**Comment by david-wg2** [comment]
The WebJar is live on https://webjars.org now, hopefully I'll be able to deploy new versions of it myself. Thanks for your support :)

**Comment by jamesward** [comment]
@david-wg2 Oh no. That is bad. Not sure how this hasn't come up before. I've identified the issue (filed https://github.com/webjars/webjars-file-service/issues/3) and will have a fix shortly.

**Comment by david-wg2** [comment]
> @jamesward Oh no. That is bad. Not sure how this hasn't come up before. I've identified the issue (filed https://github.com/webjars/webjars-file-service/issues/3) and will have a fix shortly.

It's not ideal, but at least it got resolved quickly! I really appreciate the work you do on WebJars :)
