### ISSUE TITLE
Fork request for AlertifyJS 1.13.1

### ISSUE THREAD

**Issue by dheid** [webjars/webjars#1959]
Hi @jamesward !

I want to contribute the AlertifyJS library (https://alertifyjs.com/) version 1.13.1 as a WebJar. The repository URL is https://github.com/MohammadYounes/AlertifyJS

AlertifyJS is licensed under GPLv3 (https://github.com/MohammadYounes/AlertifyJS/blob/master/LICENSE).

Could you please fork the repository https://github.com/dheid/alertifyjs and release a WebJar with it?

Thanks in advance!

Daniel

**Comment by jamesward** [comment]
I noticed there is already a WebJar for this: https://github.com/webjars/alertify.js

Let me know if that is the right one.

**Comment by dheid** [comment]
@jamesward They have the same names, but are different. So I need the second one as well.

**Comment by jamesward** [comment]
Ah cool. Here is the fork:
https://github.com/webjars/alertifyjs

This will be released shortly.
