### ISSUE TITLE
New webjar request

### ISSUE THREAD

**Issue by Bozzzzzo** [webjars/webjars#1965]
I prepared new maven webjar repo for jsrender: https://github.com/Bozzzzzo/jsrender
Can you include it.

Best regards,
D.R.

**Comment by jamesward** [comment]
There is already an NPM WebJar for this:
```
"org.webjars.npm" % "jsrender" % "1.0.2"
```

Would this work for you?

**Comment by Bozzzzzo** [comment]
Hi James,

Well I just checked and I am afraid it is not really good:
 - the version is not the expected one
     (though this is not very important - I just wanted to replace local
copy with proper dependency whitout changing version and then consider
changeing version sometime later)
 - the use of this *org.webjars.npm* package seems to brings tones of
unused dependencies
     this is not only a problem for build perf ; but also for our
*WhiteSource* code scanner that will believe those are used and add it to
bill-of-materials and thirdparty vulnerability scan.

Actually we only need; either *jsrender.js* or *jsrender-min.js* ... (it
was initially copied into our project with is real bad thing to do) ...
But now we have to download it through real maven dependency so that
*WhiteSource* code scanner can see this as a proper third-party.

Hum... but wait let-me try the *org.webjars.bower *instead ...
 ... Ah... that one is way better... it does not pull additional
dependencies...
 *so I could use that one*...
 still could you have the version *"org.webjars.bower" % "jsrender" % "
0.9.74"*  added ?

Best regards,
Didier Reis.

note additional dependencies:
[INFO] +- org.webjars.npm:jsrender:jar:1.0.2:runtime
[INFO] |  \- org.webjars.npm:through2:jar:2.0.5:runtime (version selected
from constraint [2.0.0,3))
[INFO] |     +- org.webjars.npm:readable-stream:jar:2.3.7:runtime (version
selected from constraint [2.3.6,2.4))
[INFO] |     |  +- org.webjars.npm:core-util-is:jar:1.0.3:runtime (version
selected from constraint [1.0.0,1.1))
[INFO] |     |  +- org.webjars.npm:util-deprecate:jar:1.0.2:runtime
(version selected from constraint [1.0.1,1.1))
[INFO] |     |  +- org.webjars.npm:inherits:jar:2.0.4:runtime (version
selected from constraint [2.0.3,2.1))
[INFO] |     |  +- org.webjars.npm:safe-buffer:jar:5.1.2:runtime (version
selected from constraint [5.1.1,5.2))
[INFO] |     |  +- org.webjars.npm:string_decoder:jar:1.1.1:runtime
(version selected from constraint [1.1.1,1.2))
[INFO] |     |  +- org.webjars.npm:process-nextick-args:jar:2.0.1:runtime
(version selected from constraint [2.0.0,2.1))
[INFO] |     |  \- org.webjars.npm:isarray:jar:1.0.0:runtime (version
selected from constraint [1.0.0,1.1))
[INFO] |     \- org.webjars.npm:xtend:jar:4.0.2:runtime (version selected
from constraint [4.0.1,4.1))


Le lun. 11 avr. 2022 à 16:24, James Ward ***@***.***> a
écrit :

**Comment by jamesward** [comment]
I've deployed `org.webjars.bower:jsrender:0.9.74` and it should be in Maven Central in a few hours.  You can deploy NPM & Bower WebJars yourself via https://webjars.org

But let me know if you need a Classic WebJar instead.
