### ISSUE TITLE
New WebJars request for zopfli.js

### ISSUE THREAD

**Issue by northteam** [webjars/webjars#1966]
WebJar project: https://github.com/northteam/zopfli.js-webjars
Original upstream project: https://github.com/imaya/zopfli.js
Thanks.

**Comment by jamesward** [comment]
We usually need a tagged release but the upstream repo doesn't have any tags.  Do you know if this library has any official releases somewhere?

**Comment by northteam** [comment]
I don't think so. But I've released the current version to npm and deployed it to webjars.org. It's really a great feature that we can deploy packages anonymously.
