### ISSUE TITLE
Trying to build new WebJar from NPM fails with "Invalid credentials provided."

### ISSUE THREAD

**Issue by PorkLip** [webjars/webjars#1971]
I just tried to add a new WebJar at www.webjars.org for the npm named "minio", version 7.0.28 ( https://www.npmjs.com/package/minio ) but it fails with the following in the deploy log:

```shell
Starting Deploy
{"id":"unauthorized","message":"Invalid credentials provided."}
```
Is this a problem with www.webjars.org or with the npm package for minio ?

**Comment by jamesward** [comment]
I'm sure this is because of: https://status.heroku.com/incidents/2413

I'll see if I can roll some credentials and get this going again.

**Comment by jamesward** [comment]
I've rolled the credentials and I think this is working again.
