### ISSUE TITLE
NPM WebJar deployment not going through

### ISSUE THREAD

**Issue by slauriere** [webjars/webjars#1972]
Hello,

I'm trying to publish an NPM module as a WebJar. Its identifier is `@slauriere/green-audio-player`, version `1.1.3`. When I hit the "Deploy" button in the "Add a New WebJar" modal, I get the message below with no error as far as I can tell, but the deployment does not go through. I assume there is something invalid in the NPM module but I can't figure it out. Any help appreciated.

```
Starting Deploy
Got package info for org.webjars.npm slauriere__green-audio-player 1.1.3
Determining dependency graph
[...]
```

Regards and thumbs up for a very useful project,

**Comment by slauriere** [comment]
I was actually not patient enough, the WebJar got published successfully 🙂 so everything's fine.

**Comment by jamesward** [comment]
Cool.  Sometimes the dependency graph takes a long time to resolve. Related: https://github.com/webjars/webjars/issues/1725
