### ISSUE TITLE
Adding version 1.1.5 of org.webjars.npm:web-encoding fails

### ISSUE THREAD

**Issue by PorkLip** [webjars/webjars#1973]
I'm trying to add version 1.1.5 of the https://www.npmjs.com/package/web-encoding NPM package but it fails with the message
```
Starting Deploy
The metadata was missing a required field: /repository/url
[ [37minfo [0m] a.a.CoordinatedShutdown - Running CoordinatedShutdown with reason [ApplicationStoppedReason]

```
The repository url is https://github.com/gozala/web-encoding according to https://www.npmjs.com/package/web-encoding .

I saw in another issue that the URL of the repository could be entered directly in the text field when adding a new WebJar, but that will not work in this case since the Maven coordinate ( GAV ) will be incorrect.

**Comment by jamesward** [comment]
Interesting... The required field is in the default branch:
https://github.com/Gozala/web-encoding/blob/default/package.json
But not on the 1.1.5 tag:
https://github.com/Gozala/web-encoding/blob/v1.1.5/package.json

I am manually deploying this WebJar to workaround the issue.
