### ISSUE TITLE
Unauthorized error when deploying new version

### ISSUE THREAD

**Issue by itatdcer** [webjars/webjars#1974]
I was trying to deploy a new version of the package bootstrap-table (1.20.1) but I get the following error:

`{"id":"unauthorized","message":"Invalid credentials provided."}`

![image](https://user-images.githubusercontent.com/64224426/169099869-080b3b54-6f0d-401e-af7e-baaf083df9f8.png)

**Comment by jamesward** [comment]
I've rolled the credentials and this is now fixed.
