### ISSUE TITLE
JAX-RS Resource example for serving Webjars?

### ISSUE THREAD

**Issue by xgp** [webjars/webjars#1975]
Thanks for the great project. I have used Webjars in many projects of mine.

I recently have the requirement of serving Webjars from a JAX-RS resource. Are there any examples or libraries that already do this (like the Spring MVC ones you have)?

Thank you!

**Comment by jamesward** [comment]
What kind of server are you using?

**Comment by xgp** [comment]
I am writing it as a JAX-RS resource so that it can run on multiple servers types. However, the likely candidates are Wildfly (Undertow) and Quarkus (Vert.x).

**Comment by jamesward** [comment]
Reason I ask is that I think usually the server provides serving of the classpath resources - so no need for anything JAX-RS.  I haven't kept up on all the JAX-RS stuff though.  Some details on WebJars in Quarkus is here: https://quarkus.io/guides/http-reference

Does that help at all?

**Comment by xgp** [comment]
I'll try that. Thanks!
