### ISSUE TITLE
Can't deploy @vue/compiler-sfc:2.7.7

### ISSUE THREAD

**Issue by manuelleduc** [webjars/webjars#1976]
Hello all,

In order to deploy `vue:2.7.7` (https://search.maven.org/artifact/org.webjars.npm/vue/2.7.7/jar) I apparently need to deploy `@vue/compiler-sfc:2.7.7` as well.

But, when deploying on https://www.webjars.org/, I have the following logs:

```
Starting Deploy
The metadata was missing a required field: /repository/url
[[37minfo[0m] a.a.CoordinatedShutdown - Running CoordinatedShutdown with reason [ApplicationStoppedReason]
```

![image](https://user-images.githubusercontent.com/327856/179931884-6039e5b7-b5a2-41aa-a170-c024bd2cbf85.png)

Looking for the logger error, I came across https://github.com/webjars/webjars/issues/1774 where @jamesward proposed to manually override the missing field.

Would it be possible to do the same operation for `@vue/compiler-sfc:2.7.7`?

Thanks.

**Comment by manuelleduc** [comment]
Note that I managed to deploy `vue:2.7.10` https://www.webjars.org/ so the issue has probably been fixed.

**Comment by jamesward** [comment]
I'm manually deploying that with the repo url.  Can you try this operation again in a couple hours and reopen this if you have any issues?  Thanks!
