### ISSUE TITLE
tiny-svg: seems to be broken in 3.0.0

### ISSUE THREAD

**Issue by jfastnacht** [webjars/webjars#1982]
The WebJAR for [`tiny-svg`](https://github.com/bpmn-io/tiny-svg) in `org.webjars.npm` seems to be broken in version [`3.0.0`](https://repo.maven.apache.org/maven2/org/webjars/npm/tiny-svg/3.0.0/).

While it is available in the Maven repository, it does not contain all files that should be there (e.g. `jar` itself and `pom`):

![grafik](https://user-images.githubusercontent.com/6183607/212097774-5861206e-cd43-4cfc-b0a8-2f6d7d1f88e4.png)

And in the dropdown on webjars.org the version `3.0.0` is not available:

![grafik](https://user-images.githubusercontent.com/6183607/212097908-a8f4df39-f794-432f-8f57-5fe0b308ab8a.png)

I have tried to add it, but it doesn't seem to work (maybe because it's already there, even if broken).

**Comment by jfastnacht** [comment]
I have created an issue in the Community Support: https://issues.sonatype.org/browse/MVNCENTRAL-7806

**Comment by jfastnacht** [comment]
It was fixed.

**Comment by jamesward** [comment]
Sorry I somehow missed this issue!  It appears that when this artifact was first published it didn't get all the files.  You did the correct thing to get Sonatype to delete what was there so it could be republished.  Now all appears correct.  Thanks for tackling this and sorry again that I missed it.
