### ISSUE TITLE
Error with simplepicker jar

### ISSUE THREAD

**Issue by coreagile** [webjars/webjars#1985]
After adding simplepicker:2.0.4, I get dependency resolution issues:

```
No versions available for org.webjars.npm:atob:jar:[2.1.1,3) within specified range
No versions available for org.webjars.npm:atob:jar:[2.1.2,3) within specified range
Could not resolve version conflict among [org.webjars.npm:simplepicker:jar:2.0.4 -> 
org.webjars.npm:ts-loader:jar:[5.4.3,6) -> org.webjars.npm:micromatch:jar:[3.1.4,4) -> 
org.webjars.npm:snapdragon:jar:[0.8.1,0.9) -> org.webjars.npm:base:jar:[0.11.1,0.12) -> 
org.webjars.npm:cache-base:jar:[1.0.1,2) -> 
org.webjars.npm:has-value:jar:[1.0.0,2), org.webjars.npm:simplepicker:jar:2.0.4 -> 
org.webjars.npm:ts-loader:jar:[5.4.3,6) -> org.webjars.npm:micromatch:jar:[3.1.4,4) -> 
org.webjars.npm:snapdragon:jar:[0.8.1,0.9) -> org.webjars.npm:base:jar:[0.11.1,0.12) -> 
org.webjars.npm:cache-base:jar:[1.0.1,2) -> org.webjars.npm:unset-value:jar:[1.0.0,2) -> 
org.webjars.npm:has-value:jar:[0.3.1,0.4)]
```

I wonder if it may be related to the fact that `atob` is hosted on a gitea repo and there was an error converting it? The only available git URL I saw on their website was https://git.coolaj86.com/coolaj86/atob.js.git

Attempting to use the URL caused the deployer to choose a different package name to publish to maven, which likely wouldn't help with my dependency issue.

Deploy log for `atob`:

```
Starting Deploy
Got package info for org.webjars.npm atob 2.1.2
Determining dependency graph
No dependencies.
Resolving licenses & dependencies for org.webjars.npm atob 2.1.2
Resolved Licenses: MIT,Apache-2.0
Converted dependencies to Maven
Converted optional dependencies to Maven
Could not convert provided source uri 'git://git.coolaj86.com/coolaj86/atob.js.git' to a URL
[[37minfo[0m] a.a.CoordinatedShutdown - Running CoordinatedShutdown with reason [ApplicationStoppedReason]
```

**Comment by jamesward** [comment]
I think I can get that fixed.  Will keep you posted.

**Comment by coreagile** [comment]
Thanks!Stephen Castro-Starkeyforgiveness | bravery | honesty | fairness | leadership | creativitySent from my iPhoneOn Mar 17, 2023, at 12:28, James Ward ***@***.***> wrote:﻿
I think I can get that fixed.  Will keep you posted.

**Comment by jamesward** [comment]
This should be deployed in ~15 minutes.  Will see if it fixes it.

**Comment by jamesward** [comment]
The atob artifact was deployed:
```
GroupID = org.webjars.npm
ArtifactID = atob
Version = 2.1.2
```

Hopefully that fixes your issue.

**Comment by coreagile** [comment]
Thanks! I wish I knew how to debug this stuff. Purged my `.m2` cache and refetched. Here's what I get now:

```
No versions available for org.webjars.npm:atob:jar:[2.1.1,3) within specified range
No versions available for org.webjars.npm:atob:jar:[2.1.2,3) within specified range
Could not resolve version conflict among [org.webjars.npm:simplepicker:jar:2.0.4 -> 
org.webjars.npm:ts-loader:jar:[5.4.3,6) -> org.webjars.npm:micromatch:jar:[3.1.4,4) -> 
org.webjars.npm:snapdragon:jar:[0.8.1,0.9) -> org.webjars.npm:base:jar:[0.11.1,0.12) -> 
org.webjars.npm:cache-base:jar:[1.0.1,2) -> 
org.webjars.npm:has-value:jar:[1.0.0,2), org.webjars.npm:simplepicker:jar:2.0.4 -> 
org.webjars.npm:ts-loader:jar:[5.4.3,6) -> 
org.webjars.npm:micromatch:jar:[3.1.4,4) -> org.webjars.npm:snapdragon:jar:[0.8.1,0.9) -> 
org.webjars.npm:base:jar:[0.11.1,0.12) -> org.webjars.npm:cache-base:jar:[1.0.1,2) -> 
org.webjars.npm:unset-value:jar:[1.0.0,2) -> org.webjars.npm:has-value:jar:[0.3.1,0.4)]

```
Is any of that meaningful to you? If not, we may as well close this and I'll go with downloading the JS and CSS manually and including it directly in my project. I don't want to waste your time! haha

**Comment by jamesward** [comment]
Sorry, I forgot to mention that it takes a couple of hours for the artifact to get to Maven Central.  You can check here:
https://repo1.maven.org/maven2/org/webjars/npm/atob/

The new version isn't there yet so give it an hour or so and try again.

**Comment by coreagile** [comment]
Ok thanks!

**Comment by coreagile** [comment]
The `atob` issue is gone now! But this issue continues:

```
Could not resolve version conflict among [org.webjars.npm:simplepicker:jar:2.0.4 -> 
org.webjars.npm:ts-loader:jar:[5.4.3,6) -> org.webjars.npm:micromatch:jar:[3.1.4,4) -> 
org.webjars.npm:snapdragon:jar:[0.8.1,0.9) -> org.webjars.npm:base:jar:[0.11.1,0.12) -> 
org.webjars.npm:cache-base:jar:[1.0.1,2) -> 
org.webjars.npm:has-value:jar:[1.0.0,2), org.webjars.npm:simplepicker:jar:2.0.4 -> 
org.webjars.npm:ts-loader:jar:[5.4.3,6) -> org.webjars.npm:micromatch:jar:[3.1.4,4) -> 
org.webjars.npm:snapdragon:jar:[0.8.1,0.9) -> org.webjars.npm:base:jar:[0.11.1,0.12) -> 
org.webjars.npm:cache-base:jar:[1.0.1,2) -> org.webjars.npm:unset-value:jar:[1.0.0,2) -> 
org.webjars.npm:has-value:jar:[0.3.1,0.4)]
```

I can open a separate issue if that makes things easier!

**Comment by jamesward** [comment]
That one is tricky because it looks like the transitive dependencies have different needed versions.  The easiest way to deal with that is to manually override the version for the transitives.  Which build tool are you using?

**Comment by coreagile** [comment]
Kind of you to help! I'm using leiningen. Trying out excluding the transitive dependency, hoping all that matters is the compiled JavaScript in the jar.

**Comment by jamesward** [comment]
I think where the conflict is:
```
org.webjars.npm:has-value:jar:[1.0.0,2)
org.webjars.npm:has-value:jar:[0.3.1,0.4)]
```

So maybe an explicit dependency for that one will fix it.

**Comment by coreagile** [comment]
That seems to be working. Thank you!

**Comment by coreagile** [comment]
I jumped the gun. Have gone down a rabbit hole playing whackamole with dependencies. I just excluded `org.webjars.npm/ts-loader` and am trying to see if that is sufficient to get what I need. 🤷‍♂️

**Comment by coreagile** [comment]
Yep! Since all I needed was the bundled JS and CSS, this worked:

```
[org.webjars.npm/simplepicker "2.0.4"
                  :exclusions [org.webjars.npm/ts-loader
                               org.webjars.npm/typescript]]
```
