### ISSUE TITLE
I added a dependency @ant-design/icons-vue , but it's been a week since he updated it in time

### ISSUE THREAD

**Issue by gsdukbh** [webjars/webjars#2001]
I added a dependency from npm @ant-design/icons-vue v6.1.0 at https://www.webjars.org/ according to the guidelines.

![image](https://user-images.githubusercontent.com/43371824/237003440-32cb36aa-5138-4b80-b4cc-bac7c12501a0.png)
But there is still only version 6.0.1 in maven, and the latest 6.1.0 has not been released.
What should I do to make it work properly?
![image](https://user-images.githubusercontent.com/43371824/237003862-9134bef2-1b02-4d24-8f80-02767f078088.png)

**Comment by jamesward** [comment]
How long ago did you add it?  It takes a few hours for it to get to Maven Central and then it takes a few more hours for it to show up in the index / web view.

**Comment by gsdukbh** [comment]
> How long ago did you add it? It takes a few hours for it to get to Maven Central and then it takes a few more hours for it to show up in the index / web view.
 I added it on April 28th, but it still doesn't appear in the maven. When adding other dependencies they are usually available the next day, but this one seems to be a bit unusual

**Comment by jamesward** [comment]
Ah, it should have shown up by now.  Trying to redeploy it.

**Comment by jamesward** [comment]
Looks like it deployed so it should be available soon:
```
GroupID = org.webjars.npm
ArtifactID = ant-design__icons-vue
Version = 6.1.0
```

**Comment by gsdukbh** [comment]
Thanks, I'll try to see
