### ISSUE TITLE
Please release escape-velocity classic WebJar version 1.0.1

### ISSUE THREAD

**Issue by gilles-gosuin** [webjars/webjars#2019]
I created this pull request a while ago; I'm not sure if that's the process to request classic WebJar updates, but the webjars org fork repository doesn't have GitHub Issues enabled, which makes the version update button on the main page of webjars.org a broken link :/

https://github.com/webjars/escape-velocity/pull/1

**Comment by jamesward** [comment]
Whoops! Sorry I missed that.  You followed the right process but I failed my part somehow.  I'll respond over on the PR.
