### ISSUE TITLE
lit-html version 2.8.0 not selectable for deployment

### ISSUE THREAD

**Issue by wimdeblauwe** [webjars/webjars#2022]
lit 2.8.0 depends on lit-html 2.8.0. Lit itself is already deployed as a webjar, but lit-html is not. I tried to select the version on the webjars website, but it does not show that version in the dropdown.

You can see here it is available on npm: https://www.npmjs.com/package/lit-html

Any idea why it is not available?

**Comment by jamesward** [comment]
Is this in the search results or in the "Add WebJar" list?  In the "Add WebJar" screen, the version was listed for me and is now being deployed so it should be available in a few hours.

**Comment by wimdeblauwe** [comment]
Right, sorry. It was in the search results screen indeed. Got confused there. Thanks for deploying it!
