### ISSUE TITLE
Please publish ckeditor4-fmath-editor

### ISSUE THREAD

**Issue by mpellicer** [webjars/webjars#2042]
Hey,

I've released the ckeditor4-fmath-editor webjar in this GitHub repository:

https://github.com/sakaicontrib/ckeditor4-fmath-plugin

As far as I can tell it builds correctly:
![image](https://github.com/webjars/webjars/assets/8653754/24b3ebf8-78e5-41fe-a3da-b511af865162)

It contains this CKEditor addon https://ckeditor.com/cke4/addon/FMathEditor with a very small set of fixes, documented in separate commits https://github.com/sakaicontrib/FmathEditor

**Comment by jamesward** [comment]
Thanks! Here is the fork:
https://github.com/webjars/ckeditor4-fmath-plugin

This will be releases shortly.

**Comment by mpellicer** [comment]
Thanks @jamesward. I have a question, I've re-released the library under the same version (3.3) because I needed to fix the library path again, but I don't see the changes in the downloaded jar because surely it's in Maven central. Shall I create a minor release or do we have a method to re-push the same version to maven central?

Thanks

**Comment by mpellicer** [comment]
> Thanks @jamesward. I have a question, I've re-released the library under the same version (3.3) because I needed to fix the library path again, but I don't see the changes in the downloaded jar because surely it's in Maven central. Shall I create a minor release or do we have a method to re-push the same version to maven central?
> 
> Thanks

If it's not possible, don't worry much, let's make a new release 3.4
https://github.com/webjars/ckeditor4-fmath-plugin/issues/1

**Comment by jamesward** [comment]
Maven Central doesn't allow overwriting versions.  So I'll release the new version.  In the future you can file an issue or PR on my fork: https://github.com/webjars/ckeditor4-fmath-plugin

**Comment by mpellicer** [comment]
> Maven Central doesn't allow overwriting versions. So I'll release the new version. In the future you can file an issue or PR on my fork: https://github.com/webjars/ckeditor4-fmath-plugin

That makes sense, thanks James, next time I'll submit the work done.
