### ISSUE TITLE
Ladybug 0.0.50 deploy failed?

### ISSUE THREAD

**Issue by jacodg** [webjars/webjars#2044]
My colleague used the Add a WebJar button at https://webjars.org/ for 0.0.50 some time ago but it seems it wasn't successfully deployed because I cannot find version 0.0.50 on the website and at Maven central:

https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/

I tried the Add a WebJar button for this version again but it gives me:

Starting Deploy
Got package info for org.webjars.npm wearefrank__ladybug 0.0.50

Determining dependency graph

No dependencies.

WebJar org.webjars.npm wearefrank__ladybug 0.0.50 has already been deployed

[[37minfo[0m] a.a.CoordinatedShutdown - Running CoordinatedShutdown with reason [ApplicationStoppedReason]

**Comment by jamesward** [comment]
Thanks for reporting. It looks like something went wrong with the deploy.  I've force deployed it so it should be available in a couple hours.  Please re-open if it doesn't work.
