### ISSUE TITLE
Ladybug 0.0.50 deploy still failed

### ISSUE THREAD

**Issue by jacodg** [webjars/webjars#2045]
As I do not have the rights to re-open https://github.com/webjars/webjars/issues/2044 I create a new one. I'm still not able to find version 0.0.50 at https://webjars.org/ and https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/

Thanks for your time and effort.

**Comment by mkurz** [comment]
This is a "problem" with Maven central which I experience a lot. Sometimes it takes a while until the html index pages catch up with the files deployed.
This is not our fault and everything works anyway.

**Comment by jacodg** [comment]
Just checked https://webjars.org/ and https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/ again and now 0.0.50 is listed. @mkurz do you mean that https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/0.0.50/wearefrank__ladybug-0.0.50.jar was probably already available but https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/ wasn't showing it yet?

**Comment by mkurz** [comment]
> @mkurz do you mean that https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/0.0.50/wearefrank__ladybug-0.0.50.jar was probably already available but https://repo.maven.apache.org/maven2/org/webjars/npm/wearefrank__ladybug/ wasn't showing it yet?

Exactly. Sometimes it happens that the files are available already for download, but the listing html page takes a bit longer to get updated or maybe they are cached somewhere/-how and it takes a while until the caches gets cleared.
