### ISSUE TITLE
Deployment Error

### ISSUE THREAD

**Issue by rhazarian** [webjars/webjars#2049]
Hello!

I am trying to deploy `client-only` npm library (https://www.npmjs.com/package/client-only/v/0.0.1?activeTab=versions) but it fails with an error:

```
Starting Deploy
The metadata was missing a required field: /repository/url
```

This library is very small and simple, however it is used as a dependency by various projects (`graphiql` in my case).

I tried to make a github repo for it and use the repo link, however it results in a different `artifactId` so it doesn't help to solve the issue (as the artifactId is needed to be exactly `client-only` for the build system to work propertly).

**Comment by jamesward** [comment]
I can manually deploy it but need to know the repo url. Do you know where the source is?

**Comment by rhazarian** [comment]
@jamesward I would be very glad if you could deploy it! Unfortunately, I was unable to find the source repository. It is possible that it doesn't even exist. You can grab the sources from NPM itself: https://www.npmjs.com/package/client-only/v/0.0.1?activeTab=code
I've also made a repository with the exact copies of these files if it helps. https://github.com/rhazarian/client-only

**Comment by jamesward** [comment]
I've manually deployed this:
```
GroupID = org.webjars.npm
ArtifactID = client-only
Version = 0.0.1
```

Let me know if you have any issues.
