### ISSUE TITLE
Dependency resolution gets an incompatible (too new) version

### ISSUE THREAD

**Issue by rhazarian** [webjars/webjars#2050]
Hello!

I'm trying to deploy `@graphiql/react` version `0.20.3`.

This is how the dependency graph looks:

```
Determining dependency graph


Deploying these dependencies: popmotion#11.0.3 @radix-ui/react-arrow#1.0.3 meros#1.3.0 @react-aria/interactions#3.20.1 toggle-selection#1.0.6 react-remove-scroll-bar#2.3.4 tabbable#6.2.0 is-primitive#3.0.1 @radix-ui/react-use-callback-ref#1.0.1 isobject#3.0.1 hey-listen#1.0.8 @radix-ui/react-use-size#1.0.1 loose-envify#1.4.0 @radix-ui/react-visually-hidden#1.0.3 @radix-ui/react-dropdown-menu#2.0.6 entities#2.1.0 copy-to-clipboard#3.3.3 uc.micro#1.0.6 get-nonce#1.0.1 @radix-ui/react-collection#1.0.3 @radix-ui/react-menu#2.0.6 @headlessui/react#2.0.0-alpha.4 clsx#2.1.0 @types/tern#0.23.9 codemirror-graphql#2.0.10 @radix-ui/react-primitive#1.0.3 framesync#6.0.1 @react-aria/focus#3.16.0 @react-aria/utils#3.23.0 @radix-ui/rect#1.0.1 use-callback-ref#1.3.1 @react-aria/ssr#3.9.2-nightly.4430 @graphiql/toolkit#0.9.1 regenerator-runtime#0.14.1 @swc/helpers#0.5.6 aria-hidden#1.2.3 @radix-ui/react-compose-refs#1.0.1 nullthrows#1.1.1 style-value-types#5.0.0 @radix-ui/react-dialog#1.0.5 linkify-it#3.0.3 @floating-ui/core#1.6.0 @types/estree#1.0.5 @radix-ui/primitive#1.0.1 @radix-ui/react-use-controllable-state#1.0.1 @tanstack/virtual-core#3.0.0-beta.60 @radix-ui/react-focus-guards#1.0.1 @radix-ui/react-focus-scope#1.0.4 @radix-ui/react-tooltip#1.0.7 mdurl#1.0.1 @babel/runtime#8.0.0-alpha.6 @radix-ui/react-use-rect#1.0.1 @react-types/shared#3.22.0 framer-motion#6.5.1 @radix-ui/react-portal#1.0.4 react-remove-scroll#2.5.5 @floating-ui/react#0.26.9 @radix-ui/react-use-layout-effect#1.0.1 vscode-languageserver-types#3.17.6-next.1 graphql-language-service#5.2.0 js-tokens#4.0.0 react-style-singleton#2.2.1 @radix-ui/react-context#1.0.1 @n1ru4l/push-pull-async-iterable-iterator#3.2.0 @radix-ui/react-slot#1.0.2 is-plain-object#2.0.4 @tanstack/react-virtual#3.0.0-beta.60 codemirror#5.65.16 set-value#4.1.0 @radix-ui/react-presence#1.0.1 invariant#2.2.4 @react-stately/utils#3.9.0 @types/codemirror#5.60.15 @floating-ui/utils#0.2.1 @radix-ui/react-direction#1.0.1 argparse#2.0.1 @floating-ui/react-dom#2.0.8 @floating-ui/dom#1.6.1 @radix-ui/react-use-escape-keydown#1.0.3 tslib#2.6.2 @radix-ui/react-id#1.0.1 @radix-ui/react-roving-focus#1.0.4 markdown-it#12.3.2 @radix-ui/react-popper#1.1.3 use-sidecar#1.1.2 @radix-ui/react-dismissable-layer#1.0.5 detect-node-es#1.1.0
```

Here you can see that WebJars is trying to grab `@headlessui/react#2.0.0-alpha` as an example.

However, in the `@graphqil/react`'s `package.json` (https://github.com/graphql/graphiql/blob/main/packages/graphiql-react/package.json) the following version is specified: `"@headlessui/react": "^1.7.15",`.

As far as I know, `2.0.0-alpha` doesn't match `^1.7.15` version spec.

The same problem affects some other dependencies (there is a few of `alpha`s and `beta`s in the dependency graph - they're all wrong).

**Comment by jamesward** [comment]
Thanks for filing this.  Turns out it is tricky because we have to convert NPM ranges to Maven ranges.  The range `^1.7.15` gets converted to `[1.7.15,2)` but Maven considers `2.0.0-alpha` to be less than `2` which I think makes sense.  It seems that the best way to deal with this is to instead make the range `[1.7.15,1.99999)` (which is what [the Maven docs recommend](https://maven.apache.org/pom.html#version-order-specification)).  It is a bit fugly but I think it should fix this.  WDYT?

**Comment by rhazarian** [comment]
Interesting! I didn't know about Maven treating `2.0.0-alpha` less than `2`, but it does make sense indeed.

I think converting it to `[1.7.15,1.99999)` should work! (I agree that it looks a bit ugly, but it seems like there is no better solution, so better to have it like this than incorrect I guess :)).

**Comment by jamesward** [comment]
I've fixed the depGraph resolution time - one example I was working on went from 1m20s to 9s.  So hopefully that is much better. :)  I've deployed the semver change it it seems like version resolution is happening correctly now.  Let me know if you have any issues!

**Comment by rhazarian** [comment]
@jamesward Thank you for the fix! Is there a way to repair the previously deployed WebJars? It appears that the dependency resolution algorithm is now working correctly, however when I try to redeploy `@graphiql/react` (0.20.3) - it's a dependency of `graphiql` (3.1.1) - in the end I get the message that it is already deployed (indeed, I've deployed it previously), and it seems that it's stuck on the previously deployed version with the incorrect dependencies.

**Comment by jamesward** [comment]
With Maven Central we can't redeploy the same version but we can deploy something like `graphiql` `3.1.1-1` which should have the correct ranges in it.  Let me know if you want me to do that.

**Comment by rhazarian** [comment]
Oh, thank you for explanation!

I guess it would be a bit more complex, since there are a few inner dependencies that are affected (so that we would need to deploy `@graphiql/react` `0.20.3-1`, then `graphiql` 3.1.1-1 and so on...

I think for now I'll try to use an older version that I haven't tried to deploy yet - so it should deploy with the correct dependencies. Then I'll try to switch to a newer one some time later.

**Comment by jamesward** [comment]
Yeah, getting the transitives right will be tricky but we can definitely try and if they don't work you'll have to use transitive overrides in your build.  To get things started, I've deployed:
```
org.webjars.npm graphiql 3.1.1-1
org.webjars.npm graphiql__react 0.20.3-1
```

Let me know here how that goes!
