### ISSUE TITLE
Webjar Request: datatables-searchpanes

### ISSUE THREAD

**Issue by maurercw** [webjars/webjars#2066]
Would like to have a webjars classic created for the Datatables SearchPanes plugin:

https://github.com/DataTables/SearchPanes

**Comment by jamesward** [comment]
Outside of NPM, where are the downloadable built js artifacts?

**Comment by maurercw** [comment]
I was looking for them myself while I waited for this to be setup and was disappointed to find they were not part of the release zip!  Not sure how it jives with your process, but you can get them from the cdn:
https://cdn.datatables.net/#SearchPanes

Direct links for the latest version:
https://cdn.datatables.net/searchpanes/2.3.0/css/searchPanes.dataTables.min.css
https://cdn.datatables.net/searchpanes/2.3.0/js/dataTables.searchPanes.min.js

**Comment by jamesward** [comment]
Thanks. That is great. Any other files you need from the CDN?

**Comment by maurercw** [comment]
Not as far as I know yet, thanks!

**Comment by maurercw** [comment]
Well, I take that back.  I think I also need datatables-select, but I can do that as a separate request since it is a separate plugin.

**Comment by jamesward** [comment]
I think that one exists: https://github.com/webjars/datatables-select
Should datatables-searchpanes depend on that WebJar?

**Comment by jamesward** [comment]
Cool. Here is the repo:
https://github.com/webjars/datatables-searchpanes

Can you review before I create the release?

**Comment by maurercw** [comment]
Looks reasonable!

**Comment by jamesward** [comment]
This has been released and should be in Maven Central shortly.
```
org.webjars:datatables-searchpanes:2.3.0
```
