### ISSUE TITLE
Swagger-UI: OSGi manifest is missing starting from v5.15.2

### ISSUE THREAD

**Issue by vkolomeyko** [webjars/webjars#2070]
In the JAR artefact for version [5.15.1](https://repo1.maven.org/maven2/org/webjars/swagger-ui/5.15.1/swagger-ui-5.15.1.jar) the is `META-INF/MANIFEST.MF` file present with the following content:
```
Manifest-Version: 1.0
Bundle-Description: WebJar for Swagger UI
Bundle-License: https://github.com/swagger-api/swagger-ui
Bundle-SymbolicName: org.webjars.swagger-ui
Bundle-Name: Swagger UI
Bundle-Version: 5.15.1
Bundle-ManifestVersion: 2
Build-Jdk-Spec: 1.8
Created-By: Apache Maven Bundle Plugin 5.1.4
Tool: Bnd-5.1.1.202006162103
```
However, in the version [5.15.2](https://repo1.maven.org/maven2/org/webjars/swagger-ui/5.15.2/swagger-ui-5.15.2.jar) this file is no longer present which makes it non-trivial to use this library in the OSGi-enabled environment.
Could you please explain why `MANIFEST.MF` had been removed and if it would be possible to restore it in the next version?

The other thing noticed is that starting from version `5.15.2`: https://repo1.maven.org/maven2/org/webjars/swagger-ui/5.15.2/ new JAR files started to be published: [swagger-ui-5.15.2-sources.jar](https://repo1.maven.org/maven2/org/webjars/swagger-ui/5.15.2/swagger-ui-5.15.2-sources.jar) and [swagger-ui-5.15.2-javadoc.jar](https://repo1.maven.org/maven2/org/webjars/swagger-ui/5.15.2/swagger-ui-5.15.2-javadoc.jar). These JARs are empty and IMO there is little value in publishing them.

Duplicates: https://github.com/swagger-api/swagger-ui/issues/9869

**Comment by jamesward** [comment]
Can you review: https://github.com/webjars/webjars/pull/2071

**Comment by jamesward** [comment]
This change will be deployed shortly.  Once it is deployed I can try a `5.17.2-1` release to see if it works.
