### ISSUE TITLE
NPM Webjar htmx-ext-response-targets:2.0.0 unusable due to duplicate resource name

### ISSUE THREAD

**Issue by axelfontaine** [webjars/webjars#2082]
`org.webjars.npm:htmx-ext-response-targets:2.0.0` contains two `response-targets.js` files. One in the root and one in the `test` directory.

Either the Webjar locator or the webjar building process should ignore that test directory.

Currently referencing `/webjars/htmx-ext-response-targets/response-targets.js` (as would be expected) triggers a `MultipleMatchesException`. 

Because of this, rendering the `htmx-ext-response-targets` effectively unusable.

See also https://github.com/webjars/webjars-locator-core/issues/164

Workaround:
```
<script src="/webjars/htmx-ext-response-targets/2.0.0/response-targets.js"></script>
```
instead of
```
<script src="/webjars/htmx-ext-response-targets/response-targets.js"></script>
```

**Comment by jamesward** [comment]
The NPM WebJars just copy the entire contents of the NPM package over. Unfortunately there isn't a good way to do general filtering of these packages. So the only alternatives are:
- Utilize a Classic WebJar where we can provide more specific packaging
- Work with the upstream htmx-ext-response-targets project to have them exclude the `test` dir in their NPM artifact

Question: What web framework are you using? Spring will move to https://github.com/webjars/webjars-locator-lite which hopefully will resolve this (and if not, we should fix it).

**Comment by axelfontaine** [comment]
I'm using Ktor. I already filed an issue with them 3 months ago to switch to `webjars-locator-lite` after I saw your discussion with the Spring Boot folks. Unfortunately not much has happened since.

See https://youtrack.jetbrains.com/issue/KTOR-6858/Make-webjars-support-compatible-with-native-image

**Comment by axelfontaine** [comment]
Closing as this has been fixed upstream with the merge of
- https://github.com/bigskysoftware/htmx-extensions/pull/53
