### ISSUE TITLE
Cannot add `htmx-ext-head-support` as an NPM Type WebJar

### ISSUE THREAD

**Issue by RobertoGraham** [webjars/webjars#2084]
Deploy Log for version `2.0.0`:

```text
Starting Deploy
Got package info for org.webjars.npm htmx-ext-head-support 2.0.0

Determining dependency graph

No dependencies.

Resolving licenses & dependencies for org.webjars.npm htmx-ext-head-support 2.0.0

The license could not be determined for NPM - htmx-ext-head-support 2.0.0
```

I'm happy to raise an issue in https://github.com/bigskysoftware/htmx-extensions but I'd like to understand what exactly they should do to resolve this.

**Comment by jamesward** [comment]
Thanks for reporting. I think the easiest thing would be for them to add a license to: https://github.com/bigskysoftware/htmx-extensions/blob/main/src/head-support/package.json

And maybe all of their other packages.  Let me know if that doesn't work and we can investigate some other options.
