### ISSUE TITLE
Unable to deploy govuk-frontend 5.4.1 (getting 403 - Forbidden)

### ISSUE THREAD

**Issue by JoPintoPaul** [webjars/webjars#2086]
I'm trying to deploy the latest release of govuk-frontend (https://github.com/alphagov/govuk-frontend) via webjars.org, but I'm getting a 403 - Forbidden response. Is there any more information available, or is anyone able to do this for me?

<img width="1381" alt="Webjars_GovukFrontend_Forbidden" src="https://github.com/user-attachments/assets/baf43112-c9cf-468f-bf06-1fa973ef6745">

**Comment by jamesward** [comment]
Thanks for reporting! I think Sonatype changed something with their auth.  I've updated the credentials and verified it works by deploying govuk-frontend 5.4.1 - let me know if you have any issues.

**Comment by JoPintoPaul** [comment]
Thanks @jamesward 👍
