### ISSUE TITLE
Update etherjs

### ISSUE THREAD

**Issue by straumat** [webjars/webjars#2088]
Hi and thanks a lot for your work! It feels so good to have a nice way to add javascript in my java app!
I don't know how it works but [ethers](https://docs.ethers.org/v6/) is now in release `6.13.1` but on webjars.org, it is stucked to `5.4.6`, do you plan to update it or not ?

**Comment by jamesward** [comment]
Thanks! Since that one is an NPM WebJar, you should be able to click the + button and deploy new versions. I'm doing that now for `6.13.1` and will report back if there are any issues.

**Comment by jamesward** [comment]
After some Maven Central issues, this has now been deployed.
