### ISSUE TITLE
Error boxed content on publishing from npm

### ISSUE THREAD

**Issue by jgribonvald** [webjars/webjars#2089]
Hi
we get a boxed exception when publishing a js lib from NPM, and it doesn't provide help to know the reason of the problem.
![Capture d’écran](https://github.com/user-attachments/assets/56e26cb3-65e6-4653-aae0-3ff529f21535)

Someone can help ?

**Comment by jamesward** [comment]
Well that is not a great error :) I'm investigating.

**Comment by jamesward** [comment]
The fix for this will be deployed in about 15 minutes.
