### ISSUE TITLE
SheetJS - source code moved  

### ISSUE THREAD

**Issue by daanhoogenboezem** [webjars/webjars#2093]
About two years ago, sheetjs moved their source code from https://github.com/SheetJS/sheetjs to https://git.sheetjs.com/sheetjs/sheetjs.

In pull request https://github.com/webjars/sheetjs/pull/1 I've updated the recipe for building the webjar, pointing to the repository that is now authoritative.

**Comment by jamesward** [comment]
Thanks for fixing that!
