### ISSUE TITLE
Add trendchart-elements

### ISSUE THREAD

**Issue by straumat** [webjars/webjars#2095]
Hello and thanks for your work!
Is it possible to add [https://github.com/WebLogin/trendchart-elements](https://github.com/WebLogin/trendchart-elements) ? 
[https://www.npmjs.com/package/@weblogin/trendchart-elements](https://www.npmjs.com/package/@weblogin/trendchart-elements)

Thank you.

**Comment by jamesward** [comment]
This has been published:
```
GroupID = org.webjars.npm
ArtifactID = weblogin__trendchart-elements
Version = 2.0.1
```

In the future you can publish NPM WebJars on your own via https://webjars.org
