### ISSUE TITLE
Locating webjars in a group-independent way, without guessing or scanning the classpath

### ISSUE THREAD

**Issue by dren-dk** [webjars/webjars#2114]
I've seen several takes on methods to get rid of the need to manually change references to the webjar files when a version changes, these all boil down to having a list of well-known maven groups and then searching through the classpath for 
/META-INF/maven/${group}/${webjar}/pom.properties files that then tell the user what version to look for.

This seems inefficient regardless of how the search is performed and I wonder if there ought to be a better mechanism for locating the (hopefully) singular, webjar version in a classpath.

It seems to me that a very easy solution would be to duplicate the pom.properties file to /META-INF/resources/webjars/${artifact}/pom.properties that way anyone looking for the version of the webjar available can just hit that resource, in stead of any inefficient classpath scanning or guessing.

Is this a silly idea and is there a better place to ask about it?

**Comment by jamesward** [comment]
The WebJars locator libraries (like https://github.com/webjars/webjars-locator-lite) do this kind of lookup for you. Is that what you are looking for?

**Comment by flfr-stibosystems-com** [comment]
Yes, thank you!

I was completely unaware of the META-INF/resources/webjars-locator.properties mechanism and had only ever seen the ghastly guess-a-maven-group approach in several other places and I was wondering if that really was the only way.

**Comment by dren-dk** [comment]
Yes, thank you!

I was completely unaware of the META-INF/resources/webjars-locator.properties mechanism and had only ever seen the ghastly guess-a-maven-group approach in several other places and I was wondering if that really was the only way.
