### ISSUE TITLE
A webjar for facebook react.js, please?

### ISSUE THREAD

**Issue by ghost** [webjars/webjars#258]
Hi - please could we have a webjar for react.js -  http://facebook.github.io/react/index.html ?

The library has also been referenced by others at the scala.js mailing list - https://groups.google.com/forum/?fromgroups=#!topic/scala-js/ht20_sDS3Cw

Many thanks!

**Comment by pmgautam** [comment]
Hi  I wanted to use react.js in play framework and imported it as:
  "org.webjars.npm" % "react" % "16.3.2"

Now I see, react.production.js is in two locations one inside cjs and another inside umd which resulted in MultipleMatchException. I've also posted question at https://stackoverflow.com/questions/50459243/multiplematchesexception-while-using-react-webjar but no response so far. Can anyone help me. Thanks!!!!!
