### ISSUE TITLE
new library tablesorter (jQuery plugin)

### ISSUE THREAD

**Issue by drdamour** [webjars/webjars#307]
stab at repo @ https://github.com/drdamour/tablesorter

**Comment by Mottie** [comment]
I'm totally new to webjars, is there a way I can deploy to webjars directly from my repo? 

What do I need to do? From a quick glance, I can easily add & update the version number in the `pom.xml`, but then do I need to add a webhook?

**Comment by jamesward** [comment]
There are a few maintainers that can release Classic WebJars.  You can send Pull Requests to Classic WebJars repos so that we can review, merge, and release new versions.  Or you can contribute more WebJars like you've done already.
