### ISSUE TITLE
New webjar request for strip-json-comments project

### ISSUE THREAD

**Issue by chinmaybijwe** [webjars/webjars#761]
Hi,
I want to list the webjar I have created here:
https://github.com/chinmaybijwe/strip-json-comments

The original source code for the project is here: 
https://github.com/sindresorhus/strip-json-comments/

Thanks for your help and time.

Best,
Chinmay

**Comment by huntc** [comment]
Does this work for you? You need the package.json as per the example I forwarded to you.

**Comment by chinmaybijwe** [comment]
It builds successfully on my local. package.json is included in the referenced project already right? I opened the zipfile in the target folder that contains the whole project with the package.json. Am I missing something? Apologies for the confusion.

**Comment by huntc** [comment]
Cool. Just wanted to make sure.

**Comment by huntc** [comment]
Will publish this now... standby.

**Comment by huntc** [comment]
Released. Thanks!

**Comment by chinmaybijwe** [comment]
awesome! thanks :+1:
