### ISSUE TITLE
Upgrading from play2.2 to play2.3 of the original allocation problem?

### ISSUE THREAD

**Issue by mysoko** [webjars/webjars#762]
index.html：
```html
<html lang="en">
    <head>
	@Html(org.webjars.play.RequireJS.setup("js/app"))
	</head>
...
```
js/app.js：
```js
'use strict';

requirejs.config({
    urlArgs: "bust=" + app_version,
    paths: {
        "ace": webjars.path('ace', 'src-min-noconflict/ace'),
        ...
    },
    shim: {
        "angular-ui-ace": [ "angular", "ace"],
        ...
    }
});

require(['jquery', 'angular', 'angular-ui-ace',
    function($, angular) {
    ...
```
###### Error message:
 The webjars.path() method of getting a WebJar path has been deprecated.  The RequireJS config in the ace WebJar may need to be updated.  Please file an issue: http://github.com/webjars/ace/issues/new(index):31 webjars.pathapp.js:8 (anonymous function)
 ...

I upgraded to play2.3 just do this several versions change:
```sbt
 "org.webjars" %% "webjars-play" % "2.3.0-2",
 "org.webjars" % "bootstrap" % "3.1.1-2",
 "org.webjars" % "requirejs" % "2.1.15",
```

 What do I need to change is correct?

**Comment by jamesward** [comment]
It looks like you need to upgrade your `ace` WebJar to a newer version to get the new RequireJS config.

**Comment by mysoko** [comment]
I use the new ace: "org.webjars" "ace" "%% 01.08.2014",
Not only a ace library error. Have other problems. I didn't do what, just want to upgrade play2.3, before play2.2 is good.

other errors：
![image](https://cloud.githubusercontent.com/assets/75619/5608585/cbe831ea-94c3-11e4-9f7c-5051afd50c11.png)

**Comment by jamesward** [comment]
The newest version of the `ace` WebJar is `1.1.7-1`.  The version ordering probably isn't right because `ace` changed it's versioning system a while back.

For the other WebJars, make sure you have the latest version and if you do then file an issue with each WebJar so that the new RequireJS syntax can be added.

BTW: Those messages are really just warnings so they shouldn't prevent the app from working.

**Comment by mysoko** [comment]
> The webjars.path() method of getting a WebJar path has been deprecated. 

The problem is not the library, webjars changes. I this configuration should be how to change:
```scala
@Html (org.webjars.play.RequireJS.setup ("js/app"))
```
New official has not this configuration:
![image](https://cloud.githubusercontent.com/assets/75619/5609263/2c5d5f92-94d7-11e4-80e1-183d2bf76dc6.png)

With the new configuration I specifies how js/app.js?

**Comment by jamesward** [comment]
Like:

    <script data-main="@routes.Assets.versioned("js/app.js")"
      src="@routes.WebJarAssets.at(WebJarAssets.locate("require.min.js"))"></script>

Is that what you need?
