### ISSUE TITLE
Update webjar request for strip-json-comments project

### ISSUE THREAD

**Issue by chinmaybijwe** [webjars/webjars#763]
Hi,

I recently created a webjar for the strip-json-comments project. Unfortunately I didn't include the maven-antrun-plugin. I have updated my repo with the latest pom.xml and verified that it produces package.json and strip-json-comments.js in the target/classes/META-INF/resources/webjars/ folder.

Here is my repo:
https://github.com/chinmaybijwe/strip-json-comments

Thanks :)

**Comment by huntc** [comment]
Thanks for this. Can you please raise a PR on https://github.com/webjars/strip-json-comments which is a fork of your repo.

**Comment by jamesward** [comment]
As @huntc said, the actual WebJar repo is the right place for issues and PRs pertaining to a WebJar.  So closing this.
