### ISSUE TITLE
WebJar for Polymer/paper-elements

### ISSUE THREAD

**Issue by eximius313** [webjars/webjars#764]
Could you please add new WebJar for Polymer's paper-elements?
https://www.polymer-project.org/docs/elements/paper-elements.html

Kind regards

**Comment by jamesward** [comment]
I can't find a versioned download for that project.  Can you point me to one?

**Comment by eximius313** [comment]
I think this is only what is under the "Get the paper elements" button

**Comment by jamesward** [comment]
I'm not seeing that anywhere...

**Comment by Phil4** [comment]
It would be great for me as well to have paper-element as webjar.
I found the github which tracks its releases: https://github.com/Polymer/paper-elements

**Comment by jamesward** [comment]
This will be fixed by #862.

**Comment by cheleb** [comment]
Is stackoverflow the right place to ask question like this one: http://stackoverflow.com/questions/28657435/webjars-flat-gav-layout ?

**Comment by jamesward** [comment]
GitHub issues and pull requests are the more appropriate place for these kinds of discussions.
