### ISSUE TITLE
Request to create a new webjar: ember-i18n

### ISSUE THREAD

**Issue by bquenin** [webjars/webjars#767]
Hi,

Is it possible to create a new webjar for "ember-i18n"? The cdnjs page is the following:
https://cdnjs.com/libraries/ember-i18n

The requried files are the following:
https://cdnjs.cloudflare.com/ajax/libs/ember-i18n/3.0.0-beta.2/i18n-plurals.js
https://cdnjs.cloudflare.com/ajax/libs/ember-i18n/3.0.0-beta.2/i18n-plurals.min.js
https://cdnjs.cloudflare.com/ajax/libs/ember-i18n/3.0.0-beta.2/i18n.js
https://cdnjs.cloudflare.com/ajax/libs/ember-i18n/3.0.0-beta.2/i18n.min.js

Regards,
BQ.

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/ember-i18n

This will be released shortly.

**Comment by bquenin** [comment]
Great, thanks!
