### ISSUE TITLE
Webjar request for jel-camel

### ISSUE THREAD

**Issue by giacomolm** [webjars/webjars#771]
Hi, 
i created this repo [1] following Contributing page instructions: i hope it's correct.
FYI, jel is a graphical editor that helps working with DSL. 

Thanks for your support!

[1] https://github.com/giacomolm/webjars-jel-camel

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jel-camel

This will be released shortly.
