### ISSUE TITLE
Import AngularJS-drag-drop 

### ISSUE THREAD

**Issue by prasadubhalkar** [webjars/webjars#774]
Here are the necessary items to import angularjs-drag-drop utility to webjars

https://raw.githubusercontent.com/prasadubhalkar/pu_angularjs-drag-drop/master/pom.xml

https://github.com/codef0rmer/angular-dragdrop

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/codef0rmer-angular-dragdrop

This will be released shortly.
