### ISSUE TITLE
Bootstrap Tagsinput: update to latest (0.4.2) and remove pom dependency to bootstrap 2

### ISSUE THREAD

**Issue by bquenin** [webjars/webjars#777]
Hi,

Would it be possible to update Bootstrap Tagsinput to the latest release (0.4.2) and also remove the dependency to bootstrap 2 from the pom, as it's compatible with bot bootstrap 2 and 3, and it conflicts with the bootstrap 3 webjar.

Thanks,
BQ.

**Comment by jamesward** [comment]
What version of Bootstrap does it depend on?

In the future please file these kinds of things on the actual WebJar, i.e. https://github.com/webjars/bootstrap-tagsinput

**Comment by bquenin** [comment]
Sorry for the wrong project issue ... Do you want me to reopen it there?

It relies on:

<dependencies>
<dependency>
<groupId>org.webjars</groupId>
<artifactId>bootstrap</artifactId>
<version>[2.3.2,)</version>
</dependency>
</dependencies>

Whereas it shouldn't rely on any specific bootstrap version (it's compatible with both bootstrap 2 and 3)  since bootstrap is usually provided explicitely.

The problem is that when relying on bootstrap 2, you end up with bootstrap 3 and bootstrap 2 since this webjars requires it.

**Comment by jamesward** [comment]
The dependency definition is just the default but you should be able to easily override it.  And you should never get two different versions of the same artifact.  That isn't allowed by the Maven-metadata-based build tools.

I'm not opposed to the version range but I don't particularly like them.  If you want the version range can you send a PR to the `bootstrap-tagsinput` repo?
