### ISSUE TITLE
Webjar for QUnit 1.16.0   and webjars/qunit issues repository

### ISSUE THREAD

**Issue by bcopy** [webjars/webjars#779]
Hello,

Can you possibly add the QUnit v 1.16 webjar ?

Also, just a note that  : http://github.com/webjars/qunit/issues/new 
raises a HTTP 404 (there's no issues list for that github repo)

Thanks a lot !!

Brice

**Comment by jamesward** [comment]
This will be released shortly.

BTW: I've enabled issues on that repo.  Thanks for the heads up on that.
