### ISSUE TITLE
Add Bootstrap 3 Vector UI Kit

### ISSUE THREAD

**Issue by kfowlks** [webjars/webjars#784]
This is a request for Bootstrap 3 Vector UI Kit as a webjar. 

http://bootstrapuikit.com/

**Comment by jamesward** [comment]
I can't find a versioned download or a license for that library.  Can you point me to those?

**Comment by kfowlks** [comment]
Thanks for looking, I just took a look too and didn't find anything. I just sent off a message hopfully they respond.

**Comment by kfowlks** [comment]
It appears I'm a moron and misread the site. They don't offer HTML/CSS templates just images for web designer layouts.
