### ISSUE TITLE
Add jquery.terminal

### ISSUE THREAD

**Issue by cbeams** [webjars/webjars#790]
Here it is at v0.8.8: https://github.com/etherj/jquery.terminal

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jquery.terminal

This will be released shortly.

**Comment by cbeams** [comment]
Great. Do you encourage / mind the original repository getting deleted at this point? i.e. treating the new fork as canonical/official from here out?

Cheers. Loving webjars, btw. First time really going for it, and it's so much better than dealing with integrating npm/bower/other js toolchains just for dependency management.

**Comment by jamesward** [comment]
It is up to you.  I no longer need your repo.

Thanks for your support!
