### ISSUE TITLE
Webjar for Webpack

### ISSUE THREAD

**Issue by GitsMcGee** [webjars/webjars#792]
Please make a webjar for http://webpack.github.io/

Thank You!

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/webpack

This will be released shortly.

**Comment by GitsMcGee** [comment]
Thanks @jamesward! This might be a dumb question, but for a webjar like this, which has [many dependencies](https://github.com/webpack/webpack/blob/master/package.json), do those dependencies all need to be webjars as well?

**Comment by jamesward** [comment]
Yeah, technically they should be transitive dependencies.  Can you file new issues for the missing ones?  Then once we have them all we should update the `webpack` WebJar to include the transitive dependency definitions.

**Comment by GitsMcGee** [comment]
Great. Will do.

**Comment by GitsMcGee** [comment]
I feel bad creating all this work. I went through and files issues for all of the dependencies, but many of those dependencies have dependencies, which I will get to next.

**Comment by jamesward** [comment]
Well it does motivate me to work more on the npm WebJar sync system. :)  The reason you've discovered so many missing WebJars is that today most WebJar users are browser library users.  This sequence of libraries are more Node / dev toolchain focused.

It will probably take me a few weeks to get all of these done.  We can speed that up if you can tackle some of these as well: http://www.webjars.org/contributing

**Comment by GitsMcGee** [comment]
Sounds good. I'll jump in and tackle a few of these when I can. I want to learn how to do this kind of stuff.

P.S. an npm WebJar sync system would be amazeballs.
