### ISSUE TITLE
Artifact id - Json2  version update 

### ISSUE THREAD

**Issue by himanshu4141** [webjars/webjars#801]
Hi,
Please create a new version of the Json2 webjar.

I have the repo setup at following location -
https://github.com/himanshu4141/json2

Thanks,
Himanshu

**Comment by jamesward** [comment]
How is this different than https://github.com/webjars/json2 ?

**Comment by himanshu4141** [comment]
this the only difference ..  
      <upstreamVersion>20110223</upstreamVersion>
changed to - 
      <upstreamVersion>20140204</upstreamVersion>

**Comment by jamesward** [comment]
Ah. I see.  Can you send a Pull Request to: https://github.com/webjars/json2

**Comment by himanshu4141** [comment]
done ..
