### ISSUE TITLE
Add jsonld.js

### ISSUE THREAD

**Issue by betehess** [webjars/webjars#804]
Here is the repo I created https://github.com/betehess/org.webjars-jsonld.js

Thanks!

**Comment by betehess** [comment]
Not sure how to tie the pom with the tagged release (e.g. https://github.com/digitalbazaar/jsonld.js/releases/tag/0.3.19). The files get published on https://cdnjs.cloudflare.com/ajax/libs/jsonld/${upstream.version} as advertised in their README.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jsonld.js

This will be released shortly.
