### ISSUE TITLE
Webjar for react-tools

### ISSUE THREAD

**Issue by GitsMcGee** [webjars/webjars#815]
https://github.com/facebook/react

Thanks!

**Comment by jamesward** [comment]
Do you need something additional in the existing `react` WebJar?

**Comment by GitsMcGee** [comment]
Hmmm... I'm actually not sure exactly what's going on here. I was specifically referring to this: https://www.npmjs.com/package/react-tools 

But if you look at the repo it's pointing to, it's just the main react repo, that I mentioned above. So are they one in the same? I'll try and dig in a little more.

**Comment by jamesward** [comment]
Here are all of the files in the `react` WebJar: http://www.webjars.org/listfiles/react/0.12.2
If there are additional files from the upstream repo that we should include in there, let me know.
