### ISSUE TITLE
Handsontable

### ISSUE THREAD

**Issue by ukman** [webjars/webjars#818]
Hello WebJars!

I use HandsonTable and ngHandsonTable in my project and that would be really great if I can add these libs as SBT libs.

http://handsontable.com/
https://github.com/handsontable/ngHandsontable

Thnx

**Comment by jamesward** [comment]
Here are the new WebJars:
https://github.com/webjars/handsontable
https://github.com/webjars/ngHandsontable

These will be released shortly.
