### ISSUE TITLE
Please add kube (http://imperavi.com/kube/)

### ISSUE THREAD

**Issue by wizzytod** [webjars/webjars#820]
Kube Web Framework
Kube is a minimalistic Web framework for professional developers and designers.
Kube is one of the world's most advanced and flexible frameworks.
Kube helps you spend less time on routine tasks and more time creating amazing products.
Focus on success, and Kube will cover the technology behind it.

Home:  http://imperavi.com/kube
GitHub: https://github.com/imperavi/kube

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/kube

This will be released shortly.

**Comment by wizzytod** [comment]
Thanks! Great!
