### ISSUE TITLE
Facebook/css-layout

### ISSUE THREAD

**Issue by pasviegas** [webjars/webjars#835]
Hey, facebook just released css-layout. would be awesome to have it in webjars.

https://github.com/facebook/css-layout

Thanks

**Comment by jamesward** [comment]
I can't find a tagged release of that library.  Can you point me to one?

**Comment by cocojack42** [comment]
https://github.com/facebook/css-layout/archive/v1.1.1.zip

how about this?

**Comment by cocojack42** [comment]
How about this: https://github.com/facebook/css-layout/archive/v1.1.1.zip

**Comment by jamesward** [comment]
I've deployed this as an NPM WebJar:
```
GroupID = org.webjars.npm
ArtifactID = css-layout
Version = 1.1.1 
```
