### ISSUE TITLE
Request: Crossroads.js javascript router library

### ISSUE THREAD

**Issue by jn73** [webjars/webjars#841]
http://millermedeiros.github.io/crossroads.js/

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/crossroads.js

This will be released shortly.

**Comment by jn73** [comment]
Excellent, thank you :)

This webjars, and two others doesn't have a proper name. They are listed as WEBJAR_NAME. Just in the directory. The filter function works etc - so I'm happy, but you might wanna have a look at it.

**Comment by jamesward** [comment]
Whoops. I've fixed that and it should be updated on the site later today.
