### ISSUE TITLE
jquery-ui-slider-pips

### ISSUE THREAD

**Issue by paddymahoney** [webjars/webjars#843]
Requesting
https://github.com/simeydotme/jQuery-ui-Slider-Pips

**Comment by paddymahoney** [comment]
http://simeydotme.github.io/jQuery-ui-Slider-Pips/#installation

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/jQuery-ui-Slider-Pips

This will be released shortly.
