### ISSUE TITLE
WebJar for FileSaver

### ISSUE THREAD

**Issue by brunobodson** [webjars/webjars#846]
https://github.com/eligrey/FileSaver.js/

A webjar of FileSaver would really help me out.

Thank you in advance

**Comment by jamesward** [comment]
There isn't a tagged release for this library in which case we usually don't create a WebJar.  I've filed an issue asking that they tag a release:
https://github.com/eligrey/FileSaver.js/issues/130

**Comment by linghengqian** [comment]
Shouldn't this question be closed?  After all filesaver is now in the npm repository.

**Comment by jamesward** [comment]
Sure!
