### ISSUE TITLE
Webjar for Angular-Multiselect

### ISSUE THREAD

**Issue by Aonlaan** [webjars/webjars#848]
Hello,

This is a request for a new webjar to be created for https://github.com/amitava82/angular-multiselect.

Thanks!

**Comment by jamesward** [comment]
There isn't a tagged release for this library and we usually don't create WebJars unless there is a tagged release.  I've asked the library authors to tag a release: https://github.com/amitava82/angular-multiselect/issues/47

In the meantime maybe the other similar Angular library will work for you: https://github.com/webjars/angular-multi-select

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/angular-multiselect

This will be released shortly.
