### ISSUE TITLE
WebJar for rot.js

### ISSUE THREAD

**Issue by ForNeVeR** [webjars/webjars#855]
I've created WebJar for [rot.js](http://ondras.github.io/rot.js/hp/) - roguelike toolkit for JavaScript. Please add it to the WebJars repository. Here's link to my repository: https://github.com/ForNeVeR/rot.js

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/rot.js

This will be released shortly.

**Comment by ForNeVeR** [comment]
And thank you!
