### ISSUE TITLE
Webjar for Paths.js

### ISSUE THREAD

**Issue by andreaferretti** [webjars/webjars#861]
I have made a webjar repository for [Paths.js](https://github.com/andreaferretti/paths-js). The URL of the webjars repo is

https://github.com/andreaferretti/paths-js-webjars

I hope I got everything right in the POM, let me know if there are any issues.

Following other repositories, I have put the main file under `src/main/resources` instead of `src/main/resources/META-INF/resources/paths-js/0.3.2`. The reason is that the main use case I envisage would be to import this library in scala.js projects using [Paths.scala.js](https://github.com/andreaferretti/paths-scala-js) and I think this directory structure is more well-suited for that use case. Again, let me know if this is an issue and I should move the file.

**Comment by jamesward** [comment]
Thanks! Here is the fork:
https://github.com/webjars/paths-js

I've removed the file from the source and replaced it with the release files.  Also I am using the standard WebJar layout for the files.  If you need to deal with path stuff check out the https://github.com/webjars/webjars-locator library.

This will be released shortly.

**Comment by andreaferretti** [comment]
Great! Now, what do I need to do exactly when releasing a new version? I could not find this information on the site.

By the way, I see the name is missing from the main site. The correct name is "Paths.js". I assume this is due to a missing tag `<name>` on the POM? Should I file a PR?

**Comment by jamesward** [comment]
Yeah, please send a PR for the name and anytime you want a new version.

**Comment by andreaferretti** [comment]
Ok, thanks. Just one more info: is there a way to republish the 0.3.2 version with the `<name>` tag? Otherwise I will just add the name for the 0.3.3 version.

**Comment by jamesward** [comment]
For this kind of update we will make it `0.3.2-1`.
