### ISSUE TITLE
new WebJar request  sigmajs

### ISSUE THREAD

**Issue by dilbertside** [webjars/webjars#876]
Hi 
I contributed a new webjar

My webjar contributed is https://github.com/dilbertside/sigmajs.git
Original Library is located https://github.com/jacomyal/sigma.js

I'm open to suggestions to improve the lib compilation.

Remarks:
requirejs is may wrong

**Comment by jamesward** [comment]
Rather than putting the files into the source repo we need to have the build download and re-package them.  Can you take care of that and send a PR to the fork: https://github.com/webjars/sigma.js

**Comment by dilbertside** [comment]
I would kindly oblige if you can give some pointers or some webjars
example, I can get inspiration from, to do that.

The contribution page is missing that part, I guess!

**Comment by jamesward** [comment]
Is the example `pom.xml` not working on the contribution page?  If not, here is the project: https://github.com/webjars/webjars-template-zip
