### ISSUE TITLE
WebJar Request: regularjs

### ISSUE THREAD

**Issue by leeluolee** [webjars/webjars#877]
https://github.com/regularjs/regular 

Thanks!

releaase list at : https://github.com/regularjs/regular/releases/tag/0.3.1

**Comment by jamesward** [comment]
I've created a new WebJar for this from the Bower repo using a new Bower sync engine.  Can you try this out? groupId = `org.webjars.bower` artifactId = `regularjs` version = `0.3.1`

Let me know if you have any problems.
