### ISSUE TITLE
angular-openlayers-directive

### ISSUE THREAD

**Issue by mrevucky** [webjars/webjars#885]
https://github.com/tombatossals/angular-openlayers-directive 

as an alternative to angular-leaflet-directive

THX

**Comment by mrevucky** [comment]
i created this pom, based on the angular-leaflet-directive - is it ok?

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>7</version>
    </parent>

    <packaging>jar</packaging>
    <groupId>org.webjars</groupId>
    <artifactId>angular-openlayers-directive</artifactId>
    <version>0.0.3</version>
    <name>angular-openlayers-directive</name>
    <description>WebJar for angular-openlayers-directive</description>
    <url>http://webjars.org</url>

    <developers>
        <developer>
            <id>mrevucky</id>
            <name>Michal Revucky</name>
            <email>michal.revucky@gmail.com</email>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>MIT</name>
            <url>https://github.com/tombatossals/angular-openlayers-directive/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <url>http://github.com/webjars/angular-openlayers-directive</url>
        <connection>scm:git:https://github.com/webjars/angular-openlayers-directive.git</connection>
        <developerConnection>scm:git:https://github.com/webjars/angular-openlayers-directive.git</developerConnection>
        <tag>HEAD</tag>
    </scm>
    
    <dependencies>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>angularjs</artifactId>
            <version>1.2.16</version>
        </dependency>
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>openlayers</artifactId>
            <version>3.2.0</version>
        </dependency>
    </dependencies>
    
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <upstream.version>0.0.3</upstream.version>
        <upstream.url>https://raw.githubusercontent.com/tombatossals/angular-openlayers-directive/v${upstream.version}/dist</upstream.url>
        <destDir>${project.build.outputDirectory}/META-INF/resources/webjars/${project.artifactId}/${upstream.version}</destDir>
        <requirejs>
            {
                "paths": {
                    "angular-openlayers-directive": "angular-openlayers-directive"
                },
                "shim": {
                    "angular-openlayers-directive": [ "angular" ]
                }
            }
        </requirejs>
    </properties>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>wagon-maven-plugin</artifactId>
                <version>1.0-beta-4</version>
                <executions>
                    <execution>
                        <id>download-full-js</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>download-single</goal>
                        </goals>
                        <configuration>
                            <url>${upstream.url}</url>
                            <fromFile>angular-openlayers-directive.js</fromFile>
                            <toDir>${destDir}</toDir>
                        </configuration>
                    </execution>
                    <execution>
                        <id>download-min-js</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>download-single</goal>
                        </goals>
                        <configuration>
                            <url>${upstream.url}</url>
                            <fromFile>angular-openlayers-directive.min.js</fromFile>
                            <toDir>${destDir}</toDir>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5</version>
            </plugin>

            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.5.1</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>sonatype-nexus-staging</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>true</autoReleaseAfterClose>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>${project.basedir}/src/main/resources</directory>
                <targetPath>${destDir}</targetPath>
            </resource>
        </resources>
    </build>

</project>

**Comment by jamesward** [comment]
Thanks! Here is the new WebJar: https://github.com/webjars/angular-openlayers-directive

This will be released shortly.
