### ISSUE TITLE
is.js

### ISSUE THREAD

**Issue by domkun** [webjars/webjars#886]
Would be geat to have is.js in webjars:
http://arasatasaygin.github.io/is.js/
https://github.com/arasatasaygin/is.js

Links for Version 0.7.1:
https://raw.githubusercontent.com/arasatasaygin/is.js/v0.7.1/is.js
https://raw.githubusercontent.com/arasatasaygin/is.js/v0.7.1/is.min.js

Licence: MIT

**Comment by jamesward** [comment]
I've created a new WebJar from the Bower repo for is.js.  This is based on a new Bower sync engine.  Can you try this out?  groupId = `org.webjars.bower` artifactId = `is_js` version = `0.7.1`

Let me know if you have any problems.

**Comment by domkun** [comment]
Works like a charm. Thank you very much. (Need to have a look on how this works, so next time I am hopefully able to directly send a pull request)

**Comment by jamesward** [comment]
Here are some details on how it works: https://github.com/webjars/webjars/pull/896
