### ISSUE TITLE
Bootstrap-table

### ISSUE THREAD

**Issue by PlsDontPanic** [webjars/webjars#894]
Hi,

I tried to fill in your new webjars request form but just received an exception.
So could you add bootstrap-table
https://github.com/wenzhixin/bootstrap-table

Thanks!

**Comment by jamesward** [comment]
Thanks for trying! Looks like I have some bugs to figure out.  What browser are you using?  Did you fill in all of the fields?

**Comment by pbelmann** [comment]
I'm using firefox and I just left out the optional field.

**Comment by jamesward** [comment]
Can you try the new Bower-based WebJar for this?
groupId = `org.webjars.bower`
artifactId = `bootstrap-table`
version = `1.6.0`
