### ISSUE TITLE
angular-growl-2 RequireJS

### ISSUE THREAD

**Issue by fracoon** [webjars/webjars#895]
Please add {'angular-growl-2-css' : ['/webjarslocator/angular-growl-2/angular-growl']} to angular-growl-2.

This already works great for bootstrap:
requirejs.config({"paths":{"bootstrap":["/webjars/bootstrap/3.3.2-1/js/bootstrap","js/bootstrap"],"bootstrap-css":["/webjars/bootstrap/3.3.2-1/css/bootstrap","css/bootstrap"]},"shim":{"bootstrap":["jquery"]},"packages":[]})

**Comment by jamesward** [comment]
The new css config addition will be released shortly as `0.7.3-1`.  Here is the change:
https://github.com/webjars/angular-growl-2/commit/d7ca64bbe453ac73728f0f828829a956b2ea619f

In the future please file issues on existing WebJars, on their actual repo, like:
https://github.com/webjars/angular-growl-2
