### ISSUE TITLE
WebJar fork request for: Magnific-Popup

### ISSUE THREAD

**Issue by aruizca** [webjars/webjars#911]
https://github.com/aruizca/magnific-popup

Cheers

**Comment by jamesward** [comment]
This WebJar already exists: https://github.com/webjars/magnific-popup

**Comment by aruizca** [comment]
Hi @jamesward 
Sorry about that. I was not aware that the webjars search form was case sensitive and I was looking for "magnific" and "popup" :-)

I have made a PR to upgrade the library to the latest version:
https://github.com/webjars/Magnific-Popup/pull/1

Cheers,

**Comment by jamesward** [comment]
No problem. Thanks for filing an issue about the case sensitive filter.
