### ISSUE TITLE
Webjars new feature fork request -> Enable webjars for Servlet 2.x containers via Servlet

### ISSUE THREAD

**Issue by aruizca** [webjars/webjars#925]
Hi @jamesward 
I have written a library which basically contains a HttpServlet that enables webjars resources to be served by non compliant Servlet 3.x Java EE containers.

The reason I am requesting the fork is because I would like it to be  published in Maven central with your groupid and be part of the webjars initiative.

You can find the library here:
https://github.com/aruizca/webjars-servlet-2.x

I hope you would consider adding this library to your fantastic initiative.

Cheers,

**Comment by mwanji** [comment]
This is cool, but a few remarks:

Why does it respond to a POST?
I don't think it should add caching headers, or at least it should be possible to turn them off. For example, servers often handle etags themselves and provide configurable caching filters.
There's a typo: prepareChache should be prepareCache.
I think you should trim the copy method down to what you actually need, rather than have 3 methods.

**Comment by aruizca** [comment]
Hi @mwanji 

> Why does it respond to a POST?

Just in case I guess...

> I don't think it should add caching headers, or at least it should be possible to turn them off.

You are right. I will add an option to turn it off. But I think the cache is a sensible default for something that never changes unless the version changes.

> There's a typo: prepareChache should be prepareCache.

Upss! :-)

> I think you should trim the copy method down to what you actually need, rather than have 3 methods.

Agreed

Thanks for the feedback. I let you know when I make changes.

**Comment by aruizca** [comment]
@mwanji I have made the suggested changes. Please have a look

**Comment by jamesward** [comment]
Thanks @aruizca! I've forked the project:
https://github.com/webjars/webjars-servlet-2.x

Just to test things I've published `1.0-SNAPSHOT` into the Maven Central Snapshot repo.

Can you also add docs for this? https://github.com/webjars/webjars/blob/master/app/views/documentation.scala.html

Moving forward we can collaborate on this via PRs and issues on the new repo.

**Comment by aruizca** [comment]
@jamesward Can I contribute? :-)

**Comment by aruizca** [comment]
BTW, I have tested it in Tomcat 6 only

**Comment by jamesward** [comment]
I think that pull requests will be the best way to contribute since we can review and release as part of that process.

**Comment by dballardgh** [comment]
Hi @aruizca, I've noticed that webjars/webjars-servlet-2.x doesn't set the contentType on responses. In my testing, browsers will not interpret CSS unless the content type "text/css" is returned. Lack of content type for JS and images don't seem to cause a problem. Have you seen this behavior?

**Comment by jamesward** [comment]
@dballardgh Can you file an issue at: https://github.com/webjars/webjars-servlet-2.x

**Comment by dballardgh** [comment]
Will do. Thanks.
