### ISSUE TITLE
Bower Webjars request for github.com/Polymer/polymer fails

### ISSUE THREAD

**Issue by gjdev** [webjars/webjars#928]
Trying to add a Bower Webjar for github.com/Polymer/polymer version 0.5.5 I get the following error:

Failed!
Could not convert npm version to maven for: core-component-page Polymer/core-component-page#^0.5
Please file an issue: https://github.com/webjars/webjars/issues

**Comment by jamesward** [comment]
Thanks for trying this out.  Unfortunately the dependency definitions in https://github.com/Polymer/polymer/blob/master/bower.json can't be converted to a Maven style dependency.  So for now we will have to stick with Classic WebJars for this.
