### ISSUE TITLE
WebJar Request: linkuriousjs

### ISSUE THREAD

**Issue by dilbertside** [webjars/webjars#932]
Hi
I contributed a new webjar

My webjar contributed is https://github.com/dilbertside/linkuriousjs.git
Original Library is located https://github.com/Linkurious/linkurious.js

It looks like the packaging is fine

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/linkurious.js

This will be released shortly.

**Comment by dilbertside** [comment]
Thanks a lot for your time.
Next time I go through the form :-)
