### ISSUE TITLE
Failed to deploy bower webjar for https://github.com/choffmeister/roboto-fontface-bower

### ISSUE THREAD

**Issue by rkrzewski** [webjars/webjars#933]
I was trying out Bower WebJars self-service deployment, but it didn't work:
```
Failed!
{"error":{"code":"ENOTFOUND","data":{"endpoint":{"name":"","source":"roboto-fontface-bower","target":"0.3.0"}}}}
Please file an issue: https://github.com/webjars/webjars/issues
```
Running `bower install roboto-fontface --save` on my machine installs the package successully.

**Comment by jamesward** [comment]
Thanks for giving this a try.  The problem is that the `name` specified in the upstream project doesn't match the registered name: https://github.com/choffmeister/roboto-fontface-bower/blob/develop/bower.json#L2

Can you file an issue with the upstream project to have them correct this?
