### ISSUE TITLE
add jquery-mobile-spinbox

### ISSUE THREAD

**Issue by paranoiabla** [webjars/webjars#936]
Here's my repo:
https://github.com/paranoiabla/jquery-mobile-spinbox

**Comment by jamesward** [comment]
That repo looks like it is missing the `pom.xml` file.

**Comment by paranoiabla** [comment]
Sorry.. I added it.

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jquery-mobile-spinbox

This will be released shortly.
