### ISSUE TITLE
hal-browser webjar release request

### ISSUE THREAD

**Issue by andrekampert** [webjars/webjars#946]
Simple webjar to package hal-browser in a webjar.

Easily allows including the rich HAL+JSON explorer with a HATEOS API.

Since the author does not offer releases, the webjar references a commit hash in it's pom.xml

Webjar repo: https://github.com/Product-Foundry/hal-browser-webjar

Hal browser repo: https://github.com/mikekelly/hal-browser
Hal browser demo: http://haltalk.herokuapp.com

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/hal-browser

This will be released shortly.
