### ISSUE TITLE
License 'BSD-2-Clause' does not exist

### ISSUE THREAD

**Issue by seanf** [webjars/webjars#948]
Trying to package https://github.com/jgm/commonmark.js version 0.18.1, I got the error `License 'BSD-2-Clause' does not exist`.  

Could you please add the licence `BSD-2-Clause`?  It seems to be valid according to the Bower spec:

- https://github.com/bower/bower.json-spec#license
- https://spdx.org/licenses/

The deploy log:

	Failed!
	License 'BSD-2-Clause' does not exist
	If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

	Created WebJar
	Fetched Bower zip
	Generated POM
	Converted dependencies to Maven
	Got Bower info
	Starting Deploy

**Comment by jamesward** [comment]
This should be deployed in about 10 minutes.  Can you try it again then?

**Comment by seanf** [comment]
Looks good, thanks @jamesward !

**Comment by seanf** [comment]
@jamesward I can see the commonmark.js jar on bintray, and I expect it will get to Maven Central soon.  But it's not showing up in the search on http://www.webjars.org/bower yet.  I assume that's to be expected?

**Comment by seanf** [comment]
@jamesward I did noticed a minor thing about the package: bintray is complaining (with an exclamation mark icon) that the license BSD 2-Clause does not exist, on this page: https://bintray.com/webjars/maven/org.webjars.bower%3Acommonmark/view

It seems to link to a perfectly valid license page though: http://opensource.org/licenses/BSD-2-Clause

**Comment by jamesward** [comment]
Yeah, jCenter will sync with Maven Central soon.  The webjars.org/bower index pulls from Maven Central with a 1 hour cache.  So it might be a few hours before it shows up there.

That is pretty odd about the license no existing.  When I'm logged into BinTray I don't see it, but I do when I'm incognito.  I'll ping the BinTray folks.
