### ISSUE TITLE
Bootstrap Material Design

### ISSUE THREAD

**Issue by malchmih** [webjars/webjars#949]
Hi!
I'd like to create Bower WebJar for this library: https://github.com/FezVrasta/bootstrap-material-design.
When I try to do this, I got "License https://github.com/FezVrasta/bootstrap-material-design/blob/master/LICENSE.md is not acceptable on BinTray". This library (outdated version) is available as a classic WebJar
What should I do?

Thank you!

**Comment by jamesward** [comment]
The easiest way to resolve this is to get the upstream project to fix their license:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/bower.json#L44

That should follow the rules here: https://github.com/bower/bower.json-spec#license
