### ISSUE TITLE
Getting error when trying to add DOMPurify bower library

### ISSUE THREAD

**Issue by jasonconkey** [webjars/webjars#950]
When trying to add DOMPurify bower library, I get the error below after I select the version. I tried the two latest versions, 0.6.1 and 0.6.2:

Failed! {"error":{"code":"ENOTFOUND","data":{"endpoint":{"name":"","source":"DOMPurify","target":"0.6.2"}}}} 
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Starting Deploy

![screen shot 2015-04-02 at 3 34 24 pm](https://cloud.githubusercontent.com/assets/6083388/6975146/ea093114-d94d-11e4-9cba-be4e4923e348.png)

**Comment by jasonconkey** [comment]
It might be related to how the library is named lowercase "dompurify" in bower but it's looking for source: "DOMPurify"?

**Comment by jamesward** [comment]
You are right that there is a case sensitivity issue...
https://bower-as-a-service.herokuapp.com/info/DOMPurify
https://bower-as-a-service.herokuapp.com/info/dompurify

The Bower index has it as `dompurify`:
https://bower-component-list.herokuapp.com/

But the version `0.6.2` has the `name` as `DOMPurify`:
https://bower-as-a-service.herokuapp.com/info/dompurify/0.6.2

I'm so confused by these case sensitive (but not really) Bower artifacts.  So I'm not sure how to handle this.  I'll dig in, but if you have any thoughts, I'm all ears.

**Comment by jasonconkey** [comment]
Thanks for fixing this!
