### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by 1mdc** [webjars/webjars#954]
I have timeout error when adding any new library into webjars/bower. This is the error message:

Failed! Request timed out to bintray.com/108.168.194.93:443 of 120000 ms

**Comment by 1mdc** [comment]
It is fine now. Please close.

Thanks.

**Comment by cemcatik** [comment]
I'm seeing this issue trying to deploy http://github.com/lodash/lodash. Ran into same issue with versions 2.4.1 and 2.4.2

**Comment by jamesward** [comment]
It looks like those versions have been deployed:
https://repo1.maven.org/maven2/org/webjars/bower/lodash/

**Comment by cemcatik** [comment]
Good to know. Though when I search for those versions in webjars.org I'm not seeing them. Could the timeout error cause them to not get picked up?

![image](https://cloud.githubusercontent.com/assets/4639/7481467/ef3d4d64-f324-11e4-8d4a-bad11e106dd9.png)

**Comment by jamesward** [comment]
The index on `webjars.org` is cached from http://search.maven.org which is also a cache.  So it takes some time for new stuff to show up.  I should add a note about that on the site.
