### ISSUE TITLE
Conflict Error for Missing RequireJS Plugins Artifact

### ISSUE THREAD

**Issue by michaelahlers** [webjars/webjars#956]
When attempting to create a Bower package for [`millermedeiros/requirejs-plugins`](http://github.com/millermedeiros/requirejs-plugins), deployment fails claiming the artifact (for 1.0.3) already exists. However, it does not does not appear in [the directory](webjars.org/bower).

**Comment by jamesward** [comment]
I just tried it again and I think it should be working now.  Reopen if not.  (It might take an hour or so to sync everything to the webjars.org site but it should be on Maven Central now.)
