### ISSUE TITLE
Jqm-autocomplete

### ISSUE THREAD

**Issue by paranoiabla** [webjars/webjars#957]
Hi there,

here's a repository for jqm-autocomplete:
https://github.com/paranoiabla/jqm-automplete

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jqm-automplete

This will be released shortly.

**Comment by paranoiabla** [comment]
Hi James,

sorry for the trouble, but seems like I messed this one :( The upstream.url points to:

https://github.com/commadelimited/autoComplete.js/blob/master/jqm.autoComplete-1.5.2.js

which in an html page, instead of:

https://raw.githubusercontent.com/commadelimited/autoComplete.js/master/jqm.autoComplete-1.5.2.js

Sorry about that.. do you want me to change it in my repo, or are you going to change it in the webjars repo?

**Comment by jamesward** [comment]
Can you send a pull request?

**Comment by paranoiabla** [comment]
Done.
