### ISSUE TITLE
Outdated bower search index

### ISSUE THREAD

**Issue by th0br0** [webjars/webjars#958]
Hey,

the bower index that is used for searching seems to be outdated (e.g. HubSpot/tether is not included). Manually initiating the package by POSTing to http://www.webjars.org/deploy/bower/tether/0.6.5 creates the package though.

Therefore, it might make sense to update the index

**Comment by jamesward** [comment]
There is a 1 hour cache for the index.  I see the package in there now.  I could reduce the cache time if this comes up often.
