### ISSUE TITLE
Error on deploying bower repo google/material-design-icons

### ISSUE THREAD

**Issue by kreyssel** [webjars/webjars#960]
If i try to deploy the bower repo https://github.com/google/material-design-icons/ I get an "503 internal server error".

Can you please check what happen?

Thanks guys.

**Comment by jamesward** [comment]
Thanks for the heads up.  It looks like this is due to Bower taking a really long time to get the package info for this large package:
```
$ time bower info material-design-icons
...
real	3m30.582s
user	2m4.824s
sys	1m16.864s
```

Ouch.  I'm not sure what to do about this yet.  I'll noodle it.

**Comment by jamesward** [comment]
Just noticed another issue with doing a Bower WebJar for this... The `CC-BY-4.0` license is not a valid license on BinTray.  So even if I fix this issue, we won't be able to make it work.  We could do a Classic WebJar for it.  Feel free to send a request if it doesn't already exist.

I'm relocating this issue to the underlying microservice: https://github.com/jamesward/bower-as-a-service/issues/1

**Comment by jamesward** [comment]
FYI, there is now a Classic WebJar for material-design-icons: https://github.com/webjars/material-design-icons
