### ISSUE TITLE
Couldn't create Bower WebJar for `breakpoint-sass`.

### ISSUE THREAD

**Issue by a1russell** [webjars/webjars#970]
From http://www.webjars.org/bower I've tried to "Add a New Bower WebJar" for [breakpoint-sass](https://github.com/at-import/breakpoint), version 2.4.2.

I believe the deploy log the first time stated:

    Failed!
    Request timed out to bintray.com/108.168.194.93:443 of 120000 ms
    If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

    Published BinTray Version
    Signed BinTray Assets
    Published BinTray Assets
    Created BinTray Version    
    Created BinTray Package
    Converted project licenses
    Created WebJar
    Fetched Bower zip
    Generated POM
    Converted dependencies to Maven
    Got Bower info
    Starting Deploy

I tried again, and now the deploy log says:

    Failed!
    Version 2.4.2 for path 'webjars/maven/org.webjars.bower:breakpoint-sass already exists
    If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues
    
    Created BinTray Package
    Converted project licenses
    Created WebJar
    Fetched Bower zip
    Generated POM
    Converted dependencies to Maven
    Got Bower info
    Starting Deploy

**Comment by lstreet-aquent** [comment]
I tried creating a bower WebJar for [angular-selectize](https://github.com/machineboy2045/angular-selectize) and encountered the same error.

**Comment by jamesward** [comment]
It looks like things were taking longer than usual.  I've redeployed `breakpoint-sass`.

Is https://bintray.com/webjars/maven/org.webjars.bower%3Aangular-selectize2/view the other package you need?

**Comment by a1russell** [comment]
Thanks @jamesward. I think that @lstreet-aquent wanted the other package. Closing this issue.
