### ISSUE TITLE
Extjs webjar is 85MB.

### ISSUE THREAD

**Issue by paranoiabla** [webjars/webjars#971]
Hi there,

I'm having troubles with the extjs webjar. Here's the full thread:

http://jetty.4.x6.nabble.com/jetty-dev-Maven-Jetty-Plugin-Slow-with-Java8-td4963888.html

but basically the servlet 3.1 spec says if there's any `ServletContextInitializer` in the classpath that has a `HandlesTypes` annotation, then the servlet container needs to scan the whole classpath. Thus the jetty servlet container starts very slow (~ 15 mins) because of the extjs webjar - it is nearly 85 MB. If I remove the this webjar is starts almost instantaneously. I noticed there's another webjar on pentahohub:
````
<dependency>
    <groupId>com.pentahohub</groupId>
    <artifactId>webjars-extjs</artifactId>
    <version>5.1.0</version>
</dependency>
````
which is 13MB.  It only contains the needed javascript and the packages.

**Comment by paranoiabla** [comment]
I just checked and seems like the pentahohub extjs webjar is missing the extjs css files :(

**Comment by mwanji** [comment]
You could improve the POM to exclude the folders and files you don't need. An 85MB webjar doesn't sound useful to anybody.

**Comment by jamesward** [comment]
@paranoiabla I'm not sure what I should exclude. Can you send a PR with updates to the packaging? Here is the project: https://github.com/webjars/extjs

**Comment by paranoiabla** [comment]
Here it is: https://github.com/webjars/extjs/pull/12

**Comment by jamesward** [comment]
Closing this in favor of https://github.com/webjars/extjs/pull/12
