### ISSUE TITLE
Bower deploy of angularjs 1.4.0-rc.0 fails

### ISSUE THREAD

**Issue by kreyssel** [webjars/webjars#972]
Hello,

i try to deploy the bower angularjs 1.4.0-rc.0 release, but it fails with the following error:

> Failed! 
> Version 1.4.0-rc.0 for path 'webjars/maven/org.webjars.bower:angulerjs already exists 
> If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  
> 
> Created BinTray Package 
> Converted project licenses 
> Created WebJar 
> Fetched Bower zip 
> Generated POM

Can you please check it?

**Comment by jamesward** [comment]
The Bower WebJar does exist but notice the typo in the name: `angulerjs`  This typo comes from the Bower repo.  But there are also other Bower package names for this package including `angular-latest`.  I don't want to start working around Bower repo issues.  So I think this will just have to be the way it is until Bower fixes their repo issues.

For reference here is the package in Maven Central: https://search.maven.org/#search%7Cga%7C1%7Cangulerjs
