### ISSUE TITLE
Add Support for CC-BY-3.0 License

### ISSUE THREAD

**Issue by yatskevich** [webjars/webjars#977]
Hi,

I tried to deploy `font-awesome` library but got the following result:
```
Failed! 
License OFL-1.1 is not acceptable on BinTray 
If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  

Created WebJar 
Fetched Bower zip 
Generated POM 
Converted dependencies to Maven 
Got Bower info 
Starting Deploy
```

I've contacted BinTray support and they've told me that OFL-1.1 license is available under the name ‘Openfont-1.1’.

One possible solution could be to extend [normalization of license name](https://github.com/webjars/webjars/blob/master/app/utils/BinTray.scala#L149-L151). What do you think?

**Comment by jamesward** [comment]
Yeah, it looks like we will have to do some mapping because the accepted BinTray licenses don't match the [Bower ones](https://spdx.org/licenses/).

**Comment by yatskevich** [comment]
@jamesward thanks a lot!

**Comment by jamesward** [comment]
No problem. Let me know if you have any issues deploying.

**Comment by yatskevich** [comment]
Well, it complains about CC-BY-3.0 license now. Unfortunately, BinTray [does not support](https://bintray.com/docs/usermanual/uploads/uploads_requestinganewlicense.html) Creative Commons licenses:
> Note: Bintray does not accept Creative Commons licenses for packages; these licenses were never meant to be used for software (click [here](http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F) for more information).

**Comment by jamesward** [comment]
aye yai yai...  Well, I could make it so that if there is at least one accepted license, we drop the unacceptable ones.  Not sure how the upstream authors will feel about that.  But it might be the least worst option.

**Comment by yatskevich** [comment]
Yeah, that's the question. Funny thing is that `font-awesome` uses 3 licenses - OFL for the font itself, MIT for CSS/LESS/Sass and finally - CC BY 3.0 for documentation.

**Comment by jamesward** [comment]
I've debated this and I think the right thing to do is to see if we can get BinTray to accept `CC-BY-3.0`.  I'll reach out to them.

**Comment by yatskevich** [comment]
Right, I guess it may simplify many people's lives if BinTray adds it.

**Comment by jamesward** [comment]
BinTray says they have deployed this change.  @yatskevich Can you give it a try?

**Comment by jamesward** [comment]
Looks like the `font-awesome` package has been deployed already.  So I'm going to close this.

**Comment by yatskevich** [comment]
@jamesward awesome!
