### ISSUE TITLE
Bower webjar for polymer

### ISSUE THREAD

**Issue by sergiuszkierat** [webjars/webjars#979]
Unfortunatelly, there is only 0.5.4 polymer within classic webjars.

During creation webjar for https://github.com/Polymer/polymer/tree/v0.8.0-rc.6, I came across this error

> Failed! License http://polymer.github.io/LICENSE.txt is not acceptable on BinTray

Intrigued, is it possible to create bower webjar with this license?

Update : License retrieved from https://bower-as-a-service.herokuapp.com/info/polymer/0.8.0-rc.6 is not compatible with https://github.com/webjars/webjars/blob/master/app/utils/BinTray.scala#L159

**Comment by jamesward** [comment]
The upstream project needs to be fixed since [their license](https://github.com/Polymer/polymer/blob/v0.8.0-rc.6/bower.json#L7) does not follow the [bower.json spec](https://github.com/bower/bower.json-spec#license).

**Comment by sergiuszkierat** [comment]
> SPDX license identifier **or path/url to a license**

@jamesward, I think that upstrem project follows the bower.json spec, because it uses path to a license, could you reopen this one?

**Comment by jamesward** [comment]
Sure enough!  I'll make this work with URLs.
