### ISSUE TITLE
Sortable

### ISSUE THREAD

**Issue by just-boris** [webjars/webjars#982]
https://github.com/RubaXa/Sortable

This sortable plugin supports most of modern JS frameworks and doesn't depend from any, even jquery

**Comment by jamesward** [comment]
I've created a Bower WebJar for this:
```
GroupID = org.webjars.bower
ArtifactID = Sortable
Version = 1.2.0
```

**Comment by just-boris** [comment]
Wonderful, thanks!
Look @baev, we can use Sortable!
