### ISSUE TITLE
Failed to deploy videogular-buffering and videogular-overlay-play at 1.2.0

### ISSUE THREAD

**Issue by JeffPlummer** [webjars/webjars#983]
I was unable to deploy the following bower components:
"videogular-buffering" % "1.2.0",
 "videogular-overlay-play" % "1.2.0"

I was able to install 1.1.1, but it died on 1.2.0.   I was successful on 3 other related libraries for "1.2.0", but the above 2 wouldn't work.  Not sure.  Re-deloying fails now because it says they already exist.

Thanks,
Jeff

**Comment by jamesward** [comment]
I'm not sure what went wrong but I've tried to resync those and it appears to have worked.  Reopen this if they don't show up in the next few hours.

**Comment by jamesward** [comment]
Oh wait. I know what went wrong...  For some reason it thinks that `1.1.1` is the latest version and it's only syncing that version.  I've deleted `1.2.0` from BinTray so you should be able to redeploy those from http://webjars.org/bower

If that doesn't work, reopen this.
