### ISSUE TITLE
Permit Octicons license (SIL OFL 1.1, MIT) for Bower WebJar

### ISSUE THREAD

**Issue by rtyley** [webjars/webjars#984]
Creating a Bower WebJar for Octicons currently fails:

```
Failed! License SIL OFL 1.1, MIT is not acceptable on BinTray
```

https://github.com/github/octicons/blob/master/LICENSE.txt

**Comment by jamesward** [comment]
This needs to be fixed upstream because the correct id for the OFL license is `OFL-1.1` according to:
https://spdx.org/licenses/

Can you file an issue with the octicons project?
