### ISSUE TITLE
WebJar request: Start Bootstrap - Agency

### ISSUE THREAD

**Issue by anand-singh** [webjars/webjars#993]
### [Start Bootstrap - Agency](https://github.com/IronSummitMedia/startbootstrap-agency)
A clean, stylish, one page Bootstrap portfolio theme perfect for your agency or small business.

#### Description:

Agency is a stylish, one page Bootstrap theme for agencies and small businesses. The design of Agency is based off of the Golden PSD Theme by Mathavan Jaya. You can download the PSD verison of this theme at FreebiesXpress.com.

#### Features:
- Fully responsive
- Custom collapsing navigation with active classes, smooth page scrolling, and responsive fallback stylings
- Services section with CSS only circle icons by Font Awesome
- Portfolio grid with modal window popup previews for portfolio item details
- About section with a responsive timeline, special thanks to Bootsnipp
- Team member section with circle profile images and social media links
-  Working PHP contact form with validation - just add your email address to the PHP file included
-  Footer with social links, copyright information, and other links
-  LESS files included for deeper customization options

![agency](https://cloud.githubusercontent.com/assets/4903911/7467125/a11bf6be-f30e-11e4-8612-140bce39abcd.jpg)

**Comment by anand-singh** [comment]
@jamesward :  could you please look into this or give me a way to add it

Thanks,
Anand

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/startbootstrap-agency

This will be released shortly.
