### ISSUE TITLE
WebJar request: Start Bootstrap - Grayscale

### ISSUE THREAD

**Issue by anand-singh** [webjars/webjars#994]
# [Start Bootstrap - Grayscale](https://github.com/IronSummitMedia/startbootstrap-grayscale)
Grayscale is a multipurpose, one page HTML theme for Bootstrap created by Start Bootstrap. This template features various content sections and a Google Maps section with a custom map marker.

### Features:

- LESS files and compiled CSS included
- Fixed top navigation that collapses on scroll
- Smooth scrolling animations
- Scrollspy that highlights active page sections
- Custom outline button style
- Google Maps API integration with a custom Google Maps skin by Snazzy Maps
- New! Easy to edit custom PNG map marker

![grayscale](https://cloud.githubusercontent.com/assets/4903911/7467176/c631f33a-f30f-11e4-83ba-6142b3b29ae8.jpg)

**Comment by anand-singh** [comment]
@jamesward : could you please look into this or give me a way to add it

Thanks,
Anand

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/startbootstrap-grayscale

This will be released shortly.
