### ISSUE TITLE
WebJar request: Start Bootstrap - Freelancer

### ISSUE THREAD

**Issue by anand-singh** [webjars/webjars#995]
# [Start Bootstrap - Freelancer](https://github.com/IronSummitMedia/startbootstrap-freelancer)
Freelancer is a one page Bootstrap portfolio theme for freelancers. This theme is built using the Flatly theme by Bootswatch.

### Features:

- Flat icons by flaticons.com
- LESS files and compiled CSS included
- Fixed top navigation that collapses on scroll
- Scrollspy on navigation items
- Perfectly responsive portfolio grid with hover effects
- Responsive, full screen modal windows for featuring project details
- Custom horizontal rules using Font Awesome icons
- Custom outline button style
- Mobile friendly contact form with floating form labels
- Easy to edit PHP file to make the contact form send messages
- Includes jqBootstrapValidation plugin for contact form validation

![Freelancer](http://startbootstrap.com/assets/img/templates/freelancer.jpg)

**Comment by anand-singh** [comment]
@jamesward : could you please look into this or give me a way to add it

Thanks,
Anand

**Comment by jamesward** [comment]
I can create this for your when I get the chance.  If you want to move things along faster you can create and contribute it: http://www.webjars.org/contributing

**Comment by jamesward** [comment]
Here is the new WebJar: https://github.com/webjars/startbootstrap-freelancer

This will be released shortly.
