### ISSUE TITLE
WebJar request: SB Admin

### ISSUE THREAD

**Issue by anand-singh** [webjars/webjars#996]
# [SB Admin 2](https://github.com/IronSummitMedia/startbootstrap-sb-admin-2)

A Bootstrap based admin theme, dashboard, or web application UI featuring powerful jQuery plugins for extended functionality.

![sb-admin-2](http://startbootstrap.com/assets/img/templates/sb-admin-2.jpg)

**Comment by anand-singh** [comment]
@jamesward : could you please look into this or give me a way to add it

Thanks,
Anand

**Comment by jamesward** [comment]
It looks like this is available in Bower so you should be able to add it yourself: http://webjars.org/bower
