### ISSUE TITLE
WebJar request: jQuery.mmenu

### ISSUE THREAD

**Issue by tryIO** [webjars/webjars#997]
Hi! here my contribution to the project: https://github.com/tryIO/jQuery.mmenu.git

here you can find the original widget: https://github.com/BeSite/jQuery.mmenu/

**Comment by jamesward** [comment]
Thanks.  It seems the `pom.xml` is missing from that repo.

**Comment by tryIO** [comment]
How embarrassing! I had some issues with my connection and I didn't notice that my last push has failed! it should be there now :)

**Comment by jamesward** [comment]
Thanks! Here is the fork: https://github.com/webjars/jQuery.mmenu

This will be released shortly.
