### ISSUE TITLE
Classic webjar for angular-wizard

### ISSUE THREAD

**Issue by cemcatik** [webjars/webjars#998]
https://github.com/cemcatik/webjars-angular-wizard

The Bower webjar for angular-wizard depends on `"lodash": ">=1.3.0 <2.5.0"` but I wasn't able to deploy appropriate version from webjars.org. This should be useful none the less.

**Comment by jamesward** [comment]
Can you file an issue on the lodash deployment problem?

Thanks for the WebJar!  Here is the fork: https://github.com/webjars/angular-wizard

This will be released shortly.

**Comment by cemcatik** [comment]
The issue is a clone of https://github.com/webjars/webjars/issues/954. Additionally to that if I try to re-deploy the failed webjar I see the following error:

    Failed! Version 2.4.2 for path 'webjars/maven/org.webjars.bower:lodash already exists
