### ISSUE TITLE
Maven Central notification should only notify deployer

### ISSUE THREAD

**Issue by cowwoc** [webjars/webjars#999]
I've been get notifications every time someone deploys a webjar to Maven Central, and the volume keeps on increasing.

Is it possible to change the notification configuration so only the person doing the deployment gets the notification instead of everyone in the Webjars organization?

**Comment by mwanji** [comment]
+1

**Comment by jamesward** [comment]
Sorry guys.  I know this is really noisy.  I'm not sure what to do about it.  Can someone file an issue at: https://issues.sonatype.org/secure/Dashboard.jspa

**Comment by cowwoc** [comment]
Filed: https://issues.sonatype.org/browse/OSSRH-15419

**Comment by jamesward** [comment]
If OSS can't find a way to do this we could switch to using BinTray / JCenter and then just have a single deployer account on OSS.

**Comment by cowwoc** [comment]
@jamesward Please read https://issues.sonatype.org/browse/OSSRH-15419

**Comment by mwanji** [comment]
I've never deployed to org.webjars, so I'm fine with being removed and
losing deployment rights, if that's easiest.

**Comment by jamesward** [comment]
I'm in the process of setting up a `webjars` user on OSS that BinTray can use for automated deploys.  We can have Sonatype put that user into a different deploy profile so that we don't get notifications for those.  How does that sound?

**Comment by cowwoc** [comment]
On 11/06/2015 10:57 AM, James Ward wrote:
>
> I'm in the process of setting up a |webjars| user on OSS that BinTray 
> can use for automated deploys. We can have Sonatype put that user into 
> a different deploy profile so that we don't get notifications for 
> those. How does that sound?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/webjars/webjars/issues/999#issuecomment-111163428>.
>

Sounds good to me, but will we still be able to deploy? As what user?

Gili

**Comment by jamesward** [comment]
Yeah, everyone will still be able to deploy and we will get notifications for those manual deployments.  Is that ok?

**Comment by jamesward** [comment]
Also...  To totally silence the notifications, we could eventually all move to BinTray and do deployments through there as the new `webjars` user.

**Comment by cowwoc** [comment]
Sounds good.

**Comment by jamesward** [comment]
[Check the latest comments on the OSS Jira](https://issues.sonatype.org/browse/OSSRH-15419) and see if you all are ok with that solution.

**Comment by cowwoc** [comment]
A disappointing end, but better than the current situation, so I'm for it :)

**Comment by mwanji** [comment]
I'm fine with being removed from the group of deployers

>

**Comment by jamesward** [comment]
I missed @cowwoc but that should be taken care of shortly.
For anyone who wants to deploy, email me and I'll give you the password for the `webjars` user.

If anyone is interested in seeing the list of the deployments, I could setup a Google Group and auto-forward the deploy emails to it.  Or something like that.  Let me know if anyone is interested in that.
